### ISSUE TITLE
Sound behavior on reset all

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#100]
When reset all is pressed, only reset all button sound should be heard, not the other sounds as the objects move to “reset” position.

**Comment by zepumph** [comment]
I can't reproduce the bug where pressing the reset-all button triggers any other sound. Could you please explain a reproduceable case for me?

**Comment by zepumph** [comment]
I still can't reproduce this. Unassigning

**Comment by emily-phet** [comment]
Seems fine to me now. Closing.
