### ISSUE TITLE
Scene Summary for explore screen needs an update

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/ratio-and-proportion#101]
Right now the scene summary for screen one the explore screen says:
_The Play Area has two freely moving objects that can be moved around to find the current proportions and five mystery scene selection buttons. The Control Area has a button to reset the sim._

It should read:
**The Play Area is an open space with two movable hands. Hands can be moved individually or simultaneously to explore a challenge. There are options to adjust the look and feel of the open space that may help you master the challenges. The Control Area has a button to reset the sim.**

**Comment by zepumph** [comment]
Updated above.
