### ISSUE TITLE
Updates to aria-live alerts

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#104]
After discussing with @Matthew-Moore240, we will be moving some descriptions over to aria-valuetext for the left/right positions. This issue is to go along with the aria-valuetext implementation issue (https://github.com/phetsims/ratio-and-proportion/issues/105), to make sure that aria-live get's cleaned up.

**Comment by zepumph** [comment]
I went through and cleaned quite a bit up here. I didn't see a lot of direction in the design doc, so I went with my gut a bit. @Matthew-Moore240 and I decided to get rid of positional alerts, and to only keep the direction (up/down) and ratio context in the alert. It wasn't clear though if we should keep what was currently implemented in the alerts about the "first alert" edge case, which happens once for "up" and once for "down" and sounds like:  `Moving Right Hand up. Somewhat close to ratio.`

Please review the current alert structure in conjunction with new positional aria-valuetext in place over in https://github.com/phetsims/ratio-and-proportion/issues/105

**Comment by zepumph** [comment]
I should also add that these alerts now trigger from slider input (instead of just from mouse end drag.

**Comment by terracoda** [comment]
See #108, you can also remove the up/down strings in the responses.

**Comment by terracoda** [comment]
Other than #108, ready to close.
