### ISSUE TITLE
Dynamic Screen Sumamry - Add "Play Area" to values

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#107]
Like in the `aria-valuetext`, please add "Play Area" to the dynamic descriptions of the hands

**Example:**
Currently, at ratio, on Challenge 1
- Left hand somewhat close to the bottom **of Play Area**
- Right hand in the middle **of Play Area**

**Comment by zepumph** [comment]
Implemented above, please review.

**Comment by Matthew-Moore240** [comment]
Looks good, Closing.
