### ISSUE TITLE
Context Responses - remove up down related responses

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#108]
Get rid of up and down context responses completely.
- "up"
- "down"
- "moving {{left hand}} down"
- "moving {{left hand}} up"

These are not as useful as we thought.

**Comment by zepumph** [comment]
Implemented above. Now the only context responses are the current state of the ratio. They are only triggered at the end of an interaction (i.e. end drag or keyboard arrow). Please review.

**Comment by Matthew-Moore240** [comment]
Looks great much less cluttered now. Closing
