### ISSUE TITLE
Both Hands - Accessible name not heard on keyboard focus

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#109]
Tabbing to both hands with KB doesn’t say both hands. It just says movable. When reading with cursor keys, though, it says Both hands, movable.

Is this a coding issue?

Can you make it say, Both hands, movable on focus, please?

**Comment by zepumph** [comment]
* The inner content of the `div`  was "Both Hands", but I added an `aria-label` of the same value to make sure the name was right.
* I renamed "Both Hands" to "Both hands"
* I updated the aria-roledescription from `movable` to `movable on focus`.

Please review.

**Comment by Matthew-Moore240** [comment]
On NVDA its saying "both hands movable on focus" was that intended @zepumph

**Comment by zepumph** [comment]
Oh poop. maybe this was a missunderstanding. @terracoda said:

>Can you make it say, Both hands, movable on focus, please?

But she meant "Can you make it say, 'Both hands, movable' on focus, please?"


Updates on the way!!!

**Comment by zepumph** [comment]
Please review master, perhaps from phettest.

**Comment by Matthew-Moore240** [comment]
Haha no worries! This sounds good! Closing
