### ISSUE TITLE
Need "At ratio" for non-visual experience

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#111]
Currently, we only get "very close to ratio" when we hit the darkest green and hear the ratio sound.

We need it to say "at ratio". 
Can the descriptions follow the same fitness value as the other modalities?

Can we hack this in for interviews at least?

**Comment by terracoda** [comment]
I realize this is and unintentional out come of all the tolerances that have been designed in.

**Comment by zepumph** [comment]
Implemented above. @terracoda please review.

**Comment by Matthew-Moore240** [comment]
This works really well, I tried a bunch of weird ratios and was able to get the "At ratio" response every time. Closing
