### ISSUE TITLE
Add "button" to aria-roledescription on Sim Screen buttons

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#116]
"sim screen" alone in the `aria-roledescription` for the sim screen buttons likely won't work for learners. They will not know it is a button and that they need to press space or enter to choose a screen.

The `aria-roledescription`, if we use it, needs to have the word "button" in it.

Please add "button" to the `aria-roledescription` for all sim screen buttons, including Home Scree and in the bottom nav bar on each Sim Screen.

I have a feeling there is a joist issue for this.

Please move issue there if needed.

**Comment by jessegreenberg** [comment]
Thanks, moved to https://github.com/phetsims/joist/issues/496.
