### ISSUE TITLE
MovingInProportion Sound, Lock Ratio bug

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#118]
If you lock the ratio while InProportion, pick up, translate slightly, the choir sound plays without requiring further movement.

In other words, you can be not moving and getting the MovingInProportion sound, though it requires an initial (very small) movement. 

I'm calling this a bug because it seems from the sound meeting (that did not include @zepumph ), that this was not intended. I think it may be fallout from removing the velocity threshold. It may be that we need just a very very low velocity threshold.

**Comment by zepumph** [comment]
Thanks for the report. I had a bug in how velocity was being calculated such that it wasn't ever truly 0. This was exposed by the lockRatio feature, but not caused by it. This is fixed in master now.

**Comment by BLFiedler** [comment]
Looks good!
