### ISSUE TITLE
Make white hand circle transparent

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#121]
We would like the white circle in the hand to be transparent. Right now, we are placing a white circle on top of the hand icon.

Current look:
![image](https://user-images.githubusercontent.com/6856943/89935629-ef1ac680-dbbe-11ea-95ce-f9188835bf59.png)

`ai` file: https://github.com/phetsims/ratio-and-proportion/blob/13d8ee98ae71bc575bc47766f40cb58924a0f358/assets/filled-in-hand.ai

current png: https://github.com/phetsims/ratio-and-proportion/blob/13d8ee98ae71bc575bc47766f40cb58924a0f358/images/filled-in-hand.png

Here is the actual rasterized Node from the sim with the white circle on it: 
![handwithCircle](https://user-images.githubusercontent.com/6856943/89937684-ea0b4680-dbc1-11ea-817d-0ca60a342af7.png)

In the code the white circle has a radius of 10 pixels, and its positioning on top of the current png icon looks like: 
```js
    // empirical multipliers to center hand on palm. Don't change these without altering the layout for the cue arrows too.
    handImage.right = handImage.width * .4;
    handImage.bottom = handImage.height * .475;
```
And the hand png is scaled down by `.4`.

@arouinfar, would it be easy to provide an `ai` and `png` with an added transparent circle replacing the white circle here?

I'm happy to talk more about this if you have any questions.

**Comment by zepumph** [comment]
Ideally this could be done today, so that I could get it into a new version of a sim for interviews tomorrow. Marking the same priority as the parent issue.

**Comment by arouinfar** [comment]
@zepumph I'll get started on this now. Would you prefer that I cut out the white dot entirely so that there's a fully transparent portion of the hand, or should the white circle still remain on top of the hand but with reduced opacity? I'm going to proceed with the former, if you want the latter, please let me know what alpha level you want for the white dot.

**Comment by arouinfar** [comment]
@zepumph I vertically aligned the center of the cutout with the top of the thumb, and horizontally centered it within the body of the hand. The result is that the cutout takes out a bit of the fingers. Please let me know if you would like for me to adjust the alignment/proportions.

![image](https://user-images.githubusercontent.com/8419308/89953806-0c668980-dbed-11ea-8e26-974102b87d6b.png)

Here are the updated assets: [cutout-hand.zip](https://github.com/phetsims/ratio-and-proportion/files/5059736/cutout-hand.zip)

**Comment by zepumph** [comment]
That looks great, thanks! Added above. Feedback will be given over in #122. Closing
