### ISSUE TITLE
Tweaks from design meeting today

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#122]
From today's meeting, there are three things that would be ideal to tweak in the sim before the next interview tomorrow:

1. Right now there is a white circle inside each hand. It would be great to make that circle transparent. See https://github.com/phetsims/ratio-and-proportion/issues/121
2. "hollywood" low region to <.2 instead of <.5
3. snap to grid lines (only for 0 to 10 grid range). Snap the width of the circle around the grid lines. Don't let this effect other grid line range, or keyboard behavior.

**Comment by zepumph** [comment]
RE 3: To calculate what the percentage of the circle is in terms of the grid lines space, I wanted to determine what the transform on both were. I'm unsure if I did right, but here is how I got each height:

`hand` is an instance of a `RatioHalf.RatioHandNode`
```
// Circle
hand.children[1].localToGlobalBounds(hand.children[1].localBounds).height
9.734375

// Grid circles
hand.parent.children[2].height
717.5944355270198
hand.parent.children[2].minorHorizontalLineSpacing
71.65944355270197
```

From this, I think we should snap to the grid within 13.5842179584% of the grid line (half of which on each side of the grid line).

**Comment by zepumph** [comment]
(3) implemented above. I like the use of mutating the positionProperty and then notifying listeners static. It feels cleaner to me than creating a new Vector2 each time. It could be improved by only notifying if a change actually occurs, but right now I'm not too worried.

**Comment by zepumph** [comment]
(1) was implemented above. I have a couple tweaks I want to make to the lock ratio feature, and then I plan to make a dev version for tomorrow's interview.

**Comment by zepumph** [comment]
Everything has been implemented here, and put into https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.50/phet/ratio-and-proportion_all_phet.html. I'm going to close this. @BLFiedler please reopen if there are issue.

**Comment by BLFiedler** [comment]
Just one thought - at least in my imagination, I think the snap only happened when you released the hands, rather than sticking while you were still moving the hands. Is this possible? It feels a little weird for the hands to snap as I'm actively moving them as it creates this "Stop-start" feeling as you explore.

**Comment by zepumph** [comment]
Agreed! I also found a bug with locking the horizontal movement on first drag with the lock ratio feature. I added it in here. Here is a new dev version:

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.51/phet/ratio-and-proportion_all_phet.html

**Comment by BLFiedler** [comment]
Looks great to me!
