### ISSUE TITLE
Grid Lines Radio Group: Change Grid lines to Tick Marks

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#124]
Describing the lines as "grid lines" was unclear to non-visual learners. We will use "tick marks" instead. We will indicate in some way in the screen summary that the tick marks are represented as horizontal lines.

@zepumph, please make the following changes to the radiobutton group for the visual changes to the Play Area. "Tick marks" will also show up in the dynamic descriptions and the eventual responses.

- [x] For the H3, change "Grid Options" to "Guide Options"
- [x] Change help text from:
  - "Choose how you see or hear grid information." to
  - "Choose how you see or hear your guided exploration."
- [x] For the radiobutton labels, please use these three new names: 
  - No Tick Marks
  - Tick Marks 
  - Numbered Tick Marks

**Note:** I intentionally removed the word "Show" from the label names.

**Comment by terracoda** [comment]
We may change the order of radio buttons over in issue #120. I am checking with @emily-phet on that.

**Comment by zepumph** [comment]
Implemented above. I think there are quite a few other spots where "grid" is mentioned, but I'm not sure if this is the issue for it though. Here are some other spots I see in the description:

* Description that says something like "above grid position 5"
* "Grid Hidden" as the value of the disabled combo box
* "grid range" values of the combo box
* grid range help text
* Grid range screen summary bullet

Let me know if and how you want those changed too.

**Comment by terracoda** [comment]
Yep, there will be a cascade of changes, that we need to find, thanks for this list. It is helpful.

**Comment by terracoda** [comment]
Looks good, thanks @zepumph. Closing.
