### ISSUE TITLE
Change PDOM order in design doc back to the way it was

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#126]
@Matthew-Moore240 and @terracoda think that it makes much more sense to have the Ration Challenges combobox and the My Challenges accordionbox come before the radio buttons about the guides (no tick marks).

On screen one, please swap the order of the combobox interaction and the radiobutton group.

On screen two please put the collapsed My Challenges accordionbox above the radiobutton group.

Pleas make appropriate visual spacing changes as needed.

**Comment by zepumph** [comment]
Does this mean that the visual layout will adjust also? If so, it would be great to have a bit more specific on that to simplify the iteration on that. 

Does this mean that the keyboard navigation order will change along with this? To something like ratio->challenge selector-> grid stuff.

**Comment by zepumph** [comment]
Tagging visual peeps too just in case @emily-phet and @BLFiedler

**Comment by terracoda** [comment]
@emily-phet and @BLFiedler, @Matthew-Moore240 and I would like to change the tab order and the visual order to better support the prominence of the Ratio Challenges combobox and the My Challenges accordionbox.

These interactions are pedagogically more important than the Guide Options radiobutton group.

The new order is outlined in the tables under [Heading Outline & Focus Order](https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit#heading=h.gamh8gxjx7g5)

It would mean that the visuals are spaced differently. I don't think (though I could be wrong) that this would not be problematic for visual learners.

Can you please comment on this issue.

**Comment by terracoda** [comment]
@BLFiedler, I didn't realize the pedagogical importance of the radio buttons.

For non-visual access there may be little to no interaction with the non-numbered lines, so it seemed in my interviews that it was important to change challenges.

Let's leave it as is and hopefully, the entire described experience will be more complete and less buggy in the next round of interviews.

**Comment by terracoda** [comment]
Assiging to myself to re-order the design doc again and then close the issue  when that is done.

**Comment by terracoda** [comment]
Adding @Matthew-Moore240 to this ISSUE.
One of us will re-re-order the items in the design doc to match the current implementation

**Comment by emily-phet** [comment]
Updated the design doc just now. Closing.
