### ISSUE TITLE
Create Screen - Dynamic summary - remove first bullet item

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#128]
On the second screen, the dynamic screen summary potentially has up to 4 bullets.
Please remove the first one that describes the state of the My Challenges accordionbox.

In interviews, users tried to interact with that content.

@Matthew-Moore240 and I think the accordionbox interaction can speak for itself and it does not need to be described in the dynamic summary.

**Comment by zepumph** [comment]
Implemented above. This included getting rid of the sub bullet. Please review.

**Comment by terracoda** [comment]
Actually, @zepumph, please remove the third bullet, too. This is the bullet that describes the selection of the range for the grid lines (or soon to be the range for the tick marks). These settings speak for themselves are not needed for the big-picture view.

**Comment by zepumph** [comment]
Sounds good to me.

**Comment by terracoda** [comment]
Verified. Thanks!
