### ISSUE TITLE
New intro text for the Static Screen Summary - both screens (State Descriptions) 

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#130]
To better scaffold non-visual learners, we want to create a more "search & discover" feeling, and make the ratio challenges more prominent.

In issue #123 we will hopefully change screen 1's name from "Explore Screen" to "Discover Screen". Regardless, though, @Matthew-Moore240 and I want to use the word "discover" more in the State Descriptions to scaffold non-visual learners better.

In interviews, learners expressed they did not know what they were doing or why they were doing it.

The H1 and the first paragraph (P1) are dependent on issue #123, so they are mentioned in that issue.  I start the screen summary changes at P2.

**New P2 of the Static Screen Summary for Screen 1** 
In the Play Area you have two movable hands and a set of ratio challenges to discover. Hands can be moved up and down individually or simultaneously to discover multiple places where the chosen ratio challenge is true. There are options to add plain or numbered tick marks, evenly-spaced horizontal lines, to divide up the vertical space of the Play Area. The Control Area has a button to reset the sim.

**New P2 of the Static Screen Summary for Screen 2** 
On this screen you can create your own ratio challenge. The Play Area has two movable hands that can be moved freely individually or simultaneously, or as a single interaction with the ratio locked to explore the ratio challenges you create. There are options to add plain or numbered tick marks, evenly-spaced horizontal lines, to divide up the vertical space of the Play Area. In addition, you can increase the range of tick marks for a finer exploration of your ratio challenges. The Control Area has a button to reset the sim.

Related changes to Dynamic state-of-sim and the initial interaction hints  for each screen will be outlined in related issues.

**Comment by terracoda** [comment]
@zepumph, I am making a slight change to the wording (already changed in design doc). I think using the word "shown" can simplify the sentence structure.

**New P2 of the Static Screen Summary for Screen 1** 
In the Play Area you have two movable hands and a set of ratio challenges to discover. Hands can be moved up and down individually or simultaneously to discover multiple places where the chosen ratio challenge is true. There are options to add plain or numbered tick marks shown as evenly-spaced horizontal lines that divide up the vertical space of the Play Area. The Control Area has a button to reset the sim.

**New P2 of the Static Screen Summary for Screen 2** 
On this screen you can create your own ratio challenge. The Play Area has two movable hands that can be moved freely individually or simultaneously, or as a single interaction with the ratio locked to explore the ratio challenges you create. There are options to add plain or numbered tick marks shown as evenly-spaced horizontal lines that divide up the vertical space of the Play Area. In addition, you can increase the range of tick marks for a finer exploration of your ratio challenges. The Control Area has a button to reset the sim.

**Comment by terracoda** [comment]
Assigning to @Matthew-Moore240 to verify.

**Comment by emily-phet** [comment]
@zepumph - Please remove the word "freely" from the scene summary in the Create screen. Once that's done, this looks good to go to me.

**Comment by zepumph** [comment]
I'm going to close this. Please reopen if anyone has thoughts.
