### ISSUE TITLE
New wording for Dynamic state-of-sim both screens (State Descriptions)

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#131]
Related to screen summary changes in issue #130.
With coming changes to screen 2's dynamic screen summary, the two screens are now more aligned. The two descriptions use teh same parameters, however, still there is a slight wording difference as screen 2 refers to "my challenge ratio" rather than just "challenge ratio".

**The Dynamic state-of-sim description for Screen 1:** 
Currently, hands are {{proximity-to-ratio}} the challenge {{1}} ratio with 
- Left hand {{hand-position-qualitative or hand-position-numbered}}
- Right hand {{hand-position-qualitative or hand-position-numbered}}

**Examples for no tick marks {{hand-position-qualitative}}**
Currently, hands are {{at}} the challenge {{1}} ratio with 
- Left hand {{near bottom {{of Play Area}}}}
- Right hand {{just below middle {{of Play Area}}}}

_After moving left hand up a little_
Currently, hands are {{extremely close to}} the challenge {{1}} ratio with 
- Left hand {{somewhat near bottom {{of Play Area}}}}
- Right hand {{just below middle {{of Play Area}}}}

**Examples for numbered tick marks {{hand-position-numbered}}:**
Currently, hands are {{at}} the challenge {{1}} ratio with
- Left hand {{on tick mark 2}} 
- Right hand {{on tick mark 4}} 

_After moving left hand up a little_
Currently, hands are {{extremely close to}} the challenge {{1}} ratio with
- Left hand {{on tick mark 2.2}}
- Right hand {{on tick mark 4}}

_After moving both hands up to new tick marks_
Currently, hands are {{somewhat close to}} the challenge {{1}} ratio with
- Left hand {{on tick mark 3}}
- Right hand {{on tick mark 5}}

**NOTE:** that the described ratio values are approximate, and will need to be aligned with the fitness values created for the visuals. There are new 9-point scales for both proximity to ratio and qualitative hand position to be posted in related issues, shortly.

**Comment by terracoda** [comment]
Oops forgot example for screen 2.

**Dynamic state-of-sim Screen 2:**
_Example on initial screen load_
Currently, hands are {{at}} the my challenge ratio with
- Left hand {{near bottom {{of Play Area}}}}
- Right hand {{just below middle {{of Play Area}}}}

**Comment by zepumph** [comment]
In the above example, I see that we are only saying "of Play area" for qualitative description. I think this is the issue to update that about, but I feel like I should ask about doing that so that you understand the scope of this change. 

in https://github.com/phetsims/ratio-and-proportion/commit/7bd2ac9b92c4a93fc3f72f16fc42dbdfadda3b4c we we now don't get "of Play Area" for quantitative descriptions in . . .
* The screen summary bullets
* hand slider aria-valuetext
* both hands interaction alerts

Let me know what you think!

**Comment by terracoda** [comment]
Thanks for the heads up @zepumph, I haven't sorted out the aria-valuetext and context responses (interaction alerts) yet.

I've started in a new parameter (proximity to /distance from other hand), but I haven't got compete examples of what it would sound like qualitatively or quantitatively yet.

Hopefully, I get get something concrete together in the morning.

**Comment by terracoda** [comment]
Assigning to @Matthew-Moore240 to verify.

**Comment by emily-phet** [comment]
Looks good, implemented as requested. We'll decide later if it's an issue that "play area" is not used for ordinal or qualitative variants of the description.
