### ISSUE TITLE
New wording for Initial Interaction Hints - both screens (State Descriptions)

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#132]
The second to last paragraph in the Screen Summary contains a Static initial interaction hint. Here are the new hints fro Screen 1 and Screen 2.

**Screen 1**
- Current hint: "Move hands individually or at the same time to explore the challenge."

_Please change to:_
- Move hands individually or at the same time to maintain the ratio challenge.

**Screen 2**
- Current hint: "Explore current challenge or set your own."

_Please change to:_
- Explore the current my challenge ratio or create your own.

Edit: changed "discover" to "maintain" for screen 1's hint.

**Comment by terracoda** [comment]
Assigning to @Matthew-Moore240 to verify.

**Comment by emily-phet** [comment]
Verified! Closing.
