### ISSUE TITLE
New Region Names and ranges for describing qualitative hand position in the Play Area

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#136]
We have a new 9-point scale for qualitative hand position regions. Please see table in design doc in section [Described Ranges for States and Responses](https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit#heading=h.dq7735d8wjok)

Here are the words:
- {{at top}}
- {{near top}}
- {{somewhat near top}}
- {{just above middle}}
- {{at middle}}
- {{just below middle}}
- {{somewhat near bottom}}
- {{near bottom}}
- {{at bottom}}

In the dynamic descriptions, the parameters are followed by "of Play Area". I am not yet sure what will be said in responses.

The table in the design doc includes rough ranges for each described region. The ranges for the regions have to be aligned with the "fitness" that is being used for the visual design.

**Comment by terracoda** [comment]
@zepumph, I don't know if having a 9-point scale here, and an 8-point scale for proximity to challenge ratio in #117 will be problematic.

**Comment by zepumph** [comment]
The above have been implemented, we can see if things need tweaking from here.

**Comment by terracoda** [comment]
I don't seem to land on "at middle" when I use default key press.
Not sure what to suggest about that.

**Comment by terracoda** [comment]
@zepumph, I am still not hearing "at middle" of Play Area neither with default key press now with little steps with Shift key.

**Comment by emily-phet** [comment]
Agreed - I can't get "at middle" to appear in a11y view either.

**Comment by zepumph** [comment]
using `?log`, I saw that in many cases it was working, but going to either extremity, and then trying to find the direct center again most often resulted in a rounding error like `.499999999999999997` in the model. I clamped this to the expected value above, and I hope that this is no longer a bug. Please confirm fixed on master.

**Comment by terracoda** [comment]
Closing.
