### ISSUE TITLE
Staccato sound should play immediately when leaving fitness=0

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#144]
I noticed that there seems to be a half second delay before hearing the first staccato sound. I thought I tried to fix this such that we have a sound right when entering the "feedback zone." There is either a bug with how I tried to do this, or I actually didn't do it. Tagging designer @BLFiedler to confirm that is expected behavior. I felt like we decided this in a sound design meeting, but didn't make it happen!

**Comment by BLFiedler** [comment]
I think for consistency it would be good to play the first sound with the first visible color change. Tagging @jbphet to see if he agrees.

**Comment by zepumph** [comment]
While working on this, I saw doc that made it seem like we made it this way to prevent getting a note often when you fling the hand from top to bottom through and past the ratio. @jbphet, this is a use case you were thinking about often. @BLFiedler and @jbphet, is it better now, or worse?

**Comment by jbphet** [comment]
I think I prefer it this way, where the sound always occurs, even if moving fast.  I'll wait to log a final opinion until we have the "success" sound playing on each crossing, which is something that we discussed at the last sound design review meeting.

**Comment by zepumph** [comment]
I don't know where the in proportion sound playing issue went, so I will do that here too.

**Comment by zepumph** [comment]
On second thought, I think I will work on that in a new issue, see https://github.com/phetsims/ratio-and-proportion/issues/162.

@BLFiedler anything else for this issue?

**Comment by BLFiedler** [comment]
Haha. Nope, that'll do here.
