### ISSUE TITLE
Weird lock ratio bug

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#146]
I think this needs to be fixed with a design decision. Here is how to reproduce:

1. Create screen
2. Target ratio 1:1
3. move both hands to about ~.4, be in proportion, but try to make the values a bit different
4. Click "lock ratio" 
5. both should snap to above .5
6. move them up to the top of the space
7. The minor different that was in proportion tolerance down low now makes a very strange weird at high levels.

Pic down low (after snap above .5 because of clicking "lock ratio"):
![image](https://user-images.githubusercontent.com/6856943/90473964-b2743100-e0d0-11ea-829d-465d01acc679.png)

Pic up high:

![image](https://user-images.githubusercontent.com/6856943/90473997-c9b31e80-e0d0-11ea-9ebc-240610b1c676.png)

**Comment by zepumph** [comment]
Can be seen in https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.52/phet/ratio-and-proportion_all_phet.html

**Comment by BLFiedler** [comment]
Let's revisit this during design meeting. There's some weird behavior while doing this where it just pops out of ratio while moving it around the middle region. 

But, wrt the above, we should maybe discuss if it's worth having the Lock Ratio automatically jump the hands to the exact ratio values (fitness == 1.000000000000000000000000000, exaggerated for emphasis)

**Comment by zepumph** [comment]
Ahhh yes, jump to exactly in ratio, I like that! But which hand holds the definition of "the ratio"  probably it's enough to just say "the left" always.

**Comment by BLFiedler** [comment]
Just to detail what we decided in the last design meeting:

Let's go ahead with the fix mentioned above re the left hand automatically jumping to make the ratio fitness precisely 1 within whatever precision is used in the sim with the understanding that the window of "dark green" is always fairly small and any jump will also be small and hardly noticed. If this is not the case and it seems jarring, we should revisit.

**Comment by zepumph** [comment]
Here is a start on this. It isn't as simple as I wished it was, as we have edge cases where automatically snapping the left will take it out of the position range. 

<details>

```diff
Index: js/common/model/RatioAndProportionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/RatioAndProportionModel.js	(revision 5eca06daef4d55586f9fc5932057da07b58a7c9b)
+++ js/common/model/RatioAndProportionModel.js	(date 1598384754496)
@@ -59,7 +59,7 @@
     } );
 
     // @public - when true, moving one ratio value will maintain the current ratio by updating the other value Property
-    this.lockRatioProperty = new BooleanProperty( false );
+    this.lockRatioProperty = new BooleanProperty( true, { reentrant: true } );
 
     // @public (read-only) - the Range that the ratioFitnessProperty can be.
     this.fitnessRange = new Range( 0, 1 );
@@ -132,11 +132,14 @@
     this.previousRightValueProperty = new NumberProperty( this.rightValueProperty.value );
     this.stepCountTracker = 0;
 
-    // Avoid reentrancy by guarding each time one valueProperty change then sets the other.
+    // Avoid infinite loops by guarding each time one valueProperty change then sets the other.
     let adjustingFromLock = false;
 
+    // Guard on the initial snap to perfect ratio when the lockRatioProperty is toggled on
+    let guardOnInitialLockSnap = false;
+
     this.leftValueProperty.lazyLink( ( newValue, oldValue ) => {
-      if ( this.lockRatioProperty.value && !adjustingFromLock ) {
+      if ( this.lockRatioProperty.value && !adjustingFromLock && !guardOnInitialLockSnap ) {
         const previousRatio = oldValue / this.rightValueProperty.value;
         adjustingFromLock = true;
         this.rightValueProperty.value = Utils.clamp( newValue / previousRatio, this.valueRange.min, this.valueRange.max );
@@ -147,7 +150,7 @@
       }
     } );
     this.rightValueProperty.lazyLink( ( newValue, oldValue ) => {
-      if ( this.lockRatioProperty.value && !adjustingFromLock ) {
+      if ( this.lockRatioProperty.value && !adjustingFromLock && !guardOnInitialLockSnap ) {
         const previousRatio = this.leftValueProperty.value / oldValue;
         adjustingFromLock = true;
         this.leftValueProperty.value = Utils.clamp( newValue * previousRatio, this.valueRange.min, this.valueRange.max );
@@ -165,7 +168,24 @@
 
     this.lockRatioProperty.link( ratioLocked => {
       this.enabledValueRangeProperty.value = new Range( ratioLocked ? LOCK_RATIO_RANGE_MIN : VALUE_RANGE_MIN, VALUE_RANGE.max );
-    } );
+
+      if ( ratioLocked ) {
+        guardOnInitialLockSnap = true;
+        // Snap the left hand to be exactly at ratio to prevent multiplicative errors when the locked ratio is expanded, see https://github.com/phetsims/ratio-and-proportion/issues/146
+        const potentialNewLeft = this.targetRatioProperty.value * this.rightValueProperty.value;
+        if ( this.valueRange.contains( potentialNewLeft ) ) {
+          this.leftValueProperty.value = potentialNewLeft;
+        }
+        else {
+          const potentialNewRight = this.leftValueProperty.value / this.targetRatioProperty.value;
+          assert && assert (this.valueRange.contains( potentialNewRight), 'if left is not in range, then right must be');
+
+          this.rightValueProperty.value = potentialNewLeft;
+          }
+          guardOnInitialLockSnap = false;
+        }
+      }
+    );
 
     this.enabledValueRangeProperty.link( enabledRange => {
       const clampPropertyIntoRange = property => !enabledRange.contains( property.value ) && property.set( enabledRange.constrainValue( property.value ) );

```
</details.

**Comment by zepumph** [comment]
In https://github.com/phetsims/ratio-and-proportion/issues/176 I am going to factor out the lockRatio logic into a single spot. It will likely make it easier to see a way to add this clamping into place.

**Comment by zepumph** [comment]
I was finally able to solve this, mostly because of work done in #181. I can no longer reproduce the initial problem (1:1 case). @BLFiedler please review. Does this feel complete to you?

**Comment by BLFiedler** [comment]
Looks like it works in the latest dev version, but we should check to make sure the jump doesn't feel funny to anyone in design meeting, just to circle back on this decision.

**Comment by zepumph** [comment]
The design team looked this over today and we don't feel like the snap is too jarring. I couldn't produce a case where the snap changed the description into a different position/distance-apart region. I'm going to close this issue.
