### ISSUE TITLE
Updates to list in screen summary - when "tick marks" only selected

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#147]
@Matthew-Moore240 
We need to discuss this situation. Currently, the implemented description does not have the ordinal wording (e.g., "first tick mark", "second tick mark") but also I think the "middle of tick mark" and the regions used for "just below" "below" etc. could be improved. Easier if we discuss in realtime though.

**Comment by Matthew-Moore240** [comment]
Do we still need this issue? I believe we discussed this and came to a conclusion about the tick marks.
