### ISSUE TITLE
Regions for in between tick marks for semi-quantitative Sceen Summary only

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/ratio-and-proportion#154]
added the table for semi-quantitative tick mark for the region between the hands and this is for the non numbered tick marks only. 

- {{on}}
- {{just below}}
- {{below}}
- {{halfway past}}
- {{above}}
- {{just above}}

Example scene summarry
Currently, hands are {{at}} the challenge {{1}} ratio with

- Left hand {{**just above** second tick mark}} 
- Right hand {{**halfway past** fourth tick mark}} 
- Hands are {{extremely far from}} each other.

**Comment by zepumph** [comment]
Right now there is nothing about larger tick mark ranges, so I will keep this here in case we need it in the future, and just follow the table for now.

<details>

```
        "eleventh": {
          "value": "Eleventh"
        },
        "twelfth": {
          "value": "Twelfth"
        },
        "thirteenth": {
          "value": "Thirteenth"
        },
        "fourteenth": {
          "value": "Fourteenth"
        },
        "fifteenth": {
          "value": "Fifteenth"
        },
        "sixteenth": {
          "value": "Sixteenth"
        },
        "seventeenth": {
          "value": "Seventeenth"
        },
        "eighteenth": {
          "value": "Eighteenth"
        },
        "nineteenth": {
          "value": "Nineteenth"
        },
        "twentieth": {
          "value": "Twentieth"
        },
        "twenty-first": {
          "value": "Twenty-first"
        },
        "twenty-second": {
          "value": "Twenty-second"
        },
        "twenty-third": {
          "value": "Twenty-third"
        },
        "twenty-fourth": {
          "value": "Twenty-fourth"
        },
        "twenty-fifth": {
          "value": "Twenty-fifth"
        }
```

**Comment by zepumph** [comment]
I updated the middle region what was "in the middle of" to be "halfway past". This is for the numbered grid also. I felt like that was what we talked about doing last design meeting also, even though it wasn't totally clear that was correct from the doc or above comment.

**Comment by zepumph** [comment]
Ordinal numbers for semi-quantitative description has been implemented above, as well as a bug fix for the "halfway past" update above.

I only implemented to "ninth" because I saw that on the table, the tenth actually swapped back to full quantitative. Is this correct?

![image](https://user-images.githubusercontent.com/6856943/91242489-0b0c8500-e6f4-11ea-9798-36acd3b6a4ce.png)


I feel fine about writing out ordinals all the way up to "thirtieth" if you want that, but perhaps you have other thoughts on the matter. Anywho, please review in master.

**Comment by Matthew-Moore240** [comment]
Yeah I think if @terracoda wants to weigh in on how far we want to take the ordinals since on the create screen the tick marks go all the way to 30.

**Comment by Matthew-Moore240** [comment]
Going with ordinals all the way to the 29th spot, and tick mark {{last number of the grid}}. This applies only to  semi-quantitative descriptions.

**Comment by terracoda** [comment]
I am sorry, I didn't understand the question.
First (zero) and last (ten, twenty, and thirty) are not ordinals to kind of cue the edges of the ranges.

**Comment by zepumph** [comment]
Ordinals up to twenty-nine implemented above. zero and top tick mark are always numbers. Please review.

**Comment by zepumph** [comment]
https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.61/phet/

**Comment by Matthew-Moore240** [comment]
So these all seem implemented I think its good to close now unless we want to wait till after interviews?

**Comment by zepumph** [comment]
How about we close this, and create new issues for any tweaks that may come from interviews. Reopen if you feel differently.
