### ISSUE TITLE
Reproducible key steps when mouse input moves off expected "grid"

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#156]
This is a question for @terracoda:

@emily-phet, @Matthew-Moore240, and I were curious about how mouse input can "throw off" the designed keyboard steps. In particular, how using the mouse can make it impossible to get to the "even with" distance alert over in https://github.com/phetsims/ratio-and-proportion/issues/152, even if you use keyboard after mouse input.

Problem: keyboard movements go to unplanned values after moving with a mouse that doesn't snap-to-tick-mark. (can't get to "even with" distance alert as a symptom)
Steps to reproduce:
* Load sim with `?log`
* use a keyboard input and look at the even values in the console
* move the hand with a mouse
* use keyboard input again and see that the value is no longer nice/designed.

We were wondering if we should snap keyboard input to the even numbers after this case, or if we don't need to support it. @terracoda what have we done (if anything) in the past to support this?

**Comment by terracoda** [comment]
Oh my, this is an interesting issue. I don't think we have run into this before because we usually have some rounding to a certain number value that is visually displayed.

I think the minimum movement of the mouse had to snap to the smallest step size that can be made with the keyboard, i.e., the Shift-key step size. I don't think we know what this is yet (1/10th or 1/12th).

Alternatively, the first step with the keyboard after mouse use would have to snap to the grid to re-even things out. I think we did this for the numbers in Ohm's Law and Resistance in a Wire.

**Comment by terracoda** [comment]
@zepumph, @emily-phet, and @Matthew-Moore240, do either of those ideas make sense?

**Comment by zepumph** [comment]
>Alternatively, the first step with the keyboard after mouse use would have to snap to the grid to re-even things out. I think we did this for the numbers in Ohm's Law and Resistance in a Wire.

I prefer this. We implemented the other snapping for mouse input (maybe I never committed it?!?!) and it felt like it took away from the "free-motion" feel of mouse/touch.

**Comment by terracoda** [comment]
@zepumph, that makes sense for the mouse. I would hope/think that snapping/rounding the key press on the first step with the keyboard is a good approach.

**Comment by zepumph** [comment]
I went ahead and had each keyboard interaction snap to the nearest shift keyboard step. To see the new feature/bug-fix you can do the following:

* Load the sim with ?log
* move the left hand with the mouse. Let's say the new value for it is `.251847895`
* keyboard focus the left hand (individually or with the "both hands interaction"
* press shiftKey+up and the new value will snap, to something like `.26`.

@emily-phet how does that sound?

**Comment by emily-phet** [comment]
@zepumph Does it snap only to the nearest shift+keypress location, regardless of whether or not the user is using the shift modifier key? If the user is not using the shift modifier key, I think it should snap to the nearest arrow keypress location. 

If someone has used a mouse first, and then the keyboard it seems their intent is to move the hand, so if the hand moves a tiny bit or little bit seems less important than making sure it moves to a useful location for continued keyboard use. If the hand just moves to the nearest shift+keypress location even if they're not using the shift modifier key, they may forever be in a situation where their keypresses are never spot-on a gridline, and this complicates the cueing of the ratio relationships. 

Does that make sense? I think the hand should snap to the nearest shift+keypress location if someone is using the shift modifier key, but the hand should snap to the nearest keypress location if someone is just using the arrow keys or the W/S keys.

**Comment by zepumph** [comment]
Great idea! I have implemented the constraint to take into account if the shiftKey is down. Please review.

**Comment by terracoda** [comment]
I agree, that should solves some issues.

**Comment by emily-phet** [comment]
I just tried this on phettest, and I can't get the hands to move at all with the keyboard after moving them with the mouse. 

For example, first screen opens, I move left hand up with mouse, then move focus to left hand, press arrow keys - nothing. 
Same happens if I move focus to the left hand, then move hand with mouse, then press arrow key (with or without focus highlight on hand) - nothing.

**Comment by zepumph** [comment]
>(with or without focus highlight on hand) - nothing.

If there is no focus highlight, I wouldn't expect any keyboard interaction to work, since that means that the PDOM element doesn't have DOM focus.

Weird! I pulled all on phettest and loaded https://bayes.colorado.edu/dev/phettest/ratio-and-proportion/ratio-and-proportion_en.html?brand=phet&ea and couldn't reproduce. 

I also haven't encountered this locally on my development machine. 

Can you try https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.72/phet/ratio-and-proportion_en_phet.html? Maybe it was a caching problem.

**Comment by emily-phet** [comment]
Got it working in dev 72 - This looks great to me!
