### ISSUE TITLE
"both hands" context alert

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#161]
In addition to a sentence in the PDOM to be added in https://github.com/phetsims/ratio-and-proportion/issues/157, what should the user hear about the ratio after each both hands interaction.

**Comment by terracoda** [comment]
This is a burning question that needs to be worked out.

**Comment by zepumph** [comment]
This was implemented over in https://github.com/phetsims/ratio-and-proportion/issues/173, closing
