### ISSUE TITLE
Some staccato sounds don't have enough attack

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#168]
@jbphet mentioned this problem, and @Ashton-Morris said that there were three of https://github.com/phetsims/ratio-and-proportion/tree/fcd294f172c15db52a6cd170ce22a84ff761a0de/sounds/staccato that sounded like there was less attack.

Over to him to make fixes for me to put them in the sim.

**Comment by Ashton-Morris** [comment]
@zepumph Can you replace the old files with the same name with these ones. I have fixed the attack on these.

[Files here](https://drive.google.com/drive/folders/1A2SV3y_Qd0xAFx_IVCaMEqg9Mbq9wduk?usp=sharing)

marimba-variation-v2-g.mp3
marimba-variation-v2-c-sharp.mp3
marimba-variation-v2-c-sharp.wav
marimba-variation-v2-d-sharp.mp3
marimba-variation-v2-d-sharp.wav
marimba-variation-v2-e-001.mp3
marimba-variation-v2-e-001.wav
marimba-variation-v2-e.mp3
marimba-variation-v2-e.wav
marimba-variation-v2-g.wav

**Comment by zepumph** [comment]
@jbphet could you please review to see that this is fixed on master now.

**Comment by jbphet** [comment]
Yes, I think this is an improvement.
