### ISSUE TITLE
Shape, Size, and Behavior of Freely Moving Cursors

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#17]
>1. zepumph There's a bit of "momentum" [edit I think I mean inertia specifically] to dragging the object, which I'm a little uncertain of since it pulls the visual away from your body movement a little when moving quickly (I notice this pretty strongly using my hands and a touch screen). I'd like to hear others' thoughts on this.

>2. It might be worth considering the optimal size of the objects - slightly bigger or asymmetric objects would let me see them under my fingers. However, perhaps not seeing the objects and only relating to hand movement is preferable pedagogically.

_Originally posted by @BLFiedler in https://github.com/phetsims/proportion/issues/7#issuecomment-610432553_

There has been some discussion on the shape and size of the cursor/crosshair already by @emily-phet and @ Dor. 

Adding one idea to the conversation that I think retains some of the "fun" while remaining abstract. Should not be reminiscent of anything gun-like. Not required, but I wondered about a small transparent center to see the gridlines beneath (compared to a more open crosshair)

![image](https://user-images.githubusercontent.com/47331395/79246628-ab919500-7e36-11ea-8ae0-466a32f3b9ee.png)

**Comment by BLFiedler** [comment]
Dor, from #7 

>1. Momentum would be a nice, realistic effect. Still, I worry about confusion over the “where” of my finger. I think finger-to-cursor tightness is less ambiguous.

>2. Thinking ahead to the appearance of the grid, I’d want the player to see the cursor’s precise location on the grid. The crosshairs of the “plus” cursor enable acuity in calibrating cursor location.

**Comment by BLFiedler** [comment]
Emily drew up a few designs and I was inspired to make a few based on some blobbier designs & some mixtures, as well as a few asymmetric and totally different ideas.

![image](https://user-images.githubusercontent.com/47331395/79262028-e3580700-7e4d-11ea-881d-d38ce3d7f3f6.png)

@emily-phet 's picture:
![image](https://user-images.githubusercontent.com/47331395/79262085-f9fe5e00-7e4d-11ea-8f84-f7238a33c270.png)

**Comment by zepumph** [comment]
- [  ] In addition to shape, it may be nice to think about extending pointer areas so that there is a way to have your finger to the side of the middle.

**Comment by zepumph** [comment]
- [ ] Also do we want the behavior to be such that the shape changes when the proportion is in a perfect/correct state?

**Comment by emily-phet** [comment]
From Clement in design doc

> Could the symbols be different? E.g. a cross and a circle to differentiate the two points for free moving. Like how categorical information is encoded with shapes in a scatterplot, while interval information is encoded in position.

I wonder if having two completely different symbols may be problematic pedagogically. Happy to explore that though, there may be benefits.
Another approach might be to have starting objects with natural handed-ness or chirality. Maybe even something as simple as a small left and right hand.

**Comment by emily-phet** [comment]
In response to @zepumph [comment](https://github.com/phetsims/proportion/issues/17#issuecomment-613622631): I think changing shape is a good idea to keep in our pocket. I'd like to see how far we can get without that, as i think it might be 1) challenging to design potentially multiple object designs that work well when changing sizes and 2) work well when using a touch screen versus other input. 

Let's revisit after we try a few other cueing approaches, and see if this seems like a needed additional strategy to include.

**Comment by emily-phet** [comment]
I'd like to try using two "hands" for the default style of the free moving objects. We would also probably want to provide another design option (like those explored above). See #22 for info on the hand design and progress.  

Let's try out the hands alone, as we're working out the basic design, and revisit other options if/when there are issues with the hand representation, or when we're ready to add in a second representation.

**Comment by BLFiedler** [comment]
Not to muddy up the issue where this art is being requested, I'll just offer up some "chiral" hand options that have a "physical" feel much like we'd be doing in the tangible interface - grabbing, pinching, etc that create a natural opening to see the grid underneath:

![image](https://user-images.githubusercontent.com/47331395/79766961-eb98c200-82e5-11ea-9555-a007c09f8d64.png)

![image](https://user-images.githubusercontent.com/47331395/79767074-11be6200-82e6-11ea-97cd-28c2bb0e7b7f.png)

Could even had a small transparent object (circle, etc) in the grip that is the "pointer" part.

**Comment by zepumph** [comment]
Note that as part of https://github.com/phetsims/ratio-and-proportion/issues/31, cursor options have been moved to the options dialog.

**Comment by emily-phet** [comment]
@zepumph Please add white circles to each hand when grid is present. (Note, used old screenshot to make mockup below, sim should still have only horizontal gridlines). 
<img width="820" alt="Screen Shot 2020-05-22 at 6 37 26 AM" src="https://user-images.githubusercontent.com/5109055/82673490-ce158b80-9bf6-11ea-9b79-b60f226e1a3d.png">

**Comment by zepumph** [comment]
Added above. Please review:

![Uploading image.png…]()

**Comment by zepumph** [comment]
@amanda-phet said in https://github.com/phetsims/ratio-and-proportion/issues/51#issuecomment-634804642:

>Not sure if this is the right issue to mention this but I think the white dots in the hands could be smaller. Maybe 50% of the current diameter, so it looks more like a "point."

Let me know what you want @emily-phet.

**Comment by emily-phet** [comment]
See my previous comment [here](https://github.com/phetsims/ratio-and-proportion/issues/51#issuecomment-635368320) in issue #51.

**Comment by zepumph** [comment]
The radius was 16. I changed it to 10. 8 felt a bit small, but let me know what you would like

**Comment by zepumph** [comment]
I centered them above. This then in turn has made the cue arrows uncentered to other pointers (circle and cross). It would be nice if we could just get rid of this option, and only support the Hand. Otherwise I will want to go in and add more logic to appropriately support the cue arrow layout with all pointers. Let me know what you would like.

**Comment by emily-phet** [comment]
I just remembered, my hope had been to have the circle only appear on the hands once the gridline and numbered grid option are selected. Can you make that happen? I hope the cue arrows still look reasonable in their current (new) location. They always seemed slightly misaligned before, because of the asymmetric nature of the hand markers. 

I think we can lose the "circle" and "cross" options for markers.

**Comment by zepumph** [comment]
I was able to do a bunch of cleanup regarding the other pointer options. I also implemented the circle visibility logic that you asked for. Please note that I made this logic apply to the "My Challenge" icons as well, which is either cool or weird, I can't yet decide. Let me know what you'd like!

**Comment by emily-phet** [comment]
@zepumph  I like the circle appearance/disappearance behavior! Nice touch that the hands on the custom challenge input match. Nice!
