### ISSUE TITLE
Add proximity to ratio alerts when changing the challenge ratio

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#177]
On the first screen, this will be easy, when the combo box selects an element, then we should alert just the state of the current ratio, like:

"Somewhat close to challenge ratio."
"At challenge ratio."

etc.

On the second screen, we want this same type of alert when you change either number picker. There may be a way to implement this with AccessibleValueHandler, but I'm not sure.

**Comment by zepumph** [comment]
This description is called "proximity to ratio" description.

**Comment by zepumph** [comment]
Implemented above. Over to @Matthew-Moore240 to review once I create a dev version for interviews.

**Comment by Matthew-Moore240** [comment]
This is great! Closing.
