### ISSUE TITLE
Staccato sound bug

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#179]
From https://github.com/phetsims/ratio-and-proportion/issues/174#issuecomment-692980081

some of the repeating sounds are mixed up and different pitches.

To reproduce:
1st screen
challenge 1
move right value to 3

**Comment by zepumph** [comment]
Good catch @jbphet! I traced it back to a naming issue, but when I redownloaded e-001 from https://drive.google.com/drive/u/1/folders/10-kHZgFSu0HEMUfNk0zEn0cvPRK8gFXg and it sounds correct now. Over to @jbphet to confirm on master.

**Comment by jbphet** [comment]
Yep, seems fine on master.  Closing.
