### ISSUE TITLE
Should horizontal boundaries get a boundary sound

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#180]
Over in https://github.com/phetsims/ratio-and-proportion/issues/174#issuecomment-692980081 @jbphet mentioned that it is weird to get the boundary bumps on vertical boundaries but not horizontal. @BLFiedler do you think that this deserves design attention.

**Comment by BLFiedler** [comment]
My gut reaction is that the horizontal boundaries have no pedagogical meaning and I wouldn't want to draw attention to them with sounds. The vertical boundaries indicate the edge of the dimension that provides feedback through movement. Horizontal displacement only exists for mouse and touch interaction (not keyboard) and we generally want people to quickly figure out it has no bearing on how they receive feedback. 

If there's no description of horizontal movement, then it's not clear to me that a non-visual user would benefit from the horizontal boundary sound either while hearing only reports on vertical translation/relation.

**Comment by zepumph** [comment]
I think that this is only for mouse input, and not for keyboard. I agree it isn't very pedagogically important, but perhaps it would be a nice minor improvement for continuity. Either way is good with me, just let me know what you would like.

**Comment by BLFiedler** [comment]
Let's just get a quick consensus on this from the group during sound design meeting.

**Comment by zepumph** [comment]
@emily-phet said that we normally add these sorts of sounds unless there is a reason not to. We feel like we should add this, and then note for future use if we see a problem with it.

**Comment by zepumph** [comment]
Implemented above. Closing

**Comment by zepumph** [comment]
Tagging #174 as this may want review over there
