### ISSUE TITLE
Test the "In Proportion" sound with alternate fade out styles

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/ratio-and-proportion#182]
[Here are two alternate fade styles to try out.](https://drive.google.com/drive/folders/1A2SV3y_Qd0xAFx_IVCaMEqg9Mbq9wduk?usp=sharing)

- in-proportion-quick-fade.mp3
- in-proportion-quick-fade.wav
- in-proportion-studio-fade.mp3
- in-proportion-studio-fade.wav

**Comment by zepumph** [comment]
In the above commit I added these two as options for the in proportion sound. The default is still in place, but you can change to either of these two by in the console typing:

```js
inProportionProperty.value = 'quick'
inProportionProperty.value = 'studio'

```

Setting the value to any other string will go back to default. I'm looking forward to discussion tomorrow about this. You can test this out on https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.65/phet/


My opinion is that we should go with "quick", which isn't quick, but is much shorter than the default (it is only ~3 seconds)

**Comment by zepumph** [comment]
today during sound design meeting, we felt like we wanted `studio` fade, but even shorter than the current `quick` version of the above. Perhaps only 1.5 or 2 seconds long?

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/ratio-and-proportion/issues/178#issuecomment-696997581 we decided to revert the change that caused this long sound from always playing fully. 

After that is done, we will just have this issue (long sound playing) on keyboard input when you don't focus away. We feel like using the above "quick" version of this sound is short enough to cover this case. I will put that into the sim.

**Comment by zepumph** [comment]
"Quick" sound is now in place, and the `wav` file was added to assets. Closing

**Comment by zepumph** [comment]
Tagging #174 as this may want review over there

**Comment by Ashton-Morris** [comment]
[I added some sounds here](https://drive.google.com/drive/folders/1A2SV3y_Qd0xAFx_IVCaMEqg9Mbq9wduk?usp=sharing)

Based off of my notes from the meeting "TODO:  Studio Fade on ringing out but a little bit shorter (1.5 or 2 seconds long)"

- in-proportion-studio-fade-1.5-sec.mp3
- in-proportion-studio-fade-1.5-sec.wav

But reading above maybe we decided not to do that edit? Either way the files are here if needed.
