### ISSUE TITLE
Left/Right Hand Sliders need vertical orientation

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#186]
In the last interviews, the Left and Right Hand sliders sounded horizontal (Left-Right slider).

@zepumph, can you verify that `aria-orientation="vertical"` is being used on the sliders, please.

It's possible, it's there, but JAWS doesn't recognize it (not sure).

**Comment by zepumph** [comment]
I see `horizontal` right now:
![image](https://user-images.githubusercontent.com/6856943/94467674-c3a06b00-016f-11eb-84fd-eeafb5879646.png)


Sorry about that! one change coming right up.

**Comment by zepumph** [comment]
It's now vertical. Closing
