### ISSUE TITLE
Finalize names of sound files

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#191]
From #127 checklist:

>Finalize the names of all sound files that have been added and get uncompressed versions of them and add them to
the assets directory. Make sure the names match, e.g. bonk.mp3 in the sounds directory and bonk.wav in the
assets directory.

We still have our prototype-like names of sounds in the project, and not all of them have associated `.wav` files in the `assets` folder.

I want to do this issue with @Ashton-Morris so that whatever names he has for files are updated in correlation with the github files.

**Comment by zepumph** [comment]
Thoughts I have to change:

* marimba-variation-v2-... should maybe be named more for `staccato` than for `marimba`.
 * every sound should have a number suffix (000/001/002 OR 001/002/003 OR 1/2/3). I think I like 1/2/3.
 * How about something like:
    * staccato-c-1.mp3
    * staccato-c-2.mp3
    * staccato-c-3.mp3
    * ....
    * staccato-f-sharp-1.mp3 etc...
* in-proportion-quick-fade -> `in-proportion.mp3`
* moving-in-proportion-loop-option-4 -> moving-in-proportion-organ-loop
* choir-ahhh-loop -> moving-in-proportion-choir-loop


@Ashton-Morris, any qualms with the above plan?

**Comment by Ashton-Morris** [comment]
I have no issues. I have the changed the names of those files on my computer. Did you want to change them on your end also, or have me send some? @zepumph

**Comment by zepumph** [comment]
I will rename now. 

I used this script to change all the staccato filenames:
```js
const fs = require( 'fs' );

const path = '../ratio-and-proportion/sounds/staccato/';
let files = fs.readdirSync( path );
files = files.filter( file => file.startsWith( 'marimba' ) );

files.forEach( fileName => {
  const newFileName = fileName.replace( 'marimba-variation-v2-', 'staccato-' );
  fs.renameSync( `${path}${fileName}`, `${path}${newFileName}` );
} )

```

**Comment by zepumph** [comment]
Everything is renamed, now I just need to add the staccato sound `wav` files to assets. I'll get them from the google drive folder.

**Comment by zepumph** [comment]
Grabbing the wav files from https://github.com/phetsims/ratio-and-proportion/issues/9#issuecomment-654891590

**Comment by zepumph** [comment]
I used this script to rename and move wav files into assets:

```js
const fs = require( 'fs' );

const outputPath = '../ratio-and-proportion/assets/staccato/';
const inputPath = './rap-sounds/'
let files = fs.readdirSync( inputPath );
files = files.filter( file => file.endsWith( '.wav' ) );

files.forEach( fileName => {
  const newFileName = fileName.replace( 'marimba-variation-v2-', 'staccato-' );
  fs.copyFileSync( `${inputPath}${fileName}`, `${outputPath}${newFileName}` );
} )
```

Everything seems done to me now. @Ashton-Morris will you please take a look at file names in the following dirs to make sure all looks good from your end. Feel free to close.

https://github.com/phetsims/ratio-and-proportion/tree/master/assets
https://github.com/phetsims/ratio-and-proportion/tree/master/assets/staccato
https://github.com/phetsims/ratio-and-proportion/tree/master/sounds

Thanks!

**Comment by Ashton-Morris** [comment]
Looks good

**Comment by zepumph** [comment]
I found https://drive.google.com/drive/u/1/folders/1A2SV3y_Qd0xAFx_IVCaMEqg9Mbq9wduk with outdated file names. Does this folder stick around past the design phase of a sim? We already store all the underlying `wav` files in the github repo, so I'm not sure we need this.

**Comment by Ashton-Morris** [comment]
I have copies of all of the in-developement working files on my computer so I don't thing we need this, but usually I just leave them there out of habit.

**Comment by zepumph** [comment]
It's redundant to have the same resources check into git as well as in drive. It also seems problematic to me to have them with outdated filenames that no longer link to the same resources in github, and (hopefully) on your computer. I would expect that from this issue, all of the filenames on your computer (wav/reaper-projects/tracks-in-reaper/mp3/etc) would have the new name. Thus something titled "marimba-variation-v2" is actually confusing and negative to stick around. 


Maybe we can improve the collaboration around keeping the asserts dir as this central scrap page: https://github.com/phetsims/ratio-and-proportion/tree/master/assets. Right now it is all top level, but there is nothing saying we couldn't have a sub-dir for `sound-design/`, and then we just end up promoting the sounds that we actually end up using in the sim. Furthermore, having this space in git would allow us to keep references to sounds even when we delete them. For example, I could point to https://github.com/phetsims/ratio-and-proportion/blob/27653070bf4c2303c8feb0352e0c3ca1aa85e607/assets/in-proportion-quick-fade.wav even though that file no longer exists on master (thanks git!!).

>I have copies of all of the in-development working files on my computer so I don't thing we need this

It is a PhET standard in general to try to maximize the percentage of resources that are in shared spaces. It doesn't always work (like I know it won't for reaper files), but in general the more in the PhET cloud things are, the more maintainable and transparent things are. Would it work for you to have these local files centered around local git checkouts of RaP and other sims?

I'm happy to keep discussing.

**Comment by Ashton-Morris** [comment]
I see what you are saying. I think this ties into the soundboard idea that JB and I will be diving into. I can bring up this in relation during those talks because I do think it's good to have a better tracked workflow overall.

**Comment by zepumph** [comment]
I ceated https://github.com/phetsims/tambo/issues/127 to track the tail of this conversation. I think this specific issue is ready to be closed.
