### ISSUE TITLE
Add sound design credits

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#192]
From https://github.com/phetsims/ratio-and-proportion/issues/127:

>If there were individuals who were only involved in the sound design and thus not already on the team or
other lists in the credits, add them using the soundDesign key.

I think this is just going to be @Ashton-Morris, but I thought I would double check.

**Comment by zepumph** [comment]
Anything else here @Ashton-Morris?

**Comment by Ashton-Morris** [comment]
@zepumph Not that I am aware of.
