### ISSUE TITLE
Object & Context Responses for Ratio Challenges Combo Box

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#196]
Yesterday we discussed new approach with the number spinners on Screen 2, see issue #195.

On screen 1 we have the Challenge Ratio combobox that allows learners to change between 3 different pre-set challenge ratios.

In the design document I sketched out what the interaction sounds like, and 2 options for the context response. There are pros and cons to both options. I am wondering which one @Matthew-Moore240 and @emily-phet think is best.

Option 1 stays in synch with sim and communicates the proximity to ratio.
Option 2 encourages interaction with the hands.

I didn't sketch out an option 3 that would combine option 1 and 2, as it would be long. 

@emily-phet and @Matthew-Moore240 could you review this table int he design doc
[Table: Object & Context Responses for Ratio Challenges combobox (screen 1)](https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit#heading=h.6s1v78qubkmw)

And tell me what you think?

The choice would affect how I feel about the sonification review in #174.

**Comment by Matthew-Moore240** [comment]
I really like option 2. I think that is a pretty elegant solution to the problem.

**Comment by emily-phet** [comment]
My initial thought was also to go with option 2. 

A few additional thoughts: I was trying to think through how people would conceptualize a combobox interaction in general. My guess is that maybe our kind of use is probably pretty uncommon, but I don't know for sure. For example, I can't think of common examples of a combobox where after you make the choice it essentially sets the whole underlying "world" you're and now you should figure out what to do next (as opposed to something like making choice of what toppings on your burrito and moving to the next question). 

With the sound, there was a version where when you change the combobox, if the hands are ever at that particular ratio, you get the success sound. The sound meeting folks collectively disliked this... it seems right in theory, but in practice it felt off - hearing the combobox sound + the hand success sound just seemed at best like it was taking your attention away from you were currently in an unhelpful way, or just plain confusing at worst.

This might relate to why we're all leaning towards option 2 - maybe there's something about a combobox that feels wrong about it giving you all the "Play Area" feedback, and it feels more "right" to have it just indicate to direct your attention (and literal navigation focus) back to the actual hands.

**Comment by terracoda** [comment]
Re, is a combobox the right interaction?
- We could try out a group of three radiobuttons to see if that works better. Both interactions provide a list of options to choose from. I think the combobox interaction might have been chosen for its visual brevity (compactness).

We can also look very carefully at how the combobox is being experienced non-visually. There seems to be subtle differences between RaP's "Ratio Challenges" combobox and Moalrity's "Solute" combobox.

We can also try using _aria-roledescription_ to call it a combobox instead of a pop-up button?

Regardless, @emily-phet, I think we do indeed need to communicate to learners that they are changing their underlying situation. The interactive description design has three pieces that can directly communicate this: the name, the help text, and the context response. For this interaction we have:

- Name: Challenge 1, pop-up button (announced on focus, or read with arrow keys)
- Help text: Choose a ratio challenge to discover. (read with arrow keys)
- Context responses under discussion:
    1. Hands, {{somewhat close to}} challenge {{2}} ratio. 
    2. Move hands to explore challenge {{2}} ratio.

Option 3 (not in design doc):
 - Move hands to explore challenge {{2}} ratio. Hands, {{somewhat close to}} challenge ratio.
- Personally, I think option 3 is too long.

**Comment by terracoda** [comment]
Discussed October 8th.
Sketch out smaller scale for proximity to ratio and indication to play with hands.

**Comment by Matthew-Moore240** [comment]
Scale for proximity

- on
- around/near
- far-off/distant




1. Last part changes to this if they are already in ratio:

Hands, {{on}} challenge ratio. _Move hands again to explore more of challenge {{2}} ratios._

2. This is shorter, near/around could be used when the screen is any shade of green that isnt {{on}}

Hands, {{near}} challenge _{{2}} ratio. Use hands to find ratio._

3. This is also shorter, and this would be used when the screen is white

Hands, _{{far-off}} from challenge {{2}} ratio. Use hands to find ratio._

**Comment by Matthew-Moore240** [comment]
We want to avoid using words that are already in other parts of the description.

**Comment by zepumph** [comment]
The context responses for this combo box were changed as part of  https://github.com/phetsims/ratio-and-proportion/issues/195#issuecomment-708095506 for the other screen.

**Comment by terracoda** [comment]
@Matthew-Moore240, I am thinking what @zepumph has implemented things in a way that gets us on the right track.

I think if we make the help text more explicit, and add "new" to the response, so it is clear that the challenge is new and thus different we may achieve much better scaffolding.

Personally, I would rather make the help text more lengthy and explicit than create a response with different regions that could potentially be confusing, so I suggest we re-examine Option 1 with some iterations. 

**Here's my updated plan for this interaction:**

1. Change heading text to: "Challenge Ratio"
    - Only one is selected at a time, so I think it is better if the heading is singular.
2. Make help text more explicit. There are [several iterations in the design doc](https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit#heading=h.3pwy6hgtb3s8). This one is shortest and thus my fav, but I think any would work, so choose a different one if you like:
    - Choose a challenge, then move hands to explore it.
3. Indicate the challenge is new - add the word "new" to the response. I had originally asked for the number to be in the response, but I like the sound of what @zepumph has implemented. Adding the word "new" might help emphasize a change was made, and also keep the response more general.

**Mini arrow-key walk-through:**
- Heading level 3, **Challenge Ratio**
- Challenge 1, pop-up button
- **Choose a challenge, then move hands to explore it**.
- (Left arrow to go back)
- Challenge 1, pop-up button
- (Space to open combobox)
- - Challenge 1, 1 of 3 text
- (Arrow down to read through items)
- Challenge 2, 2 of 3 text
- (Enter to select Challenge 2)
- Hands, somewhat close to **new** challenge ratio.

**Comment by terracoda** [comment]
Hopefully, the help text makes it clear to go move the hands to explore the new challenge.

**Comment by terracoda** [comment]
Assigning to @Matthew-Moore240, and @emily-phet and @zepumph are welcome to chime it.

I have a feeling these changes to the strings would be quite trivial to implement.

**Comment by Matthew-Moore240** [comment]
Yeah I think the shorter string for the help text is good, I am okay with taking this new approach.

**Comment by zepumph** [comment]
Implemented above. 

>Hands, somewhat close to new challenge ratio.

RE #199, should this be ratio challenge?

**Comment by terracoda** [comment]
@zepumph, the object and context responses are working nicely for the combobox. I'll close this issue and head over to #199 to note changes to the heading for the combobox.
