### ISSUE TITLE
Investigate aria-orientation="horizontal" for radio button group

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#201]
@Matthew-Moore240 mentioned that during an interview, a learner thought the radio buttons were vertical, and so preferred using up/down arrow keys to move them, we have not to my knowledge investigated using an aria orientation on our radio buttons, but I think we should!

**Comment by zepumph** [comment]
When I added this patch, it didn't seem any different to me on NVDA. Neither reported an orientation, and since the interaction works with any arrow key, it seems to be moot for that device.

I witnessed the same thing on the iPad with VO. There isn't any orientation provided through the radio button group. I'm still happy to add in this minor patch to see if things improve in the case that @Matthew-Moore240.

@Matthew-Moore240 can you please also state as many specifics as you can like device. screen reader. relevant settings, sim interaction, and expected vs provided behavior?

```diff
Index: js/common/view/RAPScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RAPScreenView.js	(revision 224ce65f2392e88da66654987a7c87ba0e4faa48)
+++ js/common/view/RAPScreenView.js	(date 1602025556319)
@@ -11,6 +11,7 @@
 import LinearFunction from '../../../../dot/js/LinearFunction.js';
 import ScreenView from '../../../../joist/js/ScreenView.js';
 import merge from '../../../../phet-core/js/merge.js';
+import Orientation from '../../../../phet-core/js/Orientation.js';
 import ResetAllButton from '../../../../scenery-phet/js/buttons/ResetAllButton.js';
 import ParallelDOM from '../../../../scenery/js/accessibility/pdom/ParallelDOM.js';
 import Node from '../../../../scenery/js/nodes/Node.js';
@@ -248,6 +249,8 @@
       helpTextBehavior: ParallelDOM.HELP_TEXT_BEFORE_CONTENT
     } );
 
+    this.tickMarkViewRadioButtonGroup.setAccessibleAttribute( 'aria-orientation', Orientation.HORIZONTAL.ariaOrientation );
+
     // add this Node to the layer that is scaled up to support vertical aspect ratios
     this.topScalingUILayerNode.addChild( this.tickMarkViewRadioButtonGroup );
     this.bottomScalingUILayerNode.addChild( this.resetAllButton );

```

**Comment by Matthew-Moore240** [comment]
@zepumph At this point I think we can just ignore this interaction, it doesnt seem to break anything. As opposed to everything else this is really low priority. Let me know what you think and if you agree we can close.
