### ISSUE TITLE
My Challenge Accordion Box needs Context Responses

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#211]
Related to https://github.com/phetsims/ratio-and-proportion/issues/195#issuecomment-710490937

Please create context responses for the accordion expand/collapse interaction.
- When box is actively expanded
    - “Current challenge ratio {{1}} to {{2}}.
- When the current challenge is actively collapsed
    - “Current challenge hidden.”

**Comment by terracoda** [comment]
@zepumph, you may have already done, this, I am just checking my issues now.

**Comment by terracoda** [comment]
These responses are not implemented yet, apologies for not assigning this issue to you on Friday. Over to you now :-)

**Comment by zepumph** [comment]
Implemented on master.

**Comment by terracoda** [comment]
@zepumph, I like the way the responses are working, but when the box is collapsed, I would like the response to be:
- “Current challenge hidden.”

Currently, the same response fire on expanding and on collpasing.

**Comment by zepumph** [comment]
I'm terribly sorry. Very sloppy on my end! Implemented now.

**Comment by terracoda** [comment]
No worries :-)
Thanks for fixing. It looks good now! Closing.
