### ISSUE TITLE
My Challenge accordion -Possible code change

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#213]
Related to https://github.com/phetsims/ratio-and-proportion/issues/195#issuecomment-710490937

There must be some “grouping” logic that is causing the “My Challenge Region” to be spoken when one first enters the My Challenge box. I am wondering if it’s critical, or maybe we can remove it?

Example comparison:
![Screen Shot 2020-10-16 at 12 23 54 PM](https://user-images.githubusercontent.com/1902116/96303780-91976180-0fd5-11eb-9f55-963305f183bc.png)
![Screen Shot 2020-10-16 at 2 23 09 PM](https://user-images.githubusercontent.com/1902116/96303798-9825d900-0fd5-11eb-8026-f8931a851d80.png)

@zepumph, can we do this issue last?
I'd like to have another listen after the other improvements.

**Comment by zepumph** [comment]
Yeah sure thing, but please assign me again when you are ready to see it in place.

**Comment by terracoda** [comment]
Just waiting on final changes to #195 and #211 before deciding on any further changes.

**Comment by terracoda** [comment]
I'm thinking
![Screen Shot 2020-10-21 at 1 08 45 PM](https://user-images.githubusercontent.com/1902116/96743523-a9d4fb00-139e-11eb-846b-c22c099c1020.png)

With the label changes and the re-arrangement of Currant ratio responses, I think the region information is fine now.

The region clearly communicates that the number spinners are part of the My Challenge box.

No changes needed to the code. Closing.
