### ISSUE TITLE
Making Hands 20-50% larger

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#217]
With the new colors for the hands, and the outline stroke, I think the appear smaller than when the hands were completely filled. 

Additionally, the see-through circle seems too small. 

In today's meeting, can we look at different increased sizes of the hand (the whole thing, inner circle and all) scaled larger?

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/96625452-b08a4200-12ba-11eb-806a-c2f7e8229683.png)


The old scale was 2, the new scale is 3 (50% bigger?). I also made the scale a query parameter (`?handNodeScale=6` is fun).

**Comment by zepumph** [comment]
We should make sure to adjust pointer areas after finding a scale we like. Right now there is weird overlap:

![image](https://user-images.githubusercontent.com/6856943/96631605-01059d80-12c3-11eb-9bb7-784fac703aed.png)

**Comment by BLFiedler** [comment]
Definitely a device specific/aspect ratio scaling thing. handNodeScale=6 on a phone in portrait is actually not that bad looking but is a bit more monstrous in widescreen where the vertical space is much more limited.

![Screenshot_20201021-091654](https://user-images.githubusercontent.com/47331395/96741286-dbd66500-137e-11eb-9f9e-60840f67fe37.png)
![Screenshot_20201021-091637](https://user-images.githubusercontent.com/47331395/96741296-de38bf00-137e-11eb-9753-a7c41ca0549b.png)

handNodeScale=3 is definitely an improvement over 2 for mobile and is nice for wide laptop displays to me. 

Would it be possible to detect if the display was taller than wide and maybe increment the handNodeScale variable by like 1 integer?

**Comment by zepumph** [comment]
>Would it be possible to detect if the display was taller than wide and maybe increment the handNodeScale variable by like 1 or 2 integers?

Yes that is possible, and that is similar to discussion about how to change the height of each ratio half. The thing is that integer changes feel wonky to me, and it would probably be best to have a sliding scale based on how tall the aspect ratio. 

Here is a patch that jumps from a scale of 3 to 4 when the aspect ratio becomes "vertical":

<details>


```diff

Index: js/common/view/RAPScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RAPScreenView.js	(revision ff2e88d15cc64d9e0711c6771996bd13ee48649b)
+++ js/common/view/RAPScreenView.js	(date 1603386503021)
@@ -266,10 +266,10 @@
     ];
 
     // @private - dynamic layout based on the current ScreenView coordinates
-    this.layoutRAPScreeView = newRatioHalfBounds => {
+    this.layoutRAPScreeView = ( newRatioHalfBounds, isVerticalAspectRatio ) => {
 
-      this.numeratorRatioHalf.layout( newRatioHalfBounds );
-      this.denominatorRatioHalf.layout( newRatioHalfBounds );
+      this.numeratorRatioHalf.layout( newRatioHalfBounds, isVerticalAspectRatio );
+      this.denominatorRatioHalf.layout( newRatioHalfBounds, isVerticalAspectRatio );
       backgroundNode.rectBounds = this.visibleBoundsProperty.value;
       backgroundNode.bottom = this.layoutBounds.bottom;
 
@@ -332,8 +332,10 @@
     // set visible bounds, which are different from layout bounds
     this.visibleBoundsProperty.set( new Bounds2( -dx, -dy, width / scale - dx, height / scale - dy ) );
 
+    const isVerticalAspectRatio = width <= height;
+
     // new bounds for each ratio half
-    this.layoutRAPScreeView( new Bounds2( 0, 0, ONE_QUARTER_LAYOUT_WIDTH, Math.min( height / scale, MAX_RATIO_HEIGHT ) ) );
+    this.layoutRAPScreeView( new Bounds2( 0, 0, ONE_QUARTER_LAYOUT_WIDTH, Math.min( height / scale, MAX_RATIO_HEIGHT ) ), isVerticalAspectRatio );
   }
 
   /**
Index: js/common/view/RatioHalf.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RatioHalf.js	(revision ff2e88d15cc64d9e0711c6771996bd13ee48649b)
+++ js/common/view/RatioHalf.js	(date 1603386599078)
@@ -288,10 +288,12 @@
     positionProperty.link( updatePointer );
 
     // @private
-    this.layoutRatioHalf = newBounds => {
+    this.layoutRatioHalf = (newBounds,isVerticalAspectRatio) => {
       this.rectWidth = newBounds.width;
       this.rectHeight = newBounds.height;
 
+      this.ratioHandNode.layout( isVerticalAspectRatio );
+
       const framingRectWidth = newBounds.width - newBounds.width * .1;
       topRect.rectWidth = framingRectWidth;
       topRect.centerX = bottomRect.centerX = newBounds.centerX;
@@ -340,8 +342,8 @@
    * @public
    * @param {Bounds2} bounds - the bounds of this RatioHalf, effects dimensions, dragBounds, and width of guiding rectangles
    */
-  layout( bounds ) {
-    this.layoutRatioHalf( bounds );
+  layout( bounds, isVerticalAspectRatio ) {
+    this.layoutRatioHalf( bounds, isVerticalAspectRatio );
   }
 
   /**
Index: js/common/view/RatioHandNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RatioHandNode.js	(revision ff2e88d15cc64d9e0711c6771996bd13ee48649b)
+++ js/common/view/RatioHandNode.js	(date 1603386640256)
@@ -7,6 +7,7 @@
  */
 
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
+import NumberProperty from '../../../../axon/js/NumberProperty.js';
 import Property from '../../../../axon/js/Property.js';
 import Range from '../../../../dot/js/Range.js';
 import merge from '../../../../phet-core/js/merge.js';
@@ -19,9 +20,6 @@
 import RAPQueryParameters from '../RAPQueryParameters.js';
 import TickMarkView from './TickMarkView.js';
 
-// constants
-const HAND_PATH_SCALE = RAPQueryParameters.handNodeScale;
-
 class RatioHandNode extends Node {
 
   /**
@@ -47,6 +45,9 @@
     }, options );
     super();
 
+    // @public - the scale size of the hand, applies to filled in and cut out hand
+    this.handScaleProperty = new NumberProperty( RAPQueryParameters.handNodeScale );
+
     // Always the same range, always enabled
     !options.asIcon && this.initializeAccessibleSlider( valueProperty, enabledRatioComponentsRangeProperty, new BooleanProperty( true ), options );
 
@@ -59,6 +60,11 @@
       fill: colorProperty
     } );
 
+    this.handScaleProperty.link( scale => {
+      filledInHandNode.setScaleMagnitude( scale );
+      cutOutHandNode.setScaleMagnitude( scale );
+    } );
+
     const container = new Node( {
       children: [ filledInHandNode, cutOutHandNode ],
       excludeInvisibleChildrenFromBounds: true
@@ -83,6 +89,14 @@
 
     // touchArea dilation
     this.touchArea = this.localBounds.dilatedXY( this.width * 2, this.height * 2 );
+
+  }
+
+  /**
+   * @public
+   */
+  layout( isVerticalAspectRatio ) {
+    this.handScaleProperty.value = isVerticalAspectRatio ? 4 : RAPQueryParameters.handNodeScale;
   }
 
   /**
@@ -125,8 +139,7 @@
 
     options = merge( {
       stroke: 'black',
-      lineWidth: 2,
-      scale: HAND_PATH_SCALE
+      lineWidth: 2
     }, options );
 
     const shape = `M27.654,1.738c-0.716-0.716-1.572-1.075-2.57-1.075c-1,0-1.856,0.359-2.572,1.075c-0.717,0.717-1.074,1.573-1.074,2.571
@@ -152,8 +165,7 @@
 
     options = merge( {
       stroke: 'black',
-      lineWidth: 2,
-      scale: HAND_PATH_SCALE
+      lineWidth: 2
     }, options );
 
     const shape = `M44.323,14.238c-0.717-0.717-1.574-1.073-2.572-1.073s-1.855,0.357-2.571,1.073c-0.717,0.716-1.075,1.574-1.075,2.572v8.854

```

</details>

I think it will look best if we instead create a sliding scale between to scales. I know it is device specific, but do you think you could work within constraints and give be an ideal scale for the min height (normal/wide/horizontal aspect ratio), and then another one for the max height (the most vertical/narrow aspect ratio). Then I can likely interpolate between those two in a meaningful way. This is the same scaling strategy done for the components on the right to support mobile/vertical stuff over in #79 

Perhaps a min of 3, and a max of 6. This isn't perfect, as you can see from this screenshot where the thin window has a scale of 6, and the normal one has a scale of 3. Notice that the percent of a tick mark that each take up is different. Though I'm not sure that that is the only/best metric of comparison.

![image](https://user-images.githubusercontent.com/6856943/96907527-cb3df180-1447-11eb-9fe8-7d1d9c8f40bb.png)


Over to the designers to let me know what they would like best.

**Comment by emily-phet** [comment]
@BLFiedler 
Can you take the lead on the design side for this? I'm out of time for today, but ideally there would be decisions ready for @zepumph for Monday. 

I like the idea of having the size scale based on view window height. @BLFiedler can you confirm if a range of 3-6 makes sense to you?

@zepumph - do you need any input regarding logic for the scaling? E.g., would there be no size change on laptops for "typical" screen ratios, or would it actually scale to potentially higher than a size value of 3 within the height range of some laptop devices?

**Comment by emily-phet** [comment]
@zepumph Can we also see some screenshots with the window circle at 50% larger, and 100% larger?

**Comment by BLFiedler** [comment]
Hm. I'm not immediately concerned by the difference in size that the hand takes up of the space between the tick marks as the spacing on the tick marks also changes.

However, if there is a simple solution to have the hands match the scaling the tick mark spacing, then perhaps that would work.

Otherwise, I like 3-6 for reasonable aspect ratio (phones being the "tallest" devices that are typically in use, rather than the maximum you can shrink a window). Perhaps we floor the scale at 3 for anything "landscape" ratio and enact the sliding scale from 3-6 when we have a "portrait" or tall window?

I think related to Emily's thoughts on laptop default scaling, there seems to be something happening where if you resize the window vertically the tick mark spacing changes, but the hands do not, but in a landscape orientation, any window size changes change everything proportionally. I think for any landscape aspect ratios, it should be fine to keep it at 3.

example:

![image](https://user-images.githubusercontent.com/47331395/97055368-e7bf5400-1543-11eb-80bc-7562ef211c20.png)

**Comment by zepumph** [comment]
Sounds good. I'll work towards scaling like this.

**Comment by zepumph** [comment]
In the work done for this issue, I worked to consolidate all of the scaling being done for the hands into a single place. Up until this point there was scalling on the hand images, the `RatioHandNode` type that swaps between the two, and also in `RatioHalf` because this issue requires scaling to be done to the cue arrows in addition to the hand Nodes. 

As part of this work, I removed the scaling on the RatioHandNode and the individual hand images, and put everything into RatioHalf, which creates the RatioHandNode and its associated cue arrows. Then in layoutRatioHalf (which already exists), I was easily able to apply the scale in a single place.

This required dealing with less than ideal numbers, since the "3-6" range was being done inside of a scale that was already being applied at `.4`. Thus the new scale range goes from 1.2-2.5. This also required altering the arrow sizes so that the same scale could apply to the hand as the cue arrows. @emily-phet please review.

**Comment by emily-phet** [comment]
This looks fine to me. I have a few questions about behavior at very small screen sizes, but I'll ask in today's meeting.

**Comment by zepumph** [comment]
@emily-phet, is there anything else here or are we ready to close? There wasn't any feedback that came from the design meeting today.

**Comment by emily-phet** [comment]
This seems good to go! Closing.
