### ISSUE TITLE
Adding context responses to the range combobox

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/ratio-and-proportion#219]
Range COMBOBOX
Accessible Name: Range {{0 to 10}}
ARIA: aria-labelledby needed to provide the selected challenge name dynamically
PhET Type: Combobox (button and popped up listbox) 
Button Label:  selected item is part of the button’s label
Listbox list items:

- Range {{Tick Marks Hidden}}
- Range {{0 to 10}}
- Range {{0 to 20}}
- Range {{0 to 30}}

Help text: When tick marks shown, choose range for tick marks.

**New context responses for the range** 
   
- Tick mark range now 0 to 10.
- Tick mark range now 0 to 20.
- Tick mark range now 0 to 30.

**Comment by zepumph** [comment]
Context alerts changed above. The only difference between the sim and the above design from what I can see is that in the sim the "hidden" is lowercase, i.e. "Range {{Tick Marks hidden}}". This is the same value as when the tick marks are shown/numbered/hidden. Want it capitalized?

**Comment by Matthew-Moore240** [comment]
No I think its good lower case. Looks great overall, closing.
