### ISSUE TITLE
Artwork needed - Hands and gifts

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#22]
@amanda-phet @arouinfar 
We need some simple (I think) artwork for this sim. Would either of you have some time to create these this week? My hope is that it's pretty quick.

1. (Most important) A left and right hand, iconic, in the "stop" position. Something similar to [this](https://images.app.goo.gl/LyWPpTQQcgEEUrPJA). We're considering using these as the default objects for the freely moving objects. 
2. A set of five numbered presents (decorated gift boxes with a bow). Rather than the style found in Balancing Act, I like the variance in perspective and style of the gift boxes found in [this example](https://images.app.goo.gl/653jSaYwEuTr5yxf9). It would be really nice if the set of five varied more in style than BA, like 1) the lower right, 2) the middle left, and 3) maybe even  having one similar to the round gift in the middle bottom of the example. If we had one to use has a placeholder for now, and others came in later, that would be very helpful.

**Comment by arouinfar** [comment]
@emily-phet font-awesome has a hand icon (U+f256) that the developer can add to the sim without needing artwork assets.
<img src="https://user-images.githubusercontent.com/8419308/79772990-0cfdac00-82ee-11ea-82a2-d640d5ebe5df.png" width=200>

Your example had a filled hand, so I modified the font-awesome icon and have included the asset files here: [hand.zip](https://github.com/phetsims/proportion/files/4504704/hand.zip)

<img src="https://user-images.githubusercontent.com/8419308/79773037-1f77e580-82ee-11ea-9050-ee363a3106a9.png" width=200>

I don't really have the bandwidth to work on the gift artwork this week, but another alternative may be @DianaTavares.

**Comment by emily-phet** [comment]
@arouinfar Thanks very much! This is great.

Regarding the gifts artwork - @zepumph do you know how/where to find the artwork for one of the gift boxes in Balancing Act? If so, we could use that as a placeholder for now.

**Comment by amanda-phet** [comment]
Getting those cute little gift boxes is a great task for Cheryl! She would be great at that sort of thing. Let me know if you want me to create an artwork task for her.

**Comment by zepumph** [comment]
>Regarding the gifts artwork - @zepumph do you know how/where to find the artwork for one of the gift boxes in Balancing Act? If so, we could use that as a placeholder for now.

Yes, they have `ai` files titled "mystery-object-. . ." in https://github.com/phetsims/balancing-act/tree/master/assets. Is that helpful? We can reuse those exact ones if you would prefer. I'll let you take it from here.

**Comment by emily-phet** [comment]
@amanda-phet Yes please, if you could create a task for the gift boxes, that would be awesome. 

@zepumph can you add the filled hand as the default for the cursors, leaving circles and crosses as options as well?

**Comment by zepumph** [comment]
Here is a first pass at adding the filled in hand. Just like the circle, there isnt' a great notion of where the actual value is. I thought about adding a small circle point on top of the hand, but decided to discuss it first. I'll leave it up to designers to decide how to proceed. 

![image](https://user-images.githubusercontent.com/6856943/79896130-69c39a00-83b4-11ea-9c17-deb2e1b473f5.png)

**Comment by zepumph** [comment]
In a meeting today it was mentioned that the left hand should be flipped to look like a left hand. I'll do that now.

**Comment by zepumph** [comment]
Implemented above.

**Comment by emily-phet** [comment]
@zepumph This looks great!
