### ISSUE TITLE
Fine tune the size of the cut out circle of the hands

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#223]
@emily-phet and I think the cut out hand holes need to be bigger.

**Comment by zepumph** [comment]
Here is what the cut out currently looks like

![image](https://user-images.githubusercontent.com/6856943/97371180-8b22a880-1865-11eb-91a2-0ac1b33a01f0.png)

**Comment by emily-phet** [comment]
@amanda-phet Apologies for asking for yet another thing related to this, but I'd like to see the new hands (new colors, and size) with the circle cutout 50% and 100% larger. Right now, with the colored hands and the black outline stroke, the inner part of the hands look way smaller. 

@zepumph said that he'd need new svg files to make this happen in the sim. Could you make some new svg files with the circle cutout 50% and 100% larger (and/or any size value that seems good to you as you're making these)?

**Comment by emily-phet** [comment]
@amanda-phet Will you be able to take a look at this sometime this week? If not, is it possible to hand off the artwork files to someone else. 

Again, apologies - I hope this is like a five-minute thing for you.

**Comment by amanda-phet** [comment]
No worries, this is quite fast. I'll have something today.

**Comment by amanda-phet** [comment]
I'm not sure how the stroke was done- I'm guessing in code? I included an option with a thinner stroke as well, and guessed that the current one is 2px. 

Here are some options:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/7852916/98026843-fff76480-1dc8-11eb-912a-cf27ff7597bb.png">

**Comment by emily-phet** [comment]
Thanks @amanda-phet!

I like the biggest circle. At that size, it also looks more like a ball or a cutout (like a "window") and less like a crucified hand (which of course, we were trying really hard to avoid). 

@zepumph can you add in the 2px stroke and 20px circle option (the last one)? I think even if it looks slightly odd, it will increase the ability to use the cutout as a way to line up the hand, which is the whole point.

**Comment by amanda-phet** [comment]
Here you go! 


[cutout-hand-05.svg.zip](https://github.com/phetsims/ratio-and-proportion/files/5483843/cutout-hand-05.svg.zip)

**Comment by zepumph** [comment]
When I open this SVG, there are now three `path` elements:

```html
	<path d="M37.062,19.426V8.477c0-0.998-0.356-1.856-1.073-2.573c-0.717-0.715-1.574-1.073-2.572-1.073s-1.854,0.358-2.571,1.073
		c-0.716,0.717-1.074,1.574-1.074,2.573v7.213C32.721,15.841,35.331,17.261,37.062,19.426z"/>
	<path d="M44.323,14.238c-0.717-0.717-1.574-1.073-2.572-1.073s-1.855,0.357-2.571,1.073c-0.717,0.716-1.075,1.574-1.075,2.572
		v4.207c0.73,1.389,1.149,2.968,1.149,4.646c0,5.523-4.477,10-10,10c-5.523,0-10-4.477-10-10c0-1.674,0.417-3.25,1.144-4.636V8.477
		c0-0.998-0.359-1.856-1.075-2.573c-0.717-0.715-1.573-1.073-2.571-1.073c-0.999,0-1.855,0.358-2.572,1.073
		c-0.715,0.717-1.073,1.574-1.073,2.573v17.188v8.334l-5.013-6.674c-0.825-1.106-1.934-1.66-3.321-1.66
		c-1.15,0-2.132,0.406-2.945,1.221c-0.814,0.813-1.222,1.796-1.222,2.945c0,0.934,0.282,1.769,0.847,2.507l12.5,16.667
		c0.825,1.107,2.96,3.442,6.249,4.425c7.18,2.147,11.243,1.665,15.685,0.211c3.871-1.267,4.833-2.463,6.875-5.514
		c1.932-2.887,2.112-9.526,2.475-13.186c0.069-0.698,0.162-1.334,0.162-1.92v-16.21C45.396,15.812,45.038,14.954,44.323,14.238z"/>
	<path d="M28.73,15.689V4.31c0-0.998-0.358-1.854-1.075-2.571c-0.716-0.716-1.572-1.075-2.57-1.075c-1,0-1.856,0.359-2.572,1.075
		c-0.717,0.717-1.074,1.573-1.074,2.571v15.124C23.168,17.266,25.779,15.842,28.73,15.689z"/>
```

Whereas before there was just a single one. I think it would be simplest if we let scenery do the line width to avoid this complexity. 

Furthermore, if we wanted to capture lineWidth in the SVG, then we would want to be consistent about that between the filled in and cut out hands.

Thus I think it would be easiest to get cut out 5 (with the 20px cut out) but without a stroke. Thanks!

**Comment by amanda-phet** [comment]
At first I thought I accidentally exported the wrong piece of artwork, but I think those three paths are actually the hand plus the two (now separated) fingers. I didn't even notice that they were no longer connected! 

<img width="243" alt="image" src="https://user-images.githubusercontent.com/7852916/98062297-fbec3680-1e0a-11eb-973f-15a5e18df132.png">

I can put a superficial ring around the circle to connect all of the fingers to the hand, which looks like this:
<img width="325" alt="image" src="https://user-images.githubusercontent.com/7852916/98062515-71580700-1e0b-11eb-8d2f-7db67b5e0096.png">

Let me know if this works! 

[cutout-hand-06.svg.zip](https://github.com/phetsims/ratio-and-proportion/files/5485169/cutout-hand-06.svg.zip)

**Comment by zepumph** [comment]
Ah! Your are brilliant! This larger circle was easlily swapped in because of your clever work around. Thank you. @emily-phet what are you thinking about the 20px option currently in the sim?

![image](https://user-images.githubusercontent.com/6856943/98612538-d2b32680-22a0-11eb-8139-a4500d6a5767.png)

**Comment by emily-phet** [comment]
I like it! Let's show everyone at the meeting today.

**Comment by zepumph** [comment]
We met about the above change, and like it as a group. Closing
