### ISSUE TITLE
Keep Both hands interaction "j" to jump to lowest common value?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#224]
In https://github.com/phetsims/ratio-and-proportion/issues/62 we added that "J" can be used to jump the higher hand to match the lower position. It isn't documented in the keyboard help dialog, and I forgot about it. I think we should either get rid of it, or add it to the dialog. @emily-phet what do you think?

**Comment by emily-phet** [comment]
Agreed - I think we can get rid of it. I think the number keys are more intuitive to use, and too many options for moving the hands may just be confusing.
