### ISSUE TITLE
Number Key shortcut and Lock Ratio

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#225]
With lock ratio checked, I accidentally hit the 5 shortcut and both hands jumped to 5, even though ratio was locked.

Not sure what we want to do with these shortcuts when Lock Ratio is checked.

I am open to suggestions.

**Comment by zepumph** [comment]
My guess is that the number keys should either be disabled when the ratio is locked (preferred), or perhaps make it match the left hand. If we go with matching the left hand, it will be possible to lock a ratio where it isn't possible to get to all the tick marks with the left hand.

**Comment by terracoda** [comment]
@zepumph, I have some context responses coming up in a new issue for the lock ratio button.

**Comment by terracoda** [comment]
@zepumph, I just posted Lock Ratio Context Responses in #227.

If we don't disable the number key shortcuts, we can use a response to communicate what happened to the Lock situation. We have to do this for the My Challenge number spinners, so we can just do something similar with the number key short cuts.

**Comment by zepumph** [comment]
Here we decided that we do want to support number keys "pulling" the ratio out of "locked" status. This is just like the behavior of when you are locked, and you change the challenge ratio.

Thus, we should here add detection to the case where we change the challenge ratio or move the hands out of the locked status, and disabled and uncheck the "lock ratio" checkbox.

**Comment by zepumph** [comment]
These bug fixes have been solved, and context responses in these cases will come over in https://github.com/phetsims/ratio-and-proportion/issues/227

**Comment by terracoda** [comment]
Thanks @zepumph, this is verified. Closing and heading over to #227.
