### ISSUE TITLE
Hand position regions are not symmetrical

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#226]
The regions outlined here are not symmetric about the "even with" region. It is possible to .5 above even with and be "Extremely close to" but, .5 below and be "very close to"

https://github.com/phetsims/ratio-and-proportion/blob/bfc2d0af2ac723bb9f7053b9e0e721ec4bd8fbb0/js/common/view/describers/HandPositionsDescriber.js#L260-L295

**Comment by terracoda** [comment]
@zepumph, would a region called, "almost even" help solve this issue?

**Comment by zepumph** [comment]
I don't think so. This is just a minor bug with rounding.

**Comment by terracoda** [comment]
Ok, got it. A new region might help with reducing repetition which is a different issue :-)

**Comment by zepumph** [comment]
This will be covered by #241.
