### ISSUE TITLE
Slight tweaks to help text for sliders and both hands

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#235]
In light of changes to the screen summary in https://github.com/phetsims/ratio-and-proportion/issues/231#issuecomment-724974512, I think the help text for the interactions can be tweaked a little.

**Screen Summary interaction hint** (from https://github.com/phetsims/ratio-and-proportion/issues/231#issuecomment-724974512):
- Move hands to find the Challenge Ratio in different places.

## Current Help Text for Interactions
**Left and Right Hand Sliders:**
- Move hands up and down to find the challenge ratio in different locations.

**Both Hands Interaction:**
- Use W and S keys to move left hand, and Up and Down Arrow keys to move right hand. Move both hands at the same time to maintain the challenge ratio.

## New Help Text for Interactions
**Left and Right Hand Sliders:**
- Move hands up and down **individually** to find the **C**hallenge **R**atio in different **places**.

**Both Hands Interaction:**
- Use W and S keys to move left hand, and Up and Down Arrow keys to move right hand. Move both hands at the same time to **find and** maintain the **C**hallenge **R**atio.

**Comment by Matthew-Moore240** [comment]
Yeah @terracoda  those look really good to me!

**Comment by terracoda** [comment]
Over to you @zepumph .

**Comment by zepumph** [comment]
Alright!
