### ISSUE TITLE
Increasing height of boundary rectangles so parts of hand never go "off screen"

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#239]
Now that the hand sizes have been increased significantly, it feels a little clunky that at the top and bottom of the screen, part of the hands can go (visually) off-screen. 

I'm not sure if it is a big challenge to do this, but could we increase the size of the grey rectangles such that the hands don't go off-screen? (Squishing a bit the range for the hands to move)

If it's a major challenge to do this, then we shouldn't do it at this stage of the process.

**Comment by zepumph** [comment]
In meeting today, we liked the value of `32` for laptop screens, and about `64` for phones. If it is easy to do the dynamic layout to make this happen, we should do that, but otherwise we are fine hard coding for just laptops like:

```diff
Index: js/common/view/RatioHalf.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RatioHalf.js	(revision 584b3fcc9520296a2e4548421ecb7ccdb78d4f2d)
+++ js/common/view/RatioHalf.js	(date 1605636968700)
@@ -28,7 +28,7 @@
 import TickMarkView from './TickMarkView.js';
 
 // constants
-const FRAMING_RECTANGLE_HEIGHT = 16;
+const FRAMING_RECTANGLE_HEIGHT = 32;
 
 // This value was calculated based on the design of snapping within the range of the ratio hand center circle, see https://github.com/phetsims/ratio-and-proportion/issues/122#issuecomment-672281015
 const SNAP_TO_TICK_MARK_THRESHOLD = .135842179584 / 2;

```

**Comment by zepumph** [comment]
I was able to implement the sliding scale, so the min was 32 (2x what it was), and the max is 64. Let me know what you think1

**Comment by emily-phet** [comment]
I think this looks amazing! Very sharp. I think it really helps make the sim look "finished" visually, at all the different aspect ratios.
