### ISSUE TITLE
New Play Regions to align position descriptions for Sliders and Both Hands 

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#241]
I have changed the parameters for describing qualitative hand position, so the descriptions can be aligned across both slider interactions and the Both Hands interaction.

Here's the parameters that should work in both the sliders' aria-value-text and in the Both Hands. These parameters are also used in the screen summary. 

Regions for hand position | Proposed Ranges
-- | --
{{at top}} | 10
{{near top}} | 9.00 -9.99
{{in upper region}} | 6.51 - 8.99
{{in upper-middle region}} | 5.01 - 6.50
{{at middle}} | = 5.0
{{in lower-middle region}} | 3.51 - 4.99
{{in lower region}} | 1.01 - 3.50
{{near bottom}} | 0.01 - 1.00
{{at bottom}} | 0

**For the Sliders**
In the aria-valuetext, you need to add "of Play Area" to the edges:
- "at bottom of Play Area"
- "at top of Play Area"
I think it is safe to leave off "of Play Area" for all other slider values.

**For Both Hands**
I don't think we use "of Play Area" in the descriptions in the Both Hands interaction.

**For Screen Summary**
In the screen summary, things should remain the same with "of Play Area" at the end of the each of the 2 bullets that describe the position of the hands.

**Comment by terracoda** [comment]
If more detail is needed, please see the section [Responsive Descriptions for Hand Interactions](https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit#heading=h.ym5u0y2c0uow)

**Comment by zepumph** [comment]
Implemented, I commented in the design doc about a question of symmetry. See https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit?disco=AAAAK0yOKPk

Please review.

**Comment by terracoda** [comment]
The adjusted region ranges that @zepumph suggested results in a symmetric number of key presses in regions above and below "at middle". This is what I was hoping for, so thanks for catching that @zepumph.

Regions for hand position | Proposed Ranges | Default Key Presses
-- | -- | --
{{at top}} | 10 | 1
{{near top}} | 9.00 -9.99 | 2
{{in upper region}} | 6.51 - 8.99 | 4
{{in upper-middle region}} | 5.01 - 6.50 | 3
{{at middle}} | = 5.0 | 1
{{in lower-middle region}} | 3.50 - 4.99 | 3
{{in lower region}} | 1.01 - 3.49 | 4
{{near bottom}} | 0.01 - 1.00 | 2
{{at bottom}} | 0 | 1

These ranges sound good to me.
We can discuss if it useful to adjust the ranges further so there are 3 steps in each region, in between the single-value regions (landmarks top, middle, bottom). I'll mark this issue for today's meeting.

**Comment by terracoda** [comment]
For non-visual access 3 steps without a change in region is often a good range. It seems that might be easily achievable here.

**Comment by terracoda** [comment]
We will leave it as is.
