### ISSUE TITLE
Add "almost even" to distance scale describing distance between the hands

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#242]
As discussed in design meeting today, I have added a new region to the distance scale.

**Table: Distance Scale - Actual number of key presses per region describing distance between hands** 
Distance Region Name | farthest from | extremely far from | very far from | far from | not so close to | somewhat close to | very close to | extremely close to | almost even with | even with
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Both Hands | 1 | 3 | 3 | 3 | 3 | 2 | 2 | 2 | 1 | 1
RH Slider | 1 | 3 (1 closer, 2 regular regions) | 3 | 3 | 3 | 2 | 2 | 2 | 1 | 1
Range in steps when range is 0-10. Not sure about 0-20 and 0-30 | Single-value region when 10 tick marks apart | steps 9.5, 9.0, 8.5 | steps 8.0, 7.5, 7.0 | steps 6.5, 6.0, 5.5 | steps 5.0, 4.5, 4.0 | steps 3.5, 3.0 | steps 2.5, 2.0 | steps 1.5, 1.0 | step 0.5, 0 | Single-value-region when zero tick marks apart
rough distance range |   | 8.5 to 9.9 tick marks apart | 7.0 to 8.49 tick marks apart | 5.5 to 6.9 tick marks apart | 4.0 tick marks to - 5.49 tick marks part | 3.0 tick marks to  - 3.99 marks apart | 2.0 tick marks to  2.99 tick marks apart | 0.51 tick mark to - 1.99 tick marks apart | 0.1 tick marks to  - 0.50 tick marks apart |  

The new region is the "almost even" region, and then I adjusted the size of the other regions.

**Comment by terracoda** [comment]
@zepumph the table looks better in the design doc.

**Comment by zepumph** [comment]
Implemented above. Please review.

**Comment by terracoda** [comment]
Almost even is sounding good.
Thanks @zepumph.
