### ISSUE TITLE
Volume of edge sounds - can we increase the volume?

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#246]
In a recent interview (November 13), a screen reader user had trouble hearing the edge sounds when moving hands up and down in the Play Area.

I'm wonder if we can increase the volume of the edge sounds?

It might be good to make sure the edge sounds for the number spinners and the edge sounds for the hand sliders and the Both Hands are all at similar levels.

**Comment by jbphet** [comment]
I'm going to turn this over to @zepumph.  I'm in more of consulting role on this sim, whereas @zepumph is doing the bulk of the actual implementation.

**Comment by zepumph** [comment]
Seems reasonable to me! I'll confirm during meeting tomorrow.

**Comment by zepumph** [comment]
From meeting today, @terracoda will describe what type of sound issue there is (balancing vs. general level).

**Comment by terracoda** [comment]
The tick mark sounds and the edge sounds are really low in volume. I f a screen reader is speaking at the same time, they are not audible.

I can hear them when the sim is not talking.

I get why the tick mark sounds are subtle, but it seems like we are not using volume as a parameter in wood block sound that indicates nearing proportion. It seems we are using pitch and tempo there.

I am wondering if we could up the tick mark volume to be much closer to the volume of that sound (the nearing proportion sound).

If volume is being used (I don't think it is), we could make the tick mark sound slightly less that than the onset of nearing proportion (nearing the challenge ratio).

As for the actual edge sound - hitting zero or 10, think this sound could be louder. The edge sounds in GFLB seems to be much louder to me. I know in that sim the force sound plays at the same time so that might be the reason it is louder, but not sure.

I think the max and min in RaP are important boundaries, so I think the sound can be made louder, closer to the volume of the edge sounds in GFLB or the radiobutton sounds in RaP. 

I think in GFLB we upped the volume of the edge sounds when we were refining the sounds, so it's not surprising that we would do the same thing for RaP's edge sound.

**Comment by terracoda** [comment]
@Ashton-Morris, do my recommendations in https://github.com/phetsims/ratio-and-proportion/issues/246#issuecomment-734346645 seem reasonable?

And if so, can the volume be directly handled in the code?

**Comment by zepumph** [comment]
This has sat for a while, @emily-phet can you let me know what you would like to do here?

**Comment by BLFiedler** [comment]
I agree that the edge sounds could be louder with no harm. As a baseline, we can bring them in line with the relative loudness in GFLB.

@terracoda , do you have a sense for how loud the tick marks would have to be relative to how they are now? Since it is in enhanced sounds now and you must explicitly turn them on, which means you want them on, we can likely turn them up without worrying too much that it will affect the majority of users.

**Comment by zepumph** [comment]
@terracoda @BLFiedler and I increased the volume for the boundary and tick mark bumps. We like the volume increase, and consider ourselves a quorum. Closing.
