### ISSUE TITLE
How to support selection of new ratios?

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#25]
Current design has radio buttons for different Mystery ratios. I'm concerned this may be too inviting, and encourage learners to explore these options too early in interaction.

Idea 1 - **dropdown menu of ratio options** and also calling them "Challenges" to help cue that some may be more difficult than others, and implicitly indicate the default ratio may be the best one to stick with at first. 

Idea 2 - Carousel - though we've not done this with other a11y-fied sims, so potential benefits may not be worth the necessary resources atm to investigate/determine how to make an accessible carousel

**Comment by zepumph** [comment]
I added a combo box above. With a colored rectangle next to the text. For now @emily-phet and I discussed that as a placeholder, maybe in the future we will have gift boxes in there. Please review.

**Comment by emily-phet** [comment]
@zepumph Looks great. 

One small thing - Please shift the radio buttons and accordion box lower on the screen. Position them so that when the accordion box opens with a max of 4 challenges, the open accordion box sits just above the reset all button.

**Comment by zepumph** [comment]
Done!
