### ISSUE TITLE
Sim page accessories 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#259]
When sim is ready for publication - we'll need to input the following into the admin page:
Accessories (keywords, categories, description, learning goals, related sims, NSDL)

**Comment by zepumph** [comment]
Likely this is ready to be assigned.

**Comment by emily-phet** [comment]
@BLFiedler Can you speak with @arouinfar about how to do this?

**Comment by arouinfar** [comment]
The process is pretty straightforward, but is probably easiest to demonstrate over a zoom call. I'm happy to chat anytime @BLFiedler. We can also go over other pieces of the master checklist (#1) if there's anything else you'd like to consult on.

**Comment by terracoda** [comment]
Reminder @emily-phet and I created a description in #260 for the A11y Sims page, in case it is helpful.

**Comment by BLFiedler** [comment]
Yeah, so I was given admin access to the sim pages on phet.colorado.edu awhile ago for uploading the Sound Features videos. I believe all of these are on those pages and fairly straight forward. I'll ping AR though if I run into any issues while trying to implement.

**Comment by terracoda** [comment]
@BLFiedler, yes, I can also help with web admin, if needed. I mainly only add content for the A11y Pages, but it is the same principle.
