### ISSUE TITLE
Updates to mechamarkers implementation

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#26]
From a meeting today with @BLFiedler,  @Petroochio and @clementzheng, there are some tweaks we want to do to solve problems.

**Problem one:** @emily-phet and @BLFiedler have both tried to set up their mechamarkers with their laptop facing the person, and angled down onto a table top. In this set up, the camera is up-side-down to how it was originally intended to be implemented. Thus the y distance that is being calculated is negative. 
**Solution:** In https://github.com/phetsims/ratio-and-proportion/commit/6c9b0ae47b32bc05919eb37136c83d074abd22d7 we made the distances absolute values, so the base can be at the top or the bottom of the camera view port. This change makes it even more important that the base is at an edge, because if a marker moves "past and beyond" the base, you get weird results. Hopefully no one is doing that anyways.

**Problem two:** A need for control of what the full range is. Currently it is a hard coded number of pixels in the marker controller.
**Solution:** I will make this a query parameter so that everyone can adjust as desired. Another option that we decided against was to add a 4th marker to mark the top of the ratio range. This felt like more overhead than was needed. Though we can come back to it if desired.

**Problem three:** The ability for  @Petroochio and @clementzheng to prototype controllers and easily embed them into the sim. There were lots of ideas put out here, including systemic changes to the mechamarkers library to support an observable pattern. For now though, it seems easiest for them to prototype in their own system (like glitch), and then just send me a chunk of code to add into the sim. I'm going to do that for @clementzheng right now with https://glitch.com/edit/#!/two-track-proportion?path=script.js:28:42

I'm sure more will come up, but this meeting was very helpful!

**Comment by zepumph** [comment]
Ok all three have been accomplished above. 

@clementzheng, you can use your prototype with a query parameter like so https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.13/phet/ratio-and-proportion_en_phet.html?useClementPrototype1. Please take a look at https://github.com/phetsims/ratio-and-proportion/blob/master/js/common/RatioAndProportionQueryParameters.js to see how you can alter the parameters to your prototype with query parameters as well. 


@BLFiedler @emily-phet there is now support for "upside down" configuration like you were demonstrating at the last meeting. Also please adjust the `?heightInPixels` parameter to change the physical range of the markers. The default is 600, see how it changes with http://localhost:9000/dist/ratio-and-proportion_phet.html?brand=phet&ea&heightInPixels=1000.

@BLFiedler anything else here? feel free to close.

**Comment by BLFiedler** [comment]
Oops - sorry! I think the mechamarker implementation as far as this issue goes are taken care of! New issues for further mechamarkers stuff can be generated after further testing!
