### ISSUE TITLE
Flipped design for slider interactions

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#261]
Related to issue https://github.com/phetsims/ratio-and-proportion/issues/245# we will be flipping the design of the sim so that proximity-to-ratio is the object response for all interactions.

An example of what this flip will look like for sliders is found in this table in the design doc:
https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit?ts=5fc56c26#heading=h.hq2zvuiwvq6f

These examples use the newly implemented regions for distance and position and adjusted `aria-valuetext` for the sliders' object responses.

**Comment by terracoda** [comment]
@zepumph, I mapped an example for tick marks and started numbered tick marks (not finished).
The new logic does work as great with the tick marks, unfortunately.

**Comment by terracoda** [comment]
@zepumph, apologies I forgot to assign you to the issue.

**Comment by terracoda** [comment]
This issue is also related to #262.

**Comment by zepumph** [comment]
I think this is implemented, it was a bit hard to know for sure, because #262 isn't in place yet. Please review.

**Comment by terracoda** [comment]
I'll review when #262  is complete.

**Comment by terracoda** [comment]
#262 is ready, so testing.

**Comment by terracoda** [comment]
Reviewing now :-)

**Comment by terracoda** [comment]
- With No Tick Marks, distance progress responses working as requested.
- With Tick Marks (plain), distance progress responses also working as requested.
- With Numbered Tick Marks, distance progress responses also working as requested.

The flip has been implemented as I wanted. I am adding a note here that when using the slider interactions (individual left or right hand), I feel like I need position as part of the object response.

This is not the case with the Both Hands interaction where I receive comprehensive position information for each hand while interacting.

This is an interesting design issue. I will open a new issue for future investigation. It likely won't happen for the publication for this version.

**Comment by terracoda** [comment]
I opened #280 to explore the previous comment.
