### ISSUE TITLE
use globalKeyStateTracker

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#264]
Now that there is globalKeyStateTracker from https://github.com/phetsims/scenery/issues/1048, likely BothHandsInteractionListener doesn't need to make its own. I'll take a look.

**Comment by zepumph** [comment]
@jessegreenberg please review. Does this seem like the way forward for keyStateTracker?

**Comment by zepumph** [comment]
I don't think this will take long, but it may be the first sim that would use `globalKeyStateTracker`. So I'm going to have this block publication of RaP.

**Comment by jessegreenberg** [comment]
I think this looks good and is what I expect from globalKeyStateTracker. I tested it and it seems to be working well.
