### ISSUE TITLE
A11y dependencies needed between RatioHalf position Properties

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#265]
@terracoda moved the right hand, and the aria-valuetext for it updated, but the aria-valuetext for the left didn't. Since #245, we added a dependency on each. Likely the best way forward is to make the unclamped fitness Property the dependency.

**Comment by zepumph** [comment]
@terracoda can you please confirm that the above works to your liking?

**Comment by terracoda** [comment]
I verified this for the hand interactions, but lock ratio is no longer working. Not sure if it is related.

I'll open a new issue.

**Comment by zepumph** [comment]
Oops, try that.

**Comment by terracoda** [comment]
Ok, I'll try again, no new issue for now.

**Comment by terracoda** [comment]
Much better :-)
Each value for the hands, whether using the sliders, or the both hands interactions, up date in unison, so the always have the same value.
When ratio is locked, everything seems operational again, and the ratio value stays "at challenge ratio" as expected.

**Comment by terracoda** [comment]
I'll go ahead and close this issue.

**Comment by terracoda** [comment]
Please note, I only tested with A11y View. I am having trouble with using VoiceOver with this sim (investigating).

**Comment by terracoda** [comment]
verified with VO on.
Working as expected.
