### ISSUE TITLE
Fill out Credits for the sim.

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#268]
We are probably late enough in the process to get a first pass in here.

**Comment by emily-phet** [comment]
PhET folks:
Lead Design: Emily B. Moore, Dor Abrahamson
Software Development: John Blanco, Michael Kauzmann 
Team: Brett Fiedler, Matthew Moore, Taliesin Smith
Sound Design: Ashton Morris
Quality Assurance: Kathryn Woessner (and many others by the time we're done!)

Here's a starting group of folks - all in alphabetical order except me and Dor - I'll ask how he would like to be listed. 
I just sent an email to Dor and Ellen, inquiring about if/how they would like to be attributed.

**Comment by emily-phet** [comment]
Updated with info from Ellen and Dor:

Software Development: John Blanco, Michael Kauzmann
Team: Brett Fiedler, Emily B. Moore, Matthew Moore, Taliesin Smith, Dor Abrahamson and the Embodied Design Research Laboratory (UC Berkeley), Ellen Do and the ACME Lab (CU Boulder ATLAS Institute)
Sound Design: Ashton Morris
Quality Assurance: Kathryn Woessner (and many others by the time we're done!)

I'm intentionally removing the "lead designer" section - I don't think that really makes sense here.

**Comment by zepumph** [comment]
Implemented above. There is also a "graphicArts" and "thanks" section if you would like to use it. Anything else here?

**Comment by emily-phet** [comment]
One update from Ellen - please make their part of the credits read as follows:
"Clement Zheng, Peter Gyory, and Ellen Do from the ACME Lab (CU Boulder ATLAS Institute)"

**Comment by zepumph** [comment]
How's that, it's a bit weird because it is a compound list. What do you think?

**Comment by terracoda** [comment]
@emily-phet, may I suggest a separate bullet item for the group contributors. We did this in John Travoltage.

It might make the list more readable.

- Software Development: John Blanco, Michael Kauzmann
- Team: Brett Fiedler, Emily B. Moore, Matthew Moore, Taliesin Smith
- Contributors: Dor Abrahamson and the Embodied Research Lab (UC Berkeley); Clement Zheng, Peter Gyory, and Ellen Do from the ACME Lab (CU Boulder ATLAS Institute)
- Quality Assurance: Kathryn Woessner
- Sound Design: Ashton Morris 

Here's a screenshot from John Travoltage:
![Screen Shot 2021-01-11 at 12 40 57 PM](https://user-images.githubusercontent.com/1902116/104209539-6d98c000-540c-11eb-9939-74fd6b810a9c.png)

Maybe "Collaborators" is a more appropriate word for the groups?

**Comment by zepumph** [comment]
@terracoda, @BLFiedler and I separated out the compound contributors into the "Contributors" section. I like it! We also added @amanda-phet  to the team since she has been an invaluable consultant in the Math department, as well as making us some hands!

This is what it looks like now. 

![image](https://user-images.githubusercontent.com/6856943/104360394-74334000-54bd-11eb-890a-ecddd1aa1197.png)


We will handle QA Credits over in #285. Closing. Feel free to reopen if desired.
