### ISSUE TITLE
When locking ratio the lower hand is unable to go below 0.5

### ISSUE THREAD

**Issue by DevonQui** [phetsims/ratio-and-proportion#276]
**Test device**
MacBook Pro
**Operating System**
Big Sur 11.0.1
**Browser**
Safari
**Problem description**
This is for https://github.com/phetsims/QA/issues/582
When locking the ratio, the lower most hand isn't permitted to go below 0.5 even though the simulation is able to fulfill ratios at numbers lower than 0.5.
**Steps to reproduce**
1. Open the simulation
2.  Click on the Create section
3. Turn on the number line at the upper right-hand corner and set the hands to the proper ratio
4. Click "lock ratio" and try to drag the lower most hand below 0.5 (you won't be able to)
5. Now turn off "lock ratio" and move the lower most hand below 0.5 and readjust the highest hand to recreate the ratio

**Visuals**
Here is the link to the video:
https://drive.google.com/file/d/1K1ahxq5Gv01TYs768fsXJXLzXOW5h0B8/view?usp=sharing

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15
Language: en-us
Window: 1440x792
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

**Comment by zepumph** [comment]
This was a designed consideration that has to do with how finicky and small the values and relationships can get at the lower end of the range. Also note that over in https://github.com/phetsims/ratio-and-proportion/issues/247#issuecomment-740888170 we decided today that this threshold will get lowered down to .021. Closing
