### ISSUE TITLE
In proportion ding when jumping through the "no success" region of the bottom

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#278]
We don't want to be able to hear the ding if the ding would be in the "no success" region, which is currently below .021, but may change as part of #275.

To reproduce:

* move right hand to .04 (using ?log)
* click and quickly drag the left hand down to zero and up to .05 back and forth.

**Comment by zepumph** [comment]
I think that fixes it, @BLFiedler originally told me about this error, can you confirmed fixed on master and feel free to close.

**Comment by BLFiedler** [comment]
Does still happen when the right hand is in this position:
![image](https://user-images.githubusercontent.com/47331395/101799732-be459200-3ac9-11eb-8869-98d317c4f32f.png)

Does not happen when the right hand is in this position:
![image](https://user-images.githubusercontent.com/47331395/101799787-ca315400-3ac9-11eb-8d01-9975cd28115e.png)

**Comment by zepumph** [comment]
At the time of @BLFiedler's testing, the "no-success" threshold was .021, so what you showed above seems right. Yesterday, over in https://github.com/phetsims/ratio-and-proportion/issues/275,  we lowered that range to .01, so both of those above would still have this behavior. Can you please review this again in correlation with that other issue review.
