### ISSUE TITLE
Frame rate slow for Windows 10 Firefox

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/ratio-and-proportion#281]
**Test device**
Lenovo ThinkPad

**Operating System**
Windows 10 

**Browser**
Firefox 

**Problem description**
This is for https://github.com/phetsims/QA/issues/582
While quickly dragging the hands in and out of the ratio, the green colors flash at you at a blinding amount instead of being more gradual, and it is overall slightly slower than Chrome's performance. 

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
Language: en-US
Window: 1536x750
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (Mozilla)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by zepumph** [comment]
Thanks for the report! It is most helpful if you can assign me, as I'm not as good at looking at all the issues in the repo as I should be (oops), thanks!

**Comment by zepumph** [comment]
I recorded performance on my windows firefox system, and reproduced minor slowing. For me it never went lower than 40fps. When I look at the spread of time spent, nothing sim-specific stood out to me. I know my computer is better than many students', but even still, this use case doesn't feel like something we need to spend more time on. Closing as a wont-fix.
