### ISSUE TITLE
QA Credits

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#285]
Once done with RC testing.

**Comment by zepumph** [comment]
I think these are ready.

**Comment by KatieWoe** [comment]
Liam Mulhall, Kathryn Woessner, Steele Dalton, Megan Lai, Devon Quispe, Brooklyn Lash, Logan Bray

**Comment by zepumph** [comment]
I forgot to include this in RC.3, I'll do it next time.
