### ISSUE TITLE
Possible to have unlocked hands when ratio checkbox is checked

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#292]
**Device**
iPad 6th Gen
**OS**
iPadOS 14.3
**Browser**
Safari
**Problem Description**
For https://github.com/phetsims/QA/issues/582.
I'm having some trouble reproducing this reliably, but I have reproduced it a few times. I will record my best guess as to how it occurs.
When clicking the lock ratio checkbox, occasionally, the hands will not actually be locked into ratio, and moving one will only move that one. This makes the checkbox inaccessible, and you are unable to check it. Reset all also does not uncheck it, but the ratio is still not locked. If you get them back in ratio and make the checkbox available, you can click the box again. This seems to lock the ratio, and the checkbox does not change.

**Steps to Reproduce**
1. Go to the second screen.
2. Set the ratio to 1:3 (may not be needed, but this has been the setting when I reproduce it)
3. Set the left hand low, but not at 0
4. Set right hand to match ratio
5. Check the lock ratio button
6. Try to drag right hand. If both hands move, uncheck box and reatempt

**Visuals**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/41024075/102148223-4d83da00-3e29-11eb-86a0-7a7d036dd1ad.gif)

**Comment by zepumph** [comment]
@KatieWoe  can you please try to reproduce this on master? I tried a couple of times locally and couldn't. Also can you reproduce on any other device and access the console for errors? It is possible that https://github.com/phetsims/ratio-and-proportion/issues/243 fixed this problem.

I want to add a assertion to detect this case and fail loudly, but after looking at the model, I don't see an easy way to do it, since there is a lot of reentrant number "fixing" and "snapping" to maintain the locked ratio. I would not be surprised if there is a log bug or edge case in that logic, but without a reproduceable case I can't really proceed.

**Comment by KatieWoe** [comment]
I only saw it on iPad at the time, but I only tried a few times on laptop. I'll try on a Mac Safari device, in case that is the cause. Then I'll try on iPad on master.

**Comment by KatieWoe** [comment]
I reproduced with the RC build on Mac 10.15.7 Safari 14.0.1. I did not manage to get any console errors, although there was something in the console if you opened it after the bug happened, it didn't show up as a console error and I'm not sure it is related. About to check master but will probably get something to eat before that.
![buglockratio](https://user-images.githubusercontent.com/41024075/102256302-760ee100-3ec8-11eb-8134-7ac530e5b14d.gif)
![Screen Shot 2020-12-15 at 11 10 36 AM](https://user-images.githubusercontent.com/41024075/102256318-7b6c2b80-3ec8-11eb-9126-c35663045bb9.png)

**Comment by KatieWoe** [comment]
Actually, I just reproduced (on the RC build) on Win 10 Chrome, so it is not dependent on Safari.
<img width="959" alt="win10chromebug" src="https://user-images.githubusercontent.com/41024075/102259074-e3704100-3ecb-11eb-945c-dd92ab880c5c.png">

**Comment by KatieWoe** [comment]
Reproducing on master causes a full sim freeze with a console error.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/41024075/102262566-875beb80-3ed0-11eb-85c3-96c03dea24de.gif)

**Comment by zepumph** [comment]
I may be able to make an assertion that asserts that the lock ratio checkbox should never be disabled and the model locked, but I worry a bit about how reentrant the model Properties are, and don't want to just add that in right now without more testing, it could be something like this though.

```diff
Index: js/create/view/CreateScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/create/view/CreateScreenView.js b/js/create/view/CreateScreenView.js
--- a/js/create/view/CreateScreenView.js	(revision bf94ff2c2e34761c9bf228900e59ed40b526d882)
+++ b/js/create/view/CreateScreenView.js	(date 1608063624400)
@@ -170,7 +170,10 @@
 
     // The "lock ratio" checkbox should not be enabled when the ratio is not in proportion.
     model.ratioFitnessProperty.link( () => {
-      lockRatioCheckbox.enabledProperty.value = model.inProportion();
+      const inProportion = model.inProportion();
+      lockRatioCheckbox.enabledProperty.value = inProportion;
+
+      assert && !inProportion && assert( !model.ratio.lockedProperty.value, 'should not be locked in disabled' );
 
       // If the checkbox get's disabled, then unlock the ratio.
       if ( !lockRatioCheckbox.enabledProperty.value ) {

```

**Comment by KatieWoe** [comment]
Just reproduced on ChromeOS with 1:4 ration, so the 1:3 ratio doesn't matter.

**Comment by zepumph** [comment]
@KatieWoe I believe this weirdness happened in an intermediate space that no longer exists (bigger than the no-success threshold, but smaller than the locked ratio range). 

Now both of these values are at .01, or .1 of the first tick mark. Can you reproduce this now? If not, please close.

**Comment by KatieWoe** [comment]
I didn't manage to reproduce after a few tries on Win10 Chrome. I'm wondering if it would be possible with multi touch, but I didn't manage it so closing the issue. Will reopen if it comes back.
