### ISSUE TITLE
Create sound features video

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#294]
In addition to #293, this is a reminder issue that we need to create a Sound features video.

**Comment by BLFiedler** [comment]
Draft of script has been completed. @emily-phet can you review?

https://docs.google.com/document/d/1yqJegHU2fyfgQrieJQx16dB-pGSUgcvX5iRe0lKhy30/edit?usp=sharing

**Comment by BLFiedler** [comment]
https://www.youtube.com/embed/HmT-ymz-iU0

Link above. Will be added to sim page when published.
