### ISSUE TITLE
rename this sim?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#3]
It was mentioned briefly in a recent email that we aren't totally sure this is the name that will stick around. It is pretty straight forward to change it if we want to, just let me know. PhET already has a sim called "Proportion Playground" which seems worth mentioning.

**Comment by zepumph** [comment]
@jessegreenberg mentioned this today independently today, with regards to how `proportion-playground` may get "looped" into this one like it was a suite (since we have many of those). 

Another thought from me, is that currently I named to main Property in the model that keeps track of the target proportion: `ratioProperty`. It sounded better in the moment than `proportionProperty`. I'm not sure if "Ratio" is age appropriate, or pedagogically good, but I thought I would put it out as an option.

**Comment by emily-phet** [comment]
@kathy-phet 
Any reason you see at the moment not to have a sim named "Proportion"? We're creating this now as a research/design tool, but it would likely be published publicly at some point.

**Comment by kathy-phet** [comment]
I would need to know more about the simulation, and we should loop Amanda in if this is a math sim. Can you provide more information about this sim and its design and status?

**Comment by emily-phet** [comment]
Here's the [design doc](https://docs.google.com/document/d/1udBAdppMJOaJXp3-vbzNydEFYsxr0wIYpAvvDO9AEGY/edit?usp=sharing), where you can see a mockup and initial prototype. 

The a11y team is sprinting on this during this quarter, in collaboration with multiple partners. We aim to create a "traditional" a11y phet sim, visual display, description, sound, etc., and at least one coupled tangible interface this quarter (by end of June) - for research purposes. Depending on how things proceed, we'll be able to gauge better later in the quarter possible plans for publication. Collaborators include math education, embodied cognition, and tangible interface experts. Happy to loop Amanda in as well.

**Comment by kathy-phet** [comment]
@amanda-phet - Please review and let's set up a time to discuss with @emily-phet.

**Comment by emily-phet** [comment]
@kathy-phet and @amanda-phet 
Note - I have severely limited work time right now. I will try to give a brief intro at status today, covering most of what's in the design doc with a demo from @zepumph, pending kid care. I can probably fit in a quick phone call next week. Otherwise, all action is happening via email list (@amanda-phet I can add you), Google docs, and ad hoc design conversations.

**Comment by amanda-phet** [comment]
From what I can see so far, this sim is about a **ratio**. Proportionality can mean a number of things, but in the math classroom, a **proportion** is two equivalent ratios. If the learning goals were more fleshed out that would be helpful. I see one NGSS standard alignment, but if you want this sim to be used in a math classroom then it should have CCSS alignments as well. 

This CCSS page might be helpful so you can see the language used in math: http://www.corestandards.org/Math/Content/RP/

**Comment by emily-phet** [comment]
Thanks @amanda-phet. I'm guessing our math ed collaborators' work refers to this embodied activity as "proportion" as they using it as an entry into a broad range of proportion ideas, and/or see this particular embodied experience as foundational to a range of proportion concepts. 

I'll reach out to our collaborators for clarification, elaboration, and specifically ask if there are objections to calling the sim "Ratio" or some variant of that.

Also note - we, of course, ultimately want this work to be publicly disseminated and used by children around the world. Our primary focus through summer/fall, at least, is to use this sim and related interfaces as a concrete context in which to explore design and development across traditional and tangible/embodied interfaces. We'll be tackling interesting design challenges for aligning visuals, sound, description, and physical modalities, and once we have reasonably refined prototypes we'll be exploring data collection and analysis of body and (eye) gaze tracking. So, we (PhET folks) are prioritizing the following: 1) going through the process of designing and developing an accessible sim with coupled tangible/embodied interface(s) refined to meet research goals, and 2) developing and refining the use of body movement tracking with learners across a wide range of sensory needs / abilities to inform understanding of learning and accessible design.

**Comment by emily-phet** [comment]
@amanda-phet thanks for your time in considering this. I have added you to the email list. Apologies for the flood of email likely to occur. Please feel free to skim at your leisure, if there is anything that goes out requesting your involvement specifically, I will also reach out on Slack.

I spoke with the father (so-to-speak) of MITp today, and discussed the name. His response was more eloquent that I will be able to relay now, with lack of sleep, etc., but essentially we agreed that it might be more clear to you conceptually why "Proportion" if you had a few more resources indicated more the complete depth of the tool, which I will send to you by email. 

From a different perspective, thinking about future developers and disambiguating this sim as distinct code-wise from Proportion Playground, I thought "Ratio and Proportion" might be worth considering, as I believe there is no question that the sim would support engagement in the concept of "ratio".

**Comment by amanda-phet** [comment]
I am happy to look more into those resources you sent. It's not that I don't understand why it is named Proportion, I just don't think it's an appropriate name for this sim if published to the PhET website. "Ratio and Proportion" sounds great to me.

**Comment by zepumph** [comment]
What steps needs to be taken before I do this renaming?

**Comment by emily-phet** [comment]
I discussed this briefly with Dor on April 3rd, and he indicated "Ratio and Proportion" is reasonable to him. 

Let's change the sim name to "Ratio and Proportion". Code name RaP. :)

**Comment by zepumph** [comment]
Take a look at the URL! How fun.

The sim has been renamed, and is running locally and on phettest. I commented on slack and told all to rename. I'll publish a dev version next to make sure everything is working.

**Comment by zepumph** [comment]
I'm glad I ended up doing the test, because I found https://github.com/phetsims/chipper/issues/938 in the process. Here is the latest dev version:

 https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.12/phet/ratio-and-proportion_en_phet.html

Closing
