### ISSUE TITLE
Extend pointer area for "Lock Ratio" checkbox

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#302]
From #286 (code review).

I think it's conventional for us to extent the pointer areas of checkboxes, and I'm not seeing that here.  Here's a clip from the recently published "Natural Selection" sim:

![image](https://user-images.githubusercontent.com/3082831/102279931-7370b380-3ee9-11eb-8153-d72a97c4cdbe.png)

...and here's the Lock Ratio button in this sim:

![image](https://user-images.githubusercontent.com/3082831/102279975-8aafa100-3ee9-11eb-97a0-031cc8f46c1d.png)

**Comment by zepumph** [comment]
Hmm. I don't know about this convention. If there was an icon or other content that we wanted to be selectable, or if we wanted consistency between multiple components, I would feel different. I am able to click on the checkbox, and on the text. What would you want to see here?

**Comment by jbphet** [comment]
I think we often enlarge the touch area so that the checkbox can be easily used in a touch environment.  I don't have any strong attachment to this though - I just want to make sure it's user friendly.  If you're finding that it's easy to interact with on an iPad, that's fine by me, and you can just close this.

**Comment by zepumph** [comment]
@ariel-phet can you comment on expanding checkbox pointer areas in general? Is this common practice? What do you recommend for Ratio and Proportion's second screen's "lock ratio" checkbox?

**Comment by ariel-phet** [comment]
@zepumph it has been common practice and requested in multiple sims. If clicking on the checkbox or on the text is working well on a small device (like a phone) I think you are in good shape. But I would think that will require some dilation to feel correct so the expansion used in something like Natural selection would be a good model to follow.

**Comment by zepumph** [comment]
Thanks for catching me up on the protocol you two. That makes sense. There has been quite of bit of focus on dynamic layout for this sim, because of the vertical tendencies of the ratio. We have set up scaling for the controls on the right so that they aren't tiny in vertical aspect ratios. I poked around in a phone-sized layout, and feel like the scaling gets us most of the way there, but a bit extra touch area made me feel slightly better. @jbphet can you please review and let me know what you think?

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/102562124-d9447300-4082-11eb-8a91-05c66d070d2b.png)

**Comment by jbphet** [comment]
This looks better.  Might as well do a little extension in the horizontal direction too, as is shown in the Natural Selection checkboxes.  This might be nicer for a left-handed touch screen user.  After that, it's fine with me to close.

**Comment by zepumph** [comment]
Makes sense to me! I used the same x number found in `EnvironmentalFactorsPanel.js`, and extended the mouseArea too. Closing. Thanks!
