### ISSUE TITLE
Use screen.<name> for screen name keys in strings file

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#304]
From #286.

I think our convention is to name screens using the key `screen.<name>`, but for the life of me I can't remember why.  This sim isn't using that convention.

I just took a look in "Natural Selection", which is a recently published sim by one of our most experienced developers, and the convention was followed there.  I'd recommend just going with it, but if you'd like to discuss in developer meeting or search through the build tools to better understand the motivation for this convention, feel free to do so.

**Comment by zepumph** [comment]
Sounds good! I forgot about the convention.
