### ISSUE TITLE
Check and potentially remove unneeded asset files

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#306]
From #286.

There are several asset files that are of type .ai, which is Adobe Illustrator, but there are no `Image` instances that I can find in the code.  Are these still part of the sim?  By the way, I think we only keep the asset files if we derive images from them, but not if they were just part of the design - the design folder should cover that.

The files in question are `cutout-hand.ai`, `filled-in-hand.ai`, and `Gridlines.ai`.

**Comment by zepumph** [comment]
The `ai` files didn't end up rendering images, but instead were used for the SVG math, and copied into SCENERY/Path classes, Filled in/cutout hands: https://github.com/phetsims/ratio-and-proportion/blob/29577f8befa6e4f58e8a362e13092ebf02d3c67b/js/common/view/RatioHandNode.js#L208-L263
gridlines: https://github.com/phetsims/ratio-and-proportion/blob/3551afc8bfaa23a0e8d2334e1a79e0080fdfd68e/js/common/view/TickMarkViewRadioButtonGroup.js#L77-L128

How would recommend proceeding? I agree it is a bit opaque.

**Comment by jbphet** [comment]
What I've seen and found helpful in similar situations in the past is a README.md file that explains how the asset file is used to generate the artifact used in the code.  Here is an example: https://github.com/phetsims/equality-explorer/blob/master/assets/README.md

**Comment by zepumph** [comment]
Good idea, implemented above. CLosing
