### ISSUE TITLE
Mobile VO both hands instructions inconsistent

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#312]
For https://github.com/phetsims/QA/issues/582. iPadOS 14.3 Mobile VO
When reading through the second screen, when it gets to the both hands section it mentions using the lock ratio checkbox and moving a hand to move both of them, rather than the instructions given in this section in the laptop version. However, it then goes on to say that this functionality isn't available in mobile. This is referring to the wasd/arrow keys that is described in the laptop version. However, since this follows the lock ratio instructions, it sounds like it is referring to that instead. The lock ratio checkbox does work, but users may not try it due to the wording/ordering. They may also encounter https://github.com/phetsims/scenery/issues/1094#issuecomment-747087250 and think the checkbox is broken due to this and so may not make use of the feature.

**Comment by terracoda** [comment]
@KatieWoe, can you you please be more clear about what is confusing about the wording?

The intent on screen 2 is to direct mobile screen reader users to use the Lock Ratio check box if they want to move both hands at the same time. There is no other way to move the hands simultaneously when using a screen reader on a touch device (iOS). With mobile VoiceOver enabled focus can on only be one item at a time, whereas on a laptop, we were able to create a custom bi-manual interaction with W/S keys for left hand. That is not possible on iOS.

Without a screen reader enabled, learners can use bi-manual input.

Here is the exact wording for each screen if one is on iOS:
Help text for Both Hands interaction on iOS (i.e., VoiceOver users):
**Screen 1:**
Explore challenge ratio with individual Left and Right hands. This custom multi-touch interaction is not yet possible with screen reader software on a mobile device.

**Screen 2:** 
To move both hands, first check Lock Ratio. With ratio locked, move both hands as a single unit to explore the challenge ratio. This custom multi-touch interaction is not yet possible with screen reader software on a mobile device.

Would this be more explicit and clear?:
**Screen 1:**
Explore challenge ratio with individual Left and Right hands. **The custom Both Hands** interaction is not yet possible with screen reader software on a mobile device.

**Screen 2:** 
To move both hands, first check Lock Ratio. With ratio locked, move both hands as a single unit to explore the challenge ratio.  **The custom Both Hands** interaction is not yet possible with screen reader software on a mobile device.

**Comment by terracoda** [comment]
I don't think this is a bug. 
This is just about finding clear wording to redirect learners to a possible way to move both hands at the same time, assuming the Lock Ratio checkbox is working.

**Comment by terracoda** [comment]
Another Option for Screen 2:
- Explore challenge ratio with individual Left and Right hands ****. **The custom Both Hands** interaction is not yet possible with screen reader software on a mobile device.

**Comment by KatieWoe** [comment]
The issue is with screen 2 only for me. Since it talks about moving both hands, describes the way to do it, then says "this custom multi-touch interaction is not yet possible" the "this" tells me that the thing it just described (the lock ratio) is not possible. It does not tell me that there is some other method that was not described that exists but is not possible.

My suggestion would be to put the warning about it not being possible first then follow with what they can do instead. For instance:
"Explore challenge ratio with individual Left and Right hands. This custom multi-touch interaction is not yet possible with screen reader software on a mobile device. Instead, to move both hands, first check Lock Ratio. With ratio locked, move both hands as a single unit to explore the challenge ratio."

**Comment by terracoda** [comment]
Thanks @KatieWoe, I agree, the use of "this" makes it vague in the current order of the wording. To keep things shorter, it might be best to just state "The custom Both Hands interaction" as the thing that is not possible.

**Comment by terracoda** [comment]
I think I like, the iteration I came up with, so I am going to update the strings at lines 349 and 380 and make a commit.

**Comment by terracoda** [comment]
I think I addressed this issue. I will try and test it.

**Comment by terracoda** [comment]
I was able to verify the change on phettest via bayes.
I think the new help text sounds good:
- Explore challenge ratio with individual Left and Right hands. The custom Both Hands interaction is not yet possible with screen reader software on a mobile device.
- Explore challenge ratio with individual Left and Right hands or try with ratio locked. The custom Both Hands interaction is not yet possible with screen reader software on a mobile device.

Oh, I think I need a comma before the or.

**Comment by terracoda** [comment]
I addressed this issue, so closing.
