### ISSUE TITLE
Mobile VO reads out percentages in number picker

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#313]
For https://github.com/phetsims/QA/issues/582. iPadOS 14.3 mobile VO
When going through the number pickers on the second screen for the my challenge option, VO will read out the number, then a percentage, making it confusing what is being selected/done. Note that due to https://github.com/phetsims/scenery/issues/1094 I had to open the my challenge box before turning on VO to see this.
https://drive.google.com/file/d/10y6jxpKDGRTuC46q0HBuwDMvhdALzI4X/view?usp=sharing

**Comment by zepumph** [comment]
Likely duplicate of https://github.com/phetsims/ratio-and-proportion/issues/283.
