### ISSUE TITLE
(mobile a11y) Lock Ratio not checkable on iOS with VoiceOver enabled

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#315]
When testing [dev version 78](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.78/phet/ratio-and-proportion_en_phet.html) on iOS with VoiceOver enabled, I was not able to check or uncheck the Lock Ratio check box.

I tested on 
- iPhone 8 with iOS 13.5.1
- iPhone7 with iOS 14.2

**Comment by terracoda** [comment]
Tagging [QA dev test 582](https://github.com/phetsims/QA/issues/582).

**Comment by terracoda** [comment]
This issue might be related to https://github.com/phetsims/scenery/issues/1094

**Comment by zepumph** [comment]
Exact same as https://github.com/phetsims/ratio-and-proportion/issues/316#issuecomment-750689319, see https://github.com/phetsims/scenery/issues/1094 for details as to why this isn't working. Unassigning and on-hold until that one is complete.

**Comment by terracoda** [comment]
I can now check the check box.
Phone updated to iOS 14.3, and the fix in phetsims/scenery#1094 may also have been applied.
I think it is safe to close this issue for RaP.

**Comment by terracoda** [comment]
My last comment is no longer true as of this morning.

**Comment by zepumph** [comment]
This is fixed from recent changes over in https://github.com/phetsims/scenery/issues/1094. Closing
