### ISSUE TITLE
JAWS reads dash in half-way

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#319]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/582. Seen with Jaws.
When reading the word "half-way" JAWS says "half dash way" which I found distracting and potentially confusing as it was reading the position of the hands in relation to the tick marks.

**Visuals**
https://drive.google.com/file/d/1uaXRmkqKxfJhq1foQokGEXfc044CIfTt/view?usp=sharing

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment]
@KatieWoe, nice catch. Accordion Merriam-Webster dictionary, halfway does not have a dash.

**Comment by terracoda** [comment]
I changed half-way to halfway on lines 178, 181, 184 and 199.  That should cover it.
Jaws will likely read out other dashes like in lower-middle region of Play Area, but in cases like that the dash is correct spelling.

**Comment by terracoda** [comment]
I verified this change in the context responses.

**Comment by terracoda** [comment]
Closing.
