### ISSUE TITLE
Allowing user-defined custom ratios

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#32]
@zepumph I'd like to add an options dialog to the PhET menu, that allows the user to input their own ratios. 

We don't need this now, but wanted to give you a heads up that this is a desired feature. Please let me know any questions or concerns about this.

**Comment by zepumph** [comment]
The way to do this seems to be to use a keypad. It would likely be straightforward, though I don't have a good idea about what the exact UI would be besides just looking at the iOS app as a base. Let me know what more you want from me here.

**Comment by emily-phet** [comment]
What about a number...picker? interaction - like in GFL:B for changing the mass? How challenging is it to add a "Custom Challenges" dialog to the PhET menu, with three sets of number pickers in it?

**Comment by zepumph** [comment]
That sounds really nice. I have an understanding of this generally, though I think it will have to go under the "Options" dialog.

>with three sets of number pickers in it?

I don't understand this automatically. Likely we need a numerator and denominator picker, but what is the third, and what is a "set?"

**Comment by emily-phet** [comment]
There are three challenges. If we put this feature in the "options" menu, here's the use case:
teacher is setting up *all of the challenges* to be used either in class, or by student(s). Teacher can select a custom ratio for *each challenge*. So there would need to be three sets of number pickers, one for each challenge.

If we put this feature as a fourth, custom challenge, then it would only need to be one set of number pickers, as the user (teacher or student) would only be changing that single challenge value.

**Comment by emily-phet** [comment]
In 5/21 design meeting @kathy-phet pointed out that in other PhET math sims (e.g., Function Builder), they provide a way to input a custom function, and show/hide this information. This allows teachers to input a new function, and students to input new functions and challenge friends to figure it out. 
I liked this idea for RaP - would involve change of ratio feature to be in sim display rather than as an option in the PhET menu (an approach which would lend itself to teacher-only use).

**Comment by emily-phet** [comment]
Adding a second screen, which focuses on custom ratios - see #58.
