### ISSUE TITLE
Oddities in keyboard nav dialog

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#320]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/582
This is less of a bug, and more of a suggestion/something that confused me. The keyboard nav dialog is different on all three screens. This seems particularly odd to me in two cases. On the home screen, the dialog is very barebones. This may well be the first thing someone using these tools checks, and they may not think there are any other instructions after that. Second, on the Discovery screen, one section is numbered, and no others are, even on the other screen, which seemed an odd choice to me.

**Visuals**
Home
<img width="424" alt="homescreendialog" src="https://user-images.githubusercontent.com/41024075/102547950-2de1f100-4077-11eb-9ab7-0dbf2ac18476.png">
Discover
<img width="661" alt="discoverscreentext" src="https://user-images.githubusercontent.com/41024075/102548112-6681ca80-4077-11eb-9ba4-8b7c114d8366.png">
Create
<img width="667" alt="createscreentext" src="https://user-images.githubusercontent.com/41024075/102548129-6da8d880-4077-11eb-9bf6-fd5effedc62f.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.77/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-dev.77 2020-12-08 00:32:10 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by terracoda** [comment]
Thanks for the suggestion @KatieWoe. Keyboard Shortcuts are only relevant to the screen a learner is on, so that is whey the are all different.

The numbered list, represents required steps to choose a Challenge, so we chose a numbered list to help scaffold that all steps are required.

Marking as won't fix.

**Comment by terracoda** [comment]
In addition, on screen 3 we decided to not re-describe how to use the Ranges combobox. We felt it was covered by the Challenges combobox.

**Comment by terracoda** [comment]
Closing.
