### ISSUE TITLE
Re-arrange static Play Area content and add  a dynamic description for the hands

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#322]
This issue should address an information gap described in https://github.com/phetsims/ratio-and-proportion/issues/262#issuecomment-748277232 and should hopefully help with issue #200 where JAWS users had trouble accessing the help text for the Both Hands interaction once the the interaction had focus.

I propose to re-arrange the Play Area content and adding position information to a dynamic description that was already next to the Both Hands interaction.

Bolded content is the new part. Everything else is the same content as before, but slightly re-arranged.

H2: Play Area
_Dynamic Description of the Hands (in a paragraph element)_
The content of the paragraph is different depending on which Tick Mark is checked:

- If No tick Marks: **H**ands extremely close to each other, **left in lower region, right in lower-middle region.**
- If Tick Marks: **H**ands extremely close to each other, **left on second tick mark, right on fourth tick mark.**
- If Numbered Tick Marks: **H**ands extremely close to each other, **left on tick mark 2, right on tick mark 4.**

_Help text for slider interactions (in a paragraph element) - UNCHANGED_
P: Move hands up and down individually to find the Challenge Ratio in different places.

Left Hand, slider 
<hands, at challenge ratio>

Right Hand, slider 
<hands, at challenge ratio> 

_Help text for Both Hands interaction (in a paragraph element) - UNCHANGED_
P: With Both Hands activated, use W and S keys to move left hand, and Up and Down Arrow keys to move right hand. Move both hands at the same time to find and maintain the Challenge Ratio.

Both Hands, movable

**Comment by terracoda** [comment]
@zepumph, I think the dynamic description above is the same string as the Both Hands context response.

**Comment by terracoda** [comment]
I bolded the content that is different based on the current dynamic description that is sitting in the PDOM, and then I realized when I add position information it basically has the same wording and punctuation as the Both Hands context response.

**Comment by terracoda** [comment]
Let me know if you have any questions.

**Comment by zepumph** [comment]
>the description is basically the same (wording and punctuation) as the Both Hands context response.

Yes, I was able to use pretty much the exact same logic, except that in this dynamic description you never get distance-progress, and you also don't get "edge" alerts when locked. So it is just distance and position.

Please review.

**Comment by terracoda** [comment]
The new descriptions are correct and the order is exactly how I requested.
Thanks @zepumph!
Closing.
