### ISSUE TITLE
I can explore lower on the screen with ratio locked, is this okay?

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#323]
In #257, @zepumph fixed the big jumping that could happen ratio gets locked.

I have one remaining question though, is it ok that I can explore lower with ratio locked than when ratio is not locked? Is that expected?

Steps to reproduce:
1. with ratio at 1:2
2. using both hands or sliders, move left hand to 2 steps above bottom
3. move right hand down until you get ratio ding
4. lock the ratio
5. return to the hands and move them down with ratio locked

You should be able to move them down a little more.

**Lowest I can go at 1:2 without ratio locked:**
![Screen Shot 2020-12-18 at 5 10 11 PM](https://user-images.githubusercontent.com/1902116/102659652-55f35200-4154-11eb-8bc8-e33b57eda037.png)

**After locking the ratio, I can go down a little more:**
![Screen Shot 2020-12-18 at 5 11 57 PM](https://user-images.githubusercontent.com/1902116/102659690-699eb880-4154-11eb-8903-0cb00df7af40.png)

**Comment by terracoda** [comment]
I'm not saying we need to address this issue, the sim is working well.

I am just wondering based on recent changes in issue #257 and  #275 am I supposed to be able to find ratio if my Left Hand is 1 shift-key step above the bottom?

Actually, maybe this is a duplicate issue of #275.
Please close if this is a duplicate issue.

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/ratio-and-proportion/issues/275 we decided that the no-success threshold should be lowered to .01. If that is problematic I think it should be taken up in the review of that one. @terracoda please note any weirdness over there, and perhaps pass it over to EM if you think it is needed.
