### ISSUE TITLE
Hands don't move with number keys when ratio is locked at 1:1

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#329]
While verifying #227, I noticed there was something funny when I lock the ratio at 1:1.
I commented in https://github.com/phetsims/ratio-and-proportion/issues/227#issuecomment-752739803 that the hands do not move in this case.

Steps to reproduce:
1. go to screen 2
2. change My Challenge to 1:1 or any N:N
3. Lock the ratio by checking the check box
4. Move focus back to Both Hands
5. Hit the number key shortcuts

The sim sings, but they hands do not move and there are no responses, likely because the hands do not move.

This happens with and without VO enabled.

I am not sure if this is a new bug and I am not sure if I ever tired an N:N ratio with ratio locked. 

I tested the sim from master on Mac Book Pro MacOS 10.13.6 using  Safari.

**Comment by zepumph** [comment]
Likely related to #286. and maybe #327.

**Comment by zepumph** [comment]
Sorry about that! I used the wrong method call in the assertion. Feel free to close.

**Comment by terracoda** [comment]
Awesome. This issue is fixed. Thanks!
