### ISSUE TITLE
Custom focus behavior for both-hands when zoomed/panned

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#333]
Over in https://github.com/phetsims/ratio-and-proportion/issues/296 we noticed that when you are zoomed, and tab navigate to the boths hands, the zoom goes to the center of the Node. This most likely will not zoom to either hand, let alone both. 

We don't want this issue to block publication, but feel like it could be a nice case to experiment with more custom zoom/focus behavior.

**Comment by zepumph** [comment]
Perhaps instead of the pan/zoom listener always choosing the center, a Node could opt into an interface method like `onZoomedFocus` and it could return a point for the pan zoom listener to use. Tagging @jessegreenberg to see if he likes that idea when needing custom solutions.

**Comment by zepumph** [comment]
In https://github.com/phetsims/ratio-and-proportion/issues/296#issuecomment-758871051 @jessegreenberg said:

> > The zoom-to-center behavior when focused on the both hands Node
> 
> I don't really agree with this design request. It isn't just panning, but would also involve zooming out to keep both hands on screen. In the case of RAP, you have to be almost completely zoomed out to see both hands when they are apart. What if the user wants to zoom in on a hand and change ratio? Doesn't this assume too much about what the user is trying to do?



Then I responded with:
>I would love to discuss that more in #333, because I think I agree with you. But it also is informed by how we handle solution number (3) above, because this could be a custom implementation that we take based on assumptions about the particular sim (RaP).

**Comment by terracoda** [comment]
I thinking that I agree with @jessegreenberg and @zepumph that for RaP centering the hands (when zoomed in on a slider) is not so useful, especially if it means zooming out without the learner's consent.

I can imagine sims where quickly zooming out to get a little more context would be really useful. We could potentially achieve this some kind zoom-out short cut that might be useful across sims. 

Another approach would be to create a few very simple options for the zoom feature. For example, we could allow user to set a max zoom, or set a fixed zoom, so there is no accidental zooming or shrinking while interacting. Options like these leave some control in the hands of the leaner.

**Comment by zepumph** [comment]
I am inclined to close this issue, since it seems like we don't want to customize anything special for the both hands focus. Is that true @terracoda? If so feel free to close, otherwise please add what behavior we may want that would be specific to the both-hands interaction.

**Comment by terracoda** [comment]
Oh, sorry, I was talking about not needing to center the sliders like the way the Both Hands interaction gets centered.

For the Both Hands interaction, I think it would be useful if it worked more like the sliders. That is, the hand that is moving would stay in view.

If Both Hands are moving at the same time, I feel like the one hand should stay in view, ideally, if the hands are moving up, the upper hand, and if the hands are moving down, the lower hand.

And when the users uses the 0-9 shortcuts, the hands should remain in view, or at least, the tick mark that they are on should come into view, if the hands are too widely spaced to both be in view.

I think in all these cases, the user is going to have to zoom out to use the sim in a useful way, so I would not want it to block publication. 

This is a custom interaction, so I think it will need a custom solution (eventually, if not possible immediately).

Does that make sense to you?

**Comment by terracoda** [comment]
Oh @zepumph, apologies again, this issue is just about focus. Do you specifically mean, should we not center the interaction on focus?

**Comment by zepumph** [comment]
>I think in all these cases, the user is going to have to zoom out to use the sim in a useful way. . .

I agree with this. Why then would we spend time on custom behavior to track individual hands while zoomed in, when learning goals suggest that you will need to see both in order to understand the sim at all?

I don't yet see any useful value added by adding specific support to the both hands interaction to pan in a special way, either on focus or while interacting. So, to me, https://github.com/phetsims/ratio-and-proportion/issues/333#issuecomment-760501109 was trying to see if you can think of value-added logic for panning/zooming to the specific both-hands interaction that would let someone "use the sim in a useful way".

**Comment by terracoda** [comment]
Agreed, if a learner moves a hands off the screen, or uses the number key shortcuts while zoomed in, they will have to zoom out to see what happened.

For RaP, the zoom feature will be useful for reading labels, challenges, and ranges, but less useful for the hand interactions.
