### ISSUE TITLE
Hide focus highlights but keep DOM focus in response to pointer interaction

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#335]
Some things were fixed in https://github.com/phetsims/ratio-and-proportion/issues/331
And again, many iOS issues were resolved by changes to how scenery now handles events on iOS in https://github.com/phetsims/scenery/issues/1094

However, the comboboxes in RaP are no longer working at all when VoiceOver on iOS is enabled.

With VoiceOver enabled, the buttons do not get focus, so I cannot activate the button to pop-up the list of options.

**This is a common code issue** because I just checked Molarity on bayes/phettest and the Solute pop-up button has the same issue. It does not get focus.

In both RaP and Molarity, the comboboxes work fine on iOS when VoiceOver is not enabled.

@jessegreenberg and @zepumph, I might need to open an issue in sun or scenery for this issue because it is common code.

**Comment by terracoda** [comment]
When I posted this issue, I didn't realize this issue is going to be worked here in https://github.com/phetsims/scenery/issues/1137

**Comment by terracoda** [comment]
This is a duplicate issue, so closing to keep things simple.

**Comment by zepumph** [comment]
While this issue won't get worked on, instead focusing on https://github.com/phetsims/scenery/issues/1137, it would be nice to keep track of the blocking work for RAP directly in the repo (hence the creation of the "duplicate" marker issue #330). I'll reopen until this is solved generally, but there is nothing to do here.

**Comment by terracoda** [comment]
What was happening yesterday is not happening today.

The button gets focus, I can open the list box, but I just get help text before the list items, and the selected item is not focused.

**Comment by zepumph** [comment]
@jessegreenberg and I would still like to use https://github.com/phetsims/scenery/issues/1137#issuecomment-761255891 to try to  improve the combo box experience by auto focusing the listbox when the button is selected.

I'll rename to be the sim-specific version of that issue.

**Comment by zepumph** [comment]
@jessegreenberg and I have finished the common code issue. This should have fixed the combo box focus issue on iOS. That said it was a pretty extensive change to the way our focus behavior occurs in the sim. Can you please give a full review of iOS + VO, as well as let us know if Mac alternative input looks and behaves as you would expect. 

From here the only thing that I know of still blocking is https://github.com/phetsims/sun/issues/674

**Comment by terracoda** [comment]
Verified Mac alternative input. The combobox interaction still works great there.

On iOS with VO, the interaction is accessible and seems to work well. 

There are some inconsistencies in interactive highlighting. The combobox uses the black VO highlight whereas other objects get the pink PhET highlight.

There are some other inconsistencies with hgihlighting as well:
- On first rad through (can't reproduce) I didn't get pink highlights on the navbar buttons
- No pink highlight when I first got focus on the My Challenge heading/button
- When VO black highlight is on combobox, the pink highlight was still on the My Challenge heading/button
- The timing of the pink highlight is a little sticky and can remain on an object until focus is actually on a new focusable object. Maybe this is okay - need to test more.

**Comment by zepumph** [comment]
@terracoda, @BLFiedler and I went over the reasoning for the inconsistent iOS + VO highlighting behavior. @terracoda can take these and put them in a place that can be used by designers testing iOS + VO in the future. 
* VO highlight only shows up on "positioned" elements, where the PDOM element follows the scenery Node graphical element around the screen.
* We don't position anything that get's the `click` event post iOS 14, so buttons, checkboxes, sliders. So the VO highlight is in the top left corner for these.
* We must position elements when we need to pointer events from iOS + VO, and can't depend on getting a click event. For some reason, we don't get click events even on buttons when certain aria attributes are present, like `aria-haspopup` (like ComboBoxButton). Also on non "clicking" tags like `menuitem` (PhetMenu) and `option` (ComboBoxListBox).
* For reasons unknown to us, `aria-haspopup` causes a lack of "click" event on the button. Thus clicking the ComboBoxButton with iOS + VO looks the same to the code as using touch/mouse to press it.
* Focus doesn't automatically show the focus highlight, but instead you need to have the Display level switch "focusHighlightsVisibleProperty" true as well. (simplified logic) This is set to true when PDOM events come from the browser. This is set to false when mouse/touch events come from the browser.

**Comment by zepumph** [comment]
@terracoda feel free to close whenever.

**Comment by terracoda** [comment]
Closing this issue as I created a documentation issue in A11y Research repo.
