### ISSUE TITLE
Hearing keyboard instructions for Both Hands with VO on iOS

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#336]
When reading through pdom on iOS and VO enabled, I accessed Keyboard helptext

**Comment by zepumph** [comment]
From a refactor a while ago where we moved the Both Hands help text around. I think we just need to move this to the same spot: 


https://github.com/phetsims/ratio-and-proportion/blob/619bd1757e7e70f69756feba7bea5164586e6c28/js/common/view/BothHandsPDOMNode.js#L223-L226

**Comment by zepumph** [comment]
Fixed in the above commit.

**Comment by zepumph** [comment]
@terracoda feel free to close.

**Comment by terracoda** [comment]
Verified and this is issue is fixed. No more keyboard instructions on iOS + VO.
