### ISSUE TITLE
Graphical issues where screen breaks up when hand is moved

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#339]
Seen on Win 10 Firefox while sim had pointer areas on. The sim was left to sit for a fairly long time as I worked on other tasks, including a zoom call. When I came back, the sim appeared normal until I tried to drag one of the hands. As it moved, the graphical issue shown bellow occurred. It seemed to change as more interactions were attempted. As I opened the console it seemed to fix itself. I am now trying to reproduce on Chrome and Firefox without pointer areas.
<img width="947" alt="randomoddwhendragging" src="https://user-images.githubusercontent.com/41024075/106818092-0d74f280-6635-11eb-9fa7-3c7488a9c1a9.png">

**Comment by zepumph** [comment]
if you cannot reproduce this consistently, perhaps it is not worthy of blocking. Nice screenshot though!

@jonathanolson, is this what "anti-aliasing" is supposed to prevent? Do you think we should add something to prevent this? Have you seen this before?

**Comment by jonathanolson** [comment]
> is this what "anti-aliasing" is supposed to prevent?

Anti-aliasing seems unrelated. As far as PhET graphics are concerned, anti-aliasing is basically fine-grained smoothing pixel values (e.g. some pixels on the edges of paths are not FULLY empty or FULLY the path's color).

> Do you think we should add something to prevent this? Have you seen this before?

Looks like browser or GPU corruption. They usually use tiles as textures on the GPU to render webpages, and those tiles seem clearly delineated here. No way to prevent, and seems similar to more general corruptions examples (not for PhET sims).

**Comment by zepumph** [comment]
Alright thanks for the update.

**Comment by KatieWoe** [comment]
Seen again to an extent on Firefox on the same device. https://github.com/phetsims/QA/issues/617
![rangetoosmall](https://user-images.githubusercontent.com/41024075/110699521-2e88b000-81ac-11eb-9ac6-a48b1f54af68.gif)
