### ISSUE TITLE
State descriptions ready for implementation 

### ISSUE THREAD

**Issue by Matthew-Moore240** [phetsims/ratio-and-proportion#34]
Most of the Static & Dynamic State Descriptions are ready to go for H1 in the [design doc](https://docs.google.com/document/d/1HJvvGWYaUv9tlat9S7omQQVng8fGB4FuUhTEM1qx1z8/edit#heading=h.jtxmm44qd6hc). Every thing in red is ready to go. 

**Ready for implementation**

- [x] Static Screen Summary
- [x] Dynamic state-of-sim qualitative
- [x] Dynamic state-of-sim quantitative
- [x] Static sim-specific interaction hint in a paragraph
- [x] Static keyboard shortcuts hint in a paragraph (standard):

**H2: Control area and H2: Sim resources are ready for implementation**

- [x] Reset All, button
- [x] Mute Sound, toggle button
- [x] Keyboard Shortcuts, button
- [x] PhET Menu, pop-up button

**Comment by zepumph** [comment]
I believe that all state descriptions in the PDOM have been implemented, at least as a first pass. The dynamic description in the screen summary was a nice bite-sized piece to begin creating the describer structure needed for this logic. 

@Matthew-Moore240  can you please review this on phettest and let me know what you think?

**Comment by Matthew-Moore240** [comment]
Awesome! I can review it tomorrow!

**Comment by Matthew-Moore240** [comment]
All reviewed these sound really good so far! I think this is ready to close but just want to double check with you @zepumph
