### ISSUE TITLE
Create descriptions for Legends of Learning

### ISSUE THREAD

**Issue by arouinfar** [phetsims/ratio-and-proportion#344]
Related to https://github.com/phetsims/QA/issues/601 and #1 

As a part of the publication process, we create icons and descriptions for each sim for our partner, Legends of Learning. 

I went ahead and created the icons and pre-populated the [LoL spreadsheet](https://docs.google.com/spreadsheets/d/1umIAmhn89WN1nzcHKhYJcv-n3Oj6ps1wITc-CjWYytE/edit#gid=562591429&range=A8) for this sim. Things that are still needed for each screen:
* Description
* Vocab Words (terms that a student could operationally define after using the sim)
* Questions - Before (3-4 example questions that a teacher may ask a student before using the sim)
* Questions - After (3-4 example questions that a teacher may ask a student after using the sim)

I'm not familiar enough with this simulation to create this content, so I'll assign @BLFiedler. The Ready_to_Integrate tab of this spreadsheet has all the data for the other sims we've delivered to LoL and may contain useful examples. Please let me know if you have any questions or would like to discuss over zoom.

Once the sim is published and the spreadsheet data is completed, please let me know and I'll notify our contact at LoL.

**Comment by BLFiedler** [comment]
Filled out! Will leave myself assigned for now and assign @arouinfar when the sim is published.

**Comment by BLFiedler** [comment]
Good to go here @arouinfar !

**Comment by BLFiedler** [comment]
@arouinfar Just checking that this was done and can be closed?

**Comment by zepumph** [comment]
Hey, I'm working in this repo again so I thought I'd ping this issue, at least on the priority label.

**Comment by terracoda** [comment]
@BLFiedler and @arouinfar, do any updates need to be made to Legends of Learning as this sim heads to publication again with new features.

**Comment by zepumph** [comment]
Marking as blocking until this is marked as not. I'm not sure what the current status of this is.

**Comment by arouinfar** [comment]
This issue is not blocking, and was ready to close a long time ago, my apologies. LoL uses the latest version of the simulation, so they will automatically get updates.
