### ISSUE TITLE
Sim sound may play when muted

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#349]
For https://github.com/phetsims/QA/issues/601.

Found while testing Win 10 Chrome with Jaws. The sound I heard sounded like a sim sound, but it may have been a Jaws sound.

While the sim was muted, when tabbing through options with Jaws, sometimes an item would make a brief sound that sounded like a sim sound to me.

https://user-images.githubusercontent.com/41024075/107159209-d3189780-694b-11eb-95b1-e3783419327f.MOV

**Comment by zepumph** [comment]
I'm pretty certain that these are not sim sounds, and are coming from JAWS. In general these two sounds pair with when the screen reader enters and exits an HTML form (aka "forms mode"). I'll toss this over to @jessegreenberg to confirm. Feel free to close or pass back to QA to document this behavior as needed.

**Comment by jessegreenberg** [comment]
Yes, that is a JAWS sound not a sim sound.  Its letting the user know that the screen reader is entering/exiting different navigation modes like @zepumph described. Closing, but pinging @KatieWoe just so she is aware this is expected.
