### ISSUE TITLE
Sound repeats when holding down keys

### ISSUE THREAD

**Issue by brooklynlash** [phetsims/ratio-and-proportion#355]
**Test device**
Lenovo ThinkPad

**Operating System**
Win10

**Browser**
Chrome, Firefox

**Problem description**
This is for https://github.com/phetsims/QA/issues/609
When testing the keyboard navigation with the hands, when you hold down buttons and hit the bottom or top of something the sounds repeat/spam and start playing weirdly. Maybe there's a way to make it so that even if you are holding down the button it only moves once?

@zepumph let me know if you want me to upload a video with the audio abnormalities. 

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.2/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-rc.2 2021-02-13 05:25:44 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36
Language: en-US
Window: 1707x818
Pixel Ratio: 2.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by zepumph** [comment]
Excellent find! I updated the boundary sounds so that (like with individual hands), the sound only plays on keyup. Will you please confirm fixed on master. Note this also effects pressing 0 with the both-hands interaction.

**Comment by brooklynlash** [comment]
I still see an issue when holding down the enter key with the orange reset button and other buttons besides the drop-down menus, and when holding down the side, up/down keys for the numbered interval buttons.

**Comment by zepumph** [comment]
Yes, that will always occur. We have limitations with our buttons where we have to rely on using the `click` event for button presses. This is to support screen readers. We can only control multiple/spamming sounds when we have access to the keyup event, which we do in sliders (individual hands) and in custom interactions (the both-hands together interaction). Not with buttons though.

**Comment by brooklynlash** [comment]
The 0-9 buttons and key-up work now without spamming the sound, looks good!

**Comment by zepumph** [comment]
Cherry-picked.

**Comment by phet-steele** [comment]
Looks good in 1.0.0-rc.3!
