### ISSUE TITLE
Implement UI for grid "base unit" 

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#36]
Expanding from https://github.com/phetsims/ratio-and-proportion/issues/5, we should determine how to adjust the base unit for the grid. In Dor's app, there were arrows on the side of the ratio that could adjust that.

As part of https://github.com/phetsims/ratio-and-proportion/issues/31, we moved radio buttons to control this from the UI to the options dialog.

Over to designers.

**Comment by emily-phet** [comment]
@amanda-phet @ariel-phet @kathy-phet 

I would love your input on this! Here's what we're pondering:
1. Open the sim now ([latest dev](https://bayes.colorado.edu/dev/html/ratio-and-proportion/1.0.0-dev.15/phet/ratio-and-proportion_en_phet.html), or phettest, doesn't matter).
2. Select the "Numbered Grid" radio button
3. Open the phet menu
4. Select "Options...". There is an option to change the "Grid Base Unit". As you select different grid base unit options, you'll see the grid lines in the sim change. 

We need to design a user control that would allow these changes to the gridline to occur. Note - the behavior is not traditional grid scaling (so not like zoom in/zoom out). Also note, this is probably the very last thing we would want a learner to do, so it shouldn't be very inviting.

1. Is there anything like this in other PhET sims? We would try to mimic that convention if that is the case.
2. A simple thing would be to have an "up arrow" button by the top gridline, and a "down arrow" button by the bottom gridline. Does this seem reasonable to you all? If so, should the arrow be on a square shaped button, round, button, or something else? Is there a particular color convention or preference for buttons like this that we should be aware of?
3. Any other ideas (besides up/down arrow buttons) we should consider? It would be awesome to get this interaction down to a single button, to minimize interactive objects in the focus order that are not of primary importance (like this feature).

Your thoughts would be most helpful by May 8th. If you'd like to discuss further, I could request Thursday design meeting time for May 14th...

**Comment by ariel-phet** [comment]
@emily-phet apologies, I don't think I am able to add any valuable insight as it is not clear to me what the learning goals of the sim are and I haven't really had this sim contextualized in a design meeting, so it is difficult for me to make an informed comment/suggestion.

I will leave it to @amanda-phet or @kathy-phet or will wait until it comes around in design meeting.

**Comment by amanda-phet** [comment]
The closest thing I can think of is the combobox we use to select different scales on a number line. See [Number Line: Integers](https://phet.colorado.edu/sims/html/number-line-integers/latest/number-line-integers_en.html), Generic Screen.
![image](https://user-images.githubusercontent.com/7852916/81006604-06525700-8e0d-11ea-948a-16273f22da9a.png)

An up or down arrow makes me think of scrolling, and that's not what is really happening here. I'd love to try to help brainstorm some more in a design meeting, too!

**Comment by emily-phet** [comment]
@ariel-phet @amanda-phet Thanks - I'll ask for design meeting time next week if I can make it (that time slot has lately become the daycare reopening committee meeting time...).

**Comment by amanda-phet** [comment]
We could always schedule it for another time! My calendar should show my availability, so if there is a time that overlaps it doesn't need to be on Thursday afternoon.

**Comment by emily-phet** [comment]
New idea - since the minimum value will always stay the same, what if the max value (on startup that would be "10") was a dropdown menu itself. It would look different than the other numbers (inside of a drop down box) but when you select it, the other number options would drop down (10, 20, 30, 40) and once another is selected, the grid and number visuals would change to correspond with the new selection. 

I'm guessing this would work with high school/college learners, not sure about middle schoolers...

@BLFiedler - any thoughts here?

**Comment by BLFiedler** [comment]
I like the idea of moving this control to the maximum of the grid. I'm not sure if a dropdown is ideal, but I can't immediately think of something better. I kind of like the idea of something "zooming out/in", which I think the arrows sort of accomplished in Dor's iOS app, but just the visual change of the grid might do that.

Visually, we'll need to adjust the appearance of the numbers (they're a bit small and if the maximum is this big dropdown, then the other numbers should probably scale to be as large) and maybe add some padding to the top.

**Comment by emily-phet** [comment]
Note - an idea for a "number control" tool is being considered (see #51). If this is moved forward, we would want to consider ways to allow control of number changes on the tool itself. Putting this on hold for now, until we decide if we're going with a "number tool" or not.

**Comment by emily-phet** [comment]
Note - still not sure of the exact interface design, but in other PhET math sims, it's been sufficient to support 0-20 range.

**Comment by emily-phet** [comment]
This is being incorporated into a second screen, as an accordion box (as @amanda-phet suggested). Closing, can reopen if it is determined more design work needed on this feature.
