### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#361]
For https://github.com/phetsims/QA/issues/609. Screenshots need to be added before the sim can be published. Since the sim seems close to publication, I am marking this as blocking.

This was discussed on slack. @BLFiedler suggested something like this as the main screenshot:
![Screenshot Capture - 2021-02-23 - 16-51-53](https://user-images.githubusercontent.com/41024075/109078601-dab19d80-76ba-11eb-97b4-ddc5d0e52115.png)

Here are some possibilities for alt screenshots:
![Screenshot Capture - 2021-02-22 - 14-29-45](https://user-images.githubusercontent.com/41024075/109078669-f5841200-76ba-11eb-8bbc-c1dfe82f4d8f.png)
![Screenshot Capture - 2021-02-22 - 14-29-38](https://user-images.githubusercontent.com/41024075/109078671-f61ca880-76ba-11eb-97ff-a1c41824d097.png)
![Screenshot Capture - 2021-02-22 - 14-29-29](https://user-images.githubusercontent.com/41024075/109078673-f6b53f00-76ba-11eb-8457-48f729688319.png)
![Screenshot Capture - 2021-02-22 - 14-29-02](https://user-images.githubusercontent.com/41024075/109078676-f6b53f00-76ba-11eb-9550-c17fca588a57.png)

Please let me know if the main screenshot is acceptable, which screenshots should be alts, and leave suggestions if any are not acceptable. Once this is done the screenshots can be named and uploaded.

**Comment by terracoda** [comment]
These look good to me, and I like the main one.

**Comment by BLFiedler** [comment]
Thanks, @KatieWoe! I think these are all fine. If it's more appropriate to have 3, I'd eliminate Alt #1.

**Comment by KatieWoe** [comment]
Done in above commits. Closing
