### ISSUE TITLE
Hands are aligned differently between both screens

### ISSUE THREAD

**Issue by phet-steele** [phetsims/ratio-and-proportion#364]
The two hands + gray rectangles are slightly more over to the left on the Create screen, when compared to their positions on the Discover screen. Just click back and forth between the two and you should easily see that.

Seen on Win 10 Chrome. For phetsims/QA/issues/617.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-rc.3/phet/ratio-and-proportion_all_phet.html
Version: 1.0.0-rc.3 2021-03-03 03:29:06 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36
Language: en-US
Window: 1920x937
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by zepumph** [comment]
@BLFiedler would you like me to work to fix this?

**Comment by BLFiedler** [comment]
Yeah, I think this is a bit of polish that the sim should probably have, assuming it's not too difficult a fix.

**Comment by zepumph** [comment]
Done and pushed to the branch.
