### ISSUE TITLE
Bug in shift-keyboard step snap mapper

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#366]
**@terracoda said over in https://github.com/phetsims/ratio-and-proportion/issues/298#issuecomment-793987903:**

Oh no, I am mistaken, while in general I think things seem better. I can still get a description that is incorrect. In the screen shot the left hand seems to be clearly on Tick mark 2 and the and are described as being in ratio (2:3), but the position of the left hand is described as "around tick mark 2", not "on tick mark 2". 

Could this is just a rounding error? Have I asked this before?

Also, I noticed that when moving the left hand up and down is lands in different places and still hits ratio.

Note when using shift key and W/S to move up and down:
Starting at visual 2 (described as around tick mark 2) and going down one and then back up to visual 2 (described as around tick mark 2).
![Screen Shot 2021-03-09 at 11 02 30 AM](https://user-images.githubusercontent.com/1902116/110486543-4f2b0a00-80c7-11eb-9b32-f11cf25f82db.png)

Then starting again in the same place at visual 2 (described as around tick mark 2) and going up one and then back down to visual 2 (described as around tick mark 2). Strangely, the left hand is not exactly in the same place, though the step is still in ratio and the position is described as around tick mark 2. This time it looks like the left hand is more off the tick mark, even though in both cases the it should be on the tick mark and described as being on the tick mark.

I am leaving this issue open as it is weird. 
Maybe we can review it again before publication.
![Screen Shot 2021-03-09 at 11 01 50 AM](https://user-images.githubusercontent.com/1902116/110486638-64079d80-80c7-11eb-85d1-215d327ded44.png)

**Comment by zepumph** [comment]
@terracoda, I would like to discuss this issue more, because in actuality the step-mapper is behaving as it is supposed to. The asymmetry here is because in one direction you are in proportion in the shift step size (going from down .08 to .07 using `?log`). But `.06` isn't in proportion, so the step-size mapper goes from ( .06-> .066666 -> .08). Thus this issue, at least in part, is about the inconsistency that the description has in this case with the "in proportion" threshold and state. I see this as a design problem, and another byproduct of complicated interactions that we were trying to optimize for during the design of the sim. Here it is because of the shift-step-snapper-mapper working correctly (as designed and implemented), but not well for this case. But this problem has popped up all over the place during RC testing. 

Marking for meeting.

**Comment by zepumph** [comment]
There are two problems here:

1. When the left value is `.0666667`, and the tick mark says "around tick mark two". That is a rounding error, and should be fixed.
2. When the left value is `.07`, and the tick mark says "around tick mark two" when the right says "on tick mark three", that inconsistency is because of how the shift-step-mapper behaves depending on if the current ratio is in-proportion or not. We don't know how to fix this well, and don't want to go into this, because it is a bit of an edge case. We are just going to proceed without fixing this.

**Comment by zepumph** [comment]
I thought it may be because of something like toFixed rounding calls, but nothing was obvious just yet.

```diff
Index: js/common/view/getKeyboardInputSnappingMapper.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/getKeyboardInputSnappingMapper.js b/js/common/view/getKeyboardInputSnappingMapper.js
--- a/js/common/view/getKeyboardInputSnappingMapper.js	(revision dde5468ef9558dae1c36e9b4ae2b04e6a5577383)
+++ b/js/common/view/getKeyboardInputSnappingMapper.js	(date 1615941285230)
@@ -45,9 +45,9 @@
     if ( applyConservationSnap && !( alreadyInProportion && remainder === 0 ) ) {
 
       let returnValue = newValue;
-      const target = RAPConstants.toFixed( getIdealValue() );
+      const target = getIdealValue();
       if ( newValue > target !== oldValue > target && oldValue !== target ) {
-        remainder = RAPConstants.toFixed( newValue - target );
+        remainder = newValue - target;
         returnValue = target;
       }
 
Index: js/common/view/describers/TickMarkDescriber.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/describers/TickMarkDescriber.js b/js/common/view/describers/TickMarkDescriber.js
--- a/js/common/view/describers/TickMarkDescriber.js	(revision dde5468ef9558dae1c36e9b4ae2b04e6a5577383)
+++ b/js/common/view/describers/TickMarkDescriber.js	(date 1615940954448)
@@ -78,7 +78,7 @@
     const numberOfTickMarks = this.tickMarkRangeProperty.value;
 
     // account for javascript rounding error
-    const expandedValue = RAPConstants.toFixed( normalized * numberOfTickMarks );
+    const expandedValue = normalized * numberOfTickMarks;
 
     // account for javascript rounding error
     const remainder = RAPConstants.toFixed( expandedValue % 1 );

```

**Comment by zepumph** [comment]
(1) was fixed above, by limiting the amount of rounding going on:

![image](https://user-imagesithubusercontent.com/6856943/111401652-8a58aa80-867e-11eb-91db-8507b9fbf765.png)


@terracoda please review. Now we will having match "on" descriptions for both more often. In this case, they are both "on" when moving up to the ratio, but still not when moving down to it.

**Comment by terracoda** [comment]
I think it works great with range 0-10.
I think I see a slight improvement in 0-30, but I couldn't get the console to show me the values. Let's just go with this. 

Both 0-20 and 0-30 seemed to have the same description issue (slightly miss-matched descriptions at some ratios). This is expected, right? Again, 0-10 is great.

**Comment by terracoda** [comment]
@zepumph , if this slight miss-match is expected for both -20 and 0-30, let's go with this. Again, 0-10 is great.

**Comment by zepumph** [comment]
Confirmed fixed on the branch. CLosing
