### ISSUE TITLE
iPad hand moves slightly when dropped, which can make getting in ratio hard

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#371]
For https://github.com/phetsims/QA/issues/617. Seen with iPadOS 14 with Safari.
When dragging the hands around, when let go they will move slightly, usually down. It does not seem to be due to a twitch from what I can tell. The jump is enough that it can go from in ratio to out, or out of ratio to in.

**Comment by zepumph** [comment]
I am able to reproduce this in CAF and CCK-DC (both on master and on the PhET website). I am not convinced this is a blocking issues, or issue at all. @BLFiedler, can you please recommend a path forward. Should this block RC publication?

**Comment by BLFiedler** [comment]
Yeah, I don't believe this is specific to RaP. However, we actually put the snap-to-tick because I saw this in interviews.

I don't believe there is anything we can do here without a more general investigation into touch interactions.
