### ISSUE TITLE
Mobile VO does not let you click on an item to move focus there

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#372]
For https://github.com/phetsims/QA/issues/617. Found on iPadOS 14.4.1 with VO. Did not seem to happen on previously published sim (Molarity).
On previous sims, you would be able to specifically click on an item, such as a checkbox, in order to move focus to it. In this RC, you have to swipe to items it seems. Trying to click on an item moves to the nav bar or the range box, nothing else it seems. Not sure if this is an issue or not, but it is different behavior.

https://user-images.githubusercontent.com/41024075/110713598-6c430400-81bf-11eb-850d-c2491621fa0d.MOV

**Comment by zepumph** [comment]
> click on an item

I will assume that you mean press with your finger.


Yes this was a sacrifice for simplicity and performance during @jessegreenberg's and my work on supporting iOS 14 + VO. Basically now that feature is opt-in, and a biproduct of interactions that we need to handle special for iOS. Currently the main items that you can do this for are the PhetButton and ComboBox. Others will, by default, not be able to use this. Please feel free to close.
