### ISSUE TITLE
Production deploy this sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ratio-and-proportion#376]
Currently blocked by this build-server failure: https://github.com/phetsims/perennial/issues/221

**Comment by zepumph** [comment]
I was able to publish now. Thanks @pixelzoom for pushing on a quick fix. This is a very nice way to end the week! 

https://phet.colorado.edu/sims/html/ratio-and-proportion/1.0.0/ratio-and-proportion_all.html
