### ISSUE TITLE
Convert from FA4 to FA5

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#379]
From https://github.com/phetsims/sherpa/issues/83#issuecomment-821685067

**Comment by zepumph** [comment]
Removing hold because of https://github.com/phetsims/sherpa/issues/83#issuecomment-876881719. I'll take it for a test drive.

**Comment by zepumph** [comment]
Ok, here is how the regular shape looks, it's a bit smaller of an eye even though it has the same bounds. This was as large as I could make it without changing the size of the radio buttons:

![image](https://user-images.githubusercontent.com/6856943/125098200-4c472280-e083-11eb-903b-97ca8f002646.png)



And here is the "solid" version of the eye, which I don't think we want, but posted to this just in case there were opinions.


![image](https://user-images.githubusercontent.com/6856943/125098287-5c5f0200-e083-11eb-8ca3-c2167d8de84c.png)


@BLFiedler can you confirm that master (the first picture), is the new icon that we want?

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/126672269-487d1fb1-3853-418f-909c-142241408da8.png)

![image](https://user-images.githubusercontent.com/6856943/126672390-3e7ba3f5-94c6-460d-b1b0-1464b9307393.png)



You can also take a look on https://bayes.colorado.edu/dev/phettest/ratio-and-proportion/ratio-and-proportion_en.html?ea&brand=phet.

**Comment by BLFiedler** [comment]
I think that looks reasonable even on small screens like my phone. Go for it.
