### ISSUE TITLE
Implement My Challenge AccordionBox

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#381]
https://docs.google.com/document/d/1offJbONUg8y5Aa9kHewC9iTDtNISzna4giGt7WrpXCk/edit#heading=h.nvlwmm9fjx2v

Splitting out issues for individual components seems nicer here.

https://github.com/phetsims/ratio-and-proportion/issues/363

**Comment by zepumph** [comment]
Questions about accordion box to discuss with JG:

1. In AccordionBox.js, it seems like we want to specify a voicing hit area for the interactive highlight that includes the title bar. Perhaps we want to refactor the components listeners to just expand hit areas of the button instead of new listeners for the title bar.
2. The TODO in the issue, how does he recommend I add voicing object responses on focus when the interactive element is actually a sup component, perhaps we can forward to the button?

**Comment by zepumph** [comment]
After discussing with @jessegreenberg, we answered these questions:

1. See https://github.com/phetsims/scenery/issues/1212
2. Removed in the above commit. We would instead just use expandCollapseButtonOptions to pass through voicing strings.

**Comment by zepumph** [comment]
@terracoda, the AccordionBox is ready for review. No other parts, including the nested NumberPickers have been implemented, please review with https://phet-dev.colorado.edu/html/ratio-and-proportion/1.1.0-preferences.1/phet/ratio-and-proportion_all_phet.html

**Comment by terracoda** [comment]
This sounds really awesome! I think you got it right for both Mouse and Keyboard.

The only thing that sounds weird from a design perspective is when I only have "object changes" checked. In that case I get the object name multiple times: My Challenge on focus and My Challenge on opening and My Challenge on closing.

Everything is implemented as requested. Nice job!

I'll mark this as a design issue or should I make a new issue?

**Comment by zepumph** [comment]
Same issue sounds fine to me!

**Comment by zepumph** [comment]
@jessegreenberg and I spoke about how to implement the interactive highlights for the AccordionBox, and we want to try mutating the mouse/touch areas and to get rid of the extra input listeners in AccordionBox. I'll give that a try. The other solution would be to mix Voicing into each Node with an input listener, like for these:

https://github.com/phetsims/sun/blob/260e29027c31d1193a830a22417e337e476e2b8b/js/AccordionBox.js#L228-L256

**Comment by jessegreenberg** [comment]
@terracoda @zepumph after today's discussion during Voicing meeting I would like to try the design option for the "My Challenge" AccordionBox where we categorize components of speech explicitly into "object", "context" and "help" responses. Using strings from the design document it would look like this:
```
Object Response: My Challenge
Context Response: Current Challenge {{x}} to {{y}} (upon opening)
                  Current challenge hidden (upon closing)
Hint Response: When collapsed - Expand to set your challenge
               When shown: Set left and right values to create your challenge.
```
where each of these can easily be added/removed depending on user preferences.

An implementation of this was done in the above commits.

Here is a version with these strings https://phet-dev.colorado.edu/html/ratio-and-proportion/1.1.0-preferences.2/phet/ratio-and-proportion_en_phet.html that we can use for discussion.

**Comment by jessegreenberg** [comment]
I spent 35 minutes trying to match what is in the design document now using the current Voicing API. I made progress but did not finish in that time. Here is my progress. It is an example of the kind code required to create unique strings for various *combinations* of Voicing preferences.

<details>

```patch
Index: js/create/view/MyChallengeAccordionBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/create/view/MyChallengeAccordionBox.js	(revision fc470ad623b3258b7d7d4833bfe0bcd0e398804a)
+++ js/create/view/MyChallengeAccordionBox.js	(date 1620431778605)
@@ -14,6 +14,7 @@
 import Fraction from '../../../../phetcommon/js/model/Fraction.js';
 import NumberPicker from '../../../../scenery-phet/js/NumberPicker.js';
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
+import voicingManager from '../../../../scenery/js/accessibility/speaker/voicingManager.js';
 import HBox from '../../../../scenery/js/nodes/HBox.js';
 import Node from '../../../../scenery/js/nodes/Node.js';
 import RichText from '../../../../scenery/js/nodes/RichText.js';
@@ -160,28 +161,60 @@
       // strings containing responses used for Voicing
       let contextResponse = '';
       let hintResponse = '';
+      let objectResponse = '';
 
       if ( expanded ) {
-        contextResponse = ratioDescriber.getCurrentChallengeSentence( targetAntecedentProperty.value, targetConsequentProperty.value );
+        if ( voicingManager.objectChangesProperty.value && !voicingManager.contextChangesProperty.value ) {
+
+          // speaking object changes, but not speaking context changes, only include the object response
+          objectResponse = ratioAndProportionStrings.myChallenge;
+        }
+        else if ( voicingManager.contextChangesProperty.value ) {
+
+          // If we are speaking object changes AND context changes, the object response is built into the context
+          // response so only speak the context response.
+          // If ONLY speaking context responses, we use this same alert for the context response
+          contextResponse = accordionBoxUtterance.alert = ratioDescriber.getMyChallengeSentence( targetAntecedentProperty.value, targetConsequentProperty.value );
+          objectResponse = null;
+        }
+
         hintResponse = ratioAndProportionStrings.a11y.create.myChallengeExpandedHintText;
 
         accordionBoxUtterance.alert = ratioDescriber.getCurrentChallengeSentence( targetAntecedentProperty.value, targetConsequentProperty.value );
       }
       else {
-        contextResponse = ratioAndProportionStrings.a11y.ratio.currentChallengeHidden;
+        if ( voicingManager.objectChangesProperty.value && !voicingManager.contextChangesProperty.value ) {
+
+          // speaking only object changes,
+          objectResponse = ratioAndProportionStrings.myChallenge;
+          contextResponse = ratioAndProportionStrings.a11y.ratio.myChallengeHidden;
+        }
+        else if ( voicingManager.contextChangesProperty.value ) {
+
+          // If we are speaking object changes AND context changes, the object response is built into the context
+          // response so only speak the context response.
+          // If ONLY speaking context responses, we use this same alert for the context response
+          objectResponse = null;
+        }
+
         hintResponse = ratioAndProportionStrings.a11y.create.myChallengeCollapsedHintText;
 
         accordionBoxUtterance.alert = ratioAndProportionStrings.a11y.ratio.currentChallengeHidden;
       }
 
+      // don't modify the object response, that should remain constant so that it is always read correctly on focus
       this.setButtonVoicingOptions( {
         voicingContextResponse: contextResponse,
         voicingHintResponse: hintResponse
       } );
 
-      this.voicingSpeakButtonResponse( { utterance: accordionBoxVoicingUtterance } );
+      // speak overriding the normal object response which may be removed to prevent duplication in some
+      // preferences configurations
+      this.voicingSpeakButtonResponse( {
+        voicingObjectResponse: objectResponse,
+        utterance: accordionBoxVoicingUtterance
+      } );
       phet.joist.sim.utteranceQueue.addToBack( accordionBoxUtterance );
-
     } );
 
     Property.multilink( [ targetAntecedentProperty, targetConsequentProperty ], ( targetAntecedent, targetConsequent ) => {
```
</details>

**Comment by jessegreenberg** [comment]
During a discussion today we decided on a new category for responses called the "name" that is different from the object response. That could make the requested design much easier to implement, I am going to give that a try after https://github.com/phetsims/scenery/issues/1217#issuecomment-837138572

**Comment by terracoda** [comment]
Just a little extra information about how I think about object responses. 

Object responses contain object-specific information.
Depending on where the user/learner is in their interaction, the object response can be slightly different. 

Initially they will need object name and starting value, but as soon as changes happen they only need the latest information. 

I feel like separating the object name allows us to easily create two types of object responses which we naturally already have in Interactive Description design:
- initial object response (name and current value)
- changing object response (latest object value)

Every interaction is a little different.

**Comment by terracoda** [comment]
As I said in slack

> And I listened to your implementation of the accordion box. I think it sounds good as implemented. It would be less verbose if you were able to easily change "Current Challenge" to "My Challenge" as part of a robust and general system. For this interaction, however, I think we could roll with the already made PDOM strings and see if users are confused about not hearing "My Challenge" when object details are not checked in Preferences. This is actually an important research question. How far can we get with the same strings?
"Current challenge" and "My challenge" appear in the read me buttons, so maybe users will just put it all together magically like screen reader users, do.
I still think for many interactions having the object name separate is going to be super useful. I re-mapped out Friction's Grab button today . I think it works really nicely with having the button name as a separate entity for the two-step grab interaction.

**Comment by zepumph** [comment]
I am back working on this issue and it is quite messy. We have a preferences branch that can't be used anymore because RAP is now typescript. While trying to move some of that logic over to master, I found that @jessegreenberg has some prototyping that he was working on in https://github.com/phetsims/ratio-and-proportion/issues/381#issuecomment-834884186. Basically I'm going to bail because I think it is worth starting over. The original design didn't even have any name responses. I will take a look and see what we can do.

<details>

<summary>
patch to forget about from https://github.com/phetsims/ratio-and-proportion/commit/25c797c5779cb45ac5344d79bb584cb9ad4ec0b6?diff=split </summary>


```diff
Index: js/create/view/MyChallengeAccordionBox.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/create/view/MyChallengeAccordionBox.ts b/js/create/view/MyChallengeAccordionBox.ts
--- a/js/create/view/MyChallengeAccordionBox.ts	(revision 4c45507ae032506534bc05be5a78f8f6429afe03)
+++ b/js/create/view/MyChallengeAccordionBox.ts	(date 1636672410586)
@@ -28,6 +28,8 @@
 import Color from '../../../../scenery/js/util/Color.js';
 import RatioDescriber from '../../common/view/describers/RatioDescriber.js';
 import { TickMarkViewType } from '../../common/view/TickMarkView.js';
+import voicingUtteranceQueue from '../../../../scenery/js/accessibility/voicing/voicingUtteranceQueue.js';
+import SceneryEvent from '../../../../scenery/js/input/SceneryEvent.js';
 
 const PICKER_SCALE = 1.5;
 const ICON_SCALE = 0.9;
@@ -73,6 +75,22 @@
         mouseAreaYDilation: 5
       },
 
+      // voicing
+      // TODO: this doesn't work because a sub component of the AccordionBox gets focus instead of the A-box itself. https://github.com/phetsims/ratio-and-proportion/issues/381
+      voicingCreateObjectResponse: ( event: SceneryEvent ) => {
+        if ( event.type === 'focusin' ) {
+          return ratioAndProportionStrings.myChallenge;
+        }
+        return null;
+      },
+      voicingCreateHintResponse: ( event: SceneryEvent ) => {
+        if ( event.type === 'focusin' ) {
+          return ratioAndProportionStrings.a11y.create.myChallengeHintText;
+        }
+        return null;
+      },
+
+
       // phet-io
       tandem: Tandem.REQUIRED
     }, options ) as Required<AccordionBoxOptions>;
@@ -161,10 +179,21 @@
     this.expandedProperty.value = DEFAULT_EXPANDED;
 
     const accordionBoxUtterance = new ActivationUtterance();
+    const accordionBoxVoicingUtterance = new Utterance();
+
     this.expandedProperty.lazyLink( ( expanded: boolean ) => {
-      accordionBoxUtterance.alert = expanded ?
-                                    ratioDescriber.getCurrentChallengeSentence( targetAntecedentProperty.value, targetConsequentProperty.value ) :
-                                    ratioAndProportionStrings.a11y.ratio.currentChallengeHidden;
+
+      if ( expanded ) {
+        accordionBoxUtterance.alert = ratioDescriber.getCurrentChallengeSentence( targetAntecedentProperty.value, targetConsequentProperty.value );
+        accordionBoxVoicingUtterance.alert = ratioDescriber.getMyChallengeSentence( targetAntecedentProperty.value, targetConsequentProperty.value );
+      }
+      else {
+        accordionBoxUtterance.alert = ratioAndProportionStrings.a11y.ratio.currentChallengeHidden;
+        accordionBoxVoicingUtterance.alert = ratioAndProportionStrings.a11y.ratio.myChallengeHidden;
+      }
+
+      voicingUtteranceQueue.addToBack( accordionBoxVoicingUtterance );
+
       // @ts-ignore
       this.alertDescriptionUtterance( accordionBoxUtterance );
     } );
Index: js/common/view/describers/RatioDescriber.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/describers/RatioDescriber.ts b/js/common/view/describers/RatioDescriber.ts
--- a/js/common/view/describers/RatioDescriber.ts	(revision 4c45507ae032506534bc05be5a78f8f6429afe03)
+++ b/js/common/view/describers/RatioDescriber.ts	(date 1636672275481)
@@ -142,6 +142,19 @@
     } );
   }
 
+  /**
+   * @public
+   * @param {number} antecedent
+   * @param {number} consequent
+   * @returns {string}
+   */
+  getMyChallengeSentence( antecedent: number, consequent: number ) {
+    return StringUtils.fillIn( ratioAndProportionStrings.a11y.ratio.myChallenge, {
+      targetAntecedent: antecedent,
+      targetConsequent: consequent
+    } );
+  }
+
   /**
    * @public
    * @param {number} antecedent
Index: ratio-and-proportion-strings_en.json
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/ratio-and-proportion-strings_en.json b/ratio-and-proportion-strings_en.json
--- a/ratio-and-proportion-strings_en.json	(revision 4c45507ae032506534bc05be5a78f8f6429afe03)
+++ b/ratio-and-proportion-strings_en.json	(date 1636671782582)
@@ -389,6 +389,9 @@
       "myChallengeHelpText": {
         "value": "Set left and right values to create your challenge, then move hands to explore it."
       },
+      "myChallengeHintText": {
+        "value": "Expand to set your challenge."
+      },
       "bothHandsGestureDescriptionHelpText": {
         "value": "Explore challenge ratio with individual Left and Right hands, or try with ratio locked. The custom Both Hands interaction is not yet possible with screen reader software on a mobile device."
       }
@@ -525,6 +528,12 @@
       "currentChallengeHidden": {
         "value": "Current challenge hidden."
       },
+      "myChallenge": {
+        "value": "My challenge {{targetAntecedent}} to {{targetConsequent}}."
+      },
+      "myChallengeHidden": {
+        "value": "My challenge hidden."
+      },
       "capitalized": {
         "at": {
           "value": "At"

```

</details>

**Comment by terracoda** [comment]
@zepumph , I think we might be able to close this issue. 
The voicing responses that were implemented here, is what  is documented in the design doc. It sounds like you will need to re-implement this interaction.

**Comment by zepumph** [comment]
This is next on my radar to implement in master. I may try to make it happen in Common code while we are at it.

**Comment by terracoda** [comment]
AccordionBox is another 2-step interaction (like comboBox) that allows for help text to be delivered for both mouse/touch and alt/input. Hopefully, the design document communicates this clearly. Reach out if there is any confusion. I did re-document this interaction several times.

**Comment by zepumph** [comment]
(deleted previous wrong comment)

**Comment by zepumph** [comment]
I believe this is completely implemented. @terracoda will you please review the Ratio and Proportion design?

**Comment by terracoda** [comment]
The My Challenge Accordion Box is implemented as I laid out in the design and is working as designed.

But, now that it is implemented, it might be better to follow an option that more closely follows the design of Interactive Description, in particular the Context Responses. I we change it, then we would also need to change the reading block to be for all input - not just pointer input.

I am going to review the number spinners before deciding any design changes.

**Comment by zepumph** [comment]
I hear a bug. On startup, we close the accordionbox, and so I hear this because it is listening to the Property:

```
My Challenge, hidden, Expand to set your challenge.
```

**Comment by terracoda** [comment]
Ok, here are the design changes to My Challenge Accordion. 

- [ ] Remove stative custom object responses "hidden" and "1 to 2" (the value when opened).
- [ ] Remove custom hint, "Set left and right values to create your challenge." We'll just have a hint on the Reading Block.
- [ ] Remove custom hints for when opening and closing the accordionbox, "Set left and right values to set your challenge." and "Expand to set your challenge."
- [ ] Use PDOM context responses for when opening and closing the Accordion
    - "Current challenge 1 to 2." 
    - "Current challenge hidden."

- [ ] **For alternative only, and only if possible,** use the custom hint response, "Expand to set your challenge." when focus lands on a closed AccordionBox, but only if this is not a problem. I am not sure what flexibility exists here with the focus event. If this is not logical, I am willing to live without it.

Design doc is updated, here screen shots as a record of the design.
![image](https://user-images.githubusercontent.com/1902116/158887859-029623ee-50dc-4cc2-b147-3a2311a35ff4.png)
![image](https://user-images.githubusercontent.com/1902116/158889222-e8734316-7347-42a7-95fc-9560a0ae3add.png)

**Comment by zepumph** [comment]
@terracoda, please review all changes to the "My Challenge" AccordionBox interaction in this issue if helpful to. This includes the ReadingBlock (https://github.com/phetsims/ratio-and-proportion/issues/440) and NumberPickers (https://github.com/phetsims/ratio-and-proportion/issues/441).

I really appreciate all the comments outlining all the changes. I did them, and then went through all three sections in the design document to confirm the behavior was as expected. The only change in common code was saying that AccordionBox doesn't every say its hint when getting expanded or collapsed, which feels pretty reasonable to me. Let me know how this all sounds.

**Comment by zepumph** [comment]
From https://github.com/phetsims/ratio-and-proportion/issues/441#issuecomment-1071470294

>Use PDOM responses for all input.

In https://github.com/phetsims/ratio-and-proportion/issues/283 we ended up writing out words for the aria-valuetext because of a screen reader bug. As a result, and for consistency, I am using the same function for the voicing object and context responses. Do you mind having the values as words instead of actual numbers here?

**Comment by terracoda** [comment]
Ok, the number spinners sound great and the reading block sounds great.

My Challenge and related interactive things all voice nicely with pointer and focus-based inputs. Just checking touch device now.
