### ISSUE TITLE
Record all the constants and query parameter values for PhET-iO

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#382]
Today a designer requested that "threshold" values in this sim, of which there are many, would be able to be recorded so that when you look at the data stream, you would know what these constant values were. 

@samreid, is there any precedent for instrumenting constants or something like that?

Noting the request from https://github.com/phetsims/ratio-and-proportion/issues/142j

**Comment by samreid** [comment]
We do not have an established pattern for that, but I will brainstorm some ideas:

1. The constant could be made to be part of a `phetioState: true` stateful object, so that it outputs its value on startup
2. The constant could be promoted to a stateful `Property` instance which remains constant.

**Comment by zepumph** [comment]
With this patch, I can get this event in the data stream, which is enough for our purposes. Could you please advise potential improvements though? Why does this need to be in the model. That seems weird.

```
{
  "index": 289,
  "time": 1619810682729,
  "type": "model",
  "phetioID": "phetioEngine.phetioElementAddedEmitter",
  "name": "emitted",
  "componentType": "EmitterIO<StringIO, ObjectLiteralIO, NullableIO<ObjectLiteralIO>>",
  "data": {
    "phetioID": "ratioAndProportion.createScreen.model.RAPConstants",
    "metadata": {
      "phetioTypeName": "RAPConstantsIO",
      "phetioDocumentation": "",
      "phetioState": true,
      "phetioReadOnly": false,
      "phetioEventType": "MODEL",
      "phetioHighFrequency": false,
      "phetioPlayback": false,
      "phetioStudioControl": true,
      "phetioDynamicElement": false,
      "phetioIsArchetype": false,
      "phetioFeatured": false,
      "phetioDesigned": false
    },
    "state": {
      "SCREEN_VIEW_X_MARGIN": 15,
      "SCREEN_VIEW_Y_MARGIN": 15,
      "RATIO_FITNESS_RANGE": {
        "_min": 0,
        "_max": 1
      },
      "IN_PROPORTION_FITNESS_THRESHOLD": 0.025,
      "MOVING_IN_PROPORTION_FITNESS_THRESHOLD": 0.3,
      "SHIFT_KEY_MULTIPLIER": 0.2,
      "TOTAL_RATIO_TERM_VALUE_RANGE": {
        "_min": 0,
        "_max": 1
      },
      "NO_SUCCESS_VALUE_THRESHOLD": 0.01
    }
  }
}
```

**Comment by samreid** [comment]
Can you please include the patch, so I can see the context?

**Comment by zepumph** [comment]
Sorry, I edited the first comment to include the patch.

**Comment by samreid** [comment]
What you have written seems reasonable, but would it be an improvement to make RAPConstants a class with a singleton instance, and `RAPConstants extends PhetioObject` and use `ObjectLiteralIO` IO Type?

**Comment by zepumph** [comment]
Good idea

>ObjectLiteralIO IO Type?

It isn't technically possible because there is an extra prototype on the Object instance, so we can't use that. I created a new IOType, though that is a bit of a bummer. Perhaps we should change ObjectLiteralIO's signature to support this case?

Please review the commit.

**Comment by samreid** [comment]
The commit looks great, I don't have any further recommendations for this issue.  Closing.
