### ISSUE TITLE
[Voicing] implement resetAllButton

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#383]
I see JT has its own VoicingResetAllButton in the preferences branch currently. I asked @jessegreenberg if it was close to getting moved into ResetAllButton, and he said close but not quite yet. 

@jessegreenberg will you please assign this issue to me when things are ready to go so I can test/implement the pattern in this sim.

**Comment by terracoda** [comment]
I think this issue is stale. We have a voicing design for the reset all button that was published with John Travoltage and is used in other sims, too, e.g. GFLB.

I think this issue should be safe to close.
