### ISSUE TITLE
[Voicing] implement TickMarkRadioButtonGroup

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#384]
From https://github.com/phetsims/ratio-and-proportion/issues/363

**Comment by zepumph** [comment]
Activation supported above, with a refactor of the `switch. . . case` for interactive description alerts.

**Comment by zepumph** [comment]
Much of this work was done in https://github.com/phetsims/sun/issues/699.

Currently in the preferences branch in sun has commits to RectangularRadioButtonGroup that work well for focus and keyboard interaction, but don't give the object response for mouse/touch. Marking for a11y dev meeting to discuss with @jessegreenberg tomorrow.

**Comment by terracoda** [comment]
@zepumph, this issue might be stale. I didn't open it. TickMarkRadioGroup is ready from a design perspective, when you are ready to implement.

**Comment by zepumph** [comment]
I got something working in master for this, but I'm pretty sure we will want to use this chance to update common code over in https://github.com/phetsims/sun/issues/699.

**Comment by zepumph** [comment]
Don't forget about on-focus, we need more than just listening to the Property changing.

**Comment by zepumph** [comment]
Ok, I have added this to common code, and removed the custom implementation in TickMarkRadioButtonGroup. @terracoda please review after a thorough cleaning of the cache (I will pull all on phettest)

**Comment by terracoda** [comment]
The Tick Marks radio button responses sound great. Closing.
