### ISSUE TITLE
Launching from studio does not work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#385]
For https://github.com/phetsims/QA/issues/647. Win 10 Chrome. 
When in studio, if you launch the sim, the resulting sim freezes on the home screen and creates several issues in the console. If you launch without entering the sim, trying to enter the resulting launched sim will then create the freezed behavior.
<img width="960" alt="can't preview" src="https://user-images.githubusercontent.com/41024075/116937966-45390980-ac27-11eb-95e0-06e6eb4b4987.png">

**Comment by zepumph** [comment]
Good catch! Thanks.

**Comment by zepumph** [comment]
This is just a general problem with setting state. I'm not sure I had gotten to state just yet, as we are only supporting recording at this time. I'll keep you posted on priority of this.

**Comment by KatieWoe** [comment]
Yup, confirming this is a problem in the state wrapper too.

**Comment by zepumph** [comment]
The problem was that my fromStateObject was on the prototype, and not a static. I'm a bit embarrassed by how long this took me to debug. As a result I added an assertion in IOType.fromCoreType.

@samreid let me know if you can foresee trouble with that assertion.

**Comment by zepumph** [comment]
Cherry picked into 1.1 (for the study this week). Closing

**Comment by samreid** [comment]
The assertion looks correct to me, and unlikely to yield any false positivise.
