### ISSUE TITLE
Recording does not capture keyboard nav on home screen

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#387]
For https://github.com/phetsims/QA/issues/647. Seen on Win 10 Firefox with NVDA, but looking at the mirror wrapper, it seems to be tied to keyboard nav.

In attempting to enter the second screen from the home screen, the playback of the recording never shows the user leaving the home screen. On the mirror wrapper, focus doesn't seem to show up, making testing this fully there difficult, but it does seem to be the cause. On playback, keyboard focus (the pink outline) does not seem to show up, even when the effect does.

**Comment by zepumph** [comment]
Likely a subset of https://github.com/phetsims/phet-io/issues/1748

**Comment by zepumph** [comment]
The recording events is working, it is just how the playback engine works. On hold until https://github.com/phetsims/phet-io/issues/1748 is sorted out.

**Comment by zepumph** [comment]
This is fixed in master. Confirmed in the input-record-and-playback wrapper. Closing
