### ISSUE TITLE
(PDOM) Remove captitalization on "Challenge Ratio" in body of state descriptions

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#391]
Please change "Challenge Ratio" to "challenge ratio" when "Challenge Ratio" appears on body-like state descriptions in paragraphs and lists.

Heading, label, and option elements can keep capitalization.

Not sure if this is straight forward or not. If not, we should keep the capitalization in the Voicing strings. In my voicing design document I have removed all the capitalization.

**Comment by zepumph** [comment]
I believe this is pretty much done. The only two I had questions about are these two:

>With Both Hands activated, use W and S keys to move left hand, and Up and Down Arrow keys to move right hand. Move both hands at the same time to find and maintain the Challenge Ratio.

>Move hands up and down individually to find the Challenge Ratio in different places.

Would you like these usages capitalized or not?

**Comment by terracoda** [comment]
Yep, go ahead and change these two instances to "challenge ratio".

Apologies for coming to this issue so late.
