### ISSUE TITLE
(PDOM) Tick Mark Options - remove "to Play Area" from context responses

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#392]
As suggested in the design document in the [Tick Mark Options section](https://docs.google.com/document/d/1offJbONUg8y5Aa9kHewC9iTDtNISzna4giGt7WrpXCk/edit#heading=h.d3xfbu80tqt1), I'd like to try the removing "at Play Area" from the context response:

- Evenly-spaced numbered lines added to Play Area.
- Evenly-spaced horizontal lines added to Play Area.

The "Play Area" and "Control Area" sections are not explicitly defined and accessible in the Voicing experience, so I'd like to try removing these references from the Interactive Description design. 

If the removal causes confusion for non-visual access in Interactive Description, we'll need custom context responses for the Voicing design. I'd like to avoid custom Voicing responses where possible.

**Comment by terracoda** [comment]
New context responses will be:
- Evenly-spaced numbered lines added.
- Evenly-spaced horizontal lines added.

**Comment by zepumph** [comment]
Done above
