### ISSUE TITLE
(Visual Change) Change all labels (visual & description) from "Lock Ratio" to "Ratio Lock"

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#395]
Having a verb in a checkbox label can be challenging, especially when considering all inputs in the Vocing design.

As mentioned in the Voicing design doc, we think changing the visual label to “Ratio Lock” will allow us to avoid having two name responses that reflect the checked and unchecked states of the checkbox, and allow us to rely on the context responses to communicate the state changes. 

Additionally, this change allows to follow the same design pattern as we did with the GFLB checkboxes (i.e. no object responses).

Rouch visuals are also in the Voicing Design doc.
![Screen Shot 2021-09-10 at 10 58 59 AM](https://user-images.githubusercontent.com/1902116/134938958-5e9905e7-6881-4ffb-bfa7-475efcfaa08e.png)

**Comment by zepumph** [comment]
There was only one spot in description/visual-text where it needed to change, but many variables were renamed also to keep things in sync.

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/141580796-9b5080df-858d-4f0a-951f-c3c390b534cf.png)
