### ISSUE TITLE
(Description) Inconsistent sound feedback when using 0-9 shortcut keys

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#397]
If I set the ratio to essentially 1:1 and then use the hot keys 1-9, I only get the at ratio chime on the first ratio change I make. The screen remains green through out use of number key shortcuts.

After going to zero and then to a 1:1, I will again get the at ratio chime on the first ratio hit, but not subsequent ones.

Using Chrome on MacOs 11.4

I can't remember if this was intentional or if it is an oversight/bug?

**Comment by terracoda** [comment]
Oh, if I press the number keys fast (1, 2, 3, etc.), I sometimes get the proportion choir sound, but not all the time.

**Comment by terracoda** [comment]
With ratio locked, I get the proportion chime every time when using the shortcut keys, but only some times if ratio is not locked.

**Comment by BLFiedler** [comment]
I recall having a conversation about this, though not exactly the resolution. I believe we concluded in some of the more recent discussions prior to publication that the shortcut was not actually intended to be used for the exploring the ratio. If so, we'd also want it to give feedback as you pass the target ratio, which I don't believe happens?

@zepumph, do you know if this is designed behavior for the lock ratio scenario or a coincidental behavior?

**Comment by zepumph** [comment]
The behavior as it is seems just great to me. Indeed it is a bit easier to hear the "choir" sound when the ratio is locked. This is because if the ratio is locked, it bypasses a "moving fast enough" threshold in the model (note the comment):

https://github.com/phetsims/ratio-and-proportion/blob/31e449177761b443d816fcd248b0154dd8792c23/js/common/model/RAPRatio.ts#L98-L99


Ready to close?

**Comment by terracoda** [comment]
I don't hear the chime any more when going lowest point to position with the hot keys. All moves with hot keys sound good to me.
