### ISSUE TITLE
(Description) Change help text for Ratio Lock checkbox 

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#398]
Related to #395. 

**Change help text for Ratio Lock checkbox from:**
- Enabled when hands are at challenge ratio. Move hands as a single unit to maintain my challenge ratio.

**To:**
- Enabled when hands are at challenge ratio. Move hands as a single unit with ratio locked.

And since the Voicing hints use word for word the first and second halves of the help text, 
- Move hands as a single unit with ratio locked. (when checkbox is enabled)
- Enabled when hands are at challenge ratio. (when checkbox is disabled)

Does it make sense to make the paragraph in the PDOM into 2 separate strings, but still occurring within the same paragraph and on the same continue line.

The change in wording improves the help text in description and aligns the each piece of the help text to hints we need in Voicing. 

Note that if it is easy to keep the 2 sentences as separate strings, we can consider making the help text dynamic in the interactive description (pdom), but only if there is time.

Edited to include both the Voicing hints used for the two states of the checkbox.

**Comment by zepumph** [comment]
Great idea @terracoda. I have not gotten to voicing yet, but I've updated the helpText depending on the checkbox enabled.  Please review.

**Comment by terracoda** [comment]
Great. Love it.

**Comment by terracoda** [comment]
Note that the disabled Ratio Lock checkbox won't get the hint response until disabled controls can be voiced.
