### ISSUE TITLE
(Description & Voicing) Change initial interaction hint on Discover Screen

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#399]
As noted in the Voicing design doc, please change the interaction from
- Move hands to find the Challenge Ratio in different places.

To:
- Move hands up and down to explore and discover different challenges.

The content for the Play Hint button hint for Voicing is not yet implemented. With this change, the two hints will use the same content.

**Comment by zepumph** [comment]
Alright, the change has been made. I also just went ahead and implemented the hint read me button for both screens based on what you said. (since I was here). Please review.

**Comment by terracoda** [comment]
Awesome. Closing.
