### ISSUE TITLE
Cursors slightly off ratio (1.0.0-dev.16)

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#40]
Switched to crosshairs for precision, but the ratio seems to be off relative to the grid in this version (1.0.0-dev.16) Image below shows left crosshair right on 4, but right crosshair above 8 to achieve "perfect" ratio.

![image](https://user-images.githubusercontent.com/47331395/81093321-2b9f9d80-8ebf-11ea-8f14-d28236dc9916.png)

**Comment by zepumph** [comment]
Great catch! Sorry about that. Anything else here?

**Comment by BLFiedler** [comment]
Nope! Thanks!
