### ISSUE TITLE
(New) For both Description & Voicing create a scale for green-ness

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#400]
As documented in the Voicing design document, we need a qualitative scale to describe the greenness of the screen. The greenness-scale follows the described proximity to ratio regions the same as the sonification does.

**Table: Greenness & Described Proximity to Ratio**
Proximity to Ratio 8-point scale | challenge ratio | Notes on timing sonification 5-point scale | Ideas for voicing design 5-point scale
-- | -- | -- | --
extremely far from | challenge ratio | White & no sonification | “not green” or “white”?
very far from | “ | White & no sonification | not green
far from | “ | White & no sonification | not green
not so close to | “ | White & no sonification | not green
somewhat close to | “ | Green-ness & sonification starts in this region. | lightest green
very close to | “ | Darker green & faster sonification | very light  green
extremely close to | “ | Darker green & faster sonification | light green
at | “ | Darkest green & proportion chime | darkest green

I suggest we start with "not green" rather than "white".

**Comment by zepumph** [comment]
Regions were added above but the only usage is for https://github.com/phetsims/ratio-and-proportion/issues/411. @terracoda, do you want this in the create screen at all?

**Comment by terracoda** [comment]
@zepumph, yes we need the green-ness scale implemented for both screens in the state descriptions. There is no mention of the screen being green in responsive descriptions.

The full dynamic nature of the scale may not be fully implemented yet, so apologies if this is on your radar. I did notice that the screen summary details section was not in synch with what was happening with the hand sliders. See screenshot and notice that the hands are being described as "at the challenge 1 ratio", but they are not at the challenge ratio. 
![rap-secene-summary-issue](https://user-images.githubusercontent.com/1902116/142639711-9423249e-ba23-4b80-8210-3cbfbf20f21a.png)

**Comment by zepumph** [comment]
Sorry about that. I missed the ratio fitness as a dynamic piece of that. I also updates the create create and simplified some of the screen summary by having both screens share that sentence. 

The above commits cover https://github.com/phetsims/ratio-and-proportion/issues/411#issuecomment-974117159 and https://github.com/phetsims/ratio-and-proportion/issues/400#issuecomment-974124988.

**Comment by zepumph** [comment]
Alright, please review.

**Comment by terracoda** [comment]
Descriptions all look good now! Thanks.
Closing this issue. 

We might need to adjust the shade of the lightest green of the lightest green region, the edge the "some what close to ratio" region. It looks pretty white, but this detail is a new issue. I'll demo at today's voicing meeting and post an issue if needed.
