### ISSUE TITLE
typescript convention questions

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#405]
While working on https://github.com/phetsims/ratio-and-proportion/issues/404, I would like to keep track of questions I have about how we want to codify things in this new language. Most will probably be dumb questions, since I don't know the language very well.

- [x] Should we ever mark a field as `public`, isn't that redundant to the default?
- [x] How to support Enumeration values?
- [x] Exporting sub components like `export { .... }` (like an associated `*Type` or something, like TickMarkView.ts
- [x] My auto imports for typescript don't end in `*.js`. I have to add them manually or suffer the lint rule.
- [x] LinearFunction doesn't seem to fit well with Typescript, and I couldn't figure out how to annotate it with jsdoc
- [x] All ParallelDOM propeties and methods need to be ts-ignored at this time.
- [ ] Private in typescript is more strict that we are used to. In general, we called "private" as private to that file, but typescript won't allow accessing private things from helper functions in the same file (RatioHalf's accessibleNameBehavior)
- [ ] Readonly is also more strict. We normally put `@public (read-only)` to describe how others should access this, but could still mutate it internally. Typescript does not allow that AFAIK. You can use IReadonlyProperty, but you can't set it internally in that case.
- [x] ColorDef is going to need some typescript work. . . 
- [x] Orientation enum needs help
- [x] sceneryPhetStrings seems impassable, not sure how to type cast it even as "any"
- [ ] Nothing, semi colon, or comma in type declarations?
- [x] Naming around options and config, why do we need to name things like that, can it all be options now because typescript tells us what is required.
- [x] I am finding quite a few places that have to do with https://github.com/phetsims/chipper/issues/1128#issuecomment-950395105, and since the "middle" type is common code, but I only need to pass up Node options, I am just marking the options object as `NodeOptions`. This works in my cases, but would make refactoring harder if we want to pass up an option supported/defined in the "middle" type. The example I just found was marking `NodeOptions` in `BothHandsHelpSection`, but I really just want to support NodeOptions.
- [x] Documentation that was in constructor definition of property should likely be moved to where field is defined in class?
- [x] Documentation for options should likely be moved out of optionize call and into where type defines the Options?
- [x] IModel interface where we can have a declaration of its api, for example, the `step` function, is that all it has?

>Consider using explicit annotations for object literals and function return types even when they can be inferred.

- [x] Is that true even for getters and setters?

**Comment by samreid** [comment]
I noted some of these parts in https://github.com/phetsims/phet-info/blob/master/doc/typescript-conventions.md

**Comment by zepumph** [comment]
I marked the remaining items here for dev meeting discussion thursday.

**Comment by zepumph** [comment]
Here is the discussion from the dev meeting agenda on March 3:

>MK: Typescript convention questions that we didn’t get to Monday, from https://github.com/phetsims/ratio-and-proportion/issues/405#issue-1030691824. What have devs been doing when encountering these cases during conversions?
 `private` in typescript is more strict than we are used to. In general, we called "private" as private to that file, but typescript won't allow accessing private things from helper functions in the same file (RatioHalf's accessibleNameBehavior)
JB: Does it work to create a static function?
SR: (tried it, said it does in this case)
MK: I’ll write it up!
-Readonly is also more strict. We normally put `@public (read-only)` to describe how others should access this, but could still mutate it internally. Typescript does not allow that AFAIK. You can use IReadOnlyProperty, but you can't set it internally in that case.
Also, readonly is often useless, since it doesn’t prevent mutating an instance member. Should we always provide it, because it is technically true for every Property, or Node member. I get this recommendation from Webstorm: “Field can be readonly”.
SR: Attributes should be marked as readonly if they are readonly
MK: CK recommended Subitizer.isPlayButtonVisibleProperty
We 
 Nothing, semi colon, or comma in type declarations?
MK: I always use semi colons. Slight preference to be consistent across the project, but only slightly.
SR: That is our written convention, can it be enforced with TSLint?
JG: Yes, [@typescript-eslint has that](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/member-delimiter-style.md)

I think all is done here.
