### ISSUE TITLE
query parameter to show position regions

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#409]
Like we did in GFL and BASE

This is just the general regions when there are no tick marks.

**Comment by zepumph** [comment]
@terracoda please review by adding `?showRegions` to a version of RAP.


It looks like:

![image](https://user-images.githubusercontent.com/6856943/141211603-87eb86d0-146c-4e21-b9d6-044e29626f8a.png)

**Comment by zepumph** [comment]
You can use https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.1/phet/ratio-and-proportion_all_phet.html?showRegions.

**Comment by terracoda** [comment]
Looks good. This should work for me. 

Just one fix... I think "at middle" is a single value region, so the line should probably go through the middle of the words like "at top" and "at bottom".

**Comment by terracoda** [comment]
I'll assign back as soon as I determine the new region ranges.

**Comment by zepumph** [comment]
Oh no! I just realized that I input the incorrect values for the ranges, I used the distance ranges instead of the position ones. One fix coming in up.

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/141374875-1891f536-0d5c-4633-ac77-0a95cc1a40ed.png)

**Comment by zepumph** [comment]
@terracoda I'm so terribly sorry for wasting your time. Please re-review.

**Comment by terracoda** [comment]
From the screenshot it does not look like "at middle" or "at top" are single-value regions.

**Comment by zepumph** [comment]
Maybe more like this?

![Uploading image.png…]()

**Comment by terracoda** [comment]
Ok, I think you got the original PDOM regions now! That's nice!
It might be better to call the query parameter "showVoicingRegions" instead or have two parameters, though I think I only need one for Voicing. I don't want to change the regions for Interactive description.

I am wondering for Voicing if we can change the ranges for the 3 main regions around the middle to eliminate the dashed regions, "in upper-middle region" and "in lower-middle" region.

I worked the following regions out in a a table in the design doc:
**[Voicing Regions - Version 2](https://docs.google.com/document/d/1offJbONUg8y5Aa9kHewC9iTDtNISzna4giGt7WrpXCk/edit#heading=h.fgrk6sz74qoj)**
= 10 {{at top}}
9.00 - 9.99 {{near top}}
6.01 - 8.99 {{in upper region}}
5.01 - 6.00{{in middle region}}
= 5.0 {{at middle}}
4.00 - 4.99 {{in middle region}}
1.01 - 3.99 {{in lower region}}
0.01 - 1.00 {{near bottom}}
= 0 {{at bottom}}

**Comment by zepumph** [comment]
>It might be better to call the query parameter "showVoicingRegions" instead or have two parameters, though I think I only need one for Voicing. I don't want to change the regions for Interactive description.

I am wondering for Voicing if we can change the ranges for the 3 main regions around the middle to eliminate the dashed regions, "in upper-middle region" and "in lower-middle" region.

Over in https://github.com/phetsims/ratio-and-proportion/issues/433 it is very unclear if we are actually going to go through with this work. If we do, it will happen in that issue, and we can consider how it will effect this query parameter there.

I did rename it to showPositionRegions though; it was something I was wanting to do for quite a while.

After https://github.com/phetsims/ratio-and-proportion/issues/437 this is what the position regions layer now looks like:
![image](https://user-images.githubusercontent.com/6856943/156422496-8c4ce49c-6137-4d8f-9bb6-cd660f6e3b53.png)



@terracoda, is there anything else for this issue?

**Comment by terracoda** [comment]
I don't think so. I don't think we will change the regions after all, except the change we already made around the middle, ... and now that I re-look at my table, I think I may have been trying to address that edge case with the simplified regions.

Anyways, changing the regions the least amount as possible is good in the long run.

**Comment by terracoda** [comment]
Closing.
