### ISSUE TITLE
Selection box of some kind appears in the upper left corner on iPad

### ISSUE THREAD

**Issue by jbphet** [phetsims/ratio-and-proportion#41]
In the two interviews that I've watched and during my own interaction with the sim on iPad, there is a blue selection box that pops up in the upper left everyone once in a while when the user is interacting.  You can see the user get distracted by it around time index 1:58 in [this video of an interview](https://drive.google.com/file/d/1ZZVVXQOjLlKMd1Y_39ZWNc2CwQokKJ5I/view).  It shows up again around 3:02 and at several other times.

**Comment by jbphet** [comment]
Assigning to @zepumph, since he's the responsible dev.

Also - @KatieWoe - we saw this when you and I were looking at the sound design behavior on this sim yesterday, and you seemed to have some idea of what it was.  I think you may have even had a term for it.  If you have any insights to add, please do.

**Comment by KatieWoe** [comment]
Found the previous issue of this happening here: https://github.com/phetsims/scenery/issues/1006

**Comment by BLFiedler** [comment]
This is actually addressed in #39 . I confirmed it was fixed in dev.17, but if you'd like to confirm @jbphet : https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.17/phet/ratio-and-proportion_en_phet.html

**Comment by jbphet** [comment]
Sounds good.  I messed around with it on the "Pauling" iPad using the master version and was unable to get the rectangle to appear, so as far as I can tell it is indeed fixed.  Thanks, closing.
