### ISSUE TITLE
Factor out common screen summary code?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#412]

**Comment by terracoda** [comment]
@zepumph, except for the mentioning of the "Play Area" and "Control Area" in the static part of the summary, I think I already factored out the differences between the full screen summary and the the content delivered through the 3 read-me buttons.

I am pretty sure that only the content for the "Play Overview" button differs from the Interactive Description design.

At least, that is what I was aiming for :-)

**Comment by zepumph** [comment]
Yes I couldn't agree more. That nice design is perfect, but in the code, we are duplicating the two implementations almost completely in DiscoverScreenSummaryNode and CreateScreenSummaryNode. 

Upon further reflection though. . . yes there is duplication in the way that the summaries are set up, but it is a fine line between factoring things out, and just complicating the pattern by obfuscating code into a super type. I think I would prefer to leave them as is. I'm going to close this.
