### ISSUE TITLE
(Visual Change) Add lock icon to Ratio Lock checkbox

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#414]
We would like to add a visual dynamic lock icon to the Ratio Lock, check box.
For the first pass, I'd like to try having the lock next to the visual checkbox and keep the visual text label, too.

So, kind of like this:
![ratio-lock](https://user-images.githubusercontent.com/1902116/143586719-0a6a0777-b0ef-465b-aefa-130c794cca22.png)
![ratio-lock](https://user-images.githubusercontent.com/1902116/143586881-e1f456cd-1532-4e68-b209-890eb27873e7.png)

I took the icon from Equality Explorer.
![image](https://user-images.githubusercontent.com/1902116/143584417-82bb703d-02cb-41cd-98a6-64d74e85f4d2.png)

It would be nice in the future to be able to explore having an interactive lock in between the base of the columns for the hands, but we likely do not have time to explore that big of a change right now. So instead, we can proceed with the "first pass" described above.
![ratio-lock-between-the-hands](https://user-images.githubusercontent.com/1902116/143587457-1d9fe5c9-96a1-457d-97dd-519acb5bc761.png)

**Comment by terracoda** [comment]
@zepumph, in terms of priority, if this is relatively simple to add to the visual design without making changes to the PDOM or any descriptions, please add it in after you have implemented voicing for the indy-hand interactions.

If this complicates things, let's lower the priority to "low".

**Comment by zepumph** [comment]
Could you add a mockup of what you are thinking when the numbered tick marks are present? They look like they will overlap in the current state:

![Uploading image.png…]()

**Comment by terracoda** [comment]
Hmm, good point. 
![image](https://user-images.githubusercontent.com/1902116/144509388-6ce4ad14-c513-4e3e-80f3-f46bcd0f75d0.png)
![image](https://user-images.githubusercontent.com/1902116/144509446-f882b5d0-e6f6-4011-ac51-8dc2b184fee5.png)

**Comment by terracoda** [comment]
The problem with the icon outside of the checkbox label is that people will try and click on it. If we keep the visual checkbox, the icon needs to be part of the checkbox label.

I would prefer to keep the visual checkbox, and just add the icon to the label of the checkbox, is that possible?

**Comment by zepumph** [comment]
I made https://github.com/phetsims/equality-explorer/issues/182 to progress the move so we can use the same (currently sim-specific) icon

**Comment by pixelzoom** [comment]
Noted while working on https://github.com/phetsims/equality-explorer/issues/182 ...

The mockups for this look like:
![ratio-lock](https://user-images.githubusercontent.com/1902116/143586719-0a6a0777-b0ef-465b-aefa-130c794cca22.png)
![ratio-lock](https://user-images.githubusercontent.com/1902116/143586881-e1f456cd-1532-4e68-b209-890eb27873e7.png)

I don't know if the placement of the icons is intentional/required. But PhET sims typically put the icon to the right of the text.

**Comment by zepumph** [comment]
@terracoda and I agree. We will put it on the right side of the label.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/equality-explorer/issues/182, I factored out LockNode, which now lives in scenery-phet.

Here's how you'd use it to create the Checkbox for this sim:

```js
const ratioLockProperty = new BooleanProperty( true );
const content = new HBox( {
  spacing: 8,
  children: [
    new Text( 'Ratio Lock', { font: new PhetFont( 18 ) } ),
    new LockNode( ratioLockProperty, { scale: 0.5 } )
  ]
} );
const ratioLockCheckbox = new Checkbox( content, ratioLockProperty );
```

Here are what the 2 states look like. These match the mockups in https://github.com/phetsims/ratio-and-proportion/issues/414#issue-1064477105, but with the icons to the right of the text:

<img width="185" alt="screenshot_1443" src="https://user-images.githubusercontent.com/3046552/144666662-55267d37-ccb7-426e-9eb9-77e33d55e24c.png">
<img width="182" alt="screenshot_1444" src="https://user-images.githubusercontent.com/3046552/144666675-02180017-ff8d-4337-a8f7-20ff1618a01a.png">

**Comment by zepumph** [comment]
Implemented a first pass above. @terracoda, what do you think?

**Comment by terracoda** [comment]
The visual lock looks great. Thanks @zepumph and thanks to @pixelzoom, too.

**Comment by terracoda** [comment]
We won't explore other visual design changes for the Ratio Lock check box for the next release of this sim.
