### ISSUE TITLE
DragListener end drag utterance should not interrupt onchange?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#422]
From https://github.com/phetsims/ratio-and-proportion/issues/419, @terracoda said:

>Just noting that at the end of drag, i.e., the release of a hand, the interruption sometimes is less than ideal. This also happens in GFLB, so any improvement or solution here will be a general one. No action required at this time, just something to think about, in general for Voicing and sliders.

This would most likely be an easy fix, but I would want to try it out in an isolated issue (+ isolated testing) to make sure it is as we want it to me. Something to do a bit later, once the initial implementation is set.

**Comment by zepumph** [comment]
Current behavior: the response during drag and the response at the end of a drag are both powered by the same Utterance, so they interrupt each other.

Desired behavior (as I understand it):
* While dragging, each new description would still interrupt the previous one, to have the most up-to-date info while dragging
* When you let go, the end drag response doesn't interrupt the drag response currently being spoken. Instead, it will be spoken afterwards.

`@terracoda, now that #413 is closed out, can you comment on this issue. I personally don't see this change as an obvious improvement. There are many cases where the drag info would be out of date (wouldn't state it is in proportion, doesn't account for snapping behavior, etc). Do you still want me to implement this?

**Comment by terracoda** [comment]
You are absolutely correct, we can still have things out of date, and this solution might preserve the issue described in #439, rather than improve the experience.

Marking this on hold.

**Comment by zepumph** [comment]
This seems less than ideal because we don't want out of date information (from the remainder of the drag response). Closing
