### ISSUE TITLE
Object response needs to be always updated so it is correct on focus

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#425]
From https://github.com/phetsims/ratio-and-proportion/issues/419#issuecomment-1024415606. Just like with ariaValueTet in AccessibleValueHandler, we should always update the object reponse whenever the valueProperty or a11y dependencies change:

Here:

https://github.com/phetsims/sun/blob/877f09991f4ae29029c2a7c8215d814318b6a91d/js/accessibility/AccessibleValueHandler.ts#L433

**Comment by zepumph** [comment]
Alright, fixed above. @terracoda please review. Anything else here?

**Comment by terracoda** [comment]
The object responses are updating. The keyboard arrow icons are still present after movement, but that will be part of a different issue.

And I am not hearing the chime when using keyboard. You made an issue for that.

Closing this issue.
