### ISSUE TITLE
Add Voicing to Challenge ComboBox

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#428]
From https://github.com/phetsims/ratio-and-proportion/issues/363

**Comment by zepumph** [comment]
Some good progress in https://github.com/phetsims/sun/issues/726, but we aren't done yet.

**Comment by zepumph** [comment]
Alright, both combo boxes in RAP are now implemented, please review this as you review the common code in https://github.com/phetsims/sun/issues/726 (or after.

**Comment by terracoda** [comment]
The Challenge Combobox one sounds right, but the Range combobox does not.
Still reviewing. Not sure if it is my documentation or the implementation.

**Comment by terracoda** [comment]
Ok, I've made notes in the design doc that we can discuss.

I don't like hearing "Range" when arrowing through items as this part of the name response.
Maybe learners do not hear options read out if object responses is not checked.

**Comment by zepumph** [comment]
From https://github.com/phetsims/sun/issues/726#issuecomment-1048338444, @terracoda said:

>I haven't checked Molarity, but the comboboxes in RaP are good to go.

I'm going to take that this is good to close then.

**Comment by terracoda** [comment]
I got confused between the RaP issue and the sun issue.
