### ISSUE TITLE
Always want postion region when hands are at challenge ratio

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#429]
When testing latest version on phettest, I realized I missed an edge case with pointer input. I can actually hit the challenge ratio and not lift my finger (I can keep my mouse clicked)

The logic for pointer input (mouse and touch) is that during drag, we only get distance-progress in the context responses. 
And then at end of drag, we get distance-region in the context response.

We also **always** want distance-region in context response when at challenge ratio, regardless if the drag is active or has ended.

**Example responses during active dragging:**
- hands, extremely close to challenge ratio, Closer to right hand, in lower region.
- hands, very close to challenge ratio, Farther from left hand, in upper-middle region.
- _hands, at challenge ratio, Not so close to right hand, at middle._

**Example responses for end of drag:**
- ‪hands, extremely far from challenge ratio, Extremely far from right hand, near bottom.
- hands, at challenge ratio, Not so close to right hand, at middle.

I am hearing distance-progress in the italicized example above when I should get distance-region.

**Comment by zepumph** [comment]
Alright. This has been implemented. Please review. At this point, the individual hands have been fully implemented. Let me know if anything more is needed here.

**Comment by terracoda** [comment]
@zepumph, I think the position string is fixed. 

I experienced one weird thing - the hands not moving when I was hitting the arrow keys, but I can't reproduce. I think it was a temporary glitch. I just did a lot of hammering on the arrow keys, on the tab key, and with the mouse and I cannot reproduce. Just noting the weirdness for the record.

Since position is fixed, I am closing issue.
