### ISSUE TITLE
Is any Voicing possible for the disabled Range Combobox?

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#435]
Currently there is no name response on focus of the disabled Range Combobox.
<img width="212" alt="image" src="https://user-images.githubusercontent.com/1902116/155555980-6689d6e0-da07-44d7-99ee-67e4915512b6.png">

There is likely an open scenery issue for this https://github.com/phetsims/scenery/issues/1220

While at the moment we cannot click/tap on the disabled combobox and get any response voiced, I thought since the element lives in the PDOM for Alt Input and Interactive Description, it might be possible to get a response on keyboard focus. If this is possible, **it would be good to voice the Name Response & Hint Response, if hints are checked in preferences**.

I think disabled comboboxes are quite common in PhET Sims, so it would be nice to find a robust pattern for this situation.

**Comment by zepumph** [comment]
I would consider this a duplicate issue to https://github.com/phetsims/ratio-and-proportion/issues/396, which is a deferred issue. Feel free to close or mark accordingly.

**Comment by terracoda** [comment]
Closing this issue as it is a duplicate of #396
