### ISSUE TITLE
Tick mark sounds broken?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#453]
I don't know this for sure, but while trying to add boundary sounds to MediaPipe input (https://github.com/phetsims/ratio-and-proportion/issues/431#issuecomment-1063347885), I found tickMark sounds weren't playing. I couldn't get them to play during mouse input either. I'll need to investigate.

**Comment by terracoda** [comment]
I noticed, I did not hear tick marks with hands ere locked at challenge ratio. That might be intentional. I need to check with @BLFiedler.

**Comment by zepumph** [comment]
That is intentional. We don't play when the ratio is locked, or when the staccato sounds play:

https://github.com/phetsims/ratio-and-proportion/blob/b29f54a9577b63910abcdc55095b1ac83b3838be/js/common/view/RAPScreenView.ts#L167-L168

**Comment by zepumph** [comment]
AhhH!  After some investigation, I realized that we put that under "extra sounds". It is working like a charm. Oops! I'm ready to close. Feel free to @terracoda once you read the above and feel good about it.

**Comment by terracoda** [comment]
If that is how it is supposed to work, great.
