### ISSUE TITLE
Add voicing to MediaPipe input

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#454]
From https://github.com/phetsims/ratio-and-proportion/issues/431, I will commit shortly, but basically this will need some further design.

What I will commit will mimic how the "both hands" responses are formatted in the BothHands interaction. So perhaps we will automatically get improvement here when we make improvements over in #432.

**Comment by terracoda** [comment]
Issues:
- There seems to be quite the lag in the Voicing.
     - Can we voice based on velocity (or timing logic) like we do for mouse? The problem I am finding is that it is even hard to not move my hands than it is to not move a mouse. 
- When each had is moving independently in either direction, I am thinking it must be very difficult to calculate distance-progress.
     - The way it work for mouse is to only get distance-progress during active drag, and then get distance-region at ratio and on end drag...but we don't have an end drag for this input method. 
  
@BLFiedler, this feature is going to be used for co-design, should we just try to address the timing and leave other ideas for co-design? Or should we try a couple of basic options that can be explored as part of co-design activities?

**Other issues:**
- When I use a single hand, the interface does not respond properly. Is there any access to the indy slider interactions with Media Pipe?
- I think it would be nice to have pick up and let go gesture. It would make the interaction more intentional. I think that would be desirable.

**Comment by terracoda** [comment]
@zepumph had a nice idea of having a silent moving gesture versus a regular voicing gesture - simply close thumb and pointer for silent mode (non-voicing mode), then open for voicing mode.

**Comment by terracoda** [comment]
We have a few places we can tweak in the chain of commands.
-  smoothing algorhythm
- modal property position - media pipe value
- timing of utterances

@zepumph is going to start with the simplest mouse voicing logic plus close finger gesture to get and end drag event and voice lates tratio/position.

**Comment by BLFiedler** [comment]
Thanks, @terracoda! I've prioritized the publication investigation first, but all of this would be great for a discussion with all of us (+EM)! The needs for non-visual access to handtracking control is definitely not there yet, but building a common sense library of gestures seems like a great use of MediaPipe that can extend outside of Ratio and Proportion! We'll have that meeting soon.

One question though, was the Voicing lagging for you or the entire sim? Was the hand tracking itself pretty timely with respect to your hand movements?

**Comment by terracoda** [comment]
The visual hands do not seem very lag. It seems quite responsive - very good, in fact. The Voicing is gets behind immediately and stays about 2 responses behind all the time.

**Comment by zepumph** [comment]
Good progress happened with this today. @marlitas and I were able to add in the definition for a new gesture that has both thumb/index fingers touching. We used that to turn of the voicing of the hands.

Some thoughts about the implementation:
* There is currently no "smoothing" or averaging. @marlitas and I brainstormed some ideas for this like averaging each finger's last few positions, averaging the distance, and removing "outliers" that may throw off the distance because the threshold for touching is pretty small.
* The threshold itself (distance the fingers are from each other) is currently `0.04` which is a bit confusing and arbitrary as this number doesn't account for the fact that x coordinate units are different from y units (unless your screen has the same width as height in pixels). Basically @marlitas and I found that `.05` detected the gesture with about 1cm of space when I was 3ft from my camera, and `.03` was demonstrating false negatives in which I was touching my fingers together when it said I wasn't from about 3ft also.



@BLFiedler @terracoda please review and let me know what you think!

**Comment by terracoda** [comment]
@terracoda to let @zepumph how the testing goes.

**Comment by terracoda** [comment]
I think we need to do some adjusting as the sim doesn't seem to voice consistently.

Two things that seem to happen regularly are:
- when keep the OK fingers, and move my hands the sim often stops talking.
- when I am using the OK fingers and I open my hands, the sim can silence the latest response mid sentence.

What I think we are going for is:
- with OK fingers and active movement, object responses & context responses with distance progress 
- with OK fingers and relatively no movement, object response & context response with distance region
- with hands open, finish out latest response, then stop voicing

**Questions**
What can we do when ratio is locked? It doesn't seem to work right now.
Can we make it recognize a single hand when the ratio is locked and use the same OK gesture to Voice and an open hand to not Voice?

**Comment by terracoda** [comment]
Media Pipe does not seem to work in Safari.

**Comment by terracoda** [comment]
@zepumph and I discussed mediaPipe implementation June 10, 2022

We want to try the following simplified implementation:
- With active open hands - while we think we might eventually want responses with distance progress, we will first just try with sonification
- When OK-fingers are activated, we will treat that like an end drag, and give the latest response distance-region. AND we will try not to interrupt the released response.
- When OK-fingers remain and the learner continues to actively move hands (with OK-fingers), we'll again have  sonification only.

**TO DO: Think outside the box** 
- what would be the ideal responses for this input, regardless of current model constraints?
- With so much simultaneous visual & sound information & embodied movement, @terracoda needs to think what is best fro this particular Voiced experience. It's not clear that the current solutions for mouse or keyboard work well with hand tracking

**Comment by zepumph** [comment]
Some notes one how to improve the relationship with voicing and mediaPipe from a conversation with @jessegreenberg:

```
/**
 * OK sign should be really gone before saying it is gone:
 * average
 * weighted average based on old it is
 *
 * average booleans with a threshold
 * average distance over time (delay in initial output/sharpness)
 */

/**
 * HOw to hear distance progress?
 *
 * keep track of some portion of the previous description and compare it to the new description before emitting it
 *
 */
```

**Comment by zepumph** [comment]
Ok. The main updates from the above commit is that now you will only hear distance_region (since we only are supporting the "end drag" case in media pipe at this time. And I improved the detection of the OK_GESTURE such that it behaves much less buggily. @terracoda it is worth a listen, when I am using the OK_GESTURE, even when I move it around, the voicing response currently speaking almost never get's interrupted. Let me know how it goes!


Up next is to work on a way to detect and speak the distance progress intermittently during the interaction (ideas in the above comment).

**Comment by terracoda** [comment]
In #476, I decided to freeze the hands & Voice their current state (according to checked preferences) with the OK-fingers gesture.

**Comment by terracoda** [comment]
I do not know how the design decision in #476 will affect other devices connected through bluetooth described in #478

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.
