### ISSUE TITLE
Indy Hands - Hear context response when I don't make a change

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#455]
When I have Tick Marks enabled, I hear the tick mark position of the indy hand when I click and do not make a change. This is not how the indy hands work when Tick Marks are hidden.

Please make them work the same when clicking, i.e., only provide a context response about position if the hands actually move.

The focus event is fine. I do not hear position when I put keyboard focus on an indy hand.

**Comment by zepumph** [comment]
I cannot reproduce this bug, I added logging to determine if the position was not being tracked correctly, but there is "no voicing" when expected, each time I click, and let go of the hand without moving.

Is it possible that you moved a miniscule amount when letting go? I'm also happy to try to reproduce together.


Here is just an example of the voicing output, it is a bit confusing on its own, but I just wanted to show you how "no voicing" doesn't have a context response after it.

```
Tick Marks, Evenly-spaced horizontal lines added.
Right Hand, hands, at challenge ratio, Move hands.
no voicing
Right Hand, hands, at challenge ratio, Move hands.
no voicing
has voicing
hands, far from challenge ratio, Not so close to left hand, almost on seventh tick mark.
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
Numbered Tick Marks, Evenly-spaced numbered lines added.
hands, far from challenge ratio, Closer to left hand, around tick mark 8.5.
has voicing
hands, far from challenge ratio, Far from left hand, almost on tick mark 8.5.
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
has voicing
hands, far from challenge ratio, Not so close to left hand, almost on tick mark 7.5.
no voicing
Right Hand, hands, far from challenge ratio, Move hands.
has voicing
hands, far from challenge ratio, Far from left hand, almost on tick mark 8.
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
hands, far from challenge ratio, Closer to left hand, around tick mark 6.5.
has voicing
hands, far from challenge ratio, Not so close to left hand, around tick mark 6.5.
Right Hand, hands, far from challenge ratio, Move hands.
no voicing
Right Hand, hands, far from challenge ratio, Move hands.
```

**Comment by terracoda** [comment]
I just did a fresh pull, and it does not appear to be happening any more.

**Comment by terracoda** [comment]
Maybe it was a glitch. Closing until it pops up again. Thanks for the investigation.
