### ISSUE TITLE
Bug? No distance progress in both-hands interaction when ratio locked

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#459]
This is item (3) in https://github.com/phetsims/ratio-and-proportion/issues/432#issuecomment-1087838546. Also from https://github.com/phetsims/ratio-and-proportion/issues/432#issuecomment-1087937650 and https://github.com/phetsims/ratio-and-proportion/issues/432#issuecomment-1087983092

I used this to debug:

<details>

```diff
Index: js/common/view/describers/HandPositionsDescriber.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/describers/HandPositionsDescriber.ts b/js/common/view/describers/HandPositionsDescriber.ts
--- a/js/common/view/describers/HandPositionsDescriber.ts	(revision a6d0f8a481dfeda2740bcddac71e8e20f335b155)
+++ b/js/common/view/describers/HandPositionsDescriber.ts	(date 1649278060833)
@@ -326,9 +326,13 @@
     } );
   }
 
-  getBothHandsDistance( overrideWithDistanceProgress = false, capitalized = false ): string {
+  getBothHandsDistance( overrideWithDistanceProgress = false, capitalized = false, hi?: boolean = false ): string {
     const distanceRegion = this.getDistanceRegion( true );
 
+    if ( hi ) {
+
+      debugger;
+    }
     if ( overrideWithDistanceProgress ) {
       if ( distanceRegion === this.previousDistanceRegionBoth ) {
         assert && assert( capitalized, 'overriding with distance-progress not supported for capitalized strings' );
Index: js/common/view/describers/BothHandsDescriber.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/describers/BothHandsDescriber.ts b/js/common/view/describers/BothHandsDescriber.ts
--- a/js/common/view/describers/BothHandsDescriber.ts	(revision a6d0f8a481dfeda2740bcddac71e8e20f335b155)
+++ b/js/common/view/describers/BothHandsDescriber.ts	(date 1649278060863)
@@ -59,7 +59,7 @@
     }
 
     return StringUtils.fillIn( ratioDistancePositionContextResponsePatternString, {
-      distance: this.handPositionsDescriber.getBothHandsDistance( true, true ),
+      distance: this.handPositionsDescriber.getBothHandsDistance( true, true, this.hi ),
       position: this.getBothHandsPosition()
     } );
   }
Index: js/common/view/BothHandsPDOMNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/BothHandsPDOMNode.ts b/js/common/view/BothHandsPDOMNode.ts
--- a/js/common/view/BothHandsPDOMNode.ts	(revision a6d0f8a481dfeda2740bcddac71e8e20f335b155)
+++ b/js/common/view/BothHandsPDOMNode.ts	(date 1649278076674)
@@ -130,6 +130,7 @@
       tickMarkDescriber
     );
 
+    this.voicingBothHandsDescriber.hi = true;
     this.antecedentInteractedWithProperty = new BooleanProperty( false );
     this.consequentInteractedWithProperty = new BooleanProperty( false );
     this.bothHandsFocusedProperty = new BooleanProperty( false );

```

</details>

And I found that it is actually purposeful. 

In https://github.com/phetsims/ratio-and-proportion/issues/419#issue-1103933693 we decided that when locked, we only get distance region, not progress. @terracoda can you please confirm this feels alright to you?

**Comment by zepumph** [comment]
Perhaps that issue was just designed for individual hands, and not for all interactions. Sorry if I didn't understand this during the implementation.

**Comment by terracoda** [comment]
The distance-progress responses are missing on master, so I do think this is a bug.

**Comment by zepumph** [comment]
Looks like a good example of how a bug fix causes another bug.

In https://github.com/phetsims/ratio-and-proportion/issues/429 we caused this with https://github.com/phetsims/ratio-and-proportion/commit/725f4f02b78e14ee753e1a14c466d7cfb2d453e4

I will add back that option to make sure that we still get distanceProgress from description when the ratio is locked.

**Comment by zepumph** [comment]
Actually, I think that https://github.com/phetsims/ratio-and-proportion/commit/937bf0a64e93c3dadf9b2600a92c881de300f984 originally caused the bug. I may fix it as part of my both hands refactor over in https://github.com/phetsims/ratio-and-proportion/issues/432, but I'll let you know here.

**Comment by zepumph** [comment]
Adding `inProportionOverridesDistanceProgress` as part of the above larger commit fixed this bug. @terracoda please note that this applies to ALL both hands cases. This means indy hands with mouse when ratio is locked, media pipe, etc., in voicing and description. Does this seem correct to you. Ideally we wouldn't have this logic split on voicing and description, but I understand if we need it to. Let's talk more!

**Comment by terracoda** [comment]
This sounds right to me. We do not currently have non-discrete interaction with Interactive Description. 

The logic that balances distance-progress and distance-region for discrete input (keyboard and swipes) is different because the experience is actually different. 

I hope that makes sense.

**Comment by terracoda** [comment]
The distance-progress and distance-regions seem to be working with Ratio Lock checked with mouse input - I get distance-progress during drag, and then distance-region at ratio and at end drag.

Indy hand sliders still work fine, too - I get distance-progress during drag, and then distance-region at ratio and at end drag.

**Comment by terracoda** [comment]
Noting when Ratio is locked and using the keyboard, I get a good mix of of distance-progress and distance-region, so I think keyboard input is working well, too. And Both Hands & edge responses with keyboard interaction are working fine, too.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.
