### ISSUE TITLE
Shorten both hands description when tick marks are visible by removing distance region

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#460]
This info is more redundant, and can be removed. I want to wait until the initial implementation is done over in https://github.com/phetsims/ratio-and-proportion/issues/432#issuecomment-1086154317 item (1). 

This should not apply to the description, and it most likely applies to all voicing of both hands, meaning when the ratio is locked + mouse input too. On hold for now though.

**Comment by terracoda** [comment]
I like the qualitative distance-region info combined with the tick marks. I think we should leave it.

I am not sure how it will work with Media-Pipe, but with Mouse and Ratio Locked it seems fine.

**Comment by terracoda** [comment]
And with Both Hands and bi-manual input it seems fine. And with the indy sliders with keyboard input are fine, too.

I think the qualitative distance will be helpful for some learners, especially learners with vision impairments or learners with learning disabilities.

**Comment by terracoda** [comment]
I'll close after I test with media pipe.

**Comment by zepumph** [comment]
@terracoda and I discussed this, and we don't think this is needed. This would be a totally fine change, but it is good right now, and there is a chance it would be worse when it was shorter. We have control over toggling the context responses. Closing
