### ISSUE TITLE
Both hands context response is capitalized in voicing response

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#461]
This makes good sense for description, but not in voicing, I think it would be straight forward to fix. Here is what things look like right now:

```
hands, far from challenge ratio, Hands extremely close to each other, left almost on tick mark 4.5, right on tick mark 5.5.
hands, at challenge ratio, Hands very close to each other, left in lower region, right in upper-middle region.
```

**Comment by terracoda** [comment]
Are you proposing to have no capitals on the phrases? This does make sense since all periods have been removed, and we just have concatenated phrases & sentence fragments.

**Comment by terracoda** [comment]
I am inclined to not address this issue right now. 
The broader question is what do we want to do with sentence capitalization of Context responses, in general?

**Comment by samreid** [comment]
Discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs remaining in the code. Reopening.
