### ISSUE TITLE
Implementation changes after https://github.com/phetsims/scenery/issues/1403

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/ratio-and-proportion#462]
After https://github.com/phetsims/scenery/issues/1403 changes are coming to Alerter.ts and Voicing.ts which may require implementation changes in the sim. This issue is to track and review.

**Comment by jessegreenberg** [comment]
I think https://github.com/phetsims/ratio-and-proportion/commit/bea560ea9e4731b8e5ddad750d3521ffdd1bd2a6 is all we need for this issue, all other Voicing announcements go through the `voicingSpeak*` functions.

Assigning to @zepumph to confirm before closing.

**Comment by zepumph** [comment]
Looks great. Thanks!
