### ISSUE TITLE
NOTE: Large file size from MediaPipe dependencies

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#464]
Publication should not occur until there has been a decision made about the size of media pipe dependencies and how to proceed about it. See https://github.com/phetsims/tangible/issues/9 and #431. Current RAP built, minified filesize is 23MB.

**Comment by KatieWoe** [comment]
Looks like this is showing up in CT
```
ratio-and-proportion : build
Build failed with status code 1:
Running "report-media" task

Running "clean" task

Running "build" task
>> TypeScript compilation complete: 10432ms
Building runnable repository (ratio-and-proportion, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 10209ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: ../sherpa/lib/license.json: no entry for key = mediaPipeDependencies.js
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1651063188151/chipper/js/grunt/getThirdPartyLibEntries.js:37:5)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1651063188151/chipper/js/grunt/getAllThirdPartyEntries.js:22:10)
at module.exports (/data/share/phet/continuous-testing/ct-snapshots/1651063188151/chipper/js/grunt/buildRunnable.js:134:29)
at async /data/share/phet/continuous-testing/ct-snapshots/1651063188151/chipper/js/grunt/Gruntfile.js:283:11
at async wrap (/data/share/phet/continuous-testing/ct-snapshots/1651063188151/chipper/js/grunt/Gruntfile.js:56:7)
Full Error details:
AssertionError [ERR_ASSERTION]: ../sherpa/lib/license.json: no entry for key = mediaPipeDependencies.js
Snapshot from 4/27/2022, 6:39:48 AM
```

**Comment by zepumph** [comment]
@emily-phet and I discussed this and we want to proceed with publishing this where dependencies are downloaded only when a query parameter is available. I want to discuss at dev meeting though to make sure that the team is OK with us hiding downloads behind a query parameter in a production sim.

**Comment by zepumph** [comment]
Discussed at dev meeting, we think that downloading dependencies, hidden behind a query parameter, is the best path forward. Though 25MB isn't a tremendous amount of data, our global use and general internet access around the world and in offline use cases would suffer from all sims being this large. With that in mind we will download the dependencies. 

I was also noted that we have to make sure that if there is no internet connection, that we give an alert or some message.

**Comment by emily-phet** [comment]
@arouinfar @amanda-phet 
Are there any examples (either in published sims, website, or artwork somewhere) of alerts? If we could see a few I think that would help us craft something pretty rapidly that seems consistent with PhET's existing look and feel. 
Even seeing examples of other kinds of relevant things in a few sims will also help us create a look that is distinct if there is nothing at all like this across the sim or website.

**Comment by arouinfar** [comment]
The closest example I can think of is Molecule Shapes, which uses WebGL to render the graphics.  If you run the sim on a device without WebGL enabled, it's a significant downgrade in graphics quality:
https://phet.colorado.edu/sims/html/molecule-shapes/latest/molecule-shapes_en.html?webgl=false

The home screen will have this persistent warning:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/8419308/180701982-68cae969-7811-410d-b0c8-66e6b790a2ec.png">

Clicking on the warning takes the user to the Help Center with more explanation:
https://phet.colorado.edu/en/webgl-disabled-page

This approach is best suited to multi-screen sims, so probably not the best solution. We could consider opening a dialog at startup, though it seems a bit rude. We currently do this when users pass in invalid values to a query parameter, such as `screens=100`:
https://phet.colorado.edu/sims/html/geometric-optics/latest/geometric-optics_en.html?screens=100
<img width="521" alt="image" src="https://user-images.githubusercontent.com/8419308/180702981-410b57c7-0182-4749-a037-cfeefb9a02c9.png"> 

Alternatively, we could use the Preferences dialog to inform users of the tangibles support. I believe there is an "Input" tab we could use for this? 

We've also discussed adding some sort of interface to the sim pages that would let users launch a sim with the desired set of query parameters. However, we haven't had serious discussions about what that would look like or how would we support it -- it's just a cool idea for the future.

**Comment by arouinfar** [comment]
One last idea --

The website has the ability to host multiple versions on the same sim page. Perhaps we could do the same for RaP.

For example, Greenhouse Effect has three different versions available to users on its sim page.
https://phet.colorado.edu/en/simulations/greenhouse-effect

If you try to launch the sim from the sim page, you'll be presented with this dialog:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/8419308/180704862-affd614e-d4ed-4fba-9ace-80403196e479.png">

**Comment by zepumph** [comment]
That could work pretty well! I'm not sure we want this prototype feature to be so loud, but if there was a second option below the main sim called "Launch with Camera Tracking enabled (internet required)" that just included the query parameter `?mediaPipe` (to be renamed).

**Comment by emily-phet** [comment]
I really like the "multiple ways to launch" option, for when mediapipe control is fully fleshed out. I'm not sure about that now for the current state (where only the custom hands are controlled by gesture and there's not much supporting info available for users).

For the current planned RaP situation, the invalid query parameter seems the most aligned with the need - though it will need new text to indicate that the mediapipe query parameter only works with internet.

**Comment by zepumph** [comment]
@emily-phet are you talking about an alert that will occur if you add the query parameter when offline? If you are trying to have this dialog for an incorrect "value" for the query parameter, it doesn't work on flags like this. Only for values of known query parameters, like `screens=blarg`. It wouldn't know that `?mediaWipe` was a misspelling of `?mediaPipe` (for example).

**Comment by emily-phet** [comment]
@zepumph - I'm not sure I understand your comment. If it helps, I wasn't suggesting anything related to misspelling as part of the RaP mediapipe solution. Rather, when a correctly spelled mediapipe query parameter is added when the sim is offline, a pop up *like* the "Invalid query parameter* popup appears. Instead of saying "invalid query parameter" it says something like "Hand Input not available offline".
Does that help?

**Comment by zepumph** [comment]
Very much! Thanks.

**Comment by zepumph** [comment]
I think I would like to use https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine. Using `window.navigator.onLine` may not cover all cases, but @samreid and I were able to find a nice way where we can try/catch the specific failure in the Hands library, and show the offline dialog from there. Committed above.


Here is the first pass of the verbage. @emily-phet will you please wordsmith:

![image](https://user-images.githubusercontent.com/6856943/184027171-afa2a0f2-cb65-45c6-9443-8462f37b2388.png)


- [ ] From here I will need to figure out if there are any extra steps to take to add a strings file to tangible.

**Comment by samreid** [comment]
I fixed a typo in the commit

**Comment by zepumph** [comment]
I know @emily-phet is having a crazy week, so I'm going to ask @terracoda to take a first pass at this wording.

**Comment by emily-phet** [comment]
@zepumph Better late than never I hope!

Let's go with "Camera Input requires an internet connection."

**Comment by terracoda** [comment]
I'm working on wording for #491 which seems really complicated. I might need help.

**Comment by zepumph** [comment]
I adjusted the wording. I think we are ready to close! Thanks all
