### ISSUE TITLE
Increate "in-proportion" tolerance when using MediaPipe

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#465]
From https://github.com/phetsims/ratio-and-proportion/issues/431#issuecomment-1090720108, we want to make it easier to use the ratio with MediaPipe, meaning an easier time getting in ratio.

**Comment by zepumph** [comment]
@BLFiedler, I made the tolerance when using MediaPipe the same as when "moving in direction" (for the choir sound). Please review. It is definitely a lot more usable. Let me know where you want to go from here. For reference, you can see the values (in fitness units from (~-100 to 1) 1 means in proportion. 


https://github.com/phetsims/ratio-and-proportion/blob/7cfca18c54a1e124b1f0c27c2b5059f8df956219/js/common/rapConstants.ts#L23-L32

**Comment by zepumph** [comment]
@BLFiedler, you can use this dev version too btw: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.13/phet/ratio-and-proportion_all_phet.html

**Comment by BLFiedler** [comment]
I agree this helps a lot with finding the target proportion and subsequently maintaining!

I think the value chosen is a good starting point. 
- [ ] Would it be possible to create a query parameter for that value to adjust in situ if we find things are problematic for summer usage? 

We can plan to get rid of it prior to any publication of the sim with the feature.
