### ISSUE TITLE
Distance progress when dragging beyond edge with mouse

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#467]
While reviewing https://github.com/phetsims/ratio-and-proportion/issues/457#issuecomment-1113498319, I noticed I was still getting distance-progress when dragging the indy hands with mouse.

@zepumph wants to take a deeper look at how distance-progress is firing and make sure it does fire when no movement happens.

**Comment by zepumph** [comment]
I was not able to get to this today and will have to investigate when I'm back in a week.

**Comment by zepumph** [comment]
At one point I saw that the positions I was comparing were not both 0, one was 0 and the other was .000000004324 or something. So I used this patch, but I can still reproduce the bug. Perhaps I am wrong, or perhaps this is correct, but I still need to do more.


<details>

```diff
Index: js/common/view/RatioHalf.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/RatioHalf.ts b/js/common/view/RatioHalf.ts
--- a/js/common/view/RatioHalf.ts	(revision 42ae159b72138d2c6b9e449f362f6fb263a43ebf)
+++ b/js/common/view/RatioHalf.ts	(date 1652467623704)
@@ -354,8 +354,8 @@
           new Range( dragBoundsProperty.value.left, dragBoundsProperty.value.right ) );
         this.viewSounds.tickMarkBumpSoundClip.onInteract( positionProperty.value.y );
 
-        // Only new responses if the y position is different.
-        if ( positionProperty.value.y !== previousYOnLastVoicing ) {
+        // Only new responses if the y position is different. Bug with 0 !== .00000000000000432, see https://github.com/phetsims/ratio-and-proportion/issues/467
+        if ( Math.abs( positionProperty.value.y - previousYOnLastVoicing ) < 0.00001 ) {
           this.ratioHandNode.voicingSpeakFullResponse( {
             nameResponse: null,
             contextResponse: this.getSingleHandContextResponse( this.voicingHandPositionsDescriber, voicingBothHandsDescriber, {

**Comment by zepumph** [comment]
Alright. I fixed it! Though with a workaround; https://github.com/phetsims/scenery/issues/1415 tracks the actual bug.

@terracoda you should never hear a distance progress against the boundary again.

**Comment by terracoda** [comment]
Not hearing distance progress when dragging with mouse at edges.
There is still some inconsistency with the hint, but I'll comment on that  over in #457 .

Closing this issue. Thanks @zepumph !

**Comment by zepumph** [comment]
@terracoda and I ran into this same bug again but with rounding on the max value. I fixed it more generally in https://github.com/phetsims/ratio-and-proportion/commit/652a63396c28f8996b11ecb6df94b70a2d18447c. So I could remove this workaround.
