### ISSUE TITLE
Update PhET-iO data collection for summer studies

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#468]
Progressing data collection from #142 for current needs this summer

[placeholder, to be updated by BF 5/11/2022]

**Comment by zepumph** [comment]
Note a clapperboard available in the sim preferences now, see https://github.com/phetsims/scenery-phet/issues/739.

**Comment by BLFiedler** [comment]
Copied over and edited from meeting notes:

# Minimum functionality for data collection
## Synchronization
- [ ] Precise Start/Stop to data collection (@zepumph added in https://github.com/phetsims/scenery-phet/issues/739)
  - Don’t want to fully start data collection with press of button, but we can spit out the state at that point. Ignoring stuff before is “asking for trouble”.
  - Button in Pref menu w/ large visual indicator (visible from camera several feet away) and audible, unique sound (Let’s say 100ms duration for both to start)
## Storage needs
- [ ] Metacog cloud storage with 4 digit unique identifier that can be pulled from the cloud server and parsed using a script similar to what @zepumph made in https://github.com/phetsims/ratio-and-proportion/issues/142#issuecomment-832927592.

# Minimum variable tracking for data collection in Quadrilateral:
1. [ ] Time (global)
2. [ ] Sim model values (states and positions)
  - RaP: (Left hand, right hand positions, current Fitness, target ratio, tick mark range)
3. [ ] Input cluster (arrays corresponding to each input if available)
  - Drag Listeners for mouse,
  - Keyboard listeners, 
  - For RaP: We do not need the number key presses for hand position shortcuts. [BF: true until it’s not true, but not for this iteration]
  - mediaPipe interacted with (mediaPipeInteractedWithProperty) + direct mediaPipe landmarks
  - [**not for RaP yet**] OpenCV connected property (Am I being interacted with: (is the sim updating? I think) does it have enough markers to update)
  - [**not for RaP yet, but hopefully soon**] Tangible connected property (If BLE/wired serial is connected: TRUE or FALSE)
4. [ ] Sim State Information
- RaP: (inProportion, movingInDirection)
- Current value (derivedProperty) of the inProportionThreshold()
- Print initialized constants (inc tolerances)
 - Include query parameters
- (for @BLFiedler : Moving in proportion = inProportion && movingInDirection)
- (for @BLFiedler : Fitness is > 0 && not in proportion will give us the staccato sound)




@zepumph, feel free to edit and add any details I missed!

**Comment by zepumph** [comment]
Above I put MediaPipe directly onto the data stream. It is a bit spammy right now, perhaps if we don't have multiple hands, then we just don't set it. Not sure yet.

**Comment by zepumph** [comment]
Almost everything has been completed here for RAP. I added query parameter values to the constants (which already has tolerances etc). I also instrumented MediaPipe Properties. 

Still to do:
- [ ] Double check that all mediaPipe results (unparsed) are as we desire.
- [ ] AccessibleValueHandler is not instrumented, this means we don't get a specific notification about how a keyboard press caused the Property to change (like we do for freely dragging keyboard items, and DragListener in mouse/touch land). I'm unsure if we want to dive into that largish type to instrument, but I want to think about it for a bit.

**Comment by zepumph** [comment]
I think I will hold off to hear from @BLFiedler how important instrumenting AccessibleValueHandler is.

**Comment by BLFiedler** [comment]
It is unlikely keyboard will be used in upcoming studies, so it is alright to exclude. Also falls under the "nice to have" regardless. Not required for study questions at present.

I mentioned this for Quad, but it would be good for the clapperboard sync to appear in the parsed output for sync purposes.

**Comment by zepumph** [comment]
I needed to add PhET-iO instrumentation to a couple more Properties for mediaPipe and bluetooth.j

**Comment by zepumph** [comment]
I successfully tested a metacog recording loop, and brushed off the dust from the postprocessing script over in https://github.com/phetsims/special-ops/issues/202.

Here is the new version, with added phetioIDs from https://github.com/phetsims/ratio-and-proportion/issues/468#issuecomment-1123911772. 

<details>

```mjs
import fs from 'fs';
import converter from 'json-2-csv';
import _ from 'lodash';

/**
 * Steps to use:
 *
 * Requires lodash and json-2-csv (like installed via package.json)
 *
 * Take log into -> ./ratio-and-proportion.log
 *
 * Most likely the file is too big to load at once, so split up into individual lines
 * mkdir ./log-json/
 * split -l 1 ratio-and-proportion.log ./log-json/
 *
 * This script will read all the files in and output corresponding csv files in ./log-csv/.
 * node thisScript.js
 *
 */

const weCareAbout = {
  'ratioAndProportion.general.model.screenProperty': [ {
    access: 'newValue.phetioID',
    displayName: 'screenProperty'
  } ],
  'ratioAndProportion.discoverScreen.model.targetRatioProperty': [ {
    access: 'newValue',
    displayName: 'discoverScreen.targetRatioProperty'
  } ],
  'ratioAndProportion.discoverScreen.model.ratio.tupleProperty': [ {
    access: 'newValue.antecedent',
    displayName: 'discoverScreen.tupleProperty.antecedent'
  }, {
    access: 'newValue.consequent',
    displayName: 'discoverScreen.tupleProperty.consequent'
  } ],
  'ratioAndProportion.discoverScreen.model.unclampedFitnessProperty': [ {
    access: 'newValue',
    displayName: 'discoverScreen.unclampedFitnessProperty'
  } ],
  'ratioAndProportion.discoverScreen.view.tickMarkViewProperty': [ {
    access: 'newValue',
    displayName: 'discoverScreen.tickMarkViewProperty'
  } ],
  'ratioAndProportion.createScreen.model.targetRatioProperty': [ {
    access: 'newValue',
    displayName: 'createScreen.targetRatioProperty'
  } ],
  'ratioAndProportion.createScreen.model.ratio.tupleProperty': [ {
    access: 'newValue.antecedent',
    displayName: 'createScreen.tupleProperty.antecedent'
  }, {
    access: 'newValue.consequent',
    displayName: 'createScreen.tupleProperty.consequent'
  } ],
  'ratioAndProportion.createScreen.model.unclampedFitnessProperty': [ {
    access: 'newValue',
    displayName: 'createScreen.unclampedFitnessProperty'
  } ],
  'ratioAndProportion.createScreen.view.tickMarkViewProperty': [ {
    access: 'newValue',
    displayName: 'createScreen.tickMarkViewProperty'
  } ],
  'ratioAndProportion.createScreen.model.ratio.lockedProperty': [ {
    access: 'newValue',
    displayName: 'createScreen.lockedProperty'
  } ],
  'ratioAndProportion.createScreen.view.tickMarkRangeProperty': [ {
    access: 'newValue',
    displayName: 'createScreen.tickMarkRangeProperty'
  } ],
  'phetioEngine.phetioElementAddedEmitter': [ {
    access: 'phetioID',
    accessEquals: 'ratioAndProportion.global.model.rapConstants',
    dataValue: 'state',
    displayName: 'rapConstants'
  } ]
}

const phetioIDs = Object.keys( weCareAbout );


const get = ( object, key ) => {
  const keys = key.split( '.' );
  let theReturn = object;
  for ( const i = 0; i < keys.length; i++ ) {
    theReturn = object[ keys[ i ] ];
  }
  return theReturn;
}


const handlePhetEvent = ( sessionEvents, event ) => {

  if ( phetioIDs.includes( event.phetioID ) ) {

    const tableRow = {
      time: event.time
    };

    let pushThisRow = true;

    const weCareAboutEntries = weCareAbout[ event.phetioID ];
    weCareAboutEntries.forEach( entry => {

      if ( entry.accessEquals ) {
        if ( entry.accessEquals === _.get( event.data, entry.access ) ) {
          tableRow[ entry.displayName ] = JSON.stringify( _.get( event.data, entry.dataValue ) );
        }
        else {
          pushThisRow = false;
        }
      }
      else {
        tableRow[ entry.displayName ] = _.get( event.data, entry.access );
      }
    } );

    pushThisRow && sessionEvents.push( tableRow );
  }

  event.children && event.children.forEach( childEvent => handlePhetEvent( sessionEvents, childEvent ) );
};


( async () => {


  const fileNames = fs.readdirSync( './log-json' );
  fs.mkdirSync('./log-csv');

  for ( let i = 0; i < fileNames.length; i++ ) {
    const fileName = fileNames[ i ];

    const fileContents = fs.readFileSync( `./log-json/${fileName}` );
    const session = JSON.parse( fileContents );


    const sessionEvents = [];
    session.events.forEach( event => {
      const phetEvent = event.data;

      handlePhetEvent( sessionEvents, phetEvent );

    } );

    // convert JSON array to CSV string
    try {
      let csv = await converter.json2csvAsync( sessionEvents );

      csv = csv.replace( /undefined/g, 'null' );

      // write CSV to a file
      fs.writeFileSync( `./log-csv/${session.session.learner_id}_${session.session.session_id}.csv`, csv )
    }
    catch( err ) {
      console.log( err );
    }
  }
} )();
```

</details>

@BLFiedler, can you please take a look at the csv here and let me know if we need more than what is available in the columns. There is a good chance that anything else you want to add is already in the PhET-iO data stream (and could thus be added later), but it would be good to take a look prior to recording in case I missed an important piece fully from PhET-iO instrumentation.

[phettest_13494170@1656348196650.csv](https://github.com/phetsims/ratio-and-proportion/files/8995831/phettest_13494170%401656348196650.csv)

**Comment by BLFiedler** [comment]
@zepumph, can upload all of the files generated on metacog on 6/29/2022? Including parsed files. If the files aren't too large, you can just e-mail them to me. Otherwise, let me know and I'll create a temporary Drive folder.

There may be additional codesign sessions this summer with Craft lab leading the charge in which case we'll likely want to use this again. Reassign me and we'll leave the issue open until then.

**Comment by zepumph** [comment]
I sent you these files on slack, please let me know if you have any questions.

**Comment by BLFiedler** [comment]
Closing as completed for this round.
