### ISSUE TITLE
Connect external devices to Ratio and Proportion using Electron/Serial and Bluetooth API

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#473]
We're ready to connect some devices to Ratio and Proportion to be used for codesign work. 

Creating this issue to log progress or needs for this implementation.

We will plan to create a way to communicate using both Bluetooth and Serial for redundancy purposes.

Serial uses the electron app which was developed for Quadrilateral to communicate with a USB device. Relevant issues might be:
https://github.com/phetsims/quadrilateral/issues/32
https://github.com/phetsims/quadrilateral/issues/159

Bluetooth uses the chromium API (?). Relevant issues might be:
https://github.com/phetsims/quadrilateral/issues/52

**Comment by jessegreenberg** [comment]
@zepumph and I met with progress with Chris and Casey from ATLAS today got a fair amount working.

We have a successful connection one bluetooth device working well, and data from the device is updating the hand positions in RaP.

We ended with some hacky code that tries to make two bluetooth connections with one press of "Request Device".  Sometimes the connection to both devices is successful, other times it fails with error. We will try to get this part working. But if it isn't trivial we may just make it a requirement that the user connects to each device manually.

**Comment by jessegreenberg** [comment]
Over slack, Casey reported that a user interaction is required to make a connection request so we cannot batch both connections into a single button press. So we added two buttons, one for each hand that the user can press to connect to each device.

**Comment by jessegreenberg** [comment]
I was able to play with this demo today, it works very well! The sensors are sensitive enough that I could make distinctions between different proportions on the second screen.

One issue at the moment is that sound does not play while hands move from this input. @zepumph is there a trigger or field that needs to be set to play sound?

**Comment by zepumph** [comment]
I did a bit of cleanup here. @jessegreenberg and I also talked about getting voicing to work with this. If we get the "mid drag" voicing working over in #454, then we think it would be a good candidate over here too.

**Comment by zepumph** [comment]
@jessegreenberg, can you take a look at this issue and let me know if there is anything else to do besides https://github.com/phetsims/ratio-and-proportion/issues/483. Are we ready to close?

**Comment by BLFiedler** [comment]
From reports, the connection works well! Agreed that side issues should be create for anything that comes up.

**Comment by samreid** [comment]
As discovered in https://github.com/phetsims/chipper/issues/946, there are TODOs in the code referring to this issue.  Reopening.
