### ISSUE TITLE
ComboBox voicing response on selection broken

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#474]
I can reproduce this in the voice combobox in the voicing preferences, and also in the my challenge combo box. I'll take a look. I believe this is a regression, though it could have been part of the design. I thought it should say the selection when you press it. This is broken for mouse and keyboard.

**Comment by zepumph** [comment]
Discovered while poking around https://github.com/phetsims/joist/issues/813

**Comment by zepumph** [comment]
Ahhh, @jessegreenberg, we have broken voicing responses on combobox selection because of voicingVisible. The listbox get's hidden, so we don't hear it even though the combobox code hasn't changed. 

https://github.com/phetsims/sun/blob/811a46cb8e395efbbe0e59dd603af474c5d5d045/js/ComboBoxListBox.ts#L311-L326

I'll investigate a way to voice through a visible part of the combobox.

**Comment by zepumph** [comment]
@terracoda please note here, feel free to test if you'd like and let me know if you run into trouble.

@jessegreenberg, will you give me a spot check here?

**Comment by terracoda** [comment]
Sounds good.
