### ISSUE TITLE
OK_GESTURE should freeze hands in position of latest voicing response

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#476]
@terracoda had this idea. I like it! This way the voicing that you hear won't seem out of date because you can't move your hands when the OK_GESTURE is in place.

**Comment by zepumph** [comment]
Ok, this is ready to test, and I feel like it is really cool. good job @terracoda. I also updated the "memory" of detecting the OK_GESTURE from 10 frames to 20 so it takes a bit longer to snap out of the OK_GESTURE. This makes false negatives (where you are doing the gesture but mediaPipe doesn't pick it up) less obtrusive to listing to the whole voicing response. 

@terracoda, let me know what you think!

**Comment by terracoda** [comment]
The hands are not freezing for me. Do I need a query parameter?

**Comment by zepumph** [comment]
There was a bug in phettest, please retest there or in https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.21/phet/ratio-and-proportion_all_phet.html

**Comment by terracoda** [comment]
Trying with câche cleared and dev tools open :-)

**Comment by terracoda** [comment]
I have shared the link for more feedback. Hopefully, we get some.

**Comment by terracoda** [comment]
This works well, so closing the issue.
