### ISSUE TITLE
Missing context response for Challenge combobox (Discover Screen)

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#478]
On screen 2, we implemented a context response for when a learner changes the challenge with the number spinners which causes a change in the hands proximity to ratio.

That context response is missing on screen 1.

**I am not 100% sure if it was ever implemented, but I think it must have been because it is well documented, and the response also exists for interactive description in this scenario.**

**Steps to reproduce issue:**
1. Enable Voicing and ensure Object and Context Responses are checked.
2. Hands start at ratio with Challenge 1 selected. The screen is darkest green.
3. Select challenge 2. The challenge changes and without moving the hands have a new proximity to ratio, and the screen is less green and more white.

I only hear that the challenge was changed, but I should also hear the context response that describes the hands new proximity to the challenge ratio. 

The responses are documented in the input patterns in the design doc and should be the same as Interactive Description.

Edited bolded text.

**Comment by zepumph** [comment]
This is an extension of https://github.com/phetsims/ratio-and-proportion/issues/474. It looks like I didn't quite get the response completely back in the original fix over there. The context should be fixed now. Feel free to close if all sounds good.
