### ISSUE TITLE
Voicing current context response when mediaPipe hands are stationary

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#481]
This was a tendril of #454 that I don't think is currently being tracked.

**Comment by zepumph** [comment]
@terracoda, there is now logic in place such that when you keep your hands still enough, it will speak voicing to you. I wanted to make this the distance progress context response (like we designed and talked about), but couldn't because ofhttps://github.com/phetsims/utterance-queue/issues/83. No matter, please review hearing an end-drag-like response when keeping standard, "open" hands and then keeping them stationary. Also tagging https://github.com/phetsims/ratio-and-proportion/issues/480 because these issues should be reviewed together.

**Comment by zepumph** [comment]
This work/research was a precursor to getting the same behavior working over in #473

**Comment by terracoda** [comment]
I am going to close this issue. I like the way it is working.

**Comment by zepumph** [comment]
https://github.com/phetsims/utterance-queue/issues/83 was solved, so now this will be the distance progress instead of the distance region (yay!). Thanks @jessegreenberg.
