### ISSUE TITLE
Add voicing to bluetooth input

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#483]
Basically this is the current conversation over in https://github.com/phetsims/ratio-and-proportion/issues/473, but I'll make a new issue for it.

**Comment by zepumph** [comment]
Over in #481 we created logic that is exactly what we want to use here. I have tested it in mediaPipe and it is working well. Next I'll just need to implement in bluetooth and have someone else test it with bluetooth devices.

**Comment by zepumph** [comment]
Alright, I added bluetooth voicing, and created a dev version. I think we can move forward with testing this with a link like:

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.23/phet/ratio-and-proportion_en_phet.html?bluetooth&voicingInitiallyEnabled

To get voicing, keep the devices very still (stationary), and you should hear a response. If you move them again, the response should stop.

**Comment by jessegreenberg** [comment]
That seems like a promising design, I like it! I am no longer able to test the device and setup though, Ill pass to @BLFiedler to comment on next steps to verify this is working.

**Comment by BLFiedler** [comment]
I've asked Chris to test (and I believe TS did as well) when he is able. I'll also plan on testing on Monday when I'm on campus.

**Comment by terracoda** [comment]
I only tested with Media Pipe hand gestures and I liked it.

**Comment by zepumph** [comment]
I met with @BLFiedler, Chris and Casey today and got some feedback about the stationary calibration. We want to make query parameters to control the history length, and threshold, as well as changing the defaults.

**Comment by zepumph** [comment]
Ok to test here is a link with the query parameters already set to their defaults: 

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.28/phet/ratio-and-proportion_all_phet.html?bluetooth&bluetoothStationaryThreshold=.02&bluetoothHistoryLength=10

Here is the documentation about the parameters, and the defaults. 

https://github.com/phetsims/ratio-and-proportion/blob/fd6496d/js/common/RAPQueryParameters.ts#L34-L46

**Comment by terracoda** [comment]
@BLFiedler, is there anything that needs to be added to this issue? Can this issue be closed?

**Comment by BLFiedler** [comment]
Yup. All this was working fine. We'd like to retain those query parameters for future use as a note.
