### ISSUE TITLE
Reimplement ChallengeComboBoxItem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ratio-and-proportion#484]
In https://github.com/phetsims/sun/issues/768, ComboBoxItem is being converted from `class` to `type`.

From https://github.com/phetsims/sun/issues/768#issuecomment-1165735283: 

Hmmm... This makes converting ComboBoxItem to a `type` a bit more complicated.  In ratio-and-proportion:

```typescript
class ChallengeComboBoxItem extends ComboBoxItem<number> 
```

... and ChallengeComboBoxItem does some work that a `type` cannot.

ChallengeComboBoxItem is a bad design. The responsibility for setting the background color of the sim should not be in the item.  The item should select a value, and  setting the background color based on the value should be handled elsewhere.  @zepumph may I change this?

What I said about ChallengeComboBoxItem is true in general.  Items should not have responsibilities like this.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/sun/issues/768#issuecomment-1165787587, @zepumph said:
> Yes that makes sense. Go ahead and make that change. Thanks!

**Comment by pixelzoom** [comment]
Since this is a significant change, I published [1.2.0-dev.24](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.24/phet/ratio-and-proportion_all_phet.html) as a baseline before proceeding.

**Comment by pixelzoom** [comment]
Done in the above commit.

I noticed that there was a lot of duplication of the ratio constants 1/2, 1/3, 3/4 in ChallengeRatioComboBoxNode.   There was an existing Map that mapped ratio to `capitalized` and `lowercase` strings.  So I extended that Map to include other info about challenges that is needed by ChallengeRatioComboBoxNode.  That eliminated the duplication of ratio constants, and facilitates creating the ComboBoxItems by iterating over the map.

@zepumph please review.

**Comment by zepumph** [comment]
Looks amazing (obviously). Thanks for doing that refactor. I really appreciate. The code is much better.
