### ISSUE TITLE
// eslint-disable-line @typescript-eslint/consistent-generic-constructors

### ISSUE THREAD

**Issue by samreid** [phetsims/ratio-and-proportion#486]
During https://github.com/phetsims/chipper/issues/1277, I was trying to enable the rule `@typescript-eslint/consistent-generic-constructors` and found one case in RAP that required special handling:

```ts
    const positionProperty: MappedProperty<Vector2, number> = new MappedProperty( ratioTermSpecificProperty, { // eslint-disable-line @typescript-eslint/consistent-generic-constructors
      reentrant: true,
      bidirectional: true,
      valueType: Vector2,
      inverseMap: ( vector2: Vector2 ) => vector2.y,
      map: ( number: number ) => {

        // initial case
        if ( mappingInitialValue ) {
          mappingInitialValue = false;
          return initialVector.setY( number );
        }
        else {
          return positionProperty.value.copy().setY( number );
        }
      }
    } );
```

Since the positionProperty refers to itself in its definition, it cannot be used for type inference.  I added eslint-disable-line for now, but thought you might want to take a look.

**Comment by zepumph** [comment]
Thanks for the issue. It worked to just have the type on both sides of the equals sign. If either are removed, there is an error, so it seems pretty self explanatory (hence no added doc). Closing.
