### ISSUE TITLE
How to test Camera Input: Hands for publication

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#488]
For QA. This issue is mean to document how best to test Camera Input: Hands (media pipe).  

This is a new feature, that has never been tested before, and only thus far used for research. It also isn't considered "complete" because it is only set up to control the hands, and not all controls.

**Feature Explained:**
* To enable, add the query parameter: `cameraInput=hands`
* This feature is set up to control the two hands in the sim with your hands.
* You can use the `showVideo` query parameter to overlay the webcam image on top of the sim to see how the hand positions in the image correlate to the sim values.
* There are settings in the preferences "input" tab that you can use to change the input.
* Make an "O Hand" gesture, where thumb and pointer fingers touch to bring the hands into a circle shape, to freeze the hands in place. This gesture will also allow the current voicing string to be spoken fully. 

**To test:**
* Does it work on the browsers that we support? (perhaps not safari)
* Can you use 2 hands
* Can you use 1 hand to control a single hand.
* Use with ratio locked
* Check using all the camera input preferences
* Nuance about "how well" it works would be appreciated
* Use it with voicing enabled.
* We do not expect this to work with description (screen reader use).
* While `?showVideo` can be used by QA, it will not be a public query parameter, so please make sure to test without it in addition to with it.
* If there are any qa devices with multiple video cameras, it would be great to test switching between them during sim use (in the input preferences.

**Comment by Nancy-Salpepi** [comment]
@zepumph I see there is a gesture to get the hands "free" but is there a gesture that stops the hand motion or do I have to remove the query parameter/turn off camera if I want that to occur?

**Comment by zepumph** [comment]
Sorry. That was a typo. That gesture will "freeze" the hands in place, and the lack of that gesture will free them back up for movement.

**Comment by zepumph** [comment]
@Nancy-Salpepi @KatieWoe @stemilymill, I'm going to close this issue, but please feel free to add this info to QA doc, or to come back to it and improve on things as we go. Also reopen if you'd prefer.
