### ISSUE TITLE
Support mediaPipe hands when ratio is locked

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#489]
When the ratio is locked @terracoda, @emily-phet, and I think we should (semi-arbitrarily) choose a primary hand and only use that value to set the ratio.

I like it!

**Comment by zepumph** [comment]
Alright. This now works. Similar to #490, you have to use the x-flipped option to change the term that the hands apply to. Please review @terracoda.

**Comment by terracoda** [comment]
The locked hands are working well with or with out checkboxes checked.
