### ISSUE TITLE
Convert individual ratio interactions to sliders

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#49]
This issue will change them from `div` element with `role="application"` to be an `input` of type slider. This is more semantic and make the description easier. 

I'm pretty sure that we want to do this, but will assign @emily-phet to double check and for prioritization. My understanding was that we don't need keyboard interaction in the horizontal axis, and so this simplification will help pedagogically and with the implementation. 

With this, we will need to work with https://github.com/phetsims/ratio-and-proportion/issues/35 to implement description with aria-valuetext and aria-live. Not sure which of the two issues to do that work in.

**Comment by zepumph** [comment]
Oops sorry, but over in #47 I already did this conversion. It made implementing the snap logic really easy and nice. 

Now what is left in this issue is to implement the appropriate description for the sliders. This means aria-valuetext and potentially some rounding/units too. Assigning to @Matthew-Moore240 for the description support.

**Comment by emily-phet** [comment]
Handling description in other issues, closing.
