### ISSUE TITLE
Artwork needed for Camera Input: Hands

### ISSUE THREAD

**Issue by terracoda** [phetsims/ratio-and-proportion#493]
Over in #491, we are working out the words to describe how customize the hand movement.

**Here's how I currently have it described**

Customize hand movement.
[ ] Flip camera view of hands between frontal and horizontal views
[ ] Flip hand operation between mirrored hand control and opposite hand control

**Here are some sample hand drawings**
![image](https://user-images.githubusercontent.com/1902116/184429729-3e93d6af-2a5c-4d46-9deb-ff56a4e76627.png)
Sample hands from https://all-free-download.com/free-vector/download/free-vector-hands-human-hands_38058.html

Then connect a natural looking hand with the sim's hands... (working on an example)

**Comment by terracoda** [comment]
These are not very good. Just tryin to get an idea across for frontal camera view with the hands 
Directly mirrored, or
<img width="415" alt="hand-mirrored" src="https://user-images.githubusercontent.com/1902116/184431387-0a908ad6-eb43-4745-b6c9-5c87c738523a.png">

Opposite hand control
<img width="491" alt="hands-opposite" src="https://user-images.githubusercontent.com/1902116/184431404-defd8537-089e-4390-8db5-e23d1d0b95af.png">

**Comment by terracoda** [comment]
@emily-phet, could you elaborate on what you have in mind for a graphic?

**Comment by terracoda** [comment]
Maybe we need a sim screen in front of the human hands?

**Comment by zepumph** [comment]
This is blocking publication of the sim. What are the goals here?

**Comment by terracoda** [comment]
Personally, I don't think this should block publication as long as the text is understandable.

**Comment by terracoda** [comment]
Here's a rough idea with a screen in front of the hands.
![image](https://user-images.githubusercontent.com/1902116/185994774-f4d4aa94-1739-47d9-88f6-311b313b76d2.png)
![image](https://user-images.githubusercontent.com/1902116/185994812-0452ceab-67bc-4853-a24d-8f87b6172e79.png)
![image](https://user-images.githubusercontent.com/1902116/185994901-f7fcca9a-68f4-4d9b-805d-095a7e8c4733.png)

**Comment by zepumph** [comment]
It isn't clear to me what artwork you are interested it. What size generally do you want this? Is it an icon? Something for the options dialog as well as the website if we were going to filter on it/put it next to sims that supported it? Perhaps the "screen" portion of it should be general and not sim-specific. Like two hands and a blurry screen background or something. If you were trying to have an image showing how RAP works in the options Dialog, then my ideas are not the direction to go.

**Comment by terracoda** [comment]
I hadn't considered a blurry screen. That's and interesting idea.

And actually, it needs to be very simple - iconic in nature and ideally black and white. I was just using the image from the home screen button because I can't seem to draw.

Ideally, a screen on an angle with hands in front would be good.

**Comment by terracoda** [comment]
I think we may need better images of the hands, but I think we are getting closer to simple and iconic.

**Comment by terracoda** [comment]
Another options for

[ ] Flip camera view of hands between frontal and horizontal views
![image](https://user-images.githubusercontent.com/1902116/186181906-6835598b-c725-49f8-8991-98e245448b29.png)

**Comment by terracoda** [comment]
@emily-phet and @zepumph, assigning to you both for comment.

**Comment by terracoda** [comment]
**Camera Input: Hands**
With "cameraInput=hands" use your hands to move the sim's Left and Right Hands.
 
[ ] Flip hand operation between mirrored hand control and opposite hand control
![image](https://user-images.githubusercontent.com/1902116/186177319-4a737c7c-4100-4f6e-a482-ab6d7bad4ab1.png)

**Customize hand movement**
[ ] Flip camera view of hands between frontal and horizontal views

**Comment by emily-phet** [comment]
@terracoda Did you reach out to @Ashton-Morris about this? If not, I can ask him if he could put something together quickly for this when I have some afternoon meetings with him. JB is out so we'll have time for that.

**Comment by Ashton-Morris** [comment]
I am going to brainstorm and try to come up with some ideas.

**Comment by terracoda** [comment]
Thanks @Ashton-Morris, I forgot to reach out to you.

**Comment by terracoda** [comment]
These look way more interesting than the ones I hacked together.

I personally like this straight on perspective as I can see the letters there the best.
![image](https://user-images.githubusercontent.com/1902116/192872117-4849dc8c-59eb-4ece-946f-b4085c54fcee.png)

**Comment by emily-phet** [comment]
I like the straight on perspective, or the upper left one in your comment above. 
Let's have the sim hands look like the hands in the sim RAP, and distinguish them from the representation of the real human hands. 
Also - if the dimensions of the screen could be narrower, that would be great. Right now it looks more like a TV than a computer screen to me.

**Comment by terracoda** [comment]
The one in the upper left was my second favourite

**Comment by Ashton-Morris** [comment]
Update: I have made it more like a monitor a bit. Also added the Sim hands. 

Should the sim hands be intentionally red still or do you all think black and white only would be best? 
![Screen Shot 2022-10-04 at 12 02 17 PM](https://user-images.githubusercontent.com/34492870/193892759-13bb775c-ed43-4342-bc59-3b0664f006c8.png)

**Comment by zepumph** [comment]
Since we have such good progress here, I'm going to mark this as blocking to keep the conversation going.

In terms of adding this to the controls themselves:
* We could make this a radio button group where the icons are the UI.
* We could add like a "double arrow" swap to the icon and keep the flipping checkbox
* We could highlight the "selected" icon when checked, and grey out the other.

@terracoda what are you thinking about the above icons?

@terracoda what are you thinking about the final form of the preference.

**Comment by zepumph** [comment]
Next steps here from a conversation with @emily-phet:

1. We like a "toggle" style icon UI, something like Color Vision or Balancing Act:
![image](https://user-images.githubusercontent.com/6856943/194422410-08eb5022-3d80-4471-98ea-d6ffd448ee14.png)
![image](https://user-images.githubusercontent.com/6856943/194422426-7b96861b-1232-4047-b9a5-c77ca046cab8.png)

2. Create heading for the UI. Something like "Flip hands up/down" and "Flip hands left/right"
2. Do we need additional onscreen text in addition? @emily-phet and I aren't quite sure. This is a question for @terracoda, if so, then we need to figure out how to attach that to the heading/icon combo.
3. Solidify the images. I think that we should work with @Ashton-Morris to solidify the design and then we can give the idea to @mariahmaephet.

**Comment by terracoda** [comment]
Here's the current text set-up in the Preferences Menu for Reference

<img width="868" alt="image" src="https://user-images.githubusercontent.com/1902116/194604325-8c94f276-cca6-4f4e-87ea-9b4d2c18a287.png">

Regarding the suggested heading, I am not understanding "Flip hands up/down" and "Flip hands left/right".

**Comment by terracoda** [comment]
We need to communicate two things visually
1. Your camera can be in front of you, or overhead
2. You can flip the hands

I think we are currently missing something. Are people expected to flip the hands if they are using an aver the head camera. 

I am all information is visually captured yet.

![image](https://user-images.githubusercontent.com/1902116/194613306-4c7fc03c-4dbf-4930-ab9d-8776e3122427.png)

**Comment by terracoda** [comment]
Please help me understand bu comparing these two mock-ups 
Current Text Only Representation
<img width="649" alt="image" src="https://user-images.githubusercontent.com/1902116/194614865-d605d0c8-dbc3-4c2d-a1bf-eae1a6f705c6.png">

How do we or do we need to represent the Camera View with the Visual Icon Representation?
<img width="858" alt="image" src="https://user-images.githubusercontent.com/1902116/194615093-5ba646fa-1311-4840-b708-a19b3e963162.png">

**Comment by terracoda** [comment]
In the visual representation above, there are two separate choices to be made - one for the camera and one for how you want the camera to interpret the hands.

**Comment by zepumph** [comment]
Just a ping here. We are getting close to all other issues finishing up, and this is still marked as blocking RAP. Please change the blocking label or provide the wording updates desired. Thanks!

**Comment by zepumph** [comment]
@emily-phet and I feel like this is fine to go to RC with, but we will want new wording before we publish.

**Comment by terracoda** [comment]
@emily-phet, I am still a little fuzzy on how I can describe the set-up with one set of radio buttons. I think I need to assume vertical movement happens with a straight-on camera and horizontal movement happens with an over-the-head camera. That's not a choice, but an assumption. 

Then the user can choose to change the hand association from a directly mirrored mapping to an opposite mapping. Now, how to describe that?

Does 4 radio buttons make sense to you @emily? 

**Customize hand movement**
Choose vertical or horizontal hand movements to control the sim
[x] Mirrored vertical movement
[  ] Mirrored horizontal movement
[  ] Opposite vertical movement
[  ] Opposite horizontal movement

**Comment by terracoda** [comment]
I am not sure "Opposite" is the correct term. "Natural" might be better.

Oh, I just realized I have this all backwards. The hands in the sim face the same direction as me. 
The left hand in the sim is controlled naturally by my own left hand. 

Not sure why this was so confusing for me to understand.

**Customize hand movement**
Choose vertical or horizontal hand movements to control the sim.
[x] Natural vertical movement
[ ] Mirrored vertical movement
[ ] Natural horizontal movement
[ ] Mirrored horizontal movement




In "mirrored vertical movement", my own left hand operates the sim's

**Comment by emily-phet** [comment]
I think something simple like:
[ ] Flipped vertical movement
[ ] Flipped horizontal movement

would be sufficient. To me, it's ok if you wouldn't necessarily know which specific direction your choosing ("natural" or "mirrored" from the menu. You would be seeking this option if you *need* to have it flipped. So in that situation, you would know. Otherwise, you might be curious what happens when you flip it...so again, you would know. 
I do like your "natural vs mirrored", but I think four radio buttons will feel very heavy for this option. If you need this, you know you need it *changed*. To me that seems more important than a person needing to identify specifically if they want "natural" or "mirrored". I like the approach of emphasizing the change (e.g., using the word "flip" emphasizes the change in state) rather than the current state.

When Jesse, you, and I met about this awhile back, Jesse was able to find some other examples using this same kind of emphasis on the change rather than the state. That doesn't make it the best solution, but at least it's not completely uncommon. :)

**Comment by terracoda** [comment]
I almost posted "flipped" with only 2 options with only 2 radio buttons, but I was thinking that there would be no option for "natural horizontal movement", but now I realize that **natural horizontal movement** is just the default if the learner is using an over-the-head camera.

If we only have 2 radio buttons as in the following design:
**Customize hand movement**
Flip hand operation to support vertical or horizontal hand movements to control the sim.
[ ] Flipped vertical movement
[ ] Flipped horizontal movement

We still have a problem. 
How does a user get back to "natural movement" if they choose to flip the hands?

As you said, we have to assume the user (teacher or learner) has a physical set-up, either a face-to-face camera or an over-the-head camera, or even a camera directly underneath. They may need to flip the hands to optimize the situation. If they change their physical set-up, they may need to un-flip the hands or put them back to a natural orientation. 

With 2 radio buttons i think the interaction has to juxtapose natural versus mirrored. The user and their camera determine whether if the are doing vertical or horizontal movement.

**Customize hand movement**
If needed, flip the hands that control the sim to support different camera setups.
[x] Natural hand control with vertical or horizontal movement.
[ ] Flipped hand control with vertical or horizontal movement.

OR MAYBE something more explicit?
**Customize hand movement**
If needed, flip the hands that control the sim to support different camera setups.
[x] Natural hand control. Best with face-to-face camera using vertical hand movements.
[ ] Flipped hand control. Best with over-the-head camera using horizontal hands movement.

**Possible Toggle Interactions**
<img width="266" alt="image" src="https://user-images.githubusercontent.com/1902116/202498197-b29b5cf0-d7f6-4a1c-a4c6-2d6bde9c2387.png">
<img width="175" alt="image" src="https://user-images.githubusercontent.com/1902116/202498532-4f47355e-af49-4352-8d88-f16e02a93361.png">
<img width="117" alt="image" src="https://user-images.githubusercontent.com/1902116/202499238-381087ef-e7a9-4622-8f91-439c5e895da0.png">


**Possible Voicing Design:**
Focus on help text reading block, voice: "Customize hand movement. If needed, flip the hands that control the sim to support different camera setups."

Focus on toggle Interaction, voice: "Natural hand control. Best with face-to-face camera using vertical hand movements."
Up toggling to flipped hand control, voice: "Flipped hand control. Best with over-the-head camera using horizontal hands movement."

I hope this all makes sense.

**Comment by emily-phet** [comment]
Ahh - I didn't catch this until just now. I think we need only two *checkboxes*, not radio buttons. 

Horizontal and vertical movement is independent. My recommendation is to use the text I suggested above (using "flipped"), and for each of the two options there is a checkbox. The default is unchecked for both. 

Another option would be to have to sets of two radio buttons:
- Vertical option radio buttons: One radio button is for the "natural" state, the other radio button is for the "mirrored" state. 
- Horizontal option radio buttons: One radio button for the "natural" state, the other radio button for the "mirrored" state.

If @terracoda is on board with taking the approach of emphasizing the change in state, rather than describing the two different states possible for vertical and horizontal, then the two flipped checkboxes is the simplest route, and the one I recommend.

**Comment by terracoda** [comment]
I'll get back to this later this evening. I think we are finally getting on the same page.

**Comment by BLFiedler** [comment]
Popping into the issue just to note that (at least when I requested the ability to flip the camera feed), I was envisioning it much the way game developers implement control customization, in which case they use the word "inversion" or "inverting controls", "Invert x- or y- axis", etc.

In case that phrase is helpful, it is very common.

**Comment by terracoda** [comment]
OK, I prefer to keep it simple, too. Let's stick with checkboxes. I think this is what Emily is suggesting.

The words are still a bit confusing me. Am I supposed to describe an interaction that is customizing how the hands in the sim move, or how hand input operates?

**Customize hand movement** or **Customize hand operation**
If needed, flip hand operation to support different camera setups.
[ ] Flipped vertical hand movement.
[ ] Flipped horizontal movement.

Voicing design

**Comment by terracoda** [comment]
**Voicing Design**

_Move focus to reading block:_
> Customize hand movement. If needed, flip hand [[movement]] to support different camera setups.

Checking a checkbox with Voicing
_Move focus to first checkbox:_
> Flip vertical hand movement.

_Toggle checkbox with Space and here the context response:_
> Your right hand moves up and the sim's right hand moves down.

_Toggle checkbox again to unchecked with Space and here the context response:_
> Your right hand moves down and the sim's right hand moves down.

_Move focus to second checkbox:_
> Flip horizontal hand movement.

_Toggle checkbox with Space and here the context response:_
> Your right hand moves up and the sim's right hand moves down.

_Toggle checkbox again to unchecked with Space and here the context response:_
> Your right hand moves down and the sim's right hand moves down.

I don't think this is working.
Met with @BLFiedler

**Comment by BLFiedler** [comment]
@terracoda and I met briefly to discuss this. Based on the implementation in the sim, which functionally is just flipping the X or Y axis of the camera, I suggested this be taken more from a troubleshooting perspective to address what each checkbox will do for your given camera orientation. Goals for the below is to be very explicit about exactly what each checkbox does, as well as the contexts you might use them, as well as providing more detail about the camera-sim connection. Proposed something similar to the below text:
____

### Camera Input: Hands Troubleshooting

The simulation assumes your camera is facing you as with a traditional laptop webcam. If needed, use the options below to change the camera detection of your hands to match your hand movements.

Are your hands mapped to the wrong hands in the sim? 
[ ] Flip camera Y-axis. 

Are your hands going in the wrong direction in the sim?
[ ] Flip camera X-axis.

**Comment by terracoda** [comment]
Scenarios we are troubling shooting.

**Default scenario (nothing needs to be checked)**
User has a face-to-face camera and their own hands operate the same hands in the sim, and hand direction is mapped identically in the sim.
<img width="964" alt="image" src="https://user-images.githubusercontent.com/1902116/202747562-2607da8c-200c-4dac-81d6-d853932aeabd.png">

**When the physical camera is turned on the Y-axis...**
...the camera detection also needs to be rotated on the Y-axis (see incorrect hand mapping in video screen). To fix this issue the user likely needs to check "Flip camera Y-axis."
<img width="945" alt="image" src="https://user-images.githubusercontent.com/1902116/202747818-9d14d7b7-abbb-4b46-9369-5a2ddea521a9.png">

**When the physical camera is turned on the X-axis (e.g. over-head)...**
...the camera detection also needs to be rotated on the X-axis (see incorrect hand mapping in video screen). To fix this issue the user likely needs to check "Flip camera X-axis."
<img width="949" alt="image" src="https://user-images.githubusercontent.com/1902116/202748153-fe6e275b-c1dc-4be4-aedf-f194de68db43.png">

**Comment by terracoda** [comment]
###  Troubleshooting Camera Detection
The simulation assumes your camera is facing you as with a traditional laptop webcam. If this is your setup, you are ready to go.

If your camera is behind you, physically rotated on the Y-axis, your hand movements may feel like they map to the wrong objects in the sim. Try flipping the Y-axis.
[ ] Flip camera Y-axis. 

If your camera is over head, physically rotated on x-axis, your hands movements may feel like they move objects in the wrong direction. Try flipping the x-axis. 
[ ] Flip camera X-axis.

If your camera is behind you and over head, you may need to flip both the Y-axis and the X-axis.

**Comment by terracoda** [comment]
@BLFiedler I generalized the language a little bit.

**Comment by terracoda** [comment]
Actually, my version is way too long, let's try a very slightly tweaked version of @BLFiedler 's version

### Troubleshooting Camera Input: Hands

The simulation assumes your camera is facing you as with a traditional laptop webcam. If your camera setup is different, use the options below to change the camera detection of your hands to match your hand movements.

Are your hands mapped to the wrong objects in the sim?
[ ] Flip camera Y-axis.

Are your hands moving objects in the wrong direction in the sim?
[ ] Flip camera X-axis.

**Voicing context responses:**
- Upon checking: Y-axis for camera flipped.
- Upon unchecking: Y-axis for camera no longer flipped.
- Upon checking: X-axis for camera flipped.
- Upon unchecking: X-axis for camera no longer flipped.

Note the other text will need to be read blocks for Voicing.

**Comment by terracoda** [comment]
@zepumph, I think this is ready.

**Comment by terracoda** [comment]
@zepumph, any questions, please ask. This was a monster issue. You only need to look at https://github.com/phetsims/ratio-and-proportion/issues/493#issuecomment-1320392707

**Comment by terracoda** [comment]
And, there is no artwork needed :-)

**Comment by emily-phet** [comment]
@terracoda @BLFiedler 
Here's a suggestion for less text, and leaning in to the specific reference to the "simulation hands". Bold is to emphasize where I made changes only, not intended for the end user. :) 

Here's my thinking:
- I figured once we mention "hands" in the sim once, we can assume this is sim-specific text and we can keep on using it. So, I used "simulation hands" throughout. 
- The camera recognition does not change based on these settings, only how what is recognized is mapped in the sim. So I tried to make the wording more aligned with that. Camera detection is not being changed. I also think it's less important to describe our default scenario and more important to indicate "here's where you make changes", so I shortened the text to jump straight to this sentiment. 
- Under the Voicing context responses - I just suggested using "not" instead of "no longer" since it's shorter and feels more direct. 
- I don't love the use of the word "troubleshooting", since it has a negative connotation, but I think I understand why this was chosen. I trust your judgement on it's use so my suggestion below has it in. :) A bit of an aside, but there is movement towards eventually having a direct link in the sim to the sim's Github repo, issue, and discussion features, so in the future we may be able to provide a more comprehensive troubleshooting guide for features in a location that is readily accessible from the preferences or current "PhET menu".  

These are just suggestions, and @terracoda if you feel strongly about any or all of the original text, please go ahead with it. I just had some ideas that could shorten and perhaps simplify the text, and thought that might be helpful to share. 

### Troubleshooting Camera Input: Hands

**If needed,** use the options below to change the behavior **of the simulation hands to match your hand movements**. 

Are your hands mapped **to the wrong simulation hands**?
[ ] Flip camera Y-axis.

Are your hands moving **the simulation hands in the wrong direction**?
[ ] Flip camera X-axis.

Voicing context responses:

Upon checking: Y-axis for camera flipped.
Upon unchecking: Y-axis for camera **not** flipped.
Upon checking: X-axis for camera flipped.
Upon unchecking: X-axis for camera **not** flipped.

**Comment by terracoda** [comment]
Thank you @emily-phet, I think the above adjustments are really good.

**Comment by terracoda** [comment]
Over to you @zepumph. 
This issue has taught me something about web cams :-)

**Comment by zepumph** [comment]
Alrighty!

How's this?

![image](https://user-images.githubusercontent.com/6856943/203686615-fafbfc85-bffe-445b-9366-d009b729a4cd.png)


I have a preference to keep things sim-independent. But I'm happy to keep this of you'd prefer. These options live best in common code, and not in RAP (other sims will likely want to implement features to flix these dimensions).

Let me know what you'd like to do.

**Comment by emily-phet** [comment]
Looks great!

**Comment by zepumph** [comment]
Alrighty. To cherrypick: The three commits above that aren't in Quad.

**Comment by terracoda** [comment]
Yep, looks great!

**Comment by zepumph** [comment]
Cherry picked and ready for confirmation in the new version.

**Comment by KatieWoe** [comment]
The control checkboxes are reversed in RC.2. The Y axis box switches direction and the x axis box switches hands. This is the opposite of what is described.

**Comment by zepumph** [comment]
Yes thanks. Let's pick this up and cherry pick it in https://github.com/phetsims/ratio-and-proportion/issues/538. Everything here is done as far as I know. Thanks all!
