### ISSUE TITLE
Support mediaPipe on insecure sites

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#496]
from https://github.com/phetsims/ratio-and-proportion/issues/494 and https://github.com/phetsims/ratio-and-proportion/issues/472, @jessegreenberg and I found that when you are on an insecure site, but set a flag/setting in the browser to still allow media access, you do not get the deviceID. This breaks the implementation for the new MediaPipe selection, as it assumes a blank deviceID means it hasn't been set yet.

**Comment by zepumph** [comment]
I believe I have this sorted out. It was simple once I understood the problem (something @jessegreenberg was invaluable in assisting with). Committed above. 

This code added to the end of the initialize function helped me feel confident!

```js

    setTimeout( () => {
      MediaPipe.stopStream( videoElement );
      MediaPipe.stopStream( videoElement );
    }, 10000 );

    setTimeout( () => {
      MediaPipe.startStream( videoElement, '' );
      // MediaPipe.stopStream( videoElement );

      setInterval( () => {
        MediaPipe.stopStream( videoElement );
        MediaPipe.startStream( videoElement, '' );
      }, 2000 );
    }, 15000 );
```

From here I will have people test a dev version I made.

@terracoda, can you please make sure this is link is working as expected, and let me know about any trouble, please unassign yourself when you have tried out the link (if all is good).


@marlitas, can you please try this out and make sure to switch devices. I believe it will work now, from investigation on Friday, but I would like to double check. Let's pair if you run into trouble.

**Comment by terracoda** [comment]
Both work for me!

**Comment by marlitas** [comment]
Looks great! Nice job and super fun!

**Comment by zepumph** [comment]
Yay! Thanks you two. We will move towards a QA test.
