### ISSUE TITLE
Support dynamic layout for changing locales

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#499]

**Comment by zepumph** [comment]
From a first pass, here is what it seems like we still will need to do:

- [ ] Support accessibleName, innerContent, and labelContent
- [ ] Support Voicing responses
- [ ] Support Keyboard help dialog common code
- [ ] Support AccordionBox title with dynamic layout

**Comment by zepumph** [comment]
Another pass after https://github.com/phetsims/scenery/issues/1442, in general it isn't going to be easy to convert describers, it is just a lot of content that is depending on strings. I don't think I'm going down that path.

**Comment by samreid** [comment]
I pushed a workaround for a type error:

```
tsc: ../../../ratio-and-proportion/js/create/CreateScreen.ts(31,9): error TS2322: Type 'TReadOnlyProperty<string>' is not assignable to type 'string'.
```

**Comment by zepumph** [comment]
I just realized that this effects the PhET brand too, because the all HTML will have a localization tab, so I think I need to support this generally.

**Comment by zepumph** [comment]
Make sure we are disposing these texts now, see https://github.com/phetsims/scenery-phet/issues/771

**Comment by zepumph** [comment]
From a conversation with @jonathanolson:

* When scaling: look at localBounds because those don't account for scale.
* Use Aliginbox/**VBox** or maybe a Manual constraint to make sure the layout scaling nodes are good.

**Comment by zepumph** [comment]
Noting we should work on https://github.com/phetsims/scenery-phet/issues/769 to get this done too.

**Comment by zepumph** [comment]
I punted quite a few times, please search for `StringProperty.value` to complete this work for description/voicing.

**Comment by zepumph** [comment]
Good progress today.

**Comment by zepumph** [comment]
- [ ] Dynamic switching to `ja` pushes the top scaling VBox to the right:
![image](https://user-images.githubusercontent.com/6856943/196823962-852cef08-9f40-44e1-9a15-a2a26375ab72.png)

**Comment by zepumph** [comment]
- [ ] Same with `my` on the create screen:
![Uploading image.png…]()

**Comment by zepumph** [comment]
- [ ] Editing the RatioLock string in studio pushes the whole bottom scaling VBox off to the right. We need to fix this!.
- [ ] 
![image](https://user-images.githubusercontent.com/6856943/196824417-f88c5787-be26-4fbf-8875-f1350acee744.png)

**Comment by zepumph** [comment]
- [ ] I encountered many spots where I added *StringProperty.value eagerly because I didn't want to overhaul Describers (meant only for Voicing/Description) without proper cause. There are many TODOs pointing to this issue because of that. 
- [ ] There are still many usages of StringUtils.fillIn because I didn't want to create a new Property every time I formulated a dynamic description string just to be passed to the UtteranceQueue and then promptly cause a memory leak. Basically all Describer types are not set up to have persistent Properties, and I would like to brainstorm with @jonathanolson if he thinks there are better patterns that I am not thinking of. at this time.

**Comment by zepumph** [comment]
Alright. I believe that we are unblocked here. The above two checkboxes in https://github.com/phetsims/ratio-and-proportion/issues/499#issuecomment-1284707711 have TODOs pointing here, and could be worked on in the future if desired, but I sorta feel like it isn't every going to be worth the effort, and we should apply the new patterns in the new description sims we implement.

**Comment by zepumph** [comment]
QA (@KatieWoe), can you please review the work done in this issue:

I was using https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.32/phet/ratio-and-proportion_all_phet.html?keyboardLocaleSwitcher&dev and ctrl + U/I helped test this a lot. Please ensure the below issues are resolved in this sim. 

- [ ] https://github.com/phetsims/ratio-and-proportion/issues/515
- [ ] https://github.com/phetsims/ratio-and-proportion/issues/516
- [ ] Keyboard help dialog supports dynamic locale switching.

**Comment by KatieWoe** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/515 also still has a problem. Sending this back to you @zepumph. Testing was done on the provided dev version.

**Comment by zepumph** [comment]
I think I fixed keyNode here, 
![image](https://user-images.githubusercontent.com/6856943/199794658-7add8e16-6526-4983-9335-f2a76e8993b3.png)


Can you give it another shot? I'm not sure why hebrew had blank keys.

**Comment by KatieWoe** [comment]
The overlapping looks much better. There are one or two other languages that also have blank keys btw.

**Comment by zepumph** [comment]
I created https://github.com/phetsims/scenery-phet/issues/786 for the blank keys. Closing. Please reopen if you feel differently.

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.

**Comment by zepumph** [comment]
Moved todos to https://github.com/phetsims/ratio-and-proportion/issues/552. Closing
