### ISSUE TITLE
Using Camera Input: Hands results in incorrect ratios

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#500]
**Test device**
MacBook Air m1 chip

**Operating System**
macOS 12.5.1

**Browser**
Safari + chrome

**Problem description**
For https://github.com/phetsims/qa/issues/831, when using Camera-input:hands, the color changes to dark green and the happy chime is heard before the correct ratio is obtained. For example, with the 1-10 scale and Challenge 1: if my left hand is at 2, the happy chime will be heard when my right hand is at ~3.5 and the screen will be dark green from ~3.5-4.5. 

**Steps to reproduce**
1. On the Discover screen, press the Tick Marks with Values icon
2. Choose a value with your left hand and then move your right hand to achieve 1:2 ratio.

**Visuals**

https://user-images.githubusercontent.com/87318828/188148358-352c5767-c003-4336-aaff-9da5e556cd79.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html?cameraInput=hands
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1322x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
This is a purposeful design decision due to the inherent inaccuracies with hand movement. If it seems totally way too graceful we can discuss further. Feel free to close.

**Comment by Nancy-Salpepi** [comment]
@zepumph I feel like it might be a bit confusing for learners to understand what a ratio is if there are multiple correct answers for the same challenge... 1:1.5, 1:2, 1:2.5

**Comment by zepumph** [comment]
Here are the current fitness values, we can definitely decrease it a little bit to improve this usability. @terracoda and I think it is up to @BLFiedler and @emily-phet to decide if we should lessen this value. 

```
// distance (in fitness) from max fitness that still indicates a successful proportion
  public IN_PROPORTION_FITNESS_THRESHOLD = 0.025;

  // distance (in fitness) from max fitness that still indicates a successful proportion when both hands moving in the
  // same direction. See RAPRatio.movingInDirectionProperty
  public MOVING_IN_PROPORTION_FITNESS_THRESHOLD = 0.3;

  // distance (in fitness) from max fitness that still indicates a successful proportion when interacting via MediaPipe.
  public MEDIA_PIPE_IN_PROPORTION_FITNESS_THRESHOLD = RAPQueryParameters.mpInProportionThreshold; // .3
```


So .3 is the current value. 

Can you please test with https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html?cameraInput=hands&showVideo&mpInProportionThreshold=.2, and feel free to change the query parameter value and see what feels best to you!

**Comment by BLFiedler** [comment]
I'm sorry, this was happening in issue #465 and was set to experiment with summer data collection and I did not revisit the default value for publication purposes. Thanks for catching this @Nancy-Salpepi!

It is nicer to have it slightly wider than the default 0.025, but 0.3 is actually a bit too much. I had used the query parameter to adjust this during summer experimentation/studies. 

`mpInProportionThreshold` = 0.075 loosens it enough to hit the ratio and give a bit of "wiggle room" on the left or right hand while ensuring the appropriate tick mark is within the circle of the corresponding hand (if aligning with tick marks).

@zepumph, go ahead and 

- [ ] Change the default value for hitting proportion using MediaPipe:  `mpInProportionThreshold` = 0.075

**Comment by BLFiedler** [comment]
Happy issue number 500? 🥳

**Comment by zepumph** [comment]
Excellent! Done above, @Nancy-Salpepi please test and make sure all is good for you. 

Also, since we are moving towards publication, I renamed the query parameter from `mpInProportionThreshold` -> `cameraInputInProportionThreshold`

**Comment by Nancy-Salpepi** [comment]
This range is looking much better @zepumph!

**Comment by zepumph** [comment]
Great thanks!
