### ISSUE TITLE
CT error: ordinal should match, expected: first, actual: ‪first‬, Position: 0.1, TickMarkView: VISIBLE, tick mark range: 10

### ISSUE THREAD

**Issue by samreid** [phetsims/ratio-and-proportion#502]
Unit tests are failing with: 

> ordinal should match, expected: first, actual: ‪first‬, Position: 0.1, TickMarkView: VISIBLE, tick mark range: 10

Discovered in https://github.com/phetsims/joist/issues/844

@zepumph can you please investigate or advise?

**Comment by zepumph** [comment]
Thanks. It was because we introduced embedding markings into strings that were using triple equals comparison. I don't want to change the sim code at all, but I used stripEmbeddingMarks for the tests. Closing
