### ISSUE TITLE
What should happen when one hand is used?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#503]
**Test device**
macbook air, m1 chip

**Operating System**
macOS 12.5.1

**Browser**
Safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/831, @KatieWoe and I both interpreted
> Can you use 1 hand to control a single hand.

to mean, that if my right hand was down, and I was only using my left, the hand on the left side of the screen would move. If I was using only my right hand, the hand on the right side of the screen would move. However, no matter which hand we use, it is always the hand on the left side that is moving. Is that the intended behavior?

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html?cameraInput=hands
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Language: en-US
Window: 1322x704
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
Yes, although we were totally aware of this behavior, and thought it would be acceptable for this publication, @terracoda and I just had a fun idea! We can have the current behavior be the general default, but then if the hand is located in the "other half" of the screen, we will make it map to the other sim hand. I don't foresee this being too challenging, but if it takes a while to implement we will give up, being cognizant of scope creep for this publication.

**Comment by zepumph** [comment]
@Nancy-Salpepi. Now a single can can control both sim hands, one at a time, depending on what side of the camera you are on. Will you please test this out on master and see how it goes? Just add `cameraInput=hands` on phettest. Let me know if you like it!

**Comment by zepumph** [comment]
Also tagging @terracoda only if she wants to try it out.

**Comment by Nancy-Salpepi** [comment]
@zepumph things work very nicely when my hand is clearly on one side or the other! 
The behavior gets a bit unpredictable if my hand is in the center--one hand may move and then the other--but I don't think that most users would have their hand in the middle. What do you think?

**Comment by Nancy-Salpepi** [comment]
@zepumph I also wanted to clarify something based on earlier comments that you made. 

Is the change you made is now the default? When using 1 hand: If my left or right hand is on the left side of the camera, it moves the left hand. If my left or right hand is on the right side of the camera, it moves the right hand.

**Comment by zepumph** [comment]
Yes, there is no detection for what "hand" you are actually using to control, just the position of said hand. I agree the middle of the camera is a bit weird, but hopefully they will just move to either side when that happens, which is likely obvious because of how it will effect each hand individually. Does that seem good to you?

**Comment by Nancy-Salpepi** [comment]
yes it does @zepumph!
