### ISSUE TITLE
Circle hand symbol doesn't freeze hands with large movement

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#504]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/831
I noticed that the gesture freezes the hands well if you aren't moving too much, but if you try to drop your hands or move them a lot, the hands move again. This seems to be the intended behavior to pair with voicing. However, I was trying to use it to keep the hands in place while dropping my hands to do something else with the sim, such as use the lock ratio checkbox or turn on lines. This did not work well.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html?cameraInput=hands
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
This is definitely a bummer, but we have not really set up a way to stop interacting with MediaPipe at this time. We will need to handle this later when we develop a more complete Camera Input featureset (next publication).

As for the "freeze" gesture, @terracoda and I have both felt like it could be a bit more responsive, I will take a look to see if I can improve on it without sacrificing the snappiness of the general hand movement.

**Comment by zepumph** [comment]
A gesture to "stop" interacting isn't in the cards for this release. When next we work more fully on gesture support as a whole in sims, we will tackle that problem. Closing
