### ISSUE TITLE
Sim doesn't load with Preview HTML in Studio

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#511]
with macOS 12.5.1 and safari 15.6.1

For https://github.com/phetsims/qa/issues/831 in the studio wrapper:
After pressing Preview HTML, copying and saving code as html in atom, the saved sim will not load. The screen is white with several errors in the console.

I was able to replicate this on master using both Ratio and Proportion and Gravity and Orbits (FYI @samreid), but not with the most recent dev version of Gravity and Orbits (1.6.0-dev.3).

<img width="500" alt="Screen Shot 2022-09-09 at 7 17 49 AM" src="https://user-images.githubusercontent.com/87318828/189344230-3fbcb8bb-c924-42a8-9202-c79be006ba9e.png">

**Comment by samreid** [comment]
I think there is a constraint for the “unbuilt” mode that the wrapper has to be put in a certain relative path to be able to find things. Oh, and it looks like a transpiler has to be running too? I saw a path to chipper/dist.  This may not work. We will have to decide as a team whether (a) QA team should be able to test unbuild mode studio file save or (b) testing should only be done on built versions.  Right now, limiting testing to built versions seems appropriate.  Testing unbuilt mode would require QA teams checking out all code and running transpilers (I think).

**Comment by zepumph** [comment]
It is expected that this will not work in unbuilt mode, but it should definitely work in the build version of the sim. I followed these steps and was able to successfully load the standard wrapper via copy/paste with "preview".

* Go to https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet-io/wrappers/studio/
* click on Preview HTML Button
* copy and paste the text into a file in my desktop folder
* Launch file:///C:/Users/mjkauzmann/Desktop/test.html


@Nancy-Salpepi can you confirm you experienced this on a built version?

**Comment by Nancy-Salpepi** [comment]
@zepumph--It is working correctly for a built version after trying again. I went back to my original file and I could see that there was no Target API version listed as there should be, so I must have been in an unbuilt version. Sorry about that.
