### ISSUE TITLE
Voicing cuts off when you click on a hand

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#514]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/831.
When you click on a hand with voicing it will describe the hands, then start to say you can move them, but cut itself off.
**Steps to reproduce**
1. Turn on voicing and check the three checkboxes
2. Go to one of the pages
3. Click on one of the hands and listen.

**Visuals**

https://user-images.githubusercontent.com/41024075/189738876-0fa236e8-9459-4c6c-aebc-500567ccc839.MOV

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
I'm pretty sure this is a bug. Just clicking the hands is done to check their position, no movement happens. And a partial sentence is read out. I can get sound fine, I'm not sure why it isn't playing for you.

**Comment by zepumph** [comment]
OOps. The sound issue was specific to my computer, and a restart fixed it. Ok thanks! I'll take a look. Sorry for the unnecessary ping.

**Comment by zepumph** [comment]
Ok ok. I see what is happening, and the `printVoicingResponses` query parameter is very helpful. There is no bug that I can see, but the way that the response is read makes it seem like there is more to say. The string when you just click on a hand with all object/context/hint responses on is: `Left Hand, hands, at challenge ratio, Move hands.`. The "Move hands" is the hint. 

Does this seem like what you were encountering?

**Comment by KatieWoe** [comment]
Yes it does. I thought "Move hands" was the start of something like "Move hands to explore"

**Comment by zepumph** [comment]
Righto! Thanks for the bug report, also I'm not sure if you knew that `printVoicingResponses` existed, or if you want to add it to QA doc for voicing testing. I'm ready to close this issue. Let me know if there is anything else. Thank you!
