### ISSUE TITLE
Translations may now overlap objects or be too long to be fully shown

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#516]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/831
Strings that are longer than in English now overlap other objects, when they did not in published. This seems to only be seen in existing translations, not with string tests.

**Visuals**
<img width="960" alt="toolong2" src="https://user-images.githubusercontent.com/41024075/189759444-1908cd36-06dd-4122-90c5-e9868689a00c.png">
<img width="510" alt="toolong" src="https://user-images.githubusercontent.com/41024075/189759447-f9d0806a-7c1b-45f3-a055-de3a977e43cf.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Proporcijas un attiecības‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
Yes, this is expected as of now because I didn't realized we needed to support this for this release, but it will be covered in https://github.com/phetsims/ratio-and-proportion/issues/499. Please note that issue for all dynamic layout/i18n/ dynamic locale changing.

**Comment by zepumph** [comment]
This has been fixed by https://github.com/phetsims/ratio-and-proportion/issues/499
