### ISSUE TITLE
Voicing may repeat itself in studio

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#517]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/831
When I turn voicing on or off in Studio it repeats itself. I.E. it says "Voicing off, voicing off" but it doesn't seem to do so in the main sim, or when the sim is launched.
**Steps to reproduce**
1. Go to studio
2. Turn on voicing in the sim
3. Turn off voicing

**Visuals**

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-dev.31/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-dev.31 2022-08-24 16:50:40 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by zepumph** [comment]
This is byproduct of the fact that Studio creates archetypes. The code in VoicingPanelSection assumes that it has total control over the voicingProperty changing. Instead of adding voicing code to a Property listener, can we make it occur in response to user input on the toggle switch that this voicing dialog section controls. We could also not add this listener if we know we are an archetype, but I'm not sure that we would know that.

Furthermore, in the future, if we had another way of toggling this, and we wanted a different voicing string there, this code would bleed into that as well.

I want to bring up https://github.com/phetsims/utterance-queue/issues/83 even though this is a bit different. Over there we have an archetype that wants to alert (for description), but isn't connected to a display.


@jessegreenberg can we tie this to the toggleSwitch instead of the Property? What do you recommend?

**Comment by jessegreenberg** [comment]
VoicingPanelSection makes this assumption but so does PreferencesToggleSwitch. I think the way to fix this is to instrument ToggleSwitch similarly to Checkbox. It looks like the way is already paved by sound code in ToggleSwitch so this may not be too bad.

But the tricky part for the Voicing PreferencesToggledSwitch is that it still needs to use `speakIgnoringEnabled`. So we might need to forward that option to ToggleSwitch somehow.

**Comment by jessegreenberg** [comment]
- Is this also an issue for "Sim sound on/off" responses? Those are alerted way over in NavigationBarToggleButton (also linked to the Property). Do we need to speak these identical responses through both the NavigationBarAudioToggleButton and the PreferencesToggleSwitch for "All Audio"?

**Comment by zepumph** [comment]
I believe that this is the right direction:

<details>

```diff
Index: sun/js/ToggleSwitch.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/sun/js/ToggleSwitch.ts b/sun/js/ToggleSwitch.ts
--- a/sun/js/ToggleSwitch.ts	(revision 70b312f712fa47eebada926844c0055d6cab5f79)
+++ b/sun/js/ToggleSwitch.ts	(date 1664996064987)
@@ -29,6 +29,7 @@
 import switchToLeftSoundPlayer from '../../tambo/js/shared-sound-players/switchToLeftSoundPlayer.js';
 import switchToRightSoundPlayer from '../../tambo/js/shared-sound-players/switchToRightSoundPlayer.js';
 import Property from '../../axon/js/Property.js';
+import Emitter from '../../axon/js/Emitter.js';
 
 // constants
 const DEFAULT_SIZE = new Dimension2( 60, 30 );
@@ -75,6 +76,7 @@
   private readonly disposeToggleSwitch: () => void;
   public readonly switchToLeftSoundPlayer: TSoundPlayer;
   public readonly switchToRightSoundPlayer: TSoundPlayer;
+  public readonly toggledEmitter: Emitter<[ T ]>;
 
   /**
    * @param property
@@ -196,7 +198,7 @@
     const accumulatedDelta = new Vector2( 0, 0 ); // stores how far we are from where our drag started, in our local coordinate frame
     let passedDragThreshold = false; // whether we have dragged far enough to be considered for "drag" behavior (pick closest side), or "tap" behavior (toggle)
 
-    // Action that is performed when the switch is toggled.
+    // Action that is performed when the switch is toggled from user input.
     // Toggles the Property value and sends a phet-io message with the old and new values.
     const toggleAction = new PhetioAction( value => {
       property.value = value;
@@ -209,6 +211,8 @@
       phetioEventType: EventType.USER
     } );
 
+    this.toggledEmitter = toggleAction.executedEmitter;
+
     // Gets the value that corresponds to the current thumb position.
     const thumbPositionToValue = () => ( thumbNode.centerX < trackNode.centerX ) ? leftValue : rightValue;
 
Index: joist/js/preferences/PreferencesToggleSwitch.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/joist/js/preferences/PreferencesToggleSwitch.ts b/joist/js/preferences/PreferencesToggleSwitch.ts
--- a/joist/js/preferences/PreferencesToggleSwitch.ts	(revision 0f2668684a76091bc771b646ff70faf66643f965)
+++ b/joist/js/preferences/PreferencesToggleSwitch.ts	(date 1664996385694)
@@ -115,9 +115,8 @@
       toggleSwitch.addChild( options.rightValueLabel );
     }
 
-    // a11y - Describe the change in value if context responses were provided in options. Listener needs to be
-    // removed on dispose.
-    const valueListener = ( value: T ) => {
+    // a11y - Describe the change in value if context responses were provided in options.
+    toggleSwitch.toggledEmitter.addListener( ( value: T ) => {
       const alert = value === rightValue ? options.rightValueContextResponse : options.leftValueContextResponse;
 
       if ( alert ) {
@@ -126,8 +125,7 @@
           contextResponse: Utterance.alertableToText( alert )
         } );
       }
-    };
-    property.lazyLink( valueListener );
+    } );
 
     // This component manages disabledOpacity, we don't want it to compound over subcomponents.
     toggleSwitch.disabledOpacity = 1;
@@ -175,7 +173,6 @@
     }
 
     this.disposePreferencesToggleSwitch = () => {
-      property.unlink( valueListener );
       toggleSwitch.dispose();
     };
   }


```
</details>

But I still haven't fixed the main issue, which is:

https://github.com/phetsims/joist/blob/85774f55bd3e2a50b512685f8cbd3a6dfdafcefa/js/preferences/VoicingPanelSection.ts#L251-L263

**Comment by zepumph** [comment]
@jessegreenberg and I spoke, and we feel like it would be good to add support for voicing into ToggleSwitch directly. Then voicingPanelSection's link to the audioEnabledProperty can still use the newly public toggledEmitter as a listener from input instead of just a Property listener.

**Comment by zepumph** [comment]
@emily-phet and I discussed this today, and conceptually it makes a lot more sense that we would listen to the Property. Perhaps we can tackle this in a different way, where we ensure that archetypes don't do this voicing logic.

**Comment by zepumph** [comment]
This patch will be best here, but let's also move isInsidePhetioArchetype to PhetioObject instead of ParallelDOM.

```
Index: js/preferences/VoicingPanelSection.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/preferences/VoicingPanelSection.ts b/js/preferences/VoicingPanelSection.ts
--- a/js/preferences/VoicingPanelSection.ts	(revision 4cda97f21ac4f4fcca07ce07775997a6699d4554)
+++ b/js/preferences/VoicingPanelSection.ts	(date 1665761041596)
@@ -109,7 +109,7 @@
     // Voicing feature only works when running in English. If running in a version where you can change locale,
     // indicate through the title that the feature will only work in English.
     const titleStringProperty = ( localeProperty.validValues && localeProperty.validValues.length > 1 ) ?
-                        voicingEnglishOnlyLabelStringProperty : voicingLabelStringProperty;
+                                voicingEnglishOnlyLabelStringProperty : voicingLabelStringProperty;
 
     // the checkbox is the title for the section and totally enables/disables the feature
     const voicingLabel = new Text( titleStringProperty, PreferencesDialog.PANEL_SECTION_LABEL_OPTIONS );
@@ -256,7 +256,11 @@
         // in the English locale.
         voicingEnabledUtterance.alert = enabled ? voicingEnabledStringProperty :
                                         ( localeProperty.value.startsWith( 'en' ) ? voicingDisabledStringProperty : voicingOffOnlyAvailableInEnglishStringProperty );
-        voicingManager.speakIgnoringEnabled( voicingEnabledUtterance );
+
+        // DOC
+        if ( !this.isInsidePhetioArchetype() ) {
+          voicingManager.speakIgnoringEnabled( voicingEnabledUtterance );
+        }
         this.alertDescriptionUtterance( voicingEnabledUtterance );
       }
     };

**Comment by zepumph** [comment]
Committed above, and is working well. We cannot move isInsidePhetioArchetype to PhetioObject because it is about Node ancestry, not PhetioObject (phetioID/tandem) ancestry. Closing
