### ISSUE TITLE
Some preferences maintained when opening standard wrapper

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#520]
**Test device**
MacBook Air (m1 chip)

**Operating System**
MacOS 12.5.1

**Browser**
Safari 15.6.1

**Problem description**
For https://github.com/phetsims/qa/issues/831 and related to https://github.com/phetsims/joist/issues/744
STUDIO: In the audio tab of the preferences menu, the following states carry over to the standard wrapper:
      - Audio features off
      - Sounds off
      - Extra sounds on

Should any of the preferences carry over to the standard wrapper?  

From slack:
Nancy Salpepi
  [2:51 PM](https://phetsims.slack.com/archives/D028H98J7U2/p1663181486272739)
Hi Michael!
Quick question about the preferences menu and studio….what settings should be maintained when I open the standard wrapper? For example, extra sounds will stay checked, but interactive highlights won’t.

Michael Kauzmann
:house_with_garden:  [4:11 PM](https://phetsims.slack.com/archives/D028H98J7U2/p1663186297547089)
No, we specifically decided against it. Please make an issue with the confusion/worry and assign to Amy to note, confirm and to close. Also please tag https://github.com/phetsims/joist/issues/744

**Comment by zepumph** [comment]
We spoke about this during PhET-iO meeting today, and confirmed that "preferences" in general should not be stateful (persisting through to the standard wrapper). General audio (audioManager.enabledProperty) should be stateful. We will make sound and extraSound phetioState:false.

**Comment by samreid** [comment]
I applied the patch and regenerated API files, closing.

**Comment by samreid** [comment]
Or perhaps a review phase would be good if there's time?

**Comment by zepumph** [comment]
Yes great thanks.
