### ISSUE TITLE
Voicing Repeats "Everything Reset"

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#524]
**Test device**
MacBook Air m1 chip

**Operating System**
13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/852, after pressing Reset All, voicing repeats "Everything Reset" statement. 

**Steps to reproduce**
1. Go to either Screen
2. Turn on Voicing and check the Sim Voicing Options
3. Press the Reset All button.

**Visuals**

https://user-images.githubusercontent.com/87318828/202026764-01b2c452-5d98-4eb5-ae2b-42bf365d528f.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1544x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
Minor bug from https://github.com/phetsims/scenery-phet/commit/7de4c8738e13848ce1f1e35c97eb9d916b490624 while working on https://github.com/phetsims/scenery-phet/issues/780. 

To cherry pick: https://github.com/phetsims/scenery-phet/commit/36fbcee4a51368a0a0fd2d38ef8e39b7a3ba1082

**Comment by zepumph** [comment]
Done and ready for confirmation in next version.

**Comment by Nancy-Salpepi** [comment]
This looks good in 1.2.0-rc.2 with mac + chrome/safari.
