### ISSUE TITLE
Voicing says "Property Number" before each item in keyboard nav dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#525]
**Test device**
MacBook Air m1 chip

**Operating System**
13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/852, before each item in the keyboard dialog, voicing says "property number ...." 

**Steps to reproduce**
1. Turn on Voicing
2. Open Keyboard Nav dialog
3. Click  on or tab to any section. 

**Visuals**

https://user-images.githubusercontent.com/87318828/202043660-e726b2c3-2336-4a92-b2f9-85f4cd605926.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1544x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
Good catch, noting https://github.com/phetsims/scenery-phet/issues/769 here because that is where this showed up. It would be best to fully support this with a patternStringProperty, but this commit will be best to cherry pick. I'll note over in the other issue to ensure a more thorough solution.

**Comment by zepumph** [comment]
Cherry pick: the above 2 commits!

**Comment by zepumph** [comment]
Done and ready for confirmation in next version.
