### ISSUE TITLE
Voicing stops when only one hand is used with ?cameraInput=hands

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#527]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/852, when using ?cameraInput=hands, voicing only works when both hands are in view. I wasn't sure if this was intentional or not. 

**Steps to reproduce**
1. Turn on Voicing and check Sim Voicing Options checkboxes
2. Lower one hand so it is out view and move the other up and down --no Voicing is heard
3. Raise your hand so that both are in view --Voicing returns

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.1/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.1 2022-11-11 22:40:36 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1544x712
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
There is no detection of the voicing cue with one hand. @emily-phet is this something you would like me to work on? If not, I recommend closing this issue and tracking future camera input hands work in a central spot.

**Comment by zepumph** [comment]
Sounds great! I noted it in https://github.com/phetsims/ratio-and-proportion/issues/512#issuecomment-1327866985, and we can keep that list going for next time. Closing
