### ISSUE TITLE
Camera troubleshooting controls seem switched

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#538]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/863, the controls for camera troubleshooting seem to be flip-flopped. When I check Flip Camera Y-axis, the hand direction changes instead of hand mapping. When I check Flip Camera X-axis, hand mapping changes instead of hand direction. 

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.2/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.2 2022-12-05 22:59:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Language: en-US
Window: 1515x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
Oops! When we updated the doc we kinda swapped the definition of the underlying Properites and I didn't actually test as thoroughly as I should have. Thanks for the bug and sorry for the time.

**Comment by zepumph** [comment]
Cherry picked. QA, feel free to close if all is well.

**Comment by Nancy-Salpepi** [comment]
Looks fixed in 1.2.0-rc.3. Closing
