### ISSUE TITLE
Expand colored background 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#54]
During a design meeting on 5/21, @amanda-phet pointed out at the colored background only extends to the sim border. With wide screen boundaries, white edges can be seen. She strongly preferred if the colored background extended beyond the sim boundary.

**Comment by zepumph** [comment]
Great idea! I'm not sure why I didn't just do that to begin with. Implemented above.

**Comment by emily-phet** [comment]
Looks great!
