### ISSUE TITLE
Voicing turns on after entering a menu or dialog

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#541]
**Test device**
MacBook Air (m1 chip) and Chromebook

**Operating System**
macOS 13.0.1

**Browser**
safari and chrome

**Problem description**
For https://github.com/phetsims/qa/issues/863, after turning Voicing off in the Toolbar, entering/exiting the PhET Menu, Preferences dialog, or Keyboard Shortcuts dialog turns Voicing on (even though switch is still in off position). 

**Steps to reproduce**
1. In the preferences menu turn on Voicing and check all Sim Voicing Options
2. In the toolbar, turn off Sim Voicing
3. Click on the Keyboard Shortcuts dialog (or preferences or Phet menu)
4. Press Esc or click outside box
5. Move a hand with the mouse, or tab through the sim with keyboard nav--Voicing is on

I was able to reproduce this in published GFLB. 
EDIT: I can't reproduce in published GFLB. It must have been a caching issue. Sorry.

**Visuals**

https://user-images.githubusercontent.com/87318828/207389613-9c1c87af-1c0d-448b-84ba-500ae3084161.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.2/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.2 2022-12-05 22:59:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1581x816
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
Looks like a bug! Thanks

**Comment by jessegreenberg** [comment]
The above commit is a way to fix it. @zepumph can you please review?

**Comment by zepumph** [comment]
Amazing! Thanks.

**Comment by zepumph** [comment]
Cherry picked. QA, feel free to close if all is well.

**Comment by Nancy-Salpepi** [comment]
This is still broken in rc.3. 
Steps:
1. Turn on Voicing in the Preferences dialog
2. Turn off Voicing in the Toolbar
3. Turn Voicing off and then on in the Preferences dialog
4. Exit Preferences dialog
5. Click on or tab to anything--Voicing is on even though the toggle is still in the "off" position in the toolbar.

**Comment by Nancy-Salpepi** [comment]
Noting that I don't see the issue in https://github.com/phetsims/ratio-and-proportion/issues/541#issuecomment-1370939446 in Friction 1.6.0-dev.28

**Comment by jessegreenberg** [comment]
Thanks @Nancy-Salpepi, that helped identify it. It looks like the fix was cherry picked into a release branch but just didn't make it into dependencies.json for this sim. I confirmed I am not seeing this in Friction 1.6.0-dev.28 or master.

**Comment by zepumph** [comment]
Oops! I'll make sure that this is fixed in the next rc.

**Comment by zepumph** [comment]
It is in the next rc. Feel free to close in the spot check.

**Comment by Nancy-Salpepi** [comment]
This looks good in rc.4
