### ISSUE TITLE
Larger keyboard jumps don't work

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/ratio-and-proportion#542]
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome and Firefox
**Problem description**
For https://github.com/phetsims/qa/issues/863
When using keyboard nav, pgup, pgdn, home, and end all behave like the arrow keys rather than their described slider behavior of jumping larger increments. This behavior is not seen in the published version of the sim.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.2/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.2 2022-12-05 22:59:52 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0
Language: en-US
Window: 1536x731
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0
Vendor: Mozilla (ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0))
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by KatieWoe** [comment]
@Nancy-Salpepi says she did not see this on her Mac device.

**Comment by stemilymill** [comment]
i don't have pgup and pgdn on my laptop, but home and end behaved correctly on win10

**Comment by KatieWoe** [comment]
This may be somewhat device dependent, but these commands did work as expected on the published sim, so something is still odd here. @zepumph let me know if pairing would help. I'm on my personal device at the moment since I'm working from home today.

**Comment by KatieWoe** [comment]
I'm seeing the same thing on master with other sims such as Gravity Force Lab

**Comment by KatieWoe** [comment]
A number of published sims are showing the bug however. I'm not sure why only this device seems to be impacted.

**Comment by Nancy-Salpepi** [comment]
I don't see any issues on with mac or chromebook.

**Comment by KatieWoe** [comment]
This also isn't happening on my work Win 11 device. Really not sure what's up here.

**Comment by jessegreenberg** [comment]
These keys worked OK for me. @KatieWoe do those keys work on basic sliders outside of PhET like the "typical range slider" here? http://htmlpreview.github.io/?https://github.com/phetsims/a11y-research/blob/master/reader-intro.html

**Comment by KatieWoe** [comment]
They work as expected on the page linked above.

**Comment by jessegreenberg** [comment]
Due to the holidays we won't be able to investigate this until after 1/4/22.  I don't think this should block any publications, in case another RC is ready before then.

**Comment by jessegreenberg** [comment]
@KatieWoe and I were able to test and identify that this is a problem with number pads. The "Home"/"End" keys on my number pad are behaving the same way. This makes it so much easier to debug.

With this information we can take it to sun and fix AccessibleValueHandler. @zepumph FYI we can probably fix this but I don't know if it should block publication.

**Comment by zepumph** [comment]
@jessegreenberg found a good solution in https://github.com/phetsims/sun/issues/819, I'd like to cherry pick it in to the next rc.

**Comment by zepumph** [comment]
Cherry picked and ready for review. Please close if all is good.

**Comment by KatieWoe** [comment]
Looks good on master!
