### ISSUE TITLE
VoiceOver on iPad says 'end' three times when reading through screens in nav bar

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/ratio-and-proportion#544]
**Test device**
iPad 9th generation

**Operating System**
16.1.1

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/863, when I have VoiceOver read through the entire screen, it says 'end' 3 times after describing the 3 screens in the nav bar.

@KatieWoe confirmed that is happens on her iPad as well. 

**Steps to reproduce**
1. Turn on VoiceOver
2. Once you are in the sim, swipe up with 2 fingers to let VO read through everything

**Visuals**

https://user-images.githubusercontent.com/87318828/207691670-dcb558dc-dc80-42e3-bab0-084b46a936dd.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Ratio and Proportion‬
URL: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.2.0-rc.2/phet/ratio-and-proportion_all_phet.html
Version: 1.2.0-rc.2 2022-12-05 22:59:52 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Language: en-US
Window: 1581x816
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by zepumph** [comment]
@emily-phet and I feel like this is a feature of VoiceOver and not worth thinking about. Closing
