### ISSUE TITLE
Cherry pick from https://github.com/phetsims/friction/issues/314

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#546]
This one please: https://github.com/phetsims/sun/commit/e46a6bb6c08dea9d85bbfb9067664c57c8891edf

**Comment by zepumph** [comment]
done, ready to close in next rc.

**Comment by zepumph** [comment]
To confirm fixed, please follow steps in https://github.com/phetsims/friction/issues/314#issue-1509470232 and feel free to close.

**Comment by Nancy-Salpepi** [comment]
I no longer hear "close" at all in rc.4

FYI @jessegreenberg you mentioned in https://github.com/phetsims/friction/issues/314#issuecomment-1371261502 that I should still hear "Toolbar hidden" and "Toolbar shown" but that isn't what happens in the published sims with Voicing. 

If that is OK. Feel free to close this issue @zepumph @jessegreenberg

**Comment by jessegreenberg** [comment]
Oh that is good to know, thanks @Nancy-Salpepi. I believe that the published sims are incorrect and my comment in https://github.com/phetsims/friction/issues/314#issuecomment-1371261502 is best.

Ill let @zepumph close since he is responsible dev.

**Comment by zepumph** [comment]
Ok. I believe I should close this then. Thanks all!
