### ISSUE TITLE
Grid options - changing from aqua radio button to scene selection style  

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#55]
I like the look and feel of these buttons in the Area Model sims.
<img width="293" alt="Screen Shot 2020-05-22 at 7 08 42 AM" src="https://user-images.githubusercontent.com/5109055/82677713-4c752c00-9bfd-11ea-9890-201b4ff84a4f.png">

I'd like to see if this style can result in the desired sequence of interactions we want. 
I've requested artwork to fit this style in phetsims/tasks#1036.

**Comment by zepumph** [comment]
Sounds great. Let me know when you have icons for this and I can add them in.

**Comment by emily-phet** [comment]
Working on those icons now.

**Comment by zepumph** [comment]
The scene-selection-like radio buttons have been implemented above given the icons from https://github.com/phetsims/tasks/issues/1036#issuecomment-637690810. I feel like they need some pixel polishing, but this was as far as I wanted to go without getting a designer's eyes on it. Up for review. . .

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/83580807-7970eb00-a4e9-11ea-9d6f-89cd46927bf5.png)

**Comment by emily-phet** [comment]
Let's discuss this on Tuesday. I agree, they can probably use a little tweaking, but it's not obvious to me what direction to go.

**Comment by zepumph** [comment]
Today during design meeting, we got feedback on the grid ratio buttons:

@amanda-phet offered to clean up the icons a bit. She wanted to make them have transparent backgrounds, and to make them a bit less "fuzzy" for the size that we have the buttons at right now. @amanda-phet the ai file is https://github.com/phetsims/ratio-and-proportion/blob/master/assets/Gridlines.ai

**Comment by emily-phet** [comment]
@amanda-phet Please refine these icons however you think best. 
One question about transparent background, did you mean you thought the success feedback color should show through, or did you mean transparent background in a different way?

**Comment by amanda-phet** [comment]
@emily-phet Here is what I'm seeing:
![image](https://user-images.githubusercontent.com/7852916/85306411-ad498b80-b46b-11ea-99d6-db5bfe237ab9.png)

The eye has a transparent background, but the other icons have a white background, so it makes for a strange white box when the button isn't selected. I can easily export the icons to have a transparent background instead of white. I was also thinking of offering an option that is higher resolution to see if that makes the grid icons a bit less fuzzy.

**Comment by amanda-phet** [comment]
@zepumph can you try integrating these icons and see how they look?

![numbered-grid-icon](https://user-images.githubusercontent.com/7852916/85307219-dcacc800-b46c-11ea-8845-38199ddfe386.png)
![grid-icon](https://user-images.githubusercontent.com/7852916/85307221-dd455e80-b46c-11ea-8228-00202d26f738.png)

**Comment by zepumph** [comment]
Added above. Thanks for the quick turnaround. I really like the transparent backgrounds.

**Comment by amanda-phet** [comment]
They look good to me as well! I will put my changes to the ai file in assets.  Then I imagine this issue can be closed.

**Comment by emily-phet** [comment]
@amanda-phet Thanks!
