### ISSUE TITLE
Address `strictAxonDependencies: false`

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/ratio-and-proportion#554]
For https://github.com/phetsims/axon/issues/441, @samreid added several `strictAxonDependencies: false` to this sim.  I'll take a stab at addressing them, then pass this issue on to the responsible developer (@zepumph).

**Comment by pixelzoom** [comment]
All uses of `strictAxonDependencies: false` were addressed in the above commits.  Over to @zepumph to review. Close if OK.

**Comment by zepumph** [comment]
Amazing, thank you.
