### ISSUE TITLE
Add a second screen with custom ratio

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#58]
From https://github.com/phetsims/ratio-and-proportion/issues/56#issuecomment-636890198, we are going to add a second screen. This will have the same Ratio implementation, but with additional UI. Here is the sketch for it that @BLFiedler made.

![image](https://user-images.githubusercontent.com/47331395/83423837-c6b96380-a3e8-11ea-8104-168350b4a6db.png)

**Comment by emily-phet** [comment]
adding this comment from #56 here:

@zepumph we may end up wanting the radio buttons (none, grid, numbered grid), and the accordion box (0-10, 0-20, 0-30) placed under the "My Challenge" collapsible box...so if it's helpful, you might want to be anticipating that possible change.

**Comment by zepumph** [comment]
My first pass on this is complete. 

The main work done here is as follows:
* Refactoring logic used in both screens into common code
* Addition of the "My Challenge" accordion box control to specific the target ratio
* Refactor of `gridBaseUnitProperty` and the addition of the combo box to control it on the new screen.

Futher work:
* grid UI control in https://github.com/phetsims/ratio-and-proportion/issues/55
* screen names in #60 

@emily-phet @BLFiedler, please review.

**Comment by emily-phet** [comment]
Functionality looks great! I'd like to discuss the following in a Thursday design meeting:
Visual design refinements 
- Sizing of challenge control feature

Organization
- How to provide access to the grid range options, since they're only relevant when numbered grid is selected.

**Comment by zepumph** [comment]
During today's design meeting, much of the discussion centered around the second screen, so I will put most of the topics here. We decided to do the following:
- [ ] Increase the size of the number spinners
- [ ] Decrease font size of the ComboBox and label
- [ ] Make the accordion box corner radius match other buttons, use number-line-operations as an example. 
- [ ] Same with accordion box margins
- [ ] Rename grid range label to "Grid" or "Range" (we will discuss this on Tuesday).
- [ ] Have the grid combobox showing all the time, but when grid is invisible, then should a line through the comboBox display.
- [ ] Rename this screen to Create
- [ ] Rename sim to lowercase Ratio "and" Proportion
- [ ] Add space in between grid controls and My Challenge control
- [ ] Center hands above number spinners

**Comment by zepumph** [comment]
I scaled the number pickers by 1.2 (they were scaled at 1 before). Let me know if it should be larger.

**Comment by emily-phet** [comment]
Yes - let's set the width of the grey box to be the width of the radio button group. Then, let's scale the hands/pickers up so that they fill that box, leaving a moderate amount of padding between and to the box edges.

**Comment by zepumph** [comment]
> Please move the right-side controls (radio buttons, etc.) up, so that they start maybe 15% below the top right of the screen. Then, make the radio button groups on both screens at the same location, so when you switch between screens the radio button groups are in exactly the same position. So, we're moving all controls up higher on the screen in both screens.

In the above commit I did this, but it is half baked right now because I haven't yet made the challenge selector UI the same width on both screens. I'll do that now.

**Comment by zepumph** [comment]
>Rename grid range label to "Grid" or "Range" (we will discuss this on Tuesday).

I went with "Range" for now, and I think that once the spacing of controls is better, this will be clearest.

**Comment by zepumph** [comment]
Everything from the above checklists has been done. I marked this for design meeting to determine if we like the name "Range" for the combo box label on the Create screen. Otherwise everything is ready for review.

**Comment by emily-phet** [comment]
Getting close! A few tweaks to start - the reset all button needs to always be bottom right, and on the Create Screen, the font of the "My Challenge" needs to be larger while the "Range" and combobox need to be smaller. Essentially "My challenge" needs to stand out far more than the range combobox.

**Comment by zepumph** [comment]
From today's design meeting, we didn't mind "Range," and will go with that for now.

**Comment by zepumph** [comment]
@emily-phet, your suggestions were implemented above. The fonts were all 18pt. Now the range is 16, and the "My Challenge" is 22. Please review.

One more piece of pixel polishing here. Right now the position of the UI controls is based on a distance from the ratio. It would be a bit simpler, and potentially cleaner looking, if they were instead closer to the edge. What do you think about right justifying in line with the reset all button?

**Comment by emily-phet** [comment]
@zepumph 
I like the font sizes. Now the sizes of the accordion box header and the combobox need a little corresponding tweaking. Please:

- [ ] Decrease the size of the combobox by 10-20%. It looks disproportionately large compared to the "Range" font. We want it to look "a bit small", but not "that's so small I'm going to have a hard time tapping it successfully with my finger" small" - if that makes sense. 
- [ ] Add a little bit of padding to the top and bottom of the text in the accordion box header. The text looks a little squished right now.

For alignment: I agree, let's right align with rest all button, making sure there's not a big gap between the left side of the controls and the start of the right hand ratio region. So another way to think about this could be to 1) bring the reset all button right aligned underneath the controls, then right align all of the controls.

**Comment by zepumph** [comment]
>Add a little bit of padding to the top and bottom of the text in the accordion box header. The text looks a little squished right now.

By decreasing the font, the padding also increased, let me know if you want more than that.

**Comment by zepumph** [comment]
![image](https://user-images.githubusercontent.com/6856943/86154808-0d65b080-bab0-11ea-9af0-705c1cafdafd.png)

**Comment by emily-phet** [comment]
@zepumph I think this looks great! 
Can you please also:

- [ ]  right align the range text + combobox. I also think it would look nice for the combo box alone to match exactly the width of the gridline and numbered grid radio button just above it. 
- [ ] Arrange all so that the reset all button was aligned with the right alignment of the controls (radio buttons/comboboxes, etc.). I have some recollection this was already brought up by you, and written somewhere, but couldn't find it quickly so apologies if this is redundant.

**Comment by zepumph** [comment]
> right align the range text + combobox. I also think it would look nice for the combo box alone to match exactly the width of the gridline and numbered grid radio button just above it.

I right aligned the grid range combo box, but changing the width of the combo box is a bit weird because its width is based on its content. One thing I could do is increase the size of the the text to make it larger (vertically and horizontally). Otherwise I could look at extending the content width, but that would increase the size of the Combo Box and potentially look strange.

Here is the combo box with larger font (uncommitted), I think it is too big. It is only one point smaller than the accordion box:
![image](https://user-images.githubusercontent.com/6856943/87732838-715bca80-c77a-11ea-8210-b83f7d775763.png)

Want me to experiment with adding white space padding in the button?

**Comment by emily-phet** [comment]
I like the general look of the range combobox aligned with the radio buttons (as in this screenshot). I agree, though, that it makes the combobox to large given we want to minimize the visual emphasis of this.

Is there a way to decrease the height of the combobox, keeping all else the same? Maybe increasing the padding on the heading portion of the accordion box would make that a bit bigger, and then the padding for the combobox wouldn't have to be decreased as much to make the overall effect be that the combobox is less important (smaller looking
) than the accordion box.

**Comment by zepumph** [comment]
>Is there a way to decrease the height of the combobox, keeping all else the same?

Yes, but it will likely look really weird. This uses scaling just in the Y dimension to basically squish everything vertically. I don't think this would pass code review, as most of the time we try to keep the same aspect ratio for common components, especially since there is a "normally scaled" combo box on the other screen. 

![image](https://user-images.githubusercontent.com/6856943/87967821-e6c1e680-ca6b-11ea-8ea1-762dc7544798.png)
![image](https://user-images.githubusercontent.com/6856943/87967848-f2ada880-ca6b-11ea-950e-d3227040e45f.png)


> Maybe increasing the padding on the heading portion of the accordion box would make that a bit bigger, and then the padding for the combobox wouldn't have to be decreased as much to make the overall effect be that the combobox is less important (smaller looking
) than the accordion box.

Great idea, and this is already supported in ComboBox. The default spacing is 10, here is it with a few values:

30:
![image](https://user-images.githubusercontent.com/6856943/87968187-7f586680-ca6c-11ea-9d0f-210ea066ecc5.png)

20:
![image](https://user-images.githubusercontent.com/6856943/87968237-9008dc80-ca6c-11ea-93bf-26bb7968448a.png)


Does anything above seem like the right pixel polish for this?

**Comment by emily-phet** [comment]
Let's just leave this as is for now.
