### ISSUE TITLE
Screen Names needed

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#60]
We now have two screens our first thought on names are:

Screen 1: Explore
Screen 2: My Challenge

@emily-phet would like to comment and get opinions from other designers before implementing. 

@zepumph likes the above names.

**Comment by emily-phet** [comment]
Thanks @Matthew-Moore240 I like "Challenge maker" for the second screen. It's a bit long - three characters longer than "My Challenge", but captures nicely the point of that screen, which *is* for actively making challenges.

Let's go with "Explore" and "Challenge Maker" screens for now. We should keep an eye out that the "maker" in "challenge maker" doesn't encourage learners to jump ahead too soon.

**Comment by emily-phet** [comment]
Another option to consider:
"Challenge Explorer" and "Challenge Maker".

**Comment by zepumph** [comment]
For brevity I like "Explore" as the first screen. Let's go with that for now unless someone else says otherwise.

**Comment by zepumph** [comment]
Screens are now "Explore" and "Challenge Maker". let me know if there is anything else to be done here! Closing
