### ISSUE TITLE
Second round of RaP interviews - Updated Design + Sounds

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#66]
New round of interviews happening shortly to address a multitude of interaction and visual changes and first interviews with proposed sound design.

1.) Is there tolerance where we want it to be? I'll talk with @zepumph about the logistics, but we want to make sure our choice of default tolerance feels good for exploration and continuous movement (and that there are no glitches).

2.) Do we want to test only on Screen 1? So, excluding the Custom Challenge screen? If not, are there any modifications needed for screen 2 or the screen selection screen? @emily-phet 

3.) What default sounds will we present and what options do we want in the Options menu for secondary feedback? Related to #9. I'll update this after Sound design meeting on 6/16.

4.) Are we interested in cursor interaction for this round or should I push for touch-enabled devices?

**Comment by BLFiedler** [comment]
2.) Fine as is. Test full sim.

4.) We can focus touch enabled - one or two phone uses would be fine, but should try to get more tablet usage.

**Comment by BLFiedler** [comment]
1.) @zepumph updated the tolerance function. Currently it behaves more similarly to Dor's MIT app which is more reliant on the physical dimensions of the bars. Right now you'll get feedback generally around 40% of the screen (2 grid lines on either side). This felt fine testing on an iPad.

3.) Random pitch plucking is default - can try marimba (no pitch modulation) after to see user preference.

5 interviews scheduled:
Thursday (6/18) - 1 laptop/mobile
Friday (6/19) - 1 mobile/laptop, 1 iPad
Monday (6/22) - 1 touchscreen laptop, 1 iPad

**Comment by zepumph** [comment]
Implemented above. The spacing is a bit funny, but I agree it is better for this round of interviews.

https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.28/phet/ratio-and-proportion_en_phet.html

**Comment by emily-phet** [comment]
Closing this, as it seems interviews are in progress, and sim version is good to go for them.
