### ISSUE TITLE
Make Grid Range control on screen 2 appear only when numbered grid is selected

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#68]
If possible for interviewing, can we make the grid range control ( 0 to 10, 0 to 20, 0 to 30) only appear when we have Numbered Grid selected? 

I think there may be more discussion about the presentation of this control, but I think at a base minimum having it hidden when the numbers are hidden will prevent confusion.

![image](https://user-images.githubusercontent.com/47331395/84943354-7c4f0c80-b0a1-11ea-8e63-2d013a85c4cb.png)

**Comment by zepumph** [comment]
Oops, wrong issue. I addressed it in https://github.com/phetsims/ratio-and-proportion/commit/6dce1e9e1f6ab260f0771d7faca48fb1405bdd0f, see https://github.com/phetsims/ratio-and-proportion/issues/66#issuecomment-645642600

I felt like this was weird with the spacing  when hidden. I foresee, like you mentioned, that this is good for interviews now, but may need more design time.

**Comment by BLFiedler** [comment]
Looks good. Thanks, Michael!
