### ISSUE TITLE
Change visual in-proportion feedback to match auditory feedback

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#69]
@emily-phet  I'd like to think about altering the visual display to more closely match the auditory  display in representing perfect fitness (in proportion). I think the auditory display will work fine to cue visual/nonvisual users with no hearing impairments, but I am imagining deaf & HOH users or simply users who don't want the sound on may have more difficulty pinpointing the perfect ratio as implemented currently (subtle change in pastel green).

I don't have a specific proposed change other than something more contrasting to the final tick in a color gradient. A more saturated color? Texture?

@zepumph and I discussed this briefly during a meeting on tolerance and thought it worth bringing to  a meeting, but feel free to close if you disagree.

Current implementation right before ratio is reached (fitness < 1), staccato sound:
![image](https://user-images.githubusercontent.com/47331395/85053276-7b78b200-b157-11ea-9d43-82c6076a513f.png)

Current implementation at perfect ratio (fitness = 1), arpeggiated chord sound:
![image](https://user-images.githubusercontent.com/47331395/85053151-5421e500-b157-11ea-9fc5-9792c68d761c.png)

**Comment by BLFiedler** [comment]
Quick thought: if we move forward with this, the sound for success is transient. Unclear if visual indicator should also be transient or just "TRUE" when in proportion.

**Comment by zepumph** [comment]
Today during design meeting, @kathy-phet had a fun idea of changing the hand to a "thumbs up" when the ratio is perfect. This is potentially a nice balance because it could be quite subtle, and could occur without altering eye tracking results. It is also complementary with the "one shot" type of feedback that description and sound provide when in that state.

**Comment by BLFiedler** [comment]
I will say I am becoming a little more lukewarm to this entire idea the more I think about how distracting it may be. Let's see how interviews progress.

Just to add another idea that it would be a much more subtle adjustment. I sketched out the way we currently change the gradient as the right hand moves through the proportion vertically and offer up another method that may cue with just a small "jump" to full saturation.

![image](https://user-images.githubusercontent.com/47331395/85086200-22307300-b197-11ea-8b6a-1649c4f4f339.png)

**Comment by emily-phet** [comment]
@BLFiedler Let's talk about this on Tuesday - perhaps @zepumph can show us this in action, and we can tweak live.

**Comment by zepumph** [comment]
I added this in the above commit. In its current state I think it is jarring and distracting. I think it can be fixed though by tweaking the colors. I am no color designer, so I didn't spent long on that part.

By tweaking some colors in https://github.com/phetsims/ratio-and-proportion/blob/master/js/common/view/RatioAndProportionColorProfile.js#L21, we should be able to make this better. I'm excited to try this out tomorrow. Tagging @emily-phet and @BLFiedler if they have time to design some colors that we can plug in tomorrow (or you can edit the above file locally if you have the ability to do so.

**Comment by zepumph** [comment]
I demoed this as part of the design meeting today, and you can play with it here: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.31/phet/ratio-and-proportion_en_phet.html

It wasn't totally clear where we should go from here. Perhaps we can discuss this at the meeting later today.

**Comment by zepumph** [comment]
I misunderstood. Actually we made decisions:

- [ ] Instead of having such a large range for the jump, the tolerance for that "perfect" ratio color should be much smaller.

**Comment by zepumph** [comment]
Implemented above. The threshold used to be .1 on either side (1/10th of a grid line), now it is .025. This felt like a small number that was still attainable. I did not review how that worked with the bimanual interaction/sound. 

I also feel like we haven't reviewed the colors themselves, but perhaps that is more for #57.

**Comment by emily-phet** [comment]
This looks good to me - I'd like to check in that we're all still feeling good about this approach in today's design meeting. No changes from at the moment.

**Comment by zepumph** [comment]
We discussed this, and decided to implement what is outlined in https://github.com/phetsims/ratio-and-proportion/issues/83. Closing this one, please reopen if you feel differently.
