### ISSUE TITLE
Add zoom/mag feature to this sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#71]
From A11y planning meeting today, this was recognized as a feature we want to publish with the sim. It would be good to add this sooner rather than later so that it can be worked into the iterative design/dev process from here.

**Comment by zepumph** [comment]
On hold until https://github.com/phetsims/chipper/issues/956

**Comment by zepumph** [comment]
When I added this to the sim, I found that it completely co-opted the "bi-modal" interaction on a touch screen when trying to move both ratio hands at once. @jessegreenberg is there a way to "opt out" of the pan zoom listener for specific listeners? I think that we will need to code around this interaction somehow. Let's discuss tomorrow during a11y dev meeting!

**Comment by zepumph** [comment]
Note that the slider trouble described in https://github.com/phetsims/ohms-law/issues/162#issuecomment-651282523 is the same thing when trying to drag a ratio hand around when zoomed in. I think we will need to work on that interaction too.

**Comment by zepumph** [comment]
@jessegreenberg and I paired on this, and we made good progress, see https://github.com/phetsims/ohms-law/issues/162 for commits about DragListener support and a few other types. We still need to figure out how to handle RatioInteractionListener. The recommended way to support dragging is by calling a function on the Pointer that triggered the event. With KeyStateTracker, we only get DOM events, and not the Pointer via a SceneryEvent. I think that the next way to explore this will be to have KeyStateTracker work with SceneryEvents, and wrap domEvents in dummy scenery events if keyStateTracker is being used outside of that context.

**Comment by zepumph** [comment]
The above strategy was not ideal. Instead I decided to pull logic out of the keyStateTracker, and into the direct keydown listener. That way there was access to the SceneryEvent (and the Pointer). I added zoom mag on master also, because it was looking pretty good. I'm going to close this issue, and new problems that arise from zoom/mag can get their own issues.

**Comment by emily-phet** [comment]
@BLFiedler Can you take a good run through the sim, and see if you notice any issues re zoom?

**Comment by BLFiedler** [comment]
Ran through on an iPad in Safari and Chrome. Zoom feature works everywhere except when either the Left, right, or both hands are picked up. e.g. you cannot have your thumb on the left hand and try to pinch with your index to activate zoom or separate hands. 
So, seems to all check out just fine!

**Comment by emily-phet** [comment]
Great! We'll get a chance to check out the possible issue @BLFiedler brought up when we implement self-voicing in this sim in the future, and test with low vision users (not using screen readers).
