### ISSUE TITLE
Grid Range combo box disabled state

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#73]
From https://github.com/phetsims/ratio-and-proportion/issues/58#issuecomment-646377333:

> Have the grid combobox showing all the time, but when grid is invisible, then should a line through the comboBox display.

I pinged the dev channel, and this seemed to not be a normal design. In that issue, I went ahead and linked up the ComboBox enabledProperty accordingly, but I thought I would create this issue to see if more steps need to be taken to actually hide the selected view, and if so, then presumably set the range back to "0 to 10" when they are hidden?

**Comment by emily-phet** [comment]
Not sure I understand the question for me. Perhaps we can talk in the meeting later today about this?

**Comment by zepumph** [comment]
From today's design meeting, we do want to replace the disabled value of the combo box with a line. In the PDOM, we need to see what will work. We may be able to just have blank text for the button, but we will for sure need make the html button be disabled.

**Comment by zepumph** [comment]
I was able to do this for the visuals of the combo box, in which the text is swapped out for a horizontal line when the grid is not shown. Unfotunately, there wasn't an easy way to update the PDOM button text in the same way. Here is a patch to the combo box in `sun/`  that I thought would be ugly but work, but unfortunately it didn't even work fully. This is because `ComboBoxItem` is really just a POJSO, and updating values in that is not enough. Something that would work, but makes me feel "eh", is to make `ComboBoxItem.a11yLabel` a Property, and to update the button label whenever that changes. This is quite a bit of complexity to add for this solution. I'd like to talk about this next week with @jessegreenberg, perhaps he will have some insight.

**Comment by zepumph** [comment]
<details>

```diff
Index: js/ComboBox.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/ComboBox.js	(revision 1541c75a7cc7eaf4c903830111cfd5b6d36d4f68)
+++ js/ComboBox.js	(date 1592962106351)
@@ -309,7 +309,7 @@
   }
 
   /**
-   * Instead of setting accessibleName on ComboBox, forward helpText setter to the button
+   * Instead of setting helpText on ComboBox, forward helpText setter to the button
    * @param {string} helpText
    * @override
    */
Index: js/ComboBoxItem.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/ComboBoxItem.js	(revision 1541c75a7cc7eaf4c903830111cfd5b6d36d4f68)
+++ js/ComboBoxItem.js	(date 1592961743275)
@@ -28,15 +28,29 @@
       tandemName: null, // {string|null} the tandem name for this item's associated Node in the combo box
 
       // pdom
-      a11yLabel: null // {string|null} the label for this item's associated Node in the combo box
-
+      // {string|function():string|null} the label for this item's associated Node in the combo box, or a function
+      // that will return it.
+      a11yLabel: null
     }, options );
 
     // @public (read-only)
     this.node = node;
     this.value = value;
     this.tandemName = options.tandemName;
-    this.a11yLabel = options.a11yLabel;
+
+    // @private, see getter
+    this._a11yLabel = options.a11yLabel;
+  }
+
+  /**
+   * @public
+   * @returns {*}
+   */
+  get a11yLabel() {
+    if ( typeof this._a11yLabel === 'function' ) {
+      return this._a11yLabel();
+    }
+    return this._a11yLabel;
   }
 }

**Comment by zepumph** [comment]
@emily-phet, can you please review the visuals, and see if anything needs to be tweaked for that?

**Comment by emily-phet** [comment]
@zepumph Thanks for the update re combobox. Visually it looks good. Hopefully there's a straightforward solution for the non-visual side of things that emerges in discussion w/ @jessegreenberg.

**Comment by zepumph** [comment]
Assigning @jessegreenberg so that he is aware of the discussion to come for tomorrow!

**Comment by zepumph** [comment]
@jessegreenberg and I discussed a few ways to add this logic into ComboBox.js:
* We could add `disabledComboBoxItem` which is displayed when the combo box is disabled
* We could add support to ComboBoxItem to have different enabled/disabled content and tell the button to recompute that.
* ComboBoxItem could run a Property, and ComboBoxButton could listen to changes in ComboBoxItem and update accordingly.

All of these seemed really heavy-weight, and we didn't feel like this case warranted such action. Instead @jessegreenberg had a great idea to create a separate, identical looking/formatted combo box, with a single item that is always disabled, and swap that one out when we want to display the horizontal line. @jessegreenberg wondered if this was skirting around the problem too much, but to me, weighing the above implementations vs this single odd usage of ComboBox, we should not over generalize before there is more need for this feature in common code.

Thanks for your help @jessegreenberg!

**Comment by jessegreenberg** [comment]
Good luck! Removing my assignment.

**Comment by zepumph** [comment]
@emily-phet please review the look and feel in master now. Currently the disabled button has an attribute saying it is disabled, but it doesn't have any label for the button:

Disabled:
![image](https://user-images.githubusercontent.com/6856943/86407636-dfc06900-bc61-11ea-91be-b8794b365e0c.png)


Enabled:
![image](https://user-images.githubusercontent.com/6856943/86407678-f36bcf80-bc61-11ea-95e5-2e2364abb794.png)

**Comment by zepumph** [comment]
I wonder if that should be blank, or say something.

**Comment by emily-phet** [comment]
Thanks @zepumph!

Let's let @Matthew-Moore240 take the lead on answering this latest question https://github.com/phetsims/ratio-and-proportion/issues/73#issuecomment-653212930, with some help from TS if needed.

**Comment by emily-phet** [comment]
@zepumph @Matthew-Moore240 
Actually - I'd like to close this issue, so I'll make a note of the description question for combobox, and we can discuss on Tuesday, and open another description-specific issue if needed.

**Comment by terracoda** [comment]
Apologies @emily-phet, @Matthew-Moore240 and @zepumph for being late to this issue.

In the scenario below, I think there needs to be a label...
![Screen Shot 2020-07-13 at 11 01 47 AM](https://user-images.githubusercontent.com/1902116/87310303-5e39c800-c4f8-11ea-9246-6aecb41d0038.png)

How about:
```html <button>Range: Disabled when Grid hidden</button>```

Possible help text (which I shall put in design doc):
<p>When grid shown, choose range for grid.</p>

**Comment by zepumph** [comment]
I will implement and we can go from there.

**Comment by zepumph** [comment]
Oh, I see the discussion in the google doc now, let's go from there. Closing again.

**Comment by terracoda** [comment]
Ok, then use the shorter label that I put on the design doc :-) Maybe "Grid Disabled"?
