### ISSUE TITLE
Increase touch areas for ratio hands

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#75]
From today's design meeting. This will improve the ability to see the white circles on touch devices using fingers.

**Comment by zepumph** [comment]
I increased the width and height of the touchable area both by a factor of two. Here is what the sim looks like with `?showPointerAreas`. Please review.

![image](https://user-images.githubusercontent.com/6856943/85483648-b6248500-b571-11ea-90de-b5fc107c76a8.png)


I thought it best to be on the edge of "too much" dilation rather than the other way, just to experiment. Let me know if you want me to tone it down a bit. There is some chance for weirdness when the hands are as close together as they can be:

![image](https://user-images.githubusercontent.com/6856943/85483730-e1a76f80-b571-11ea-884e-6ab47da59bb8.png)


Please review.

**Comment by emily-phet** [comment]
@zepumph The touch area looks great for the hands. 

Was there a formal decision to have the touch area for accordion boxes be just the plus/minus sign box? If not, let's increase the touch area for that to include the entire heading of the accordion box.

**Comment by zepumph** [comment]
That already exists. You can open the accordion box by clicking anywhere on the title, it just doesn't show up in that above visual because it isn't a specifically enlarged area. I'm going to close this. Please reopen if there is anything else.
