### ISSUE TITLE
Move white circle on the hand

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#76]
During design meeting today, we decided to move the white circle up on the hand. Ideally the center of the circle would be on the same vertical line as the top of the thumb.

**Comment by zepumph** [comment]
This is what master now looks like. @emily-phet please review:

![Uploading image.png…]()

**Comment by zepumph** [comment]
I think it looks a bit weird. Maybe it should be a bit bigger?

**Comment by emily-phet** [comment]
Agreed - it looks good, but a little odd. Can you increase the size of the circle by about 20%, and let's see how that looks. Regardless, I think that whatever it ends up looking like will be good for awhile. We can do another round of visual tweaking once we have this round done, and a little time has passed so we can get used to the new changes.

**Comment by emily-phet** [comment]
Looks good! Let's leave it like this for now.
