### ISSUE TITLE
No sound playing on iPhone and Safari

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#78]
First two interviews on iPhones (latest updates as of 6/19) did not play any sounds (UI or Sonification) while using default Safari. Refreshing the page did not fix. Toggling sound did not fix.

@jbphet indicated it's probably **not** related to #67 . I do not have an iPhone to test this with.

**Comment by zepumph** [comment]
I don't have an iPhone either. @jbphet, can you speak to if you have noticed this problem before? Perhaps we could publish a few other sims, maybe even a dev version of Tambo, and try it out on some iPhones to see if it is reproduceable.

**Comment by jbphet** [comment]
@BLFiedler - Can you record which dev version or versions of the sim were being used when this problem occurred?  Thanks.

**Comment by BLFiedler** [comment]
All interviews were done on 1.0.0-dev28: https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.28/phet/ratio-and-proportion_en_phet.html

**Comment by jbphet** [comment]
dev.28 works fine on my personal phone, which is an iPhone 8 running iOS 13.5.1, which is the latest according to support.apple.com.  That's the only iPhone I have access to at the moment, @KatieWoe - can you please see if you can duplicate this on any devices that are available to you?

**Comment by KatieWoe** [comment]
iPhone 7 iOS 13. I had sound work for me, but the ringer needed to be on. If the phone was on silent then the sim sound would not play. I believe this is the case for other sims as well. Was the phone being used on silent?

**Comment by BLFiedler** [comment]
Ah! That may have been it. I had them set their phones to Do Not Disturb to avoid recording any personal information. So, you think even though they turned their volume up that that may have prevented them from hearing sim sound?

**Comment by KatieWoe** [comment]
Yes. The ringer silences other sounds as well. Including sim sounds. It does it other websites as well, so I'm not sure what a solution would be. @jbphet would be more familiar.

**Comment by BLFiedler** [comment]
Hm. Strange design choice. If it's baked into the OS, I suspect that's something we need to watch out for in interviews, but let me know if there is some sort of override @jbphet, otherwise feel free to close.

**Comment by jbphet** [comment]
I'm glad we figured that out.  I just tested it on my phone and as soon as I flip the switch to silent mode the sound stops and as soon as it is switched back the sound resumes.  There is no override that I know of, and I doubt it's possible.  Or desirable for that matter.  Closing.
