### ISSUE TITLE
sound static-y on safari

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#80]
Sound has a static-y, pop-y quality when using safari browser for me (EM). This is not new, it's always had this.

**Comment by zepumph** [comment]
I will test this on my iPad

**Comment by BLFiedler** [comment]
I believe this is related to my experience in #37 . The "noises" I reference are a static-y sounding version of the sounds playing from the sim. 

This typically occurred when I opened the simulation from an external link (so a new tab opened). This wasn't true across all devices and was difficult to reproduce for others.

**Comment by zepumph** [comment]
I reopened over in https://github.com/phetsims/ratio-and-proportion/issues/37, and will investigate there.

**Comment by zepumph** [comment]
Oops, this shouldn't be open.
