### ISSUE TITLE
visual cue for custom keyboard interaction 

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#81]
When navigating with the keyboard there is a custom interaction (allowing the two hands to be controlled simultaneously), and there is special jump keys (numbers and letter "j"). We need to cue at least the two hand control with a visual display when arrived at two-hand control situation, for sighted alternative input users. 

Not sure if this should also include a cue of the jump keys, or if those should be solely in the keyboard shortcut dialog.

**Comment by emily-phet** [comment]
I made these mockups for discussion today:

<img width="276" alt="Screen Shot 2020-09-01 at 6 52 35 AM" src="https://user-images.githubusercontent.com/5109055/91859805-b8fdbf00-ec1f-11ea-8bc2-9ae3a163b45c.png">

<img width="269" alt="Screen Shot 2020-09-01 at 6 52 50 AM" src="https://user-images.githubusercontent.com/5109055/91859834-c1ee9080-ec1f-11ea-9d4f-914b67703a00.png">

In addition to visual design, we need to discuss what happens when you tab to hands and they are very high or very low (will we not show the top or bottom cue if it doesn't fit, etc.).

**Comment by terracoda** [comment]
<img width="363" alt="Screen Shot 2020-09-01 at 2 43 38 PM" src="https://user-images.githubusercontent.com/1902116/91885053-b2903700-ec61-11ea-9831-93fc75095184.png">

**Comment by emily-phet** [comment]
- only see visual cue prior to first successful movement, after that, no visual cue when tabbing to both hands.
- when up against an edge (top or bottom of screen) just don't show what won't fit. 
- first try to use the yellow arrows, adjusting them so that the keyboard cues appear (and the yellow arrows, if they aren't already present) when tabbed to, and disappear when tabbed away or successfully moved.

**Comment by terracoda** [comment]
Adding images from Friction for reference. For that sim we didn't emphasize the letter keys. Take this example with a grain of salt. Friction's interaction was simple enough, visual instruction about letter keys was deemed unnecessary at some point.

Grabbed Zoomed-in Book
<img width="886" alt="Screen Shot 2020-09-01 at 2 52 18 PM" src="https://user-images.githubusercontent.com/1902116/92239398-82c97500-ee95-11ea-8ee3-1e025f5e20f2.png">

Grabbed Chemistry Book
![Screen Shot 2020-09-04 at 10 01 20 AM](https://user-images.githubusercontent.com/1902116/92239454-9e348000-ee95-11ea-857e-28ad1037d421.png)

**Comment by emily-phet** [comment]
New idea, what if we just:

- Had the yellow arrows re-appear the first time the both hands mode is navigated to by keyboard, and
- on the left hand, overlaid a "W" and "S" key graphic.

This way, the yellow arrows always mean up/down with arrow keys, and yellow arrows with W/S on them mean up/down with W/S keys. The W/S look like the W/S in the BASE grab graphic above (with boxes around them, so they look like little keyboard keys).

**Comment by emily-phet** [comment]
@zepumph Do you need artwork for the keyboard keys? 

- They W/S keys should look just like the ones used in BASE
- the up/down arrow keys should look like the ones in the example in [this comment](https://github.com/phetsims/ratio-and-proportion/issues/81#issuecomment-684871062) (lower panel)
- they should appear overlaid on the base part of each arrow (the narrow part, closest to the hand). 
- If the keyboard keys appear too small that way (the base of the arrows is kinda small), we would try next moving the keyboard keys just outside the arrow, changing the arrow position to be a little farther from each hand, with the keyboard key sandwiched between the arrow and the hand. 

Does that make sense?

**Comment by terracoda** [comment]
I like @emily-phet 's second suggestion in comment https://github.com/phetsims/ratio-and-proportion/issues/81#issuecomment-712870773

I think the cue should appear on focus on the Both Hands interaction until there is successful movement and reset after a sim reset.

**Comment by zepumph** [comment]
@emily-phet and I feel like it is acceptable to use the same arrow key icons from the keyboard help dialog along with the W and S letter key Nodes.

- [ ] Use those key Nodes
- [ ] Position them inside the base of the current cue arrows if possible.
- [ ] Make sure these things scale with the ratio hand (likely covered over in https://github.com/phetsims/ratio-and-proportion/issues/217).
- [ ] When you successfully interact with individual hand sliders, you should still get these cue arrows to show up for the both hands until the both hands interaction has successfully occurred 
- [ ] We may in the future decide that we want to show arrow keys embedded in the individual cue arrows before either of those have interacted successfully.
- [ ] Question for @emily-phet: We discussed whether the moving the individual hands first should hide the both hands interaction upon first focus (no, it shouldn't), but we didn't decide if interacting with the "both hands" interaction first should keep the individual cue arrows hidden. Up until this point there has been just a single Property in the model that determined if any cue arrows are shown, so it would be nice to decide on if each ratioHalf is now more in charge of their individual cue arrow, or if it just split on both hands vs all cue arrows controlled by individual sliders. I think I can make progress on this issue before we totally hammer this case out.

**Comment by emily-phet** [comment]
@zepumph - regarding your question in the prior comment.

The way I envision it - the left hand/right hand cue arrows should always appear and disappear together. There shouldn't be a situation where you only see the left hand arrow cue, or only the right hand arrow cue. 

Also - the both hands and the hands-as-sliders are two different interaction "modes" so moving within one should have no impact on the cue arrows of the other.

**Comment by zepumph** [comment]
Here are some key nodes in the arrows, but I think I'm going to refactor the cue arrows into RatioHandNode before continuing.

```diff
Index: js/common/view/RatioHalf.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RatioHalf.js	(revision 783ac4208e1bb4dbb5092dbc9563f9c13a72a04f)
+++ js/common/view/RatioHalf.js	(date 1605057262082)
@@ -19,6 +19,7 @@
 import merge from '../../../../phet-core/js/merge.js';
 import ModelViewTransform2 from '../../../../phetcommon/js/view/ModelViewTransform2.js';
 import ArrowNode from '../../../../scenery-phet/js/ArrowNode.js';
+import ArrowKeyNode from '../../../../scenery-phet/js/keyboard/ArrowKeyNode.js';
 import DragListener from '../../../../scenery/js/listeners/DragListener.js';
 import Rectangle from '../../../../scenery/js/nodes/Rectangle.js';
 import Tandem from '../../../../tandem/js/Tandem.js';
@@ -259,14 +260,24 @@
     const cueArrowOptions = {
       fill: RAPColorProfile.cueArrowsProperty,
       stroke: 'black',
-      headWidth: 33.33,
-      headHeight: 16.66,
-      tailWidth: 16.66
+      headWidth: 40,
+      headHeight: 20,
+      tailWidth: 20
     };
-    const cueArrowUp = new ArrowNode( 0, 0, 0, -33.33, cueArrowOptions );
+    const cueArrowUp = new ArrowNode( 0, 0, 0, -40, cueArrowOptions );
     this.addChild( cueArrowUp );
+    cueArrowUp.addChild( new ArrowKeyNode( 'up', {
+      bottom: cueArrowUp.bottom,
+      centerX: cueArrowUp.centerX,
+      scale: .70
+    } ) );
 
-    const cueArrowDown = new ArrowNode( 0, 0, 0, 33.33, cueArrowOptions );
+    const cueArrowDown = new ArrowNode( 0, 0, 0, 40, cueArrowOptions );
+    cueArrowDown.addChild( new ArrowKeyNode( 'down', {
+      top: cueArrowDown.top,
+      centerX: cueArrowDown.centerX,
+      scale: .70
+    } ) );
     this.addChild( cueArrowDown );
 
     // only display the cues arrows before the first interaction

```

**Comment by zepumph** [comment]
I got a start on this, but there is nothing to commit yet. 

Progress:

<details>

```diff
Index: js/common/view/RatioHandNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RatioHandNode.js	(revision d3e69e9ffb657fbdff7409b8f30fddd6dd7ed515)
+++ js/common/view/RatioHandNode.js	(date 1605059723076)
@@ -9,9 +9,11 @@
 import BooleanProperty from '../../../../axon/js/BooleanProperty.js';
 import Property from '../../../../axon/js/Property.js';
 import Range from '../../../../dot/js/Range.js';
+import Vector2 from '../../../../dot/js/Vector2.js';
 import merge from '../../../../phet-core/js/merge.js';
 import Orientation from '../../../../phet-core/js/Orientation.js';
 import ArrowNode from '../../../../scenery-phet/js/ArrowNode.js';
+import ArrowKeyNode from '../../../../scenery-phet/js/keyboard/ArrowKeyNode.js';
 import FocusHighlightFromNode from '../../../../scenery/js/accessibility/FocusHighlightFromNode.js';
 import Node from '../../../../scenery/js/nodes/Node.js';
 import Path from '../../../../scenery/js/nodes/Path.js';
@@ -31,7 +33,7 @@
    * @param {EnumerationProperty.<TickMarkView>} tickMarkViewProperty
    * @param {number} keyboardStep
    * @param {Property.<ColorDef>} colorProperty - controls the color of the hand. This is for both the filled in and cut out hands.
-   * @param {Property.<boolean>} firstInteractionProperty - upon successful interaction, this will be marked as false
+   * @param {Property.<boolean>} firstInteractionProperty - upon successful interaction, this will be marked as false // TODO: this should be two separate Properties, one when you interact individually, and one when using both hands.
    * @param {Object} [options]
    */
   constructor( valueProperty, enabledRatioComponentsRangeProperty, tickMarkViewProperty, keyboardStep, colorProperty, firstInteractionProperty, options ) {
@@ -47,6 +49,7 @@
       keyboardStep: keyboardStep,
       pageKeyboardStep: 1 / 5,
       shiftKeyboardStep: shiftKeyboardStep,
+      cueWS: false, // when false, cue arrows will show up/down arrow keys // TODO: implement
 
       // Because this interaction uses the keyboard, snap to the keyboard step to handle the case where the hands were
       // previously moved via mouse/touch. See https://github.com/phetsims/ratio-and-proportion/issues/156
@@ -105,6 +108,16 @@
     const cueArrowDown = new ArrowNode( 0, 0, 0, 40, merge( {
       top: container.bottom + 20
     }, cueArrowOptions ) );
+    cueArrowUp.addChild( new ArrowKeyNode( 'up', {
+      bottom: cueArrowUp.parentToLocalPoint( new Vector2( 0, cueArrowUp.bottom ) ).y,
+      centerX: cueArrowUp.centerX,
+      scale: .70
+    } ) );
+    cueArrowDown.addChild( new ArrowKeyNode( 'down', {
+      top: cueArrowDown.parentToLocalPoint( new Vector2( 0, cueArrowDown.top ) ).y,
+      centerX: cueArrowDown.centerX,
+      scale: .70
+    } ) );
     this.addChild( cueArrowUp );
     this.addChild( cueArrowDown );
 

```

</details>

@emily-phet, I have one more question, that has likely been answered but I am still unsure. As for the cues when you highlight a single hand slider, and/or on startup, do you want to default cue arrows to have arrow keys in both hands, like so? I didn't think so. I thought that the only icons occur when you focus on the both-hands interaction. That is when w/s/up/down pop onto the cue arrows.

Here is an example of what I don't think we want on startup, but I wanted to confirm:

![Uploading image.png…]()

**Comment by emily-phet** [comment]
@zepumph 

First, the overlaying of the keys on top of the arrows doesn't look good. Let's nix that idea. Instead, let's do this:
- The grey arrows and they keyboard indicators are not present at the same time - the keyboard indicators replace the grey arrows when that item (Left Hand, Right Hand, or Both Hands) is tabbed to:
- Whenever focus is on a left hand, right hand, or Both Hands, the grey arrows disappear for the thing with focus only, and the keyboard keys appear instead. Once one of these has been moved, the grey arrows and the arrow keys stop appearing for that thing only. The left hand and the right hand are treated individually, for both hands, the left hand/right hand are treated as one (once one is moved all sets of arrows stop appearing when in Both Hands).  

To answer https://github.com/phetsims/ratio-and-proportion/issues/81#issuecomment-725078642 - none of this happens on startup. The action of either the left hand, right hand or Both Hands having focus has to happen for this to occur.

**Comment by zepumph** [comment]
Implemented above. I think that in general the way of setting the cue based on each interaction is working well. Please play around with it and let me know what you think.

There are two questions I have for you.

What do you think about this buggy case?
1. Use first slider
2. go to both hands interaction
3. focus on the second slider
4. the first slider gets its arrows back.

It can also seem a bit weird tabbing through when you have interacted with one of the individual sliders, and also the both-hands, as there is a single hand that toggles displaying nothing (when both-hands is focused), and grey arrows (when the other slider is focused), and arrow keys (when it has focus).

**Comment by zepumph** [comment]
One other weirdness is that since the cue arrows are based on each interaction, it is very possible for cues to be off screen:

![Uploading image.png…]()

**Comment by emily-phet** [comment]
@zepumph I think this is looking pretty good!

Regarding questions/comments from you above:
- To this https://github.com/phetsims/ratio-and-proportion/issues/81#issuecomment-729325468 and this https://github.com/phetsims/ratio-and-proportion/issues/81#issuecomment-729315933: It's fine if all of the logic we decide on is being followed, and it just happens that sometimes one of the set of arrows or letter keys is off-screen (as shown in.  But we should be very clear on the logic we want. For the two scenarios you show/describe in the two comments, I'm not sure how you got into that situation, based on the intended logic. I think there may be a combination of slight misunderstanding/possible bug(s) happening in the current implementation.   

----------
Here's the logic I have in mind - hopefully this helps but if not let's discuss tomorrow in design meeting:
- **When using only non-keyboard interaction** (mouse, touch), only the grey arrows should be shown. In cases where mouse/touch are being used, and alternative input is not used (which we're implementing right now, but may in the future) then there is not really a single hands + both hands interaction...it's all the same. Grey arrows should appear at the start, and for each hand, grey arrows persist until that hand is moved. Then they never re-appear (unless restart all is selected, and then everything resets as if the sim is re-loaded from the browser). 

- **When using keyboard only**, at startup the grey arrows are around each hand. Once the user moves focus to a hand, then the grey arrows disappear replaced with the letter key images, and the grey arrows never reappear unless reset all is pressed (this is assumed for this case since we're assuming all keyboard use the entire time). Once the first hand gets focus, the letter key images are present for each hand in the single hand mode until that hand is successfully moved. Then the successfully moved hand has its letter key images disappear, never to return again (unless reset all is pressed). Same logic for Both Hands mode, once Both Hands has focus, then you see the letter key images for each of the hands, once each hand is successfully moved the letter key images with the successfully moved hand disappear, never to reappear (unless reset all is pressed). 

- **Mixed use - keyboard + mouse/touch**. In this case, there are a few relevant sub-scenarios: 

_1) The user successfully moves one or both hands with the mouse before transitioning to keyboard use to move the hands._ In this case, prior to hands having keyboard focus, the grey arrows stay for each hand until each hand is successfully used. As soon as keyboard focus is on the hands, the letter keys logic from a keyboard only use is used, and aligned with that logic, no grey arrows are seen again (unless reset all is pressed). 
The reason to treat the use of the keyboard as a totally new use of the hands even after successful use with the mouse/touch is because using the keyboard provides access to two modes of interaction with the hand (single hands and Both Hands) and until you move them all successfully it may not be intuitive that in one mode you use arrow keys for both hands and for the Both Hands mode you use the W/S keys for the left hand.  This is more complicated than the mouse/touch interaction for the hands, so I think it's better safe to just provide the visual cues as if you don't know how to move the hands rather than not providing the visual cues.

_2) The user moves one or both hands with the keyboard before using the mouse._ The same logic for all keyboard use is used. There might be some or now letter key images still happening when mouse/touch is used. If either or both hands have not been successfully moved at all, then only that/those hands not yet moved get the grey arrows. Once that/those hands have been moved, the grey arrow keys disappear, never to return. 

_3) The user switches back and forth between mouse/touch and keyboard._ If the user switches back and forth, the logic from case 2 or 3 is continued. So this would probably mean you need to keep track between reset all presses what hand has been successfully moved, and if it was successfully moved with keyboard or not. 

-----

One additional thought - probably best discussed in the design meeting tomorrow:

- Centering the location of the letter key images to the hand. In particular, the right hand letter key images look farther right of center than the left hand / left letter keys (in single hand and both hands mode). We'll want to look together at what the arrows/letter keys are being centered on, and make sure we like that and it results in a consistent looking alignment across all cases.

**Comment by zepumph** [comment]
I edited the above to be an ordered list to better explain my following comment.

I think that C.3 is at odds with B. In B you want focus of keyboard to turn off keyboard the grey arrows for ever, basically putting the sim in "cue-for-keyboard" mode. The issue with this is that there is no logic we can use for C.3 to turn back into "cue-for-mouse" mode. Right now we are treating the blurring of a keyboard element as that. 

Let's discuss more tomorrow on the exact behavior changes we want.

**Comment by emily-phet** [comment]
Talking tomorrow sounds good. 

For the case you bring up, the logic for B is under the assumption that the user never tries to use the mouse. The most important thing to me is that we don't leave keyboard users in the dark about what keys to use, I'm far less concerned about mouse/touch users not trying to move the mouse. If the most straightforward (or possible) solution is to just have the keyboard focus on the hands remove the grey arrows forever, that's fine with me.

**Comment by zepumph** [comment]
We discussed this during design meeting today, and came up with the following criteria:

* grey arrow (per hand):
     *visible WHILE NOT KEYBOARD FOCUSED until a successful mouse OR individual keyboard interaction

* individual-hand key arrow cues:
  * visible on focus, hidden on blur, until successfully moved with individual keyboard interaction

* both hands arrows:
  * Treat each individually, visible on focus, hidden on blur, until successfully used w/s can be hidden while up/down are not.
  * both hands is like a stacked layer on top of the individual, and when blurred, the cues should take the form of how they were before focusing the both-hands. . .EXCEPT if you have Successfully used the both both-hands (using w/s and arrows), which will hide both grey arrows.

**Comment by zepumph** [comment]
>Centering the location of the letter key images to the hand. In particular, the right hand letter key images look farther right of center than the left hand / left letter keys (in single hand and both hands mode). We'll want to look together at what the arrows/letter keys are being centered on, and make sure we like that and it results in a consistent looking alignment across all cases.

we liked this patch as it applied to the left hand. We felt like there was a bug in how this was applied to the right hand, as it felt different.

```diff
Index: js/common/view/RatioHandNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/RatioHandNode.js	(revision 9e4a7d2eca9309a13b42ca910e06939ae47dc627)
+++ js/common/view/RatioHandNode.js	(date 1606244066573)
@@ -80,7 +80,7 @@
     this.addChild( container );
 
     // empirical multipliers to center hand on palm. Don't change these without altering the layout for the cue arrows too.
-    container.right = container.width * .365;
+    container.right = container.width * .38;
     container.bottom = container.height * .54;
 
     assert && assert( !options.focusHighlight, 'RatioHandNode sets its own focusHighlight' );
```

**Comment by zepumph** [comment]
>.EXCEPT if you have Successfully used the both both-hands (using w/s and arrows), which will hide both grey arrows.

My current algorithm doesn't account for this, but I don't want to forget to come back to this part.

**Comment by zepumph** [comment]
https://github.com/phetsims/ratio-and-proportion/issues/81#issuecomment-733164835 taken care of above.


Outstanding thoughts:

- [ ] Should using the number keys in both hands mode remove the cues? Right now they don't hide the cue arrows. I added a TODO for this.
- [ ] We will need to add to this once we add back in marker input. I added a TODO for this, but I don't know if it is worth its own issue at this time, I don't think so.

@emily-phet would you like to take this review on. How is the behavior? There is a bit of inconsistency where a single grey arrow can be hidden for individual mouse input, but both grey arrows are hidden when the both-hands interaction is used.

Let me know what you think!

**Comment by emily-phet** [comment]
@zepumph - I think use of the number keys should remove all cues. It may be an accident, but if it's an "advanced user" who has looked at the keyboard help dialog, it seems like it would be annoying for them to remain. 

- What if any use of the keyboard just removed all of the grey arrows? We could consider these primarily for cueing basic up/down motion, and if you're using the keyboard you'll get the keyboard key cues, and if you're not consistently using the keyboard, you might have noticed them on startup, and in general, they're not as crucial as the keyboard key cues, since most  of the time someone will poke around clicking or tapping/dragging the biggest colorful things on the screen anyway.

**Comment by zepumph** [comment]
>What if any use of the keyboard just removed all of the grey arrows? We could consider these primarily for cueing basic up/down motion, and if you're using the keyboard you'll get the keyboard key cues, and if you're not consistently using the keyboard, you might have noticed them on startup, and in general, they're not as crucial as the keyboard key cues, since most of the time someone will poke around clicking or tapping/dragging the biggest colorful things on the screen anyway.

Seems reasonable to me, so using the mouse would remove both grey arrows forever, and using the keyboard (on individual sliders) would remove both arrow-key cues and (if applicable because you haven't used mouse yet) also the grey arrows?

**Comment by terracoda** [comment]
I think what you (@emily-phet and @zepumph) suggest is worth a try. 

We were originally thinking that the single grey arrows could remind people to move each hand, if they are only moving one, but I think for keyboard users, the pink focus highlight also cues that the other hand is interactive and hopefully it should be obvious that one would move it the same way as one moved the other one.

I was also finding a stray pair of grey arrows to be a bit weird.

**Comment by zepumph** [comment]
@emily-phet and @terracoda please play around with it. Here is the behavior I was going for:

1. Grey arrows are displayed and hidden as a pair. a single mouse or single keyboard or single both-hands interaction will hide all grey arrows.
2 individual arrow key cues are displayed and hidden as a pair. They are hidden once either individual hand is used, or upon using both sides of the both-hands interaction.
3. Both hands cues are treated separately. You need to use the specific side in order to hide it. 
4. Number keys will hide all cues possible.

**Comment by emily-phet** [comment]
Looks good - I like this. Simple, straightforward.
