### ISSUE TITLE
Tolerance values - list of tolerance variables and addressing some tolerance changes

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#83]
- [x] Below a ratio value of .05 (perhaps less later) or so, don't allow a "success" feedback (ding or dark green), but still allow tolerance fading. 
- [x] When right hand is 0, it should be white.
- [x] There is a "width" of dark green feedback when you are selecting a ratio (currently .025). When you do this with both ratios (bimodal), then widen this threshold, perhaps to .1. 
- [x] In proportion success sound threshold should be changed to match the visual threshold of dark green (.025).

We have a lot of definitions and "magic numbers" in the sim, @BLFiedler and I took some time to try to organize the different variables in the sim, and to name them. This helped us see where we had different values being used for the same sort of thing.

### Out of proportion
* Visual: green gradient (fitness of 1 on either side of ratio)
* Sound: staccato (fitness of 1 on either side of ratio)

### In Proportion
* Visual: dark green (.025 on either side of ratio)
* Sound: "success ding" (change to be same: .025 on either side of ratio)

#### In Proportion when either value less that .05 (aka half a default grid line)
In this mode, the model says we aren't in Proportion, instead we are just a hair outside of it
* Visual: a hair lighter than the dark green for normal inProportion
* No success sound ever plays
* No Moving in Proportion Sound (choir)

### Moving in Proportion (in proportion + velocity of both hands)
* Moving in Proportion Sound: choir (.8 fitness + velocity threshold passed for both hands)
* Visual: dark green (.1 on either side of ratio)
* Success Sound: "success ding" (.1 on either side of ratio)

@emily-phet let us know if anything here doesn't seem right.

**Comment by zepumph** [comment]
Today during sound design meeting, we discussed implementing Hysteresis only during "Moving in Proportion" for visual/sound, but felt like it is more complicated than the above strategy of widening the window when the choir sound is playing.

**Comment by zepumph** [comment]
- [ ] Choir sound fitness threshold is likely too big (.5). We should instead try to have it .3 around fitness, or a query parameter if it seems hard.

**Comment by zepumph** [comment]
I implemented a first pass at the above constants. Next time I work I will review this issue and then implement that patch in https://github.com/phetsims/ratio-and-proportion/issues/14#issuecomment-654418180

**Comment by zepumph** [comment]
Note to self: Add in how interactive description ranges play into the above regions.

**Comment by zepumph** [comment]
All boxes have been checked off here. @emily-phet @BLFiedler please review the tolerance and "small ratio value" behavior in master now. 

I wrote a note to the RaP slack channel about integrating interactive description related feedback into the above organization:

>To the Interactive Description team: We wrote out some sections at the top to try to describe the sound/visual behavior of the sim. It would be nice to have some idea about how (interactive description) ID fits into this. I'm thinking something like:
>* Out Proportion: description: region stated whenever they change
>* In Proportion: description: "in proportion" region stated whenever in proprotion
>* Moving in Proportion: description: ???? (not sure how this may or may not be different.
>Just an FYI, should I assign someone to try to add a first pass at those bullets into that comment?

Anything else to discuss here?

**Comment by emily-phet** [comment]
Thoughts...

- I don't think it's necessary to have the screen be required to be white when right hand is in position 0. If the screen would otherwise be a shade of green, I think that's fine. The sudden flash to white at hands position 0 seems too jarring. **@zepumph - please go ahead** and remove this requirement.
- @zepumph - can you confirm that in the most extreme case (I think 1:2) it is not possible to position the right hand just barely above zero, and raise the left hand slowly, seeing the green color go from darkening, to lightening, without hearing the success sound? If that's true, I think we're good to go.  Essentially, we don't want to have any scenarios where we see the color getting darker, then lighter, then darker without hearing the success sound. If you can find or think of a situation where that happens, let me know, we need to address it somehow. 

@zepumph can you update the first comment above to include the current values associated with the near zero behavior (adding a category for values associated with near-zero)?

What remains from this issue (I believe) is changing the [choir sound fitness threshold ](https://github.com/phetsims/ratio-and-proportion/issues/83#issuecomment-652056430), and having a quick back and forth with @BLFiedler to try it out and see if you two can find something that feels right (or good enough).

**Comment by zepumph** [comment]
>@zepumph - can you confirm that in the most extreme case (I think 1:2) it is not possible to position the right hand just barely above zero, and raise the left hand slowly, seeing the green color go from darkening, to lightening, without hearing the success sound? If that's true, I think we're good to go. Essentially, we don't want to have any scenarios where we see the color getting darker, then lighter, then darker without hearing the success sound. If you can find or think of a situation where that happens, let me know, we need to address it somehow.

This is possible. It is quite easy to put the right hand at ~.4 of a gridline, and the slowly move the left hand up from zero, and encounter it getting darker, and then lighter again. This will always be possible with this strategy a little bit, but perhaps we could make the range of this smaller, not up to .5 (half a gridline), but instead only up to .3 or something. Want to pair to discuss this nuance more?

Essentially, we don't want to have any scenarios where we see the color getting darker, then lighter, then darker without hearing the success sound.

We would never have this darker->lighter->darker again moving a single hand in the same direction, but it is possible to wiggle the left hand around at a low value and never get a success sound even though there is a distint "darkest placement" of the hand.

**Comment by zepumph** [comment]
>I don't think it's necessary to have the screen be required to be white when right hand is in position 0. If the screen would otherwise be a shade of green, I think that's fine. The sudden flash to white at hands position 0 seems too jarring. @zepumph - please go ahead and remove this requirement.

You only spoke about the right hand, but then said talked about the negatives of the "sudden flash." We get that when moving both hands, so I took this to mean remove this for both hands. Please let me know if you still wanted it to be white when only the left hand is at zero.

**Comment by emily-phet** [comment]
Correct, no need to enforce white background when it would otherwise be shades of green for right or left hand.

**Comment by zepumph** [comment]
@BLFiedler and I made a query parameter to tweak the choir sound threshold, it is called `?movingInProportionThreshold=X.` The value up until today has been .5, meaning that you get half of the fitness range to be in while still playing the choir sound (if both moving fast enough in the same direction). We felt like .7 or .75 may be a really good number for this. It had a good balance of not having too much noise in the smaller values, but not too large of a range with the higher ones. That said, we put the default at .8 to push ourselves in the opposite direction from what we are used to. 


@BLFiedler and I feel like this is important to discuss tomorrow during geneal RaP design. Specifically we want to ask if the choir feedback is distracting or incorrect for the lower values (below the first grid line).

**Comment by zepumph** [comment]
@emily-phet, you are assigned still to make sure there is nothing more to discuss about https://github.com/phetsims/ratio-and-proportion/issues/83#issuecomment-656882601.

**Comment by emily-phet** [comment]
Sounds good - on the agenda for tomorrow.

**Comment by zepumph** [comment]
Today during design meeting, and based on discussion that @BLFiedler and @emily-phet had, we decided that we need similar logic for the choir sound as we have for other feedback when values are lower than half a default grid line. 

- [ ] No choir sound should play when either hand is less than `.5`.

**Comment by zepumph** [comment]
I updated the above initial comment with the values currently in the model. I also made it so that choir ("moving in proportion success sound") cannot play when values are too small. The only thing left for this issue in my opinion is to make sure this doc ends up in `model.md` documentation.

**Comment by emily-phet** [comment]
I did lengthy exploration of the sim today, across keyboard, touch input (iPhone 8), and mouse. I didn't see any additional issues related to tolerance, beyond those I'm about to mention in the sound design and lock ratio GitHub issues.

**Comment by zepumph** [comment]
First pass at doc done above. There will be revisions, but I feel good closing this issue now.
