### ISSUE TITLE
both hands mode - gesture interaction on mobile VO

### ISSUE THREAD

**Issue by emily-phet** [phetsims/ratio-and-proportion#86]
We determined yesterday in description meeting that it is not possible to have independent simultaneous control of two objects when using mobile voice over (@jessegreenberg using iPad investigated and determined this). Two handed gesture is reserved by VO for other purposes (selecting and interacting with a single object). 

We will need to determine how to proceed - my guess is either punting (and providing mobile screen reader users with a prompt indicating that this move both hands is not available on mobile - sad but true with mobile screen reader), or creating some sort of one hand mechanism to control both hands available for just this condition. We have some early investigations of how to do this (would likely be something like...maintaining the current ratio based on current hand placement while moving both hands up). This would be different than non-mobile voiceover interaction, but probably better than saying this mode is not available...?

@jessegreenberg From your knowledge of mobile VO, would this second approach work?
@zepumph Heads up we may do something quirky for this situation.
@Matthew-Moore240 Thoughts on this, having a custom interaction for "Both Hands" mode only for mobile VO. Would require instructions on what to do (move up/down) and some indicator of what is happening (maintaining same ratio as current hand arrangement - but simpler and more concise).

**Comment by jessegreenberg** [comment]
> maintaining the current ratio based on current hand placement while moving both hands up

Yes that seems very doable. If we want a drag/drop then a double tap + hold is required to start the interaction, if we wanted more of a slider interaction then it could be just a swipe up/down to move both hands at once.

**Comment by emily-phet** [comment]
@Matthew-Moore240 Please consider which seems preferable here - the drag/drop (double tap + hold) or the slider style interaction (individual swipes increment/decrement). At first impression, the drag/drop seems more aligned with the interaction we're going for...but will probably require more work to describe well enough for intuitive use.

**Comment by Matthew-Moore240** [comment]
Its a tricky situation because to me if I want to move two sliders at the same time I would just use two fingers/thumbs to move it but I am not sure how non-visual people interact with stuff like that. As of right now I would go with the slider interaction to swipe up and down.

**Comment by emily-phet** [comment]
@Matthew-Moore240 agreed - two finger interaction would be ideal. There are limitations in this situation (mobile device use with screen reader on) because the use of the screen reader essentially takes over, and all gesture/swipes/taps, etc. are being interpreted by the screen reader. Independent control of two objects simultaneously seems, by @jessegreenberg  investigation and my understanding of how mobile screen readers work, impossible at the moment. @terracoda has asked a list of folks knowledgeable about advanced a11y tech if they know of any workarounds, but we're predicting there are none. 

So, it's single object interaction only, for the foreseeable future, for mobile VoiceOver (the mobile screen reader we support). Now we design with that in mind. 

The up/down swipe (I believe) comes with the caveat that it doesn't allow for continuous movement. It's discrete increments up - up- up - up, etc. Grab/drag allows an actual continuous drag movement (I believe), but again, is less conventional and will probably require more up front info to get the user going. (Again, I believe - speaking with @terracoda and @jessegreenberg about these things would get the ground truth of our knowledge base. :)

**Comment by jessegreenberg** [comment]
I think that https://github.com/phetsims/ratio-and-proportion/issues/86#issuecomment-656807014 accurately describes the trade-offs.

**Comment by terracoda** [comment]
I heard of one new gesture from the aria-interest-group list... 

> a so-called 'split-tap' where you hold down one finger, and tap with a second – but they are for the same control – not two different areas simultaneously.

I was wondering a custom gesture like a "split-tap" could be a way to lock proportion and then play with increasing or decreasing the space between the hands. Would that be a useful way to explore ratio and proportion?

**Comment by terracoda** [comment]
@jessegreenberg, are you aware of a resource that describes some of the less common gestures for VoiceOver?

**Comment by emily-phet** [comment]
@terracoda - the split tap sounds like a way to "select". Maybe something like "grabbing" before a drag (so grab+drag would be like "hold down finger 1, tap with finger 2, then drag with finger 1". Seems like it might be useful in some cases, but if we can get away with a slider interaction here, I'm not sure that continuous drag really buys us enough to be worth teaching someone a potentially new (since it's uncommon) interaction.

**Comment by jessegreenberg** [comment]
I have ususally checked Apple's docs: (https://support.apple.com/guide/iphone/learn-voiceover-gestures-iph3e2e2281/ios), I just found this one too though, looks pretty nice! (https://www.interactiveaccessibility.com/education/training/downloads/iOS-Cheatsheet.pdf)

The "split-tap" is listed in the Apple resource as an alternative way to activate something:
> Instead of selecting an item and double-tapping, you can use a split-tap gesture—touch and hold an item with one finger, then tap the screen with another finger.

**Comment by zepumph** [comment]
I really like the direction of this conversation. I want to add that to me we should keep time in mind as it pertains to going back and forth with each hand while interacting. I would assume that once a use was more comfortable with the interaction, that the best interaction would be the one that would allow the user to shift between the two to make fine tune adjustments quickly. This is very much tied to the fact that we are stuck with an interaction that only moves one hand at a time. The double tap and hold involves a delay time on the hold that is less appealing to me when I think of how someone will want to progress while using the sim. I don't feel like this is a larger or more important point, but rather want to add it into the trade-off pool described in https://github.com/phetsims/ratio-and-proportion/issues/86#issuecomment-656807014

**Comment by emily-phet** [comment]
@zepumph That's a good point about the time delay regarding double tap and hold. 
Let's be sure we're not talking about different things, though. 

In my comments above, i'm referring to a new - potentially mobile VO only scenario for the third tab stop. So users would be able to use a slider interaction (swipe up, swipe down) to move the two hands individually in the first (left hand) and second (right hand) tab stop. In the third tab stop, I'm proposing that for mobile VO only, grabbing the "move both hands" option actually moves both hands as a single object...something previously proposed by @BLFiedler when we were brainstorming keyboard control paradigms. So there would be no switching between hands, activating "move both hands" would fix the current hand ratio, and move the hands simultaneously either up or down maintaining their current ratio.

In your latest comment, were you meaning that in order to change the current ratio, the learner would have to alternate navigating back to the single hand sliders (either right or left) and move it, then return to "move both" in order to make much use of this, and we should consider efficiency across this switching back and forth?

**Comment by zepumph** [comment]
>In your latest comment, were you meaning that in order to change the current ratio, the learner would have to alternate navigating back to the single hand sliders (either right or left) and move it, then return to "move both" in order to make much use of this, and we should consider efficiency across this switching back and forth?

I think I pulled the conversation away from the third interaction a bit, and was talking about switching between the first two "sliders" (or however we choose to implement them on mobile). 


Maintaining the ratio for the third interaction feels like a really awesome idea, and may even also be something we would want to think about supporting for keyboard navigation. At first I felt like it may be "giving too much away for free" but I think that the key is that this is in concert with the individual controls. All together it feels like a complete and good interaction suite.

**Comment by zepumph** [comment]
Noting https://github.com/phetsims/ratio-and-proportion/issues/92 as a potential cross-modality solution for the "locking"  ratio and changing the both hands by moving one of them. A general solution over there may apply to this issue too somehow.

**Comment by zepumph** [comment]
Today, we brought this back up. We likely need to detect mobile and hide/remove change the both-hands content/interaction. Marking for a11y meeting.

**Comment by terracoda** [comment]
I'm going to add the note that when a screen reader is not enabled, and we have a self-voicing design, moving the two hands could potentially be accessible to blind learners on iOS.

**Comment by emily-phet** [comment]
In last week's design meeting - we decided to:
- there is no way to determine if someone is using a screen reader on a mobile device, so there is no way to selectively remove the both hands mode for only that scenario - both hands mode will be encountered by everyone
- we do know when someone is using a mobile device, and since the user affected by an inability to move both hands would be someone listening to the description, we can alter the description for this mode when accessed from a mobile device - we need description indicating that both hands mode is not a good thing to explore on mobile, and to cue exploring something else.

- [ ] Remaining to-do here is to create description for the scenario where someone navigates to the both hands mode on a mobile device - encouraging that they explore elsewhere.

**Comment by zepumph** [comment]
Marking this with @terracoda and @Matthew-Moore240 as a "would be nice" for interviews, but if it doesn't get done (by next week), that is alright.

**Comment by zepumph** [comment]
Pinging @terracoda and @Matthew-Moore240 to update help texts and associated description for mobile gesture a11y support.

**Comment by terracoda** [comment]
Adding this to my to do. We'll need device dependent help text that directs touch users away from the Both Hands interaction.

**Comment by terracoda** [comment]
Ok, as I wrote this out, I realized that Screen 1 (Discover Screen) and Screen 2 (Create Screen) could benefit from different instructions as the Lock Ratio checkbox is only on Screen 2.

Here's my first go at help text for the Both Hands interaction when accessed on iOS presumably with VoiceOver enabled, though we can only detect the platform not the screen reader. 

Purpose of help text is to redirect the user to the sliders, or to the Lock Ratio checkbox if they are on the Create Screen.

Discover Screen - Both Hands help text for iOS:
- Explore the challenge ratio with individual Left and Right hands. The custom both hands interaction is not possible with mobile VoiceOver. 

Create Screen - Both Hands help text for iOS: 
- To move both hands, first check Lock Ratio. With ratio locked, move both hands as a single unit to explore the challenge ratio. The custom both hands interaction is not possible with mobile VoiceOver.

Tagging @Matthew-Moore240 and @emily-phet for feedback.

**Comment by terracoda** [comment]
If we want a custom interaction, i.e. like Lock Ratio as suggested by @emily-phet in https://github.com/phetsims/ratio-and-proportion/issues/86#issuecomment-657380631, the help text would be different.

**Comment by terracoda** [comment]
We are just sticking with our current lock ration situation, so going with help text in https://github.com/phetsims/ratio-and-proportion/issues/86#issuecomment-733878148

**Comment by terracoda** [comment]
Over to you @zepumph for platform specific implementation.

**Comment by zepumph** [comment]
Implemented above. The structure is set up such that you can tweak the strings all you want in the strings json and it will show up only for gesture description (mobile a11y + VO). 

Personally, I feel like `mulit-touch` sounds a bit weird. Though I don't feel strongly, what about . . . 

This custom keyboard interaction
This custom keyboard component
This custom keyboard widget
This custom widget
. . . .


I feel like the interaction isn't keyboard-specific, not "touch". Thoughts?

**Comment by terracoda** [comment]
If "custom multi-touch interaction" is not clear,
would either of these terms be better?
- "custom bi-manual interaction"
- "custom two-point interaction"

Tagging @Matthew-Moore240, @emily-phet, and @BLFiedler for your thoughts.

**Comment by terracoda** [comment]
I didn't note @zepumph's suggestions...

If "custom multi-touch interaction" is not clear,
would either of these terms be better?
- "custom bi-manual interaction"
- "custom two-point interaction"
- "custom widget" 

Tagging @Matthew-Moore240, @emily-phet, and @BLFiedler for your thoughts.

**Comment by terracoda** [comment]
The Both Hands interaction is essentially an interaction designed for keyboard access, so I added that suggestion of @zepumph's to the list, too.

**Comment by terracoda** [comment]
On second thought, considering, mobile devices do have digital keyboards, and we do not want people to think they need to bring up their digital keyboard to access and operate this custom interaction, I would not "custom keyboard interaction".

So, our choices are, stick with the current one:
- This **custom multi-touch interaction** is not yet possible with screen reader software on a mobile device.

Or change to one of these three:
- This **custom bi-manual interaction** is not yet possible with screen reader software on a mobile device.
- This **custom two-point interaction** is not yet possible with screen reader software on a mobile device.
- This **custom widget** is not yet possible with screen reader software on a mobile device.

**Comment by terracoda** [comment]
We'll  leave wording as is, "multi-touch".

**Comment by terracoda** [comment]
I re-opened because I thought the Discover Screen's Both Hands help text was incorrect, but it is not.
Closing again.
