### ISSUE TITLE
Will tangible input be included in the published simulation?

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#89]
We started this sim in part as an exploration into adding tangible input to a phet simulation. Now, as we move towards a timeline that brings publication to a discrete place in the future, I am curious what we are going to do about tangible input. For example, I see nothing about it in https://docs.google.com/spreadsheets/d/1-9UCrkXG1QSTTdUGKxf2x_mPVypzjKQHYYnrudghPw/edit#gid=0.

@emily-phet can you comment on what your expectations are for tangible input to this simulation? At the very least, I would like to know so that I can try to clean up some of that protoype code that was implemented when we first started on this simulation.

**Comment by emily-phet** [comment]
Thanks for asking!

For an initial publication (timeline = sim design complete by end of 2020 Q3, and published by end of 2020 Q4), that publication *does not* include tangible input. That publication is planned to include - visual display, interactive auditory description, sound and sonification, magnification, (our typical set of) alternative (i.e., keyboard input), and mobile screen reader accessibility. Whew, our list of "standard" features is getting long! 

There's a small possibility we might add "self-voicing" to the list, we'll know by mid-August if that seems feasible. If not, a Round 2 of publication will likely be planned to republish with self-voicing in Q1 or Q2 of 2021.

Regarding the tangible interface, I am currently writing proposals for funding focused on tangible inputs. This would allow for a formal collaboration with Dor and Ellen, and support greater breadth of exploration into tangibles for this sim and others, as well as for PhET-folks to sort out what tech infrastructure will be needed/desired to publish with tangible features, and how we will convey this to teachers/parents/learners, etc. Fingers crossed, we'd have funding in-hand from my grant-writing efforts Fall 2021. 

In the meantime, we will still use the existing tangible prototypes as demonstrations, and to support our thinking and learning about how to design and collect data from tangible interfaces. I will include links to both the RaP sim, and the page that includes instructions to the tangible prototype as part of these application materials. Were it not for COVID, we likely would have already begun collecting data across learner populations using some of the prototype setups, but with my limited bandwidth and the lack of access to face-to-face data collection, we're holding off on some of that for now. 

So, please do let me know if there are things you could polish up regarding the prototype code for demos and grant reviewers.

**Comment by zepumph** [comment]
That sounds great to me. Here is what I think the cleanup is until we continue with tangible input:

1. Do the three issues in https://github.com/phetsims/tangible/issues (labels to the repo, move 3rd part adapter to sherpa)
2. Remove clement related input strategies from ProportionMarkerInput
3. Remove the usage of ProportionMarkerInput, so that no marker input is run on master.

**Comment by zepumph** [comment]
The above has been implemented.

The last version that had mechamarkers in it (untested in quite some time) was https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.39/phet/ratio-and-proportion_en_phet.html. Looking back at old versions and the work done in https://github.com/phetsims/ratio-and-proportion/issues/8, it looks like https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.13/phet/ratio-and-proportion_en_phet.html may be a solidly working initial prototype, for out records. Unassigning and marking deferred.

**Comment by zepumph** [comment]
Or perhaps closing is the right thing to do?
