### ISSUE TITLE
Add a "lock ratio" checkbox

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#92]
Add this to the second screen only. When checked, moving one of the hands will also change the other hand to maintain the current ratio.

could be displayed with an actual "lock" icon, maybe even in the middle between the ratio.

**Comment by zepumph** [comment]
Added above. @emily-phet @Matthew-Moore240 @BLFiedler @terracoda please review.

**Comment by zepumph** [comment]
https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.39/phet/ratio-and-proportion_en_phet.html?

**Comment by BLFiedler** [comment]
A few quick notes:

- Being able to use the cursor to drag both with only a cursor that allows for much finer movements (depending on DPI settings) than touchscreen really highlights the velocity threshold. I am not sure this is a problem yet, but you can much more easily move "slowly" and not get the choir sound.
- Dragging all the way down forcibly translates the lower hand to be even-ish with the dragged hand, so the ratio is no longer "locked". (and vice versa for the top of the screen).

Keyboard nav specific:
- May consider tab order to Lock to be a little closer to the hand so you can iterate easier. 
- Still get choir sound quite easily using coarse movement while locked in success! I like this.
   - Sub-bullet to above and first point re velocity threshold sound: It's very easy to move too slow to trigger choir sound when using fine adjustment.

Overall, I'm pretty positive about this, though there are some kinks to work out.

**Comment by terracoda** [comment]
Certainly, straightforward on how to get the coir sound now :-)

**Comment by BLFiedler** [comment]
A few more things:

- Bug: Hitting the sim reset button locks the ratio even when resetting. Does bring up cue arrows but hands are not in the original 1:2 positions :)

- This checkbox really highlights the tolerance values we've messed with at the bottom... May want to at least revisit the value we set (0.5 actually feels a little high to me now), which I think we intended to do.

- The lock ratio on the Challenge screen feels like a really interesting implementation of the "driver" screen as it was previously envisioned! Set the ratio, move one hand and see how fast the other goes!

**Comment by emily-phet** [comment]
My thoughts after significant exploration, and encapsulating (I think) the comments from @BLFiedler and @terracoda above.

Bugs: 
- When a barrier is encountered, you can move the hands out of ratio. Need to disallow further motion in that direction for both hands whenever a barrier is encountered.
- Reset all does not place hands back to their original position correctly when pressed when "lock ratio" is enabled.

Features:
- Choir sound should play *whenever there is motion* - no matter how slow - when the lock ratio feature is enabled. Consider this "lock ratio" as a distinct mode for the sim.
- Consistent with treating the "locked ratio" as a distinct mode, feedback should be consistent the entire time you are in this mode. If you start in the challenge ratio state getting success feedback, that should stay (sim stays constant dark green, choir sound plays). If you are near ratio, then all the near ratio feedback should be maintained. If you are far away from ratio, all of that feedback (no sonification, no color change) should stay the same. This may become an issue at lower regions, see my next topic below.

Other issues:
- Behavior when one or both hands are at or below 0.5. We have "hollywooded" the behavior in this region, and the "lock ratio" feature makes this hollywooding apparent. Some options come to mind for how to handle this - which I will mention below - but before we spend time attempting to tackle that, I have reached out to Dor to discuss starting the gridlines 1 instead of 0. I'd like to have that discussion with him before we spend further time on the 0.5-0 region. He is out of town now, but is due back tomorrow so I expect to be able to at least have some asynchronous back-and-forth by end of day Wednesday on this issue. Here are some thoughts I noted:
  - Not allow any hands to go below 0.5 when lock ratio is on. Problem: if starting with one or both hands at or below 0.5…then what? (there are two edge cases then, when both hands are at or below 0.5, and when only one hand is at or below 0.5_
  - Maintain consistent feedback all the way to bottom when lock ratio enabled. Problem: what happens when lock ratio is turned off then?
  - Do a bunch of specialty hollywooding depending on how you got into this low region – I would like to avoid this if at all possible.

**Comment by jbphet** [comment]
I wasn't in on the meetings where it was decided to try this out, so perhaps I can offer a bit more of an outsider's perspective.  I tested [version 1.0.0-dev.41](https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.41/phet/ratio-and-proportion_en_phet.html) and here are my thoughts after playing around with this feature for several minutes:

- The [original issue description](https://github.com/phetsims/ratio-and-proportion/issues/92#issue-65680340) says to "[a]dd this to the second screen only", but it's on both screens.  Is this intentional?
- I feel like this changes the way that users are likely to interact with the sim quite a bit.  Once users discover this, I suspect that they will learn to unlock the ratio, move them into proportion, then lock the ratio and move the hands around and watch how they behave.  This would be a pretty interesting visualization that would help them to "see" the nature of a continuously maintained proportion, but there will likely be less experimentation.  That may well be okay, but I think it's a question for the designers.
- Given that users will use this differently, do we have a good way to describe to non-visual users what's happening when the ratios are locked?
- Now that it's so easy to move the hands and maintain the ratio, it feels weird to me that the choir sound doesn't change at all when moving.  Before it was signalling, "Hey, you've done something really amazing" and it would only trigger occasionally.  Now that it's on for a long time, it seems like a different situation.  Perhaps we should consider different sound for "you did this on your own" versus "you're using the lock, here is a sonified version of what's happening".
- With this here and on both screens, I doubt many users will try to move both on a touch screen and maintain the ratio.  Why bother if the computer can do it for you?
- If we keep this, we should consider an A/B switch with icons indicating locked and unlocked, or the interactive lock that was used in [Equality Explorer's "Numbers" screen](https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_en.html?screens=2).

I noticed several behaviors that seemed buggy, but @emily-phet and @BLFiedler basically described them in their comments, so I won't repeat them here.

**Comment by zepumph** [comment]
Reset bugginess is hopefully fixed above.

**Comment by zepumph** [comment]
Now when ratio locked in proportion, you ALWAYS should get the moving in proportion sound while moving either hand.

**Comment by zepumph** [comment]
In the above commit the horizontal movement of the hands is locked when the ratio is locked.

**Comment by zepumph** [comment]
>When a barrier is encountered, you can move the hands out of ratio. Need to disallow further motion in that direction for both hands whenever a barrier is encountered.

Implemented above. Not the ratio is maintained, and progress gets stuck when either ratio hand hits an range extremity.

**Comment by zepumph** [comment]
From the above comments. I see only 4 more items for discussion/implementation:

1. 
>Consistent with treating the "locked ratio" as a distinct mode, feedback should be consistent the entire time you are in this mode. If you start in the challenge ratio state getting success feedback, that should stay (sim stays constant dark green, choir sound plays). If you are near ratio, then all the near ratio feedback should be maintained. If you are far away from ratio, all of that feedback (no sonification, no color change) should stay the same. This may become an issue at lower regions, see my next topic below.

Tolerance needs to be adjusted to maintain the same feedback for the whole range when ratio locked. This will be a fair bit of work, and should likely get its own issue.

2. This feature should only be on the second screen. I agree with this, and don't know how it slipped my mind. I will go ahead and implement the change to only make it on the second screen. Especially because @jbphet brought up many good pedagogical concerns that I think will be fixed by disallowing this feature on the first "explore" screen, since it may de-incentivize the exploration. Please let me know if that should be reverted. 

3. when ratio is less than .5 case. This is on hold until we hear back from Dor. That said, I think it would be an easy fix to have the <.5 edge case ignored when the `lockRatioProperty` is true. Let me know if you'd like that implemented. 

4. A checkbox was an easy implementation for experimenting with this new feature, but if we want to use this, then we should (a) choose the UI we want, and (b) make it accessible (I added an accessible name, but it may need help text and an alert). This likely is needed before interviews.

**Comment by BLFiedler** [comment]
Great thoughts, @jbphet! Helped trigger a few thoughts in my head.

> I feel like this changes the way that users are likely to interact with the sim quite a bit. Once users discover this, I suspect that they will learn to unlock the ratio, move them into proportion, then lock the ratio and move the hands around and watch how they behave. This would be a pretty interesting visualization that would help them to "see" the nature of a continuously maintained proportion, but there will likely be less experimentation. That may well be okay, but I think it's a question for the designers to consider carefully.

Definitely a concern if it were on the 1st screen. I think being on the second screen will help (for most cases). I have a gut feeling that if you aren't totally sure what the sim is about and haven't explored the first screen fully, the Lock Ratio will still be a confusing option... I guess we'll see in interviews if people discover this before they've fully worked out what the choir sound means on the first screen, but I think it could be a good clue that there is more happening than just finding green "spots". For a sighted user with two input points, I'm hoping they see that they can lock the ratio  and then think "Oh hey, They can both move at the same time? I can do that myself!" and possibly return to the first screen. But, that will also be an external scaffolding issue. 

> Now that it's so easy to move the hands and maintain the ratio, it feels weird to me that the choir sound doesn't change at all when moving.  Before it was signaling, "Hey, you've done something really amazing" and it would only trigger occasionally.  Now that it's on for a long time, it seems like a different situation.  Perhaps we should consider different sound for "you did this on your own" versus "you're using the lock, here is a sonified version of what's happening".

I agree with this if someone only ever locks on the target ratio. If they ever lock onto a ratio outside of our (30%? of fitness) window, then they will not hear the sound, so then it serves the same purpose. The point of the choir sound is to indicate that you are moving within a continuous, "correct" ratio-space, which is it doing there. A second sound may indicate they are exploring something else, when in reality they are exploring the same "thing", just under a different condition.

**Comment by terracoda** [comment]
I like the lock ratio checkbox. I think it is quite useful, especially for people with dexterity issues. I'm not sure how that interaction will be described, but I still thin it is quite useful.
- proporation, {{distance between hands}}
- proportion, {{new distance}}

**Comment by terracoda** [comment]
I do agree that the checkbox could heavily influence how learners explore the challenges.

**Comment by zepumph** [comment]
>when ratio is less than .5 case. This is on hold until we hear back from Dor. That said, I think it would be an easy fix to have the <.5 edge case ignored when the lockRatioProperty is true. Let me know if you'd like that implemented.

We will make it such that when the ratio is locked, the min value for either value is .05 (half a grid line). That way we avoid the hollywood region.

**Comment by zepumph** [comment]
>A checkbox was an easy implementation for experimenting with this new feature, but if we want to use this, then we should (a) choose the UI we want

We decided that we like that the checkbox is a bit more quiet in the bottom right. We don't want this feature to stand out too much. We also discussed making the ratio more attractive to help this. See https://github.com/phetsims/ratio-and-proportion/issues/99

**Comment by zepumph** [comment]
>Consistent with treating the "locked ratio" as a distinct mode, feedback should be consistent the entire time you are in this mode. If you start in the challenge ratio state getting success feedback, that should stay (sim stays constant dark green, choir sound plays). If you are near ratio, then all the near ratio feedback should be maintained. If you are far away from ratio, all of that feedback (no sonification, no color change) should stay the same. This may become an issue at lower regions, see my next topic below.

We decided to leave this as it is now, especially with interviews right around the corner.

**Comment by zepumph** [comment]
Here is a patch keeping the values above .05, not ready yet:

<details>

```diff
Index: js/common/model/RatioAndProportionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/RatioAndProportionModel.js	(revision f3fd36985fa84856ce8b31078a524d982c40cd05)
+++ js/common/model/RatioAndProportionModel.js	(date 1595961751544)
@@ -33,13 +33,16 @@
 
     // The desired ratio of the left value as compared to the right value. As in 1:2 (initial value).
     this.ratioProperty = new NumberProperty( .5 );
-    this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance );
+    this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance ); // TODO: get rid of me
 
     // @public
     // To avoid divide-by zero errors. NOTE: GridDescriber relies on the min of this mapping to "zero" as it pertains
     // to Interactive description
     this.valueRange = new Range( .0001, 1 );
 
+    // @public - when locked, the min is clamped up above the "hollywood" lower zone for simplicity, see https://github.com/phetsims/ratio-and-proportion/issues/92#issuecomment-665175449
+    this.lockedValueRange = new Range( .05, this.valueRange.max );
+
     const modelBounds = new Bounds2( -.5, this.valueRange.min, .5, this.valueRange.max );
 
     this.leftPositionProperty = new Vector2Property( new Vector2( 0, .2 ), {
@@ -135,8 +138,8 @@
       if ( this.lockRatioProperty.value && !adjustingFromLock ) {
         const previousRatio = oldValue / this.rightValueProperty.value;
         adjustingFromLock = true;
-        this.rightValueProperty.value = Utils.clamp( newValue / previousRatio, this.valueRange.min, this.valueRange.max );
-        if ( this.rightValueProperty.value === this.valueRange.min || this.rightValueProperty.value === this.valueRange.max ) {
+        this.rightValueProperty.value = Utils.clamp( newValue / previousRatio, this.lockedValueRange.min, this.lockedValueRange.max );
+        if ( this.rightValueProperty.value === this.lockedValueRange.min || this.rightValueProperty.value === this.lockedValueRange.max ) {
           this.leftValueProperty.value = previousRatio * this.rightValueProperty.value;
         }
         adjustingFromLock = false;
@@ -146,8 +149,8 @@
       if ( this.lockRatioProperty.value && !adjustingFromLock ) {
         const previousRatio = this.leftValueProperty.value / oldValue;
         adjustingFromLock = true;
-        this.leftValueProperty.value = Utils.clamp( newValue * previousRatio, this.valueRange.min, this.valueRange.max );
-        if ( this.leftValueProperty.value === this.valueRange.min || this.leftValueProperty.value === this.valueRange.max ) {
+        this.leftValueProperty.value = Utils.clamp( newValue * previousRatio, this.lockedValueRange.min, this.lockedValueRange.max );
+        if ( this.leftValueProperty.value === this.lockedValueRange.min || this.leftValueProperty.value === this.lockedValueRange.max ) {
           this.rightValueProperty.value = this.leftValueProperty.value / previousRatio;
         }
         adjustingFromLock = false;


```
</details>

**Comment by zepumph** [comment]
I'm having trouble thinking through all the cases, and will need to come back to this:

<details>

```diff
Index: js/common/model/RatioAndProportionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/RatioAndProportionModel.js	(revision e913fe9ec634197a7b8d7544e0bfb43023e27b2d)
+++ js/common/model/RatioAndProportionModel.js	(date 1595983975857)
@@ -33,13 +33,16 @@
 
     // The desired ratio of the left value as compared to the right value. As in 1:2 (initial value).
     this.ratioProperty = new NumberProperty( .5 );
-    this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance );
+    this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance ); // TODO: get rid of me
 
     // @public
     // To avoid divide-by zero errors. NOTE: GridDescriber relies on the min of this mapping to "zero" as it pertains
     // to Interactive description
     this.valueRange = new Range( .0001, 1 );
 
+    // @public - when locked, the min is clamped up above the "hollywood" lower zone for simplicity, see https://github.com/phetsims/ratio-and-proportion/issues/92#issuecomment-665175449
+    this.lockedValueRange = new Range( .05, this.valueRange.max );
+
     const modelBounds = new Bounds2( -.5, this.valueRange.min, .5, this.valueRange.max );
 
     this.leftPositionProperty = new Vector2Property( new Vector2( 0, .2 ), {
@@ -135,19 +138,26 @@
       if ( this.lockRatioProperty.value && !adjustingFromLock ) {
         const previousRatio = oldValue / this.rightValueProperty.value;
         adjustingFromLock = true;
-        this.rightValueProperty.value = Utils.clamp( newValue / previousRatio, this.valueRange.min, this.valueRange.max );
-        if ( this.rightValueProperty.value === this.valueRange.min || this.rightValueProperty.value === this.valueRange.max ) {
+        this.rightValueProperty.value = this.lockedValueRange.constrainValue( newValue / previousRatio );
+        if ( this.leftValueProperty.value <= this.lockedValueRange.min || this.leftValueProperty.value >= this.lockedValueRange.max ) {
+          this.leftValueProperty.value = this.lockedValueRange.constrainValue( newValue );
+          this.rightValueProperty.value = this.leftValueProperty.value / previousRatio;
+        }
+        if ( this.rightValueProperty.value <= this.lockedValueRange.min || this.rightValueProperty.value >= this.lockedValueRange.max ) {
           this.leftValueProperty.value = previousRatio * this.rightValueProperty.value;
+          this.rightValueProperty.value = this.lockedValueRange.constrainValue( this.rightValueProperty.value );
         }
         adjustingFromLock = false;
       }
+
     } );
     this.rightValueProperty.lazyLink( ( newValue, oldValue ) => {
       if ( this.lockRatioProperty.value && !adjustingFromLock ) {
         const previousRatio = this.leftValueProperty.value / oldValue;
         adjustingFromLock = true;
-        this.leftValueProperty.value = Utils.clamp( newValue * previousRatio, this.valueRange.min, this.valueRange.max );
-        if ( this.leftValueProperty.value === this.valueRange.min || this.leftValueProperty.value === this.valueRange.max ) {
+        // this.rightValueProperty.value = this.lockedValueRange.constrainValue( newValue );
+        this.leftValueProperty.value = this.lockedValueRange.constrainValue( newValue * previousRatio );
+        if ( this.leftValueProperty.value <= this.lockedValueRange.min || this.leftValueProperty.value >= this.lockedValueRange.max ) {
           this.rightValueProperty.value = this.leftValueProperty.value / previousRatio;
         }
         adjustingFromLock = false;

```
</details>

**Comment by zepumph** [comment]
After investigating a bit more today, I think that the way forward is with this patch. In addition to it, I will need to take a look a turning the valueRange potentially into a Property. That way the input can be bound accordingly (like the PDOM slider and dragListener). I tried going a different direciton with clamping in the model directly, and it seemed weird and buggy. 

<details>

```diff

Index: js/common/model/RatioAndProportionModel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/RatioAndProportionModel.js	(revision 94538e0a4eca7dc43c50e45fc22e2da219bfa77f)
+++ js/common/model/RatioAndProportionModel.js	(date 1596752315947)
@@ -33,13 +33,16 @@
 
     // The desired ratio of the left value as compared to the right value. As in 1:2 (initial value).
     this.ratioProperty = new NumberProperty( .5 );
-    this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance );
+    this.toleranceProperty = new NumberProperty( RatioAndProportionQueryParameters.tolerance ); // TODO: get rid of me
 
     // @public
     // To avoid divide-by zero errors. NOTE: GridDescriber relies on the min of this mapping to "zero" as it pertains
     // to Interactive description
     this.valueRange = new Range( .0001, 1 );
 
+    // @public - when locked, the min is clamped up above the "hollywood" lower zone for simplicity, see https://github.com/phetsims/ratio-and-proportion/issues/92#issuecomment-665175449
+    this.lockedValueRange = new Range( .05, this.valueRange.max );
+
     const modelBounds = new Bounds2( -.5, this.valueRange.min, .5, this.valueRange.max );
 
     this.leftPositionProperty = new Vector2Property( new Vector2( 0, .2 ), {
@@ -135,8 +138,8 @@
       if ( this.lockRatioProperty.value && !adjustingFromLock ) {
         const previousRatio = oldValue / this.rightValueProperty.value;
         adjustingFromLock = true;
-        this.rightValueProperty.value = Utils.clamp( newValue / previousRatio, this.valueRange.min, this.valueRange.max );
-        if ( this.rightValueProperty.value === this.valueRange.min || this.rightValueProperty.value === this.valueRange.max ) {
+        this.rightValueProperty.value = Utils.clamp( newValue / previousRatio, this.lockedValueRange.min, this.lockedValueRange.max );
+        if ( this.rightValueProperty.value <= this.lockedValueRange.min || this.rightValueProperty.value >= this.lockedValueRange.max ) {
           this.leftValueProperty.value = previousRatio * this.rightValueProperty.value;
         }
         adjustingFromLock = false;
@@ -146,8 +149,8 @@
       if ( this.lockRatioProperty.value && !adjustingFromLock ) {
         const previousRatio = this.leftValueProperty.value / oldValue;
         adjustingFromLock = true;
-        this.leftValueProperty.value = Utils.clamp( newValue * previousRatio, this.valueRange.min, this.valueRange.max );
-        if ( this.leftValueProperty.value === this.valueRange.min || this.leftValueProperty.value === this.valueRange.max ) {
+        this.leftValueProperty.value = Utils.clamp( newValue * previousRatio, this.lockedValueRange.min, this.lockedValueRange.max );
+        if ( this.leftValueProperty.value <= this.lockedValueRange.min || this.leftValueProperty.value >= this.lockedValueRange.max ) {
           this.rightValueProperty.value = this.leftValueProperty.value / previousRatio;
         }
         adjustingFromLock = false;

```

**Comment by zepumph** [comment]
From design meeting today:

- [ ] the lock ratio checkbox should be disabled when the ratio is not in proportion.

**Comment by zepumph** [comment]
>the lock ratio checkbox should be disabled when the ratio is not in proportion.

This is a little bit weird visually, because the checkbox's enabled get's altered exactly when the green "jumps" to/from its darkest, in-proportion green. I would like @BLFiedler and @emily-phet to confirm that this is acceptable.

**Comment by BLFiedler** [comment]
I don't actually think that is weird. It feels to me like: "You did it! Now here's another thing to play with!" And it isn't more visually jarring than the appearance of the dark green jump. At least to me.

**Comment by zepumph** [comment]
-[ ] I didn't handle the case where you change the ratio, that should recalculate the enabled of the lock ratio checkbox also.

**Comment by zepumph** [comment]
Alright, I fixed the buggy case where you change the ratio, and the checkbox is still selected, but disabled (you are stuck until you reset). I will work on the rest of this issue at some point in the future.

**Comment by zepumph** [comment]
I was finally able to make this happen. The above commit includes a pretty large underlying model change to support changing the enabled range of each draggable hand.

To support this change in the view where the dragListener is wired up:
* I created `enabledValueRangeProperty`. Many spots want to always know what the whole range is, even if some of it is no enabled (like the tick marks), so the valueRange had to stick around. It will likely become a constant soon though.
* I moved the positionProperty (which stored the Vector2) from the model over to RatioHalf. This felt pretty good to me, since that type is the only thing that cares about the horizontal movement, and more and more it feels like that is getting finalized. This is cleanup that I have wanted to get done for a very long time, and I'm glad that it helped make this issue happen (and could get done itself in the process).

For the lock ratio feature now, if you select it when hands are lower than .5, then they snap up to .5 or greater.

@emily-phet please review or assign someone to review master.

**Comment by zepumph** [comment]
See https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.52/phet/ratio-and-proportion_all_phet.html for a dev version to review.

**Comment by emily-phet** [comment]
This looks good to me.
