### ISSUE TITLE
Use mp3 sounds where possible

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#96]
We aren't here yet in the sound implementation process, but today @jbphet mentioned that I should attempt to only use mp3 files, even for loops, where possible for space saving. The moving-in-proportion sound will be a loop,and is currently a wav. I will take a look at trying to compress that when we are doing final adjustments.

**Comment by zepumph** [comment]
We have solidified sound enough that we may be able to convert some `wav` files over to `mp3`. I'm not sure how the loops will go. 


The current en_phet.html is 3.1MB large. I'm unsure how to see what proportion of that is because of sound files.

**Comment by zepumph** [comment]
I saved the two WAV file data sections into a file and saved it, and it was 1.5MB. That is 50% of the total file size. I think that it would be good to spend some time trying to make these MP3s.

**Comment by zepumph** [comment]
I was able to convert the moving-in-proportion sounds to be  `mp3` files. This was much easier than I expected with the following steps:

* Open in Audacity
* Export as mp3
* use the LAME codec
* Choose a constant rate of 48kbps
* repeat for both files.

I added the `trimSilence` option to both sound clips. I cannot tell a difference between the versions. If anyone would like to try, https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.65/phet/ratio-and-proportion_en_phet.html is a version with the `wav` files in, and master now has .mp3s.

I then moved the `wav` files into `assets/`. 

The build sim in phet brand is now 1.6MB. Pretty nice!

@jbphet, can you review the commit and above process and let me know if there is anything else to do here?

**Comment by jbphet** [comment]
Looks good to me, and it's cool that it reduced the size significantly.  I also double checked that the .wav files were in the assets dir and there were.  Closing.
