### ISSUE TITLE
Peaceful Tranquility disables sim interaction on iPad, Safari

### ISSUE THREAD

**Issue by BLFiedler** [phetsims/ratio-and-proportion#97]
If you select the Peaceful Tranquility velocity sound and then hit the reset button (iPad, Safari) it locks all interaction with the simulation. Only that sound option though. (dev40)

I know you might be removing that particular option, but just to note that whatever specifically happened there caused some problems, @zepumph

**Comment by zepumph** [comment]
Sorry! This was a bug I fixed in real time yesterday, but didn't commit. Dev version coming soon!

**Comment by zepumph** [comment]
See #9 for a dev version once I'm done with https://github.com/phetsims/ratio-and-proportion/issues/9#issuecomment-662725606

**Comment by BLFiedler** [comment]
I'm going to re-open this one rather than start a new one. 

Trying to select Chord Option 2 in master (7/24/2020) freezes the sim (tried on iPad, Safari as well Chrome, Win10)

**Comment by zepumph** [comment]
Ugh, I'm so sorry. Try this one https://phet-dev.colorado.edu/html/ratio-and-proportion/1.0.0-dev.41/phet/ratio-and-proportion_en_phet.html?
